Repository wireapp/wire-android, pull requests merged in 2018-03, with the labels that each got.

#1414 [AN-5762] Delete failed video recordings
  app/src/main/java/com/waz/zclient/pages/main/conversation/AssetIntentsManager.java
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
Labels: QA

#1430 [AN-5919] Sanitize intent uris
  app/src/main/scala/com/waz/zclient/ShareActivity.scala
Labels: QA

#1447 Fix exit animation on GuestOptionsFragment
  app/src/main/scala/com/waz/zclient/participants/fragments/GuestOptionsFragment.scala
Labels: Dev, QA, bug

#1444 [AN-5987] Blocked profile name and username
  app/src/main/java/com/waz/zclient/pages/main/connect/BlockedUserProfileFragment.java
  app/src/main/java/com/waz/zclient/pages/main/connect/PendingConnectRequestFragment.java
  app/src/main/java/com/waz/zclient/pages/main/connect/SendConnectRequestFragment.java
  app/src/main/res/layout/fragment_blocked_user_profile.xml
  app/src/main/res/layout/fragment_connect_request_pending.xml
  app/src/main/res/layout/fragment_send_connect_request.xml
  app/src/main/scala/com/waz/zclient/WireContext.scala
  app/src/main/scala/com/waz/zclient/conversationlist/ConversationListManagerFragment.scala
  app/src/main/scala/com/waz/zclient/pages/main/connect/BlockedUserProfileFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/GroupParticipantsFragment.scala
  app/src/main/scala/com/waz/zclient/sharing/ShareToMultipleFragment.scala
Labels: QA, bug

#1442 Bump release versions
  build.gradle
Labels: Dev

#1451 Fix likes list on light theme
  app/src/main/scala/com/waz/zclient/conversation/LikesAdapter.scala
Labels: Dev

#1453 Fix incorrect comparison of non-option call state
  app/src/main/scala/com/waz/zclient/calling/controllers/CurrentCallController.scala
  app/src/main/scala/com/waz/zclient/calling/views/AudioParticipantsView.scala
  app/src/main/scala/com/waz/zclient/calling/views/VideoCallingView.scala
Labels: QA

#1456 Fix blank pending connection page
  app/src/main/java/com/waz/zclient/pages/main/connect/PendingConnectRequestFragment.java
Labels: Dev

#1459 Rewrite LikesListFragment to Scala
  app/src/main/java/com/waz/zclient/pages/main/conversation/LikesListFragment.java
  app/src/main/java/com/waz/zclient/pages/main/conversation/controller/ConversationScreenController.java
  app/src/main/java/com/waz/zclient/pages/main/conversation/controller/ConversationScreenControllerObserver.java
  app/src/main/java/com/waz/zclient/pages/main/conversation/controller/IConversationScreenController.java
  app/src/main/scala/com/waz/zclient/common/controllers/ScreenController.scala
  app/src/main/scala/com/waz/zclient/conversation/LikesAdapter.scala
  app/src/main/scala/com/waz/zclient/conversation/LikesListFragment.scala
  app/src/main/scala/com/waz/zclient/conversationlist/ConversationListManagerFragment.scala
  app/src/main/scala/com/waz/zclient/messages/parts/footer/LikeDetailsView.scala
  app/src/main/scala/com/waz/zclient/pages/main/conversation/ConversationManagerFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantFragment.scala
  app/src/test/scala/com/waz/zclient/conversation/ConversationListRowTest.scala
Labels: Dev

#1470 Fix locator for user handle
  app/src/main/scala/com/waz/zclient/common/views/UserDetailsView.scala
  wire-ui/src/main/res/layout/user__details.xml
Labels: QA

#1488 Otr device page back press
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantFragment.scala
Labels: Dev

#1489 Guest options in a scroll view
  app/src/main/res/layout/guest_options_fragment.xml
Labels: Dev

#1495 Fix the create group button on the single participant screen
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
Labels: Dev
