Repository wireapp/wire-android, pull requests merged in 2018-04, with the labels that each got.

#1497 Replace logo shield
  wire-ui/src/main/res/drawable-hdpi/wire_logo_shield.png
  wire-ui/src/main/res/drawable-xhdpi/wire_logo_shield.png
  wire-ui/src/main/res/drawable-xxhdpi/wire_logo_shield.png
Labels: Design

#1527 Stop unnecessary binding of ConversationNameViewHolder
  app/src/main/scala/com/waz/zclient/participants/ParticipantsAdapter.scala
Labels: Dev, QA

#1549 Add tracking to email registration
  app/src/main/scala/com/waz/zclient/appentry/fragments/VerifyEmailWithCodeFragment.scala
  app/src/main/scala/com/waz/zclient/tracking/GlobalTrackingController.scala
  app/src/main/scala/com/waz/zclient/tracking/TrackingEvent.scala
Labels: Dev
