Repository wireapp/wire-android, pull requests merged in 2018-09, with the labels that each got.

#1767 Add mute icon to call banner
  app/src/main/res/layout/activity_settings.xml
  app/src/main/res/layout/main.xml
  app/src/main/scala/com/waz/zclient/WireContext.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
Labels: Dev

#1763 Introduce SE version with call Terminating state
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/scala/com/waz/services/calling/CallWakeService.scala
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/calling/CallingActivity.scala
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallStartController.scala
  app/src/main/scala/com/waz/zclient/calling/views/CallingMiddleLayout.scala
  app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
  app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListRow.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/CallingNotificationsController.scala
Labels: Dev

#1770 [WIP] Android 8 changes
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/waz/zclient/controllers/notifications/ShareSavedImageActivity.java
  app/src/main/java/com/waz/zclient/utils/IntentUtils.java
  app/src/main/res/layout/preference_switch.xml
  app/src/main/res/layout/preference_text_button.xml
  app/src/main/res/layout/preferences_advanced_layout.xml
  app/src/main/res/layout/preferences_dev_layout.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_no_translate.xml
  app/src/main/res/xml/provider_paths.xml
  app/src/main/scala/com/waz/services/calling/CallingNotificationsService.scala
  app/src/main/scala/com/waz/services/websocket/WebSocketService.scala
  app/src/main/scala/com/waz/zclient/BaseActivity.scala
  app/src/main/scala/com/waz/zclient/Intents.scala
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/common/views/ImageAssetDrawable.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/CallingNotificationsController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/ImageNotificationsController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/MessageNotificationsController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/NotificationManagerWrapper.scala
  app/src/main/scala/com/waz/zclient/preferences/PreferencesActivity.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/AdvancedView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DevSettingsView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/OptionsView.scala
  app/src/test/scala/com/waz/zclient/notifications/controllers/MessageNotificationsControllerTest.scala
Labels: Dev, QA, bug

#1779 Use file provider for capturing video
  app/src/main/java/com/waz/zclient/pages/main/conversation/AssetIntentsManager.java
Labels: Dev

#1782 Change layout for app entry
  app/src/main/res/layout-h550dp/app_entry_scene.xml
  app/src/main/res/layout/app_entry_scene.xml
Labels: Design
