Repository wireapp/wire-android, pull requests merged in 2019-08, with the labels that each got.

#2223 feat: Security checklist
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/preferences_dev_layout.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_no_translate.xml
  app/src/main/scala/com/waz/services/fcm/FCMHandlerService.scala
  app/src/main/scala/com/waz/zclient/BaseActivity.scala
  app/src/main/scala/com/waz/zclient/LaunchActivity.scala
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DevSettingsView.scala
  app/src/main/scala/com/waz/zclient/security/BlockWithDialogAction.scala
  app/src/main/scala/com/waz/zclient/security/RootDetectionCheck.scala
  app/src/main/scala/com/waz/zclient/security/SecureActivity.scala
  app/src/main/scala/com/waz/zclient/security/SecurityChecklist.scala
  app/src/main/scala/com/waz/zclient/security/WipeDataAction.scala
  app/src/test/scala/com/waz/zclient/SecurityChecklistTest.scala
  default.json
Labels: DO NOT MERGE

#2220 fix: Invalid system message about adding someone to the conversation
  app/src/main/scala/com/waz/zclient/messages/parts/MemberChangePartView.scala
Labels: Dev

#2255 fix: Photos from the internal camera are sometimes failing to be sent
  app/src/main/scala/com/waz/zclient/assets2/AndroidImageRecoder.scala
Labels: Dev

#2260 fix: Save image to gallery
  app/src/main/scala/com/waz/zclient/common/controllers/AssetsController.scala
  app/src/main/scala/com/waz/zclient/messages/controllers/MessageActionsController.scala
Labels: Dev

#2265 Feature: device password policy
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/device_admin.xml
  app/src/main/scala/com/waz/services/SecurityPolicyService.scala
  app/src/main/scala/com/waz/services/fcm/FCMHandlerService.scala
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/SignInFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DevSettingsView.scala
  app/src/main/scala/com/waz/zclient/security/SecureActivity.scala
  app/src/main/scala/com/waz/zclient/security/actions/BlockWithDialogAction.scala
  app/src/main/scala/com/waz/zclient/security/actions/ShowDialogAction.scala
  app/src/main/scala/com/waz/zclient/security/actions/WipeDataAction.scala
  app/src/main/scala/com/waz/zclient/security/checks/DeviceAdminCheck.scala
  app/src/main/scala/com/waz/zclient/security/checks/DevicePasswordComplianceCheck.scala
  app/src/main/scala/com/waz/zclient/security/checks/RootDetectionCheck.scala
  default.json
Labels: DO NOT MERGE, Work In Progress
