Repository wireapp/wire-android, pull requests merged in 2019-03, with the labels that each got.

#2028 fix: Restore the Block button in the bottom menu in the conv list
  app/src/main/scala/com/waz/zclient/participants/ConversationOptionsMenuController.scala
Labels: Dev

#2033 fix: Likers in the message footer should be displayed chronologically
  app/src/main/scala/com/waz/zclient/conversation/ReplyController.scala
  app/src/main/scala/com/waz/zclient/messages/UsersController.scala
  app/src/main/scala/com/waz/zclient/messages/parts/footer/LikeDetailsView.scala
Labels: Dev

#2030 fix: Go back to the conv list after leaving a group
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  app/src/main/scala/com/waz/zclient/conversationlist/ConversationListController.scala
  app/src/main/scala/com/waz/zclient/participants/ConversationOptionsMenuController.scala
Labels: Dev

#2032 fix: Back press on a send connect request screen should return to the Start UI
  app/src/main/scala/com/waz/zclient/connect/SendConnectRequestFragment.scala
Labels: Dev

#2035 feat: Use user permissions (a partner, a team member) in searching
  app/build.gradle
  app/src/main/scala/com/waz/zclient/common/controllers/UserAccountsController.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/ProfileView.scala
  app/src/main/scala/com/waz/zclient/search/SearchController.scala
  app/src/main/scala/com/waz/zclient/usersearch/SearchUIFragment.scala
Labels: Dev

#2037 fix: Stop team users from deleting their accounts
  app/src/main/scala/com/waz/zclient/preferences/pages/AccountView.scala
Labels: DO NOT MERGE

#2040 fix: Opening the participant's details from the dialog should land on the Devices tab
  app/src/main/res/layout/system_message_content.xml
  app/src/main/scala/com/waz/zclient/messages/UsersController.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
Labels: Dev

#2046 Fixes to reopening the SSO Login page and dialog
  app/src/main/scala/com/waz/zclient/InputDialog.scala
  app/src/main/scala/com/waz/zclient/WireContext.scala
  app/src/main/scala/com/waz/zclient/appentry/AppEntryActivity.scala
  app/src/main/scala/com/waz/zclient/appentry/AppLaunchFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/SSOFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/SSOWebViewFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/SignInFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/TeamNameFragment.scala
Labels: Dev

#2049 refactor: remove unused ReceivedPushData table
  app/build.gradle
  app/src/main/scala/com/waz/services/fcm/FCMHandlerService.scala
  app/src/main/scala/com/waz/zclient/tracking/GlobalTrackingController.scala
Labels: DO NOT MERGE

#2052 Addresses Issue #1946 to enable copying sent ephemeral messages
  app/src/main/scala/com/waz/zclient/messages/MessageBottomSheetDialog.scala
Labels: DO NOT MERGE

#2050 Feature/logs setting
  app/build.gradle
  app/src/main/res/layout/preferences_advanced_layout.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/services/FutureService.scala
  app/src/main/scala/com/waz/services/calling/CallWakeService.scala
  app/src/main/scala/com/waz/services/websocket/WebSocketService.scala
  app/src/main/scala/com/waz/zclient/BaseActivity.scala
  app/src/main/scala/com/waz/zclient/Intents.scala
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/ShareActivity.scala
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/log/LogShowInstancesUI.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/AdvancedView.scala
Labels: DO NOT MERGE, Dev

#2062 fix: Properly initialize the app before handling conversation and profile deep links
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/appentry/SSOFragment.scala
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  app/src/main/scala/com/waz/zclient/deeplinks/DeepLinkService.scala
  app/src/main/scala/com/waz/zclient/pages/main/MainPhoneFragment.scala
Labels: Dev

#2068 fix: Close the user profile on switching conversations with a deep link
  app/src/main/scala/com/waz/zclient/integrations/IntegrationDetailsFragment.scala
  app/src/main/scala/com/waz/zclient/pages/main/MainPhoneFragment.scala
  app/src/main/scala/com/waz/zclient/pages/main/conversation/ConversationManagerFragment.scala
  app/src/main/scala/com/waz/zclient/participants/ConversationOptionsMenuController.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsController.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantHeaderFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
Labels: Dev

#2074 fix: Unable to open SearchUI after opening a connect request from a deep link
  app/src/main/java/com/waz/zclient/pages/main/pickuser/controller/IPickUserController.java
  app/src/main/java/com/waz/zclient/pages/main/pickuser/controller/PickUserController.java
  app/src/main/java/com/waz/zclient/pages/main/pickuser/controller/PickUserControllerScreenObserver.java
  app/src/main/java/com/waz/zclient/participants/UserRequester.java
  app/src/main/scala/com/waz/zclient/connect/SendConnectRequestFragment.scala
  app/src/main/scala/com/waz/zclient/conversationlist/ConversationListManagerFragment.scala
  app/src/main/scala/com/waz/zclient/pages/main/MainPhoneFragment.scala
  app/src/main/scala/com/waz/zclient/usersearch/SearchUIFragment.scala
Labels: Dev

#2076 fix: Increasing the distance between the handle and the avatar on the user profile
  app/src/main/res/layout/fragment_participants_single_tabbed.xml
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
Labels: Dev

#2079 Fix user deep link opening for unconnected user
  app/src/main/scala/com/waz/zclient/deeplinks/DeepLinkService.scala
Labels: DO NOT MERGE
