Repository wireapp/wire-android, pull requests merged in 2020-09, with the labels that each got.

#3003 New backups (17+2r): Restoring data from the login screen
  app/build.gradle
  app/proguard-rules.txt
  app/src/main/java/com/waz/zclient/KotlinServices.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/BackUpViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/assets/AssetsBackupDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/conversations/ConversationsBackupDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/messages/LikesBackUpDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/messages/MessagesBackUpModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/receipts/ReadReceiptsBackupDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCase.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/users/UsersBackUpModel.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/User.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/mapper/UserMapper.kt
  app/src/main/scala/com/waz/zclient/appentry/fragments/FirstLaunchAfterLoginFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/BackupExportView.scala
  app/src/test/kotlin/com/waz/zclient/feature/backup/BackUpDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCaseTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCaseTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/user/mapper/UserMapperTest.kt
  buildSrc/src/main/kotlin/DependencyMap.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/conversations/ConversationsTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/messages/LikesTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/messages/MessagesTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/receipts/ReadReceiptsTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/users/UsersTestDataProvider.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/BatchDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/LikesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessagesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/receipts/ReadReceiptsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/model/UsersEntity.kt
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/MessagesMigrationTest.scala
Labels: size/L

#2989 New backups (17+1e): Remove encryption
  app/src/androidTest/kotlin/com/waz/zclient/feature/backup/EncryptionHandlerTest.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/encryption/EncryptionHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/encryption/EncryptionHandlerDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCase.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
Labels: size/L

#2990 New backups (17+2e): Encryption
  app/src/androidTest/kotlin/com/waz/zclient/feature/backup/EncryptionHandlerTest.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/encryption/EncryptionHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/encryption/EncryptionHandlerDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCase.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
Labels: size/L

#3005 [Conference Calling] : Show whether a call is using conference calling
  app/src/main/res/drawable/rounded_rectangle.xml
  app/src/main/res/layout/calling_header.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/calling/views/CallingHeader.scala
Labels: size/L

#3006 Add dialog for new backup warning
  app/build.gradle
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/Preferences.scala
Labels: size/M

#3009 [Conference Calling] : Show whether a call is using variable bitrate or constant bitrate
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/calling/views/CallingHeader.scala
Labels: size/S

#3010 Enable back up dialog for candidate builds
  app/build.gradle
Labels: size/XS

#3011 Fix back up warning dialog button click event handling
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/utils/ContextUtils.scala
Labels: size/M

#3007 Rewriting encryption/decryption back to Sodium v1
  app/src/main/kotlin/com/waz/zclient/core/extension/String.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/Crypto.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/CryptoWrapper.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/encryption/EncryptionHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/encryption/error/CryptoFailure.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/header/EncryptionHeader.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCase.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
  app/src/test/kotlin/com/waz/zclient/core/extension/ByteArrayExtensionsTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/crypto/CryptoTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/crypto/encryption/EncryptionHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/crypto/header/CryptoHeaderMetaDataTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/BatchReaderExtensionsTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCaseTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCaseTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesTableTestHelper.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/utils/crypto/LibSodiumUtils.scala
Labels: size/XL

#3012 New backups: Changing the metadata format according to the docs.
  app/src/main/java/com/waz/zclient/KotlinServices.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/BackUpViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/crypto/encryption/EncryptionHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/BackupMetaData.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCase.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/FirstLaunchAfterLoginFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/BackupExportView.scala
  app/src/test/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/crypto/encryption/EncryptionHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/crypto/header/CryptoHeaderMetaDataTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCaseTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCaseTest.kt
Labels: size/L

#3013 New backups: Remove the popup and dead code from the Scala side
  app/build.gradle
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/FirstLaunchAfterLoginFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/VerifyPhoneFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/BackupExportView.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/Preferences.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/AccountManager.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/AccountsService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/GlobalModule.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/backup/BackupManager.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/backup/EncryptedBackupHeader.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/utils/crypto/LibSodiumUtils.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/backup/BackupManagerSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/backup/EncryptedBackupHeaderSpec.scala
Labels: size/XXL

#3004 New backups: A utility method for converting time to strings according to the given format
  app/src/main/kotlin/com/waz/zclient/core/utilities/DateAndTimeUtils.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/BackupMetaData.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCase.kt
  app/src/test/kotlin/com/waz/zclient/core/utilities/DateAndTimeUtilsTest.kt
Labels: size/L

#3017 New backups: Enforce strong password validation for backups
  app/src/main/scala/com/waz/zclient/preferences/dialogs/BackupPasswordDialog.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/BackupExportView.scala
Labels: size/S

#3015 Bump AVS version to 6.3.4
  app/build.gradle
Labels: size/XS

#3018 Bugfix: Calling notification not displayed when the app is moving to the background
  app/src/main/scala/com/waz/services/calling/CallingNotificationsService.scala
Labels: size/S

#3008 [Conference Calling Improvements] To release with 3.56 (September 21th)
  app/build.gradle
  app/src/main/java/com/waz/zclient/paintcode/WireStyleKit.java
  app/src/main/res/drawable/ic_muted_overlay_dark_theme.xml
  app/src/main/res/drawable/ic_muted_overlay_light_theme.xml
  app/src/main/res/drawable/ic_unmuted_overlay_dark_theme.xml
  app/src/main/res/drawable/ic_unmuted_overlay_light_theme.xml
  app/src/main/res/drawable/rounded_rectangle.xml
  app/src/main/res/layout/calling_header.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/theme_attrs.xml
  app/src/main/res/values/themes.xml
  app/src/main/scala/com/waz/services/calling/CallingNotificationsService.scala
  app/src/main/scala/com/waz/zclient/calling/views/CallingHeader.scala
  app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
Labels: size/L

#3026 [Fix] : Sorting bug for video grid
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
Labels: size/XS

#3025 [Fix] : crash for missed group calls
  app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListRow.scala
Labels: size/XS

#3030 [Conference Calling] Bugfix: Show VBR/CBR info only once the call is established
  app/src/main/scala/com/waz/zclient/calling/views/CallingHeader.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
Labels: size/S

#3031 Bump AVS version to 6.4.1
  app/build.gradle
Labels: size/XS

#3032 [Conference Calling] Bugfix: VBR/CBR label visibility
  app/src/main/scala/com/waz/zclient/calling/views/CallingHeader.scala
Labels: size/XS

#3033 Bump version to 6.4.2
  app/build.gradle
Labels: size/XS

#3027 Refactoring WSPushService + other changes required to make wire-android work with wire-signals 0.2.2
  app/src/main/scala/com/waz/zclient/camera/views/CameraPreviewTextureView.scala
  buildSrc/src/main/kotlin/Dependencies.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/cache/CacheService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/assets/AssetService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/assets/AudioLevels.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/push/WSPushService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/queue/SyncScheduler.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/threading/Threading.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/utils/IoUtils.scala
Labels: size/L

#3028 [Conf Calling]: Prepare for public launch
  app/src/main/res/layout/calling_header.xml
  app/src/main/res/layout/preferences_options_layout.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/calling/views/CallingHeader.scala
  app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
  app/src/main/scala/com/waz/zclient/conversation/creation/CreateConversationSettingsFragment.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/OptionsView.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/Preferences.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
Labels: size/L
