Repository wireapp/wire-android, pull requests merged in 2020-07, with the labels that each got.

#2903 [Feature] Start a conference call
  app/build.gradle
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
Labels: size/M

#2905 [Chore] Remove video call restrictions
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/conversation/creation/CreateConversationSettingsFragment.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
Labels: size/S

#2906 fix: Avoid displaying 'Default' as the username in system messages
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/messages/UsersController.scala
  app/src/main/scala/com/waz/zclient/messages/parts/MemberChangePartView.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
Labels: size/M

#2907 fix: Team data gets updated but new team data is not stored
  app/src/main/scala/com/waz/zclient/preferences/pages/ProfileView.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/TeamsSyncHandler.scala
Labels: size/M

#2908 [Fix] Allow call to be promoted to video for non team user
  app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
Labels: size/XS

#2910 [Feature] Conference Calls : VideoGrid
  app/src/main/res/layout/fragment_calling.xml
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
Labels: size/S

#2911 Copy change for backup message
  app/src/main/res/values/strings.xml
Labels: size/XS

#2909 Fixed compilation issues in android tests for database tests
  storage/build.gradle
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/UserDatabaseHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetTables126to128MigrationTests.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/contact/ContactHashesTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/contact/ContactOnWireTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/contact/ContactTables126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/contact/ContactsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/email/EmailAddressesTable126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/email/EmailAddressesTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/phone/PhoneNumbersTable126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/phone/PhoneNumbersTableTestHelper.kt
Labels: size/L

#2915 Major version bump to 3.51
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#2917 [Chore] Bump AVS to 6.1.9
  app/build.gradle
Labels: size/XS

#2916 Feature : Increase handle length
  app/src/main/kotlin/com/waz/zclient/shared/user/handle/usecase/ValidateHandleUseCase.kt
  app/src/main/scala/com/waz/zclient/HandleLength.scala
  app/src/main/scala/com/waz/zclient/SetHandleFragment.scala
  app/src/main/scala/com/waz/zclient/common/views/InputBox.scala
  app/src/main/scala/com/waz/zclient/preferences/dialogs/ChangeHandleFragment.scala
  app/src/test/kotlin/com/waz/zclient/shared/user/handle/usecase/ValidateHandleUseCaseTest.kt
Labels: size/M

#2920 Fix : Wrong welcome screen shown while being connected to a custom backend
  app/src/main/scala/com/waz/zclient/appentry/SSOWebViewFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/StartSSOFragment.scala
Labels: size/S

#2919 [Chore] Internally downgrade AVS to 6.0.43
  app/build.gradle
Labels: size/XS

#2921 feature : Conf Calling - show name of participants in video grid
  app/src/main/res/layout/video_call_info_view.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
Labels: size/M

#2924 Bugfix : Login Button does not react on Enterprise Login Page
  app/src/main/scala/com/waz/zclient/appentry/AppEntryActivity.scala
  app/src/main/scala/com/waz/zclient/appentry/SSOWebViewFragment.scala
Labels: size/S

#2923 [Feature] Sort call participants by name
  app/src/main/scala/com/waz/zclient/calling/CallParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
Labels: size/M

#2918 [Fix] Restore calling tests
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
Labels: size/L

#2926 fix: CallController.participantInfos needs to be public
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
Labels: size/S

#2931 [Chore] Bump AVS to 6.2.7
  app/build.gradle
Labels: size/XS

#2932 Revert "[Chore] Bump AVS to 6.2.7 (#2931)"
  app/build.gradle
Labels: size/XS

#2933 [Refactor] Targeted messages
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/otr/OtrServiceImpl.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/LastReadSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/otr/OtrSyncHandlerSpec.scala
Labels: size/L

#2936 [Chore] Bump internal AVS to 6.2.10
  app/build.gradle
Labels: DO NOT MERGE, size/XS

#2939 [Feature] Targeted calling messages
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/call/AvsSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
Labels: size/L

#2942 [Feature] Conference calling beta
  app/build.gradle
  app/src/main/res/layout/preferences_options_layout.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/OptionsView.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/Preferences.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
Labels: size/L

#2940 Dialog to notify users around discontinued support for android 5 & 6
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/Preferences.scala
Labels: size/M

#2941 [Chore] Bump AVS to 6.2.12
  app/build.gradle
Labels: size/XS

#2944 updated content description to help automation
  app/src/main/res/layout/preferences_options_layout.xml
Labels: size/M
