Repository wireapp/wire-android, pull requests merged in 2020-06, with the labels that each got.

#2861 fix: When looking for a username of a removed user, we should get the old name
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/UserService.scala
Labels: size/S

#2859 fix: System messages on the user being removed/leaving the conversation or team
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/MessageData.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/UserService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessagesContentUpdater.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/UserServiceSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/conversation/ConversationServiceSpec.scala
Labels: size/L

#2867 Hotfix: Copy change for SSO redirection screen
  app/src/main/res/layout/fragment_start_sso.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/appentry/StartSSOFragment.scala
Labels: size/M

#2868 Fix: AVS logs within debug report
  app/build.gradle
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Avs.scala
Labels: size/XS

#2863 Deleted conversation names
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
Labels: size/L

#2872 fix: Open the profile from a mention
  app/src/main/scala/com/waz/zclient/pages/main/conversation/ConversationManagerFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
Labels: size/S

#2862 [Feature] AVS error alert
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_no_translate.xml
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/common/controllers/BrowserController.scala
  app/src/main/scala/com/waz/zclient/utils/ContextUtils.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/Preferences.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
Labels: size/M

#2874 fix: Unconnected users displayed as contacts in private accounts searches
  app/src/main/scala/com/waz/zclient/usersearch/domain/RetrieveSearchResults.scala
Labels: size/S

#2873 [Feature] AVS 5.6
  app/build.gradle
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Calling.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
Labels: size/M

#2876 fix: Generating the conversation name crashes if user data is missing
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
Labels: size/M

#2879 fix: Bottom dialog in Group Participant View shows only one option
  app/src/main/scala/com/waz/zclient/pages/main/conversation/ConversationManagerFragment.scala
Labels: size/S

#2880 fix: The "Done" button on Create Group Conversation screen unresponsive for large teams
  app/src/main/scala/com/waz/zclient/conversation/creation/CreateConversationController.scala
Labels: size/M

#2878 fix: Race condition on conversation list click while reloading the list
  app/src/main/scala/com/waz/zclient/conversationlist/adapters/ConversationFolderListAdapter.scala
  app/src/main/scala/com/waz/zclient/conversationlist/adapters/ConversationListAdapter.scala
Labels: size/S

#2882 AN-6925: Connection results not being displayed in search
  app/src/main/scala/com/waz/zclient/usersearch/domain/RetrieveSearchResults.scala
Labels: size/XS

#2887 [Fix] AVS alert shows too frequently
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
Labels: size/S

#2888 Bugfix : AN-6825 - Logging out one of multiple accounts does not land on conversations screen.
  app/src/main/scala/com/waz/zclient/preferences/pages/AccountView.scala
Labels: size/S

#2890 fix: Unable to open Group Participants View after removing a user
  app/src/main/scala/com/waz/zclient/pages/main/conversation/ConversationManagerFragment.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsController.scala
Labels: size/S

#2891 fix: System messages for member-join and member-left in conversations
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/ConvMessagesIndex.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/MessageData.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/UserData.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/UserService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessagesContentUpdater.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/MessagesServiceSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/UserServiceSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
Labels: size/L

#2884 Fix test cases in SettingsAccountEditHandleViewModelTest
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/edithandle/SettingsAccountEditHandleViewModel.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/account/edithandle/SettingsAccountEditHandleViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/framework/coroutines/CoroutineTestRule.kt
Labels: size/L

#2885 refactor: Remove the Generators class
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/utils/BiRelation.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/Generators.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/CompositeKeyTestItem.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/TestItem.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/ZMessagingDBSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/utils/BiRelationSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/utils/KeyValuePrefSpec.scala
Labels: size/XL

#2893 Increase max line length to 140
  detekt/config.yml
Labels: size/XS

#2892 Bump AVS to 6.0.36
  app/build.gradle
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Calling.scala
Labels: size/M

#2895 Fetch client list and pass to AVS (conference calling part 1)
  app/build.gradle
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Calling.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/call/AvsSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/otr/OtrSyncHandlerSpec.scala
Labels: size/L

#2896 Make request to SFT server (conference part 2)
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Calling.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/CallingClient.scala
Labels: size/M

#2894 feat: File restrictions
  app/build.gradle
  app/src/main/java/com/waz/zclient/pages/main/conversation/AssetIntentsManager.java
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/ShareActivity.scala
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/common/controllers/AssetsController.scala
  app/src/main/scala/com/waz/zclient/common/controllers/SharingController.scala
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  app/src/main/scala/com/waz/zclient/messages/MsgPart.scala
  app/src/main/scala/com/waz/zclient/messages/parts/OtrMsgPartView.scala
  app/src/test/kotlin/com/waz/zclient/shared/assets/FileRestrictionTest.kt
  default.json
  wire-android-sync-engine/zmessaging/src/main/java/com/waz/api/Message.java
  wire-android-sync-engine/zmessaging/src/main/java/com/waz/service/assets/FileRestrictionList.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/MessageData.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/GlobalModule.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/backup/BackupManager.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/utils/package.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/specs/AndroidFreeSpec.scala
Labels: size/L

#2900 [Feature] Join a conference call
  app/build.gradle
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Calling.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/CallingClient.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/call/AvsSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/otr/OtrSyncHandlerSpec.scala
Labels: size/L

#2902 Bugfix : Android 10 Incoming Call Notification
  app/src/main/scala/com/waz/services/calling/CallingNotificationsService.scala
  app/src/main/scala/com/waz/zclient/calling/CallingActivity.scala
Labels: size/XS
