Repository wireapp/wire-android, pull requests merged in 2020-03, with the labels that each got.

#2653 Fix: Change dependency configuration of viewPager2
  app/build.gradle
Labels: size/XS

#2652 [Kotlin Migration] feature/create personal account part3
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/waz/zclient/auth/registration/CreateAccountFragment.kt
  app/src/main/kotlin/com/waz/zclient/auth/registration/personal/CreatePersonalAccountViewPagerAdapter.kt
  app/src/main/kotlin/com/waz/zclient/auth/registration/personal/email/CreatePersonalAccountWithEmailFragment.kt
  app/src/main/kotlin/com/waz/zclient/auth/registration/personal/email/EmailVerificationFragment.kt
  app/src/main/kotlin/com/waz/zclient/auth/registration/personal/phone/CreatePersonalAccountWithPhoneFragment.kt
  app/src/main/kotlin/com/waz/zclient/auth/signup/CreateAccountActivity.kt
  app/src/main/kotlin/com/waz/zclient/auth/signup/CreateAccountFragment.kt
  app/src/main/kotlin/com/waz/zclient/core/extension/Context.kt
  app/src/main/kotlin/com/waz/zclient/core/extension/Fragment.kt
  app/src/main/kotlin/com/waz/zclient/core/extension/View.kt
  app/src/main/res-migration/layout/fragment_create_personal_account.xml
  app/src/main/res-migration/layout/fragment_email_verification.xml
  app/src/main/res-migration/values/styles_edittext.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: size/L

#2613 Feature: Settings Account - Delete Account functionality (Part 1)
  app/src/main/kotlin/com/waz/zclient/accounts/AccountsDataSource.kt
  app/src/main/kotlin/com/waz/zclient/accounts/AccountsLocalDataSource.kt
  app/src/main/kotlin/com/waz/zclient/accounts/AccountsRepository.kt
  app/src/main/kotlin/com/waz/zclient/accounts/di/AccountsModule.kt
  app/src/main/kotlin/com/waz/zclient/accounts/domain/model/ActiveAccount.kt
  app/src/main/kotlin/com/waz/zclient/accounts/domain/usecase/GetActiveAccountUseCase.kt
  app/src/main/kotlin/com/waz/zclient/core/di/Injector.kt
  app/src/main/kotlin/com/waz/zclient/core/exception/Failure.kt
  app/src/main/kotlin/com/waz/zclient/core/extension/DependencyInjection.kt
  app/src/main/kotlin/com/waz/zclient/core/extension/String.kt
  app/src/main/kotlin/com/waz/zclient/core/network/ApiService.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/SettingsAccountFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/SettingsAccountViewModel.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/deleteaccount/DeleteAccountDialogFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/deleteaccount/DeleteAccountUseCase.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/deleteaccount/SettingsAccountDeleteAccountViewModel.kt
  app/src/main/kotlin/com/waz/zclient/settings/di/SettingsModule.kt
  app/src/main/kotlin/com/waz/zclient/user/data/UsersDataSource.kt
  app/src/main/kotlin/com/waz/zclient/user/data/UsersRepository.kt
  app/src/main/kotlin/com/waz/zclient/user/data/source/local/UsersLocalDataSource.kt
  app/src/main/kotlin/com/waz/zclient/user/data/source/remote/UsersNetworkService.kt
  app/src/main/kotlin/com/waz/zclient/user/data/source/remote/UsersRemoteDataSource.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/waz/zclient/settings/account/SettingsAccountViewModelTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/accountdata/ActiveAccountsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/accountdata/ActiveAccountsMigration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/accountdata/SsoIdEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabaseMigration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/model/UserEntity.kt
Labels: Kotlin Migration, size/XL

#2646 fix: Count the number of call participants with ConversationsService.activeMembersData
  app/src/main/scala/com/waz/zclient/calling/CallParticipantsFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallStartController.scala
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/CallingNotificationsController.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/FlowManagerService.scala
Labels: size/L

#2656 Fix: Downgrade material library to fix bottom navigation background issue
  app/src/main/kotlin/com/waz/zclient/auth/registration/personal/CreatePersonalAccountFragment.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/S

#2660 chore: Version bump to 3.46
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#2657 Fixed the issues around ViewModels inside dialogs affecting the delet…
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/DeletePhoneDialogFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/EditPhoneNumberFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/UpdatePhoneDialogFragment.kt
Labels: Kotlin Migration, size/S

#2655 Feature: Settings Account - Delete Account functionality (Part 2)
  app/src/main/kotlin/com/waz/zclient/accounts/domain/usecase/GetActiveAccountUseCase.kt
  app/src/main/kotlin/com/waz/zclient/settings/about/SettingsAboutFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/deleteaccount/SettingsAccountDeleteAccountViewModel.kt
  app/src/test/kotlin/com/waz/zclient/accounts/AccountsDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/accounts/AccountsLocalDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/accounts/domain/usecase/GetActiveAccountUseCaseTest.kt
  app/src/test/kotlin/com/waz/zclient/settings/account/deleteaccount/DeleteAccountUseCaseTest.kt
  app/src/test/kotlin/com/waz/zclient/settings/account/deleteaccount/SettingsAccountDeleteAccountViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/user/data/source/remote/UserRemoteDataSourceTest.kt
Labels: size/L

#2663 AN-6714 && AN-6716: Conversation Search feature and about screen is broken
  app/src/main/kotlin/com/waz/zclient/settings/about/SettingsAboutActivity.kt
  app/src/main/kotlin/com/waz/zclient/settings/support/SettingsSupportActivity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/MessageContentIndexEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabaseMigration.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/MessageContentIndexDao.scala
Labels: Kotlin Migration, size/M

#2662 Create personal account part 4 - Send email verification code
  app/src/main/kotlin/com/waz/zclient/auth/registration/CreateAccountActivity.kt
  app/src/main/kotlin/com/waz/zclient/auth/registration/activation/ActivationApi.kt
  app/src/main/kotlin/com/waz/zclient/auth/registration/activation/ActivationDataSource.kt
  app/src/main/kotlin/com/waz/zclient/auth/registration/activation/ActivationRemoteDataSource.kt
  app/src/main/kotlin/com/waz/zclient/auth/registration/activation/ActivationRepository.kt
  app/src/main/kotlin/com/waz/zclient/auth/registration/activation/SendEmailActivationCodeUseCase.kt
  app/src/main/kotlin/com/waz/zclient/auth/registration/di/RegistrationModule.kt
  app/src/main/kotlin/com/waz/zclient/auth/registration/personal/CreatePersonalAccountViewModel.kt
  app/src/main/kotlin/com/waz/zclient/auth/registration/personal/email/CreatePersonalAccountWithEmailFragment.kt
  app/src/main/kotlin/com/waz/zclient/auth/registration/personal/email/CreatePersonalAccountWithEmailViewModel.kt
  app/src/main/kotlin/com/waz/zclient/core/exception/Failure.kt
  app/src/main/kotlin/com/waz/zclient/core/network/ApiService.kt
  app/src/test/kotlin/com/waz/zclient/auth/registration/activation/ActivationDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/auth/registration/activation/ActivationRemoteDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/auth/registration/activation/SendEmailActivationCodeUseCaseTest.kt
  app/src/test/kotlin/com/waz/zclient/auth/registration/personal/CreatePersonalAccountViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/auth/registration/personal/CreatePersonalAccountWithEmailViewModelTest.kt
Labels: Kotlin Migration, size/XL

#2666 ButtonData - data structure and database table
  storage/src/main/kotlin/com/waz/zclient/storage/db/ButtonEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabaseMigration.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/ButtonData.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/Uid.scala
Labels: size/M

#2640 refactor: Disable tracking on the TrackingService level
  app/src/main/scala/com/waz/zclient/pages/main/MainPhoneFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DataUsagePermissionsView.scala
  app/src/main/scala/com/waz/zclient/tracking/GlobalTrackingController.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/tracking/TrackingService.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/DisabledTrackingService.scala
Labels: size/L

#2669 Kotlin Code Review : moving layout id's to the constructor of activities/fragments
  app/src/main/kotlin/com/waz/zclient/features/auth/registration/CreateAccountActivity.kt
  app/src/main/kotlin/com/waz/zclient/features/settings/account/editphonenumber/EditPhoneNumberActivity.kt
  app/src/main/kotlin/com/waz/zclient/features/settings/devices/detail/SettingsDeviceDetailActivity.kt
  app/src/main/kotlin/com/waz/zclient/features/settings/main/SettingsMainActivity.kt
  app/src/main/kotlin/com/waz/zclient/settings/about/SettingsAboutActivity.kt
  app/src/main/kotlin/com/waz/zclient/settings/support/SettingsSupportActivity.kt
Labels: Kotlin Migration, size/S

#2670 Kotlin Code Review : rename confusing api/dao classes
  app/src/main/kotlin/com/waz/zclient/user/datasources/local/UsersLocalDataSource.kt
  app/src/main/kotlin/com/waz/zclient/user/datasources/remote/UserResponse.kt
  app/src/main/kotlin/com/waz/zclient/user/datasources/remote/UsersApi.kt
  app/src/main/kotlin/com/waz/zclient/user/datasources/remote/UsersRemoteDataSource.kt
  app/src/main/kotlin/com/waz/zclient/user/di/UsersModule.kt
  app/src/main/kotlin/com/waz/zclient/user/mapper/UserMapper.kt
  app/src/test/kotlin/com/waz/zclient/TestModels.kt
  app/src/test/kotlin/com/waz/zclient/user/datasources/UserDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/user/datasources/remote/UserRemoteDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/user/mapper/UserMapperTest.kt
Labels: Kotlin Migration, size/L

#2674 Feat: Buttons - Add migration for new Buttons table & change UserDatabase version
  storage/src/main/kotlin/com/waz/zclient/storage/db/ButtonEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabaseMigration.kt
Labels: size/S

#2668 Kotlin Code Review : remove implementation details from function names
  app/src/main/kotlin/com/waz/zclient/features/settings/about/SettingsAboutFragment.kt
  app/src/main/kotlin/com/waz/zclient/features/settings/account/edithandle/EditHandleDialogFragment.kt
  app/src/main/kotlin/com/waz/zclient/features/settings/devices/detail/SettingsDeviceDetailFragment.kt
  app/src/main/kotlin/com/waz/zclient/features/settings/devices/list/SettingsDeviceListFragment.kt
  app/src/main/kotlin/com/waz/zclient/features/settings/support/SettingsSupportFragment.kt
Labels: Kotlin Migration, size/L

#2673 fix: A fix to IndexOutOfBoundsException in PagedStorageDiffHelper
  app/src/main/scala/com/waz/zclient/messages/MessagePagedListController.scala
  app/src/main/scala/com/waz/zclient/messages/MessagesPagedListAdapter.scala
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/S

#2675 Feat: Buttons - Part 2: Add layouts for Composite view buttons
  app/src/main/res/drawable/alarm_button_progressbar_background.xml
  app/src/main/res/drawable/selector_alarm_confirmation_button_background.xml
  app/src/main/res/drawable/selector_alarm_confirmation_button_text_color.xml
  app/src/main/res/layout/composite_message_alarm_buttonitemview.xml
  app/src/main/res/layout/message_button.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/theme_attrs.xml
  app/src/main/res/values/themes.xml
  app/src/main/scala/com/waz/zclient/messages/parts/composite/ButtonContainerView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/composite/ButtonItemView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/composite/ButtonWithConfirmation.scala
  app/src/main/scala/com/waz/zclient/messages/parts/composite/CompositePartView.scala
Labels: size/L

#2680 Feat: Buttons - Display composite message
  app/src/main/res/drawable/selector_alarm_confirmation_button_background.xml
  app/src/main/res/layout/composite_message_alarm_buttonitemview.xml
  app/src/main/res/layout/layout_composite_message.xml
  app/src/main/res/layout/message_button.xml
  app/src/main/res/layout/message_composite.xml
  app/src/main/res/values/dimens.xml
  app/src/main/scala/com/waz/zclient/messages/MessageViewFactory.scala
  app/src/main/scala/com/waz/zclient/messages/MsgPart.scala
  app/src/main/scala/com/waz/zclient/messages/parts/composite/ButtonContainerView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/composite/CompositePartView.scala
Labels: size/L

#2679 AN-6745: Migration between app versions freezes the app - Part 1.
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyMap.kt
  storage/.gitignore
  storage/build.gradle
  storage/src/androidTest/kotlin/com/waz/zclient/storage/IntegrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/MigrationTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/globaldatabase/GlobalDatabase24to25MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/globaldatabase/GlobalSQLiteDbTestHelper.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/GlobalDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/accountdata/ActiveAccountsMigration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/accountdata/GlobalDatabaseMigration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/cache/CacheEntryDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/cache/CacheEntryEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/teams/TeamsDao.kt
Labels: size/XL

#2685 AN-6745: Migration between app versions freezes the app - Part 2.
  storage/src/androidTest/kotlin/com/waz/zclient/storage/accountdata/ActiveAccountsDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/accountdata/CacheEntryDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/accountdata/TeamsDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/globaldatabase/GlobalDatabase24to25MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/globaldatabase/GlobalSQLiteDbTestHelper.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/accountdata/ActiveAccountsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/cache/CacheEntryDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/teams/TeamsDao.kt
Labels: Kotlin Migration, size/L

#2688 AN-6745: Migration between app versions freezes the app - Part 3
  storage/src/androidTest/kotlin/com/waz/zclient/storage/DbSQLiteOpenHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/globaldatabase/GlobalDatabase24to25MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/globaldatabase/GlobalSQLiteDbTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/users/UsersTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/users/UsersTableTestHelper.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/model/UserEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/service/UserDao.kt
Labels: size/L

#2681 feat: Delete buttons when deleting messages
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/ButtonsStorage.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessagesContentUpdater.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/utils/CachedStorageImpl.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/MessagesServiceSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/conversation/ConversationServiceSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/conversation/ConversationsUiServiceSpec.scala
Labels: size/M

#2686 Feat: Buttons - Adjust notification, message content, and options menu for composite …
  app/src/main/res/layout/layout_composite_message.xml
  app/src/main/res/values/dimens.xml
  app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListRow.scala
  app/src/main/scala/com/waz/zclient/messages/MessageBottomSheetDialog.scala
  app/src/main/scala/com/waz/zclient/messages/MessageView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/composite/CompositePartView.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/GenericContent.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/MessageContentIndexDao.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/MessageData.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/ReceiptService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/push/NotificationService.scala
Labels: size/M

#2689 AN-6745: Migration between app versions freezes the app - Part 4
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase126To127Migration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabaseMigration.kt
Labels: Kotlin Migration, size/XL

#2690 AN-6745: Migration between app versions freezes the app - Part 5
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase126To127Migration.kt
Labels: Kotlin Migration, size/L

#2677 refactor: Automate turning collections of Identifiables into maps
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/AccentColor.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/otr/Client.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/sync/SyncJob.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/conversation/FoldersService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/otr/VerificationStateUpdater.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/push/NotificationService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/queue/SyncContentUpdater.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/utils/CachedStorageImpl.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/utils/package.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/ConversationRolesServiceSpec.scala
Labels: size/M

#2691 AN-6745: Migration between app versions freezes the app - Part 6
  app/src/main/kotlin/com/waz/zclient/user/User.kt
  app/src/main/kotlin/com/waz/zclient/user/datasources/UsersDataSource.kt
  app/src/main/kotlin/com/waz/zclient/user/datasources/remote/UserResponse.kt
  app/src/main/kotlin/com/waz/zclient/user/mapper/UserMapper.kt
  app/src/test/kotlin/com/waz/zclient/TestModels.kt
  app/src/test/kotlin/com/waz/zclient/user/datasources/UserDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/user/mapper/UserMapperTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase126To127Migration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/model/UserEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/model/UserPreferenceEntity.kt
Labels: size/M

#2695 AN-6745: Migration between app versions freezes the app - Part 8.
  storage/src/main/kotlin/com/waz/zclient/storage/db/contacts/ContactsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/contacts/ContactsOnWireEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversationmembers/ConversationMembersEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationRoleActionEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/email/EmailAddressesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/error/ErrorsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messagedeletion/MessageDeletionEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessagesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/phonenumbers/PhoneNumbersEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase126To127Migration.kt
Labels: size/L

#2694 AN-6745: Migration between app versions freezes the app - Part 7
  app/src/main/kotlin/com/waz/zclient/user/User.kt
  app/src/main/kotlin/com/waz/zclient/user/mapper/UserMapper.kt
  app/src/test/kotlin/com/waz/zclient/user/mapper/UserMapperTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/UserDatabase126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/users/UsersTableTestHelper.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/contacts/ContactsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/contacts/ContactsOnWireEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversationmembers/ConversationMembersEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationRoleActionEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/email/EmailAddressesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/error/ErrorsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messagedeletion/MessageDeletionEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessagesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/phonenumbers/PhoneNumbersEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase126To127Migration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/model/UserEntity.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/UserData.scala
Labels: size/XL

#2696 fix: The contents go to a wrong conversation
  app/src/main/scala/com/waz/zclient/messages/MessagePagedListController.scala
Labels: size/XS

#2697 Feat: Buttons - Show errors, add locator and fix progress background for composite buttons
  app/src/main/res/drawable/alarm_button_progressbar_background.xml
  app/src/main/res/layout/message_button.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/theme_attrs.xml
  app/src/main/res/values/themes.xml
  app/src/main/scala/com/waz/zclient/messages/parts/composite/ButtonItemView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/composite/ButtonWithConfirmation.scala
  storage/src/main/kotlin/com/waz/zclient/storage/db/ButtonEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase126To127Migration.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/ButtonData.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/sync/handler/MessagesSyncHandlerSpec.scala
Labels: size/L

#2699 UserDatabase Migration Tests: Part 1
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/UserDatabase126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/UserDatabaseHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/users/UsersTableTestHelper.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase126To127Migration.kt
Labels: Kotlin Migration, size/L

#2698 fix: Ignore incoming Button Action event
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
Labels: size/XS

#2701 UserDatabase Migration Tests: Part 2
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationFoldersTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationMembersTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationTables126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversatonsRoleActionTableTestHelper.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationFoldersDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationMembersDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationRoleActionDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationsDao.kt
Labels: Kotlin Migration, size/XL

#2705 UserDatabase Migration Tests: Part 4
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/errors/ErrorsTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/errors/ErrorsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/LikesTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessageContentIndexTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessageDeletionTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesTables126to127MigrationTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/likes/LikesDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessageContentIndexDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessageContentIndexEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessageDeletionEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessagesDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessagesDeletionDao.kt
Labels: size/L

#2700 UserDatabase Migration Tests: Part 3
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationFoldersTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationMembersTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationTables126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversatonsRoleActionTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/errors/ErrorsTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/errors/ErrorsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/LikesTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessageContentIndexTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessageDeletionTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesTables126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/sync/SyncJobsTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/sync/SyncJobsTableTestHelper.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationFoldersDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationMembersDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationRoleActionDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/errors/ErrorsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/errors/ErrorsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/likes/LikesDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessageContentIndexDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessageContentIndexEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessageDeletionEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessagesDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessagesDeletionDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/sync/SyncJobsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase126To127Migration.kt
Labels: size/XXL

#2703 UserDatabase Migration Tests: Part 5
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/UserDatabaseMigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetTables126to127MigrationTests.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetsV1TableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetsV2TableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/DownloadAssetsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/UploadAssetsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationTables126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/errors/ErrorsTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesTables126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/sync/SyncJobsTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/users/UserTable126to127MigrationTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/assets/AssetsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/assets/AssetsV1Dao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/assets/AssetsV1Entity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/assets/DownloadAssetsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/assets/UploadAssetsDao.kt
Labels: Kotlin Migration, size/XL

#2712 feat: Remove the background under the Buttons spinner
  app/src/main/res/drawable/alarm_button_progressbar_background.xml
  app/src/main/res/layout/message_button.xml
  app/src/main/res/values/theme_attrs.xml
  app/src/main/res/values/themes.xml
Labels: size/S

#2713 UserDatabase Migration Tests: Part 6
  storage/src/androidTest/kotlin/com/waz/zclient/storage/DbSQLiteOpenHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetsV1TableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetsV2TableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/DownloadAssetsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/UploadAssetsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/contact/ContactHashesTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/contact/ContactOnWireTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/contact/ContactTables126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/contact/ContactsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationFoldersTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationMembersTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversatonsRoleActionTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/errors/ErrorsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/LikesTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessageContentIndexTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessageDeletionTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/property/KeyValueTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/property/PropertiesTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/sync/SyncJobsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/users/UsersTableTestHelper.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/contacts/ContactHashesDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/contacts/ContactHashesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/contacts/ContactOnWireDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/contacts/ContactsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/property/PropertiesDao.kt
Labels: size/L

#2715 fix: Check if the poll's author is in the conversation
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/MessagesServiceSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/sync/handler/MessagesSyncHandlerSpec.scala
Labels: size/L

#2709 Settings Background - Part 1: Add AssetsRepository and related classes
  app/src/main/kotlin/com/waz/zclient/assets/AssetsApi.kt
  app/src/main/kotlin/com/waz/zclient/assets/AssetsRepository.kt
  app/src/main/kotlin/com/waz/zclient/assets/datasources/AssetsDataSource.kt
  app/src/main/kotlin/com/waz/zclient/assets/datasources/AssetsRemoteDataSource.kt
  app/src/main/kotlin/com/waz/zclient/assets/di/AssetsModule.kt
  app/src/main/kotlin/com/waz/zclient/assets/mapper/AssetMapper.kt
  app/src/main/kotlin/com/waz/zclient/core/di/Injector.kt
  app/src/test/kotlin/com/waz/zclient/assets/AssetsDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/assets/datasources/AssetsRemoteDataSourceTest.kt
Labels: Kotlin Migration, size/L

#2714 Fix: Do not match search query to user's email
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/UserData.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
Labels: size/S

#2710 Settings Background - Part 2: Fetch profile picture inputStream via Glide
  app/src/main/java/com/waz/zclient/WireGlideModule.java
  app/src/main/kotlin/com/waz/zclient/assets/di/AssetsModule.kt
  app/src/main/kotlin/com/waz/zclient/assets/usecase/GetPublicAssetUseCase.kt
  app/src/main/kotlin/com/waz/zclient/core/images/AssetKey.kt
  app/src/main/kotlin/com/waz/zclient/core/images/InputStreamLoader.kt
  app/src/main/kotlin/com/waz/zclient/core/images/InputStreamParserFactory.kt
  app/src/main/kotlin/com/waz/zclient/core/images/publicasset/PublicAssetFactory.kt
  app/src/main/kotlin/com/waz/zclient/features/settings/di/SettingsModule.kt
  app/src/main/kotlin/com/waz/zclient/features/settings/main/SettingsMainActivity.kt
  app/src/main/kotlin/com/waz/zclient/features/settings/main/SettingsMainViewModel.kt
  app/src/main/kotlin/com/waz/zclient/user/di/UsersModule.kt
  app/src/main/kotlin/com/waz/zclient/user/profile/GetUserProfilePictureUseCase.kt
  app/src/main/res-migration/layout/activity_settings.xml
  app/src/main/scala/com/waz/zclient/glide/AssetKey.scala
  app/src/main/scala/com/waz/zclient/glide/loaders/AssetModelLoader.scala
  app/src/main/scala/com/waz/zclient/glide/loaders/GoogleMapModelLoader.scala
  app/src/main/scala/com/waz/zclient/glide/loaders/PictureModelLoader.scala
  app/src/main/scala/com/waz/zclient/log/LogShowInstancesUI.scala
  app/src/test/kotlin/com/waz/zclient/assets/publicasset/GetPublicAssetUseCaseTest.kt
  app/src/test/kotlin/com/waz/zclient/core/images/AssetKeyTest.kt
  app/src/test/kotlin/com/waz/zclient/core/images/InputStreamFetcherTest.kt
  app/src/test/kotlin/com/waz/zclient/user/profile/GetUserProfilePictureUseCaseTest.kt
  detekt/config.yml
Labels: Kotlin Migration

#2719 UserDatabase Migration Tests: Part 9
  app/src/main/kotlin/com/waz/zclient/clients/di/ClientsModule.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/folders/FoldersTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/folders/FoldersTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/history/EditHistoryTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/history/EditHistoryTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/receipts/ReadReceiptsTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/receipts/ReadReceiptsTableTestHelper.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/folders/FoldersDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/history/EditHistoryDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/history/EditHistoryEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/receipts/ReadReceiptsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/receipts/ReadReceiptsEntity.kt
Labels: size/L

#2716 UserDatabase Migration Tests: Part 7
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/notifications/CloudNotificationsStatsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/notifications/CloudNotificationsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/notifications/NotificationDataTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/notifications/NotificationsTables126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/notifications/PushNotificationEventsTableTestHelper.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/CloudNotificationStatsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/CloudNotificationsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/NotificationDataDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/NotificationDataEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/PushNotificationEventDao.kt
Labels: size/L

#2717 UserDatabase Migration Tests: Part 8
  app/src/main/kotlin/com/waz/zclient/clients/di/ClientsModule.kt
  app/src/main/kotlin/com/waz/zclient/user/di/UsersModule.kt
  app/src/test/kotlin/com/waz/zclient/user/datasources/local/UserLocalDataSourceTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/clients/ClientsTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/clients/ClientsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/email/EmailAddressesTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/email/EmailAddressesTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/folders/FoldersTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/folders/FoldersTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/history/EditHistoryTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/history/EditHistoryTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/phone/PhoneNumbersTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/phone/PhoneNumbersTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/receipts/ReadReceiptsTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/receipts/ReadReceiptsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/users/UserTable126to127MigrationTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationMembersDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationMembersEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/email/EmailAddressesDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/folders/FoldersDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/history/EditHistoryDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/history/EditHistoryEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/LikesDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/LikesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/phone/PhoneNumbersDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/phone/PhoneNumbersEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/receipts/ReadReceiptsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/receipts/ReadReceiptsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/userclients/UserClientDao.kt
Labels: size/XL

#2720 UserDatabase Migration Tests: Part 10
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/UserDatabaseMigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetTables126to127MigrationTests.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/clients/ClientsTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/contact/ContactTables126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationTables126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/email/EmailAddressesTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/errors/ErrorsTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/folders/FoldersTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/history/EditHistoryTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesTables126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/notifications/NotificationsTables126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/phone/PhoneNumbersTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/property/PropertyTables126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/receipts/ReadReceiptsTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/sync/SyncJobsTable126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/users/UserTable126to127MigrationTest.kt
Labels: size/XL

#2725 UserDatabase Migration: Remove duplicated client entity from user database schema
  app/src/main/kotlin/com/waz/zclient/clients/di/ClientsModule.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
Labels: size/XS

#2730 AVS: Http proxy
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
Labels: size/XS

#2727 fix: Resend messages edited when offline
  app/src/main/scala/com/waz/zclient/common/controllers/AssetsController.scala
  app/src/main/scala/com/waz/zclient/conversation/ReplyView.scala
  app/src/main/scala/com/waz/zclient/cursor/CursorController.scala
  app/src/main/scala/com/waz/zclient/messages/MessageBottomSheetDialog.scala
  app/src/main/scala/com/waz/zclient/messages/MessageView.scala
  app/src/main/scala/com/waz/zclient/messages/MessageViewPart.scala
  app/src/main/scala/com/waz/zclient/messages/parts/ReplyPartView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/footer/FooterViewController.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/MessageData.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
Labels: size/M

#2731 fix: Display websites' previews on Android 9-10
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/api/impl/ErrorResponse.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/OpenGraphClient.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/znet2/HttpClientOkHttpImpl.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/znet2/http/HttpClient.scala
Labels: size/S

#2702 fix: Postpone processing notifications until after the sync
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/push/NotificationService.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/notifications/NotificationServiceSpec.scala
Labels: size/XL

#2733 Spike: Codecov - part 1
  app/build.gradle
  app/jacoco/coverage.gradle
  build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/M

#2721 Add extension functions for image loading (Glide)
  app/src/main/kotlin/com/waz/zclient/core/extension/ImageLoading.kt
  app/src/main/kotlin/com/waz/zclient/core/images/ViewBackgroundTarget.kt
  app/src/main/kotlin/com/waz/zclient/features/settings/main/SettingsMainActivity.kt
  app/src/test/kotlin/com/waz/zclient/core/extension/RequestBuilderExtensionsTest.kt
  app/src/test/kotlin/com/waz/zclient/core/images/ViewBackgroundTargetTest.kt
Labels: size/L

#2728 fix : slide in/slide out animation for settings screens
  app/src/main/kotlin/com/waz/zclient/settings/about/SettingsAboutActivity.kt
  app/src/main/kotlin/com/waz/zclient/settings/support/SettingsSupportActivity.kt
  app/src/main/res/anim/slide_in_left.xml
  app/src/main/res/anim/slide_out_right.xml
Labels: size/M

#2726 Settings background: Add image transformations, show background in About and Support
  app/src/main/kotlin/com/waz/zclient/assets/di/AssetsModule.kt
  app/src/main/kotlin/com/waz/zclient/core/images/transformations/AppBackgroundTransformations.kt
  app/src/main/kotlin/com/waz/zclient/core/images/transformations/BlurTransformation.kt
  app/src/main/kotlin/com/waz/zclient/core/images/transformations/DarkenTransformation.kt
  app/src/main/kotlin/com/waz/zclient/core/images/transformations/ScaleTransformation.kt
  app/src/main/kotlin/com/waz/zclient/core/ui/backgroundasset/BackgroundAssetObserver.kt
  app/src/main/kotlin/com/waz/zclient/core/ui/backgroundasset/BackgroundAssetOwner.kt
  app/src/main/kotlin/com/waz/zclient/core/ui/backgroundasset/BackgroundAssetViewModel.kt
  app/src/main/kotlin/com/waz/zclient/features/settings/di/SettingsModule.kt
  app/src/main/kotlin/com/waz/zclient/features/settings/main/SettingsMainActivity.kt
  app/src/main/kotlin/com/waz/zclient/settings/about/SettingsAboutActivity.kt
  app/src/main/kotlin/com/waz/zclient/settings/support/SettingsSupportActivity.kt
  app/src/main/res-migration/layout/activity_settings_about.xml
  app/src/main/res-migration/layout/activity_settings_support.xml
  app/src/main/scala/com/waz/zclient/glide/BackgroundRequest.scala
  app/src/main/scala/com/waz/zclient/glide/transformations/BlurTransformation.scala
  app/src/main/scala/com/waz/zclient/glide/transformations/DarkenTransformation.scala
  app/src/main/scala/com/waz/zclient/glide/transformations/GlyphOverlayTransformation.scala
  app/src/main/scala/com/waz/zclient/glide/transformations/GreyScaleTransformation.scala
  app/src/main/scala/com/waz/zclient/glide/transformations/ScaleTransformation.scala
  app/src/main/scala/com/waz/zclient/messages/parts/YouTubePartView.scala
  app/src/main/scala/com/waz/zclient/pages/main/ImagePreviewLayout.scala
  app/src/test/kotlin/com/waz/zclient/core/ui/backgroundasset/ActivityBackgroundAssetObserverTest.kt
  app/src/test/kotlin/com/waz/zclient/core/ui/backgroundasset/BackgroundAssetViewModelTest.kt
Labels: size/XL
