Repository wireapp/wire-android, pull requests merged in 2020-04, with the labels that each got.

#2722 feat: Remove MessageIndexStorage to assist migration
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/collection/controllers/CollectionController.scala
  app/src/main/scala/com/waz/zclient/usersearch/views/SearchResultRowView.scala
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessageContentIndexTableTestHelper.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessageContentIndexDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessageContentIndexEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase126To127Migration.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/api/ContentSearchQuery.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/ConvMessagesIndex.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/MessageIndexStorage.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/MessageContentIndexDao.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/MessageData.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/ZMessagingDBSpec.scala
Labels: size/L

#2738 Scala: About & Support screen rollback.
  app/src/main/res/layout/preferences_about.xml
  app/src/main/res/layout/preferences_about_layout.xml
  app/src/main/res/layout/preferences_support.xml
  app/src/main/res/layout/preferences_support_layout.xml
  app/src/main/scala/com/waz/zclient/preferences/pages/AboutView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/SettingsView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/SupportView.scala
Labels: Kotlin Migration, size/L

#2724 Networking enhancements Part 2: Dynamic backend
  app/src/main/kotlin/com/waz/zclient/core/backend/BackendConfig.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/BackendRepository.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/CustomBackend.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/BackendDataSource.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/local/BackendLocalDataSource.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/local/CustomBackendPreferences.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/remote/BackendApi.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/remote/BackendApiService.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/remote/BackendRemoteDataSource.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/remote/CustomBackendResponse.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/di/BackendModule.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/items/BackendItem.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/items/ProductionBackendItem.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/items/QaBackendItem.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/items/StagingBackendItem.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/mapper/BackendMapper.kt
  app/src/main/kotlin/com/waz/zclient/core/di/Injector.kt
  app/src/main/kotlin/com/waz/zclient/core/extension/Either.kt
  app/src/main/kotlin/com/waz/zclient/core/functional/Either.kt
  app/src/main/kotlin/com/waz/zclient/core/functional/FallbackOnFailure.kt
  app/src/main/kotlin/com/waz/zclient/core/network/accesstoken/AccessTokenAuthenticator.kt
  app/src/main/kotlin/com/waz/zclient/core/network/accesstoken/AccessTokenLocalDataSource.kt
  app/src/main/kotlin/com/waz/zclient/core/network/backend/CustomBackendInterceptor.kt
  app/src/main/kotlin/com/waz/zclient/core/network/di/NetworkModule.kt
  app/src/main/kotlin/com/waz/zclient/user/datasources/local/UsersLocalDataSource.kt
  app/src/test/kotlin/com/waz/zclient/core/backend/BackendClientTest.kt
  app/src/test/kotlin/com/waz/zclient/user/datasources/local/UserLocalDataSourceTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/di/StorageModule.kt
  storage/src/main/kotlin/com/waz/zclient/storage/extension/String.kt
  storage/src/main/kotlin/com/waz/zclient/storage/pref/backend/BackendPreferences.kt
  storage/src/main/kotlin/com/waz/zclient/storage/pref/global/GlobalPreferences.kt
  storage/src/main/kotlin/com/waz/zclient/storage/pref/user/UserPreferences.kt
  storage/src/test/kotlin/com/waz/zclient/storage/pref/UserPreferencesTest.kt
Labels: Kotlin Migration, size/XL

#2723 Networking enhancements Part 1: Security
  app/src/main/kotlin/com/waz/zclient/clients/datasources/ClientsDataSource.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/BackendRepository.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/CustomBackend.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/BackendDataSource.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/local/BackendLocalDataSource.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/local/CustomBackendPreferences.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/remote/BackendApi.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/remote/BackendApiService.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/remote/BackendRemoteDataSource.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/remote/CustomBackendResponse.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/di/BackendModule.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/items/BackendItem.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/items/ProductionBackendItem.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/items/QaBackendItem.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/items/StagingBackendItem.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/mapper/BackendMapper.kt
  app/src/main/kotlin/com/waz/zclient/core/config/Config.kt
  app/src/main/kotlin/com/waz/zclient/core/di/Injector.kt
  app/src/main/kotlin/com/waz/zclient/core/extension/Either.kt
  app/src/main/kotlin/com/waz/zclient/core/functional/Either.kt
  app/src/main/kotlin/com/waz/zclient/core/functional/FallbackOnFailure.kt
  app/src/main/kotlin/com/waz/zclient/core/network/accesstoken/AccessTokenAuthenticator.kt
  app/src/main/kotlin/com/waz/zclient/core/network/accesstoken/AccessTokenLocalDataSource.kt
  app/src/main/kotlin/com/waz/zclient/core/network/backend/CustomBackendInterceptor.kt
  app/src/main/kotlin/com/waz/zclient/core/network/connection/ConnectionSpecsFactory.kt
  app/src/main/kotlin/com/waz/zclient/core/network/di/NetworkModule.kt
  app/src/main/kotlin/com/waz/zclient/core/network/pinning/CertificatePin.kt
  app/src/main/kotlin/com/waz/zclient/core/network/pinning/CertificatePinnerFactory.kt
  app/src/main/kotlin/com/waz/zclient/core/network/proxy/HttpProxyFactory.kt
  app/src/main/kotlin/com/waz/zclient/core/network/useragent/UserAgentInterceptor.kt
  app/src/main/kotlin/com/waz/zclient/core/utilities/base64/Base64Transformer.kt
  app/src/main/kotlin/com/waz/zclient/user/datasources/local/UsersLocalDataSource.kt
  app/src/test/kotlin/com/waz/zclient/clients/datasources/ClientDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/core/backend/BackendClientTest.kt
  app/src/test/kotlin/com/waz/zclient/core/backend/BackendDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/core/backend/datasources/local/BackendLocalDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/core/backend/datasources/remote/BackendApiServiceTest.kt
  app/src/test/kotlin/com/waz/zclient/core/backend/datasources/remote/BackendRemoteDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/core/backend/mapper/BackendMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/core/functional/FallbackOnFailureTest.kt
  app/src/test/kotlin/com/waz/zclient/core/network/connection/ConnectionSpecsFactoryTest.kt
  app/src/test/kotlin/com/waz/zclient/core/network/pinning/CertificatePinnerFactoryTest.kt
  app/src/test/kotlin/com/waz/zclient/core/network/pinning/PinGeneratorTest.kt
  app/src/test/kotlin/com/waz/zclient/core/network/proxy/HttpProxyFactoryTest.kt
  app/src/test/kotlin/com/waz/zclient/core/network/useragent/UserAgentInterceptorTest.kt
  app/src/test/kotlin/com/waz/zclient/user/datasources/local/UserLocalDataSourceTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/di/StorageModule.kt
  storage/src/main/kotlin/com/waz/zclient/storage/extension/String.kt
  storage/src/main/kotlin/com/waz/zclient/storage/pref/backend/BackendPreferences.kt
  storage/src/main/kotlin/com/waz/zclient/storage/pref/global/GlobalPreferences.kt
  storage/src/main/kotlin/com/waz/zclient/storage/pref/user/UserPreferences.kt
  storage/src/test/kotlin/com/waz/zclient/storage/pref/UserPreferencesTest.kt
Labels: Kotlin Migration, size/XXL

#2739 build : bump version to 3.47
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#2736 Spike: Codecov - part 2
  app/build.gradle
  app/jacoco/coverage.gradle
  build.gradle
  jacoco/coverage.gradle
Labels: size/M

#2743 AN-6806 Fix: About screen crash
  app/proguard-rules.txt
Labels: size/XS

#2747 fix: Dismiss associated notification when the conversation is opened
  app/src/main/scala/com/waz/zclient/notifications/controllers/MessageNotificationsController.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/push/NotificationService.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/notifications/NotificationServiceSpec.scala
Labels: size/M

#2748 fix : revert MessageContentIndex table to fix search content with special characters
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/collection/controllers/CollectionController.scala
  app/src/main/scala/com/waz/zclient/usersearch/views/SearchResultRowView.scala
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/UserDatabaseHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessageContentIndexTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesTables126to127MigrationTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessageContentIndexDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessageContentIndexEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase126To127Migration.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/api/ContentSearchQuery.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/ConvMessagesIndex.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/MessageIndexStorage.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/MessageContentIndexDao.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/MessageData.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
Labels: size/L

#2744 Large Teams: Remove obsolete team events and team size threshold
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
  app/src/main/scala/com/waz/zclient/conversation/creation/AddParticipantsFragment.scala
  app/src/main/scala/com/waz/zclient/conversationlist/adapters/ConversationListAdapter.scala
  app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListRow.scala
  app/src/main/scala/com/waz/zclient/cursor/MentionCandidatesAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/usersearch/SearchUIAdapter.scala
  app/src/main/scala/com/waz/zclient/usersearch/domain/RetrieveSearchResults.scala
  app/src/main/scala/com/waz/zclient/usersearch/listitems/ConnectionViewItem.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/Event.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/TeamSizeThreshold.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/UserService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/TeamsSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/TeamSizeThresholdSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/UserServiceSpec.scala
Labels: DO NOT MERGE, size/L

#2754 Create personal account part 5
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/CreateAccountActivity.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountWithEmailFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountWithEmailViewModel.kt
  app/src/main/kotlin/com/waz/zclient/shared/activation/usecase/SendEmailActivationCodeUseCase.kt
  app/src/main/res-migration/layout/activity_create_account.xml
  app/src/main/res-migration/layout/fragment_create_personal_account_with_email.xml
  app/src/main/res-migration/values/styles_button.xml
  app/src/main/res-migration/values/styles_edittext.xml
  app/src/main/res-migration/values/styles_textview.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/personal/CreatePersonalAccountWithEmailViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/activation/SendEmailActivationCodeUseCaseTest.kt
Labels: size/L

#2759 Potential fix for black screen
  buildSrc/src/main/kotlin/Dependencies.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/Preferences.scala
Labels: size/XS

#2758 Migration: Anomalies
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationTables126to127MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationsTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesTables126to127MigrationTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationRoleActionEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/history/EditHistoryEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessagesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/PushNotificationEventEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase126To127Migration.kt
Labels: size/M

#2749 Kotlin: Refactor Backend configuration, resolve circular dependency
  app/src/main/kotlin/com/waz/zclient/core/backend/BackendItem.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/BackendRepository.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/CustomBackend.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/BackendDataSource.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/local/BackendLocalDataSource.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/local/CustomBackendPreferences.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/di/BackendModule.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/di/BackendRemoteDataSourceProvider.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/items/BackendItem.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/items/ProductionBackendItem.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/items/QaBackendItem.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/items/StagingBackendItem.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/mapper/BackendMapper.kt
  app/src/main/kotlin/com/waz/zclient/core/network/backend/CustomBackendInterceptor.kt
  app/src/main/kotlin/com/waz/zclient/core/network/di/NetworkModule.kt
  app/src/test/kotlin/com/waz/zclient/core/backend/BackendClientTest.kt
  app/src/test/kotlin/com/waz/zclient/core/backend/BackendDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/core/backend/datasources/local/BackendLocalDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/core/backend/mapper/BackendMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/core/network/backend/CustomBackendInterceptorTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/pref/backend/BackendPreferences.kt
Labels: size/XL

#2750 Kotlin Backend - Part 2: Scope backend configuration for dynamic change
  app/src/main/kotlin/com/waz/zclient/core/backend/BackendRepository.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/datasources/BackendDataSource.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/di/BackendConfigScopeManager.kt
  app/src/main/kotlin/com/waz/zclient/core/backend/di/BackendModule.kt
  app/src/main/scala/com/waz/zclient/utils/BackendController.scala
  app/src/test/kotlin/com/waz/zclient/core/backend/BackendDataSourceTest.kt
Labels: size/L

#2753 feat: Changes to the availability status
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/OtrClient.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/UserSearchSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/UsersSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/sync/handler/UsersSyncHandlerSpec.scala
Labels: size/L

#2761 Large Teams: Sync user data when you click on their profile
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
Labels: size/S

#2763 Scala - Room DB migration tests on Scala side
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase126To127Migration.kt
  wire-android-sync-engine/zmessaging/build.gradle
  wire-android-sync-engine/zmessaging/src/main/java/com/waz/api/Temp.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/ButtonData.scala
  wire-android-sync-engine/zmessaging/src/test/java/com/waz/KotlinMigrationHelper.kt
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/MigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/RoomDaoDBMigrationTest.scala
Labels: size/L

#2768 Scala Migration tests - Part 2
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetTables126to127MigrationTests.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationTables126to127MigrationTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/assets/AssetsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/assets/UploadAssetsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/contacts/ContactHashesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationMembersDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/property/PropertiesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase126To127Migration.kt
  wire-android-sync-engine/zmessaging/src/test/java/com/waz/KotlinMigrationHelper.kt
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/Assets2MigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/AssetsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/ContactHashesMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/ContactsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/ContactsOnWireMigration.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/ConversationFolderMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/ConversationMembersMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/ConversationRoleActionMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/ConversationsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/DownloadAssetMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/EditHistoryMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/EmailAddressesMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/ErrorsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/FcmNotificationStatsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/FcmNotificationsMigration.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/FoldersMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/KeyValueMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/LikingsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/MessageContentIndexMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/MessageDeletionMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/MessagesMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/MigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/NotificationDataMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/PhoneNumbersMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/PropertiesMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/PushNotificationEventsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/ReadReceiptMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/SyncJobsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/UploadAssetMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/UserClientsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/UsersMigrationTest.scala
Labels: size/XXL

#2771 versionName refactory
  app/build.gradle
Labels: size/S

#2770 Scala migration tests - Part 3
  storage/src/main/kotlin/com/waz/zclient/storage/db/accountdata/AccessTokenEntity.kt
  wire-android-sync-engine/zmessaging/src/main/java/com/waz/api/Temp.kt
  wire-android-sync-engine/zmessaging/src/test/java/com/waz/db/migration/KotlinMigrationHelper.kt
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/globaldatabase/ActiveAccountsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/globaldatabase/CacheEntryMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/globaldatabase/GlobalDatabaseMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/globaldatabase/TeamsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/Assets2MigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/AssetsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/ContactHashesMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/ContactsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/ContactsOnWireMigration.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/ConversationFolderMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/ConversationMembersMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/ConversationRoleActionMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/ConversationsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/DownloadAssetMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/EditHistoryMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/EmailAddressesMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/ErrorsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/FcmNotificationStatsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/FcmNotificationsMigration.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/FoldersMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/KeyValueMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/LikingsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/MessageContentIndexMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/MessageDeletionMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/MessagesMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/NotificationDataMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/PhoneNumbersMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/PropertiesMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/PushNotificationEventsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/ReadReceiptMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/RoomDaoDBMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/SyncJobsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/UploadAssetMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/UserClientsMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/UserDatabaseMigrationTest.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/UsersMigrationTest.scala
Labels: size/XXL

#2773 Add logs to some signals and database operations
  app/src/main/scala/com/waz/zclient/utils/package.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/ConvMessagesIndex.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/Preferences.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/db/Dao.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/utils/events/ClockSignal.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/utils/events/Signal.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/utils/wrappers/DB.scala
Labels: size/L

#2774 fix: A small change to how we handle a failure in RefreshSignal
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/utils/events/Signal.scala
Labels: size/S

#2775 Create personal account part 8
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/di/RegistrationModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountEmailInputFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountEmailVerificationFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountNameInputFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountPasswordInputFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountWithEmailViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/register/RegisterRepository.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/register/datasources/RegisterDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/register/datasources/remote/RegisterApi.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/register/datasources/remote/RegisterRemoteDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/register/usecase/RegisterPersonalAccountWithEmailUseCase.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/personal/CreatePersonalAccountWithEmailViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/register/datasources/RegisterDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/register/datasources/remote/RegisterRemoteDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/register/usecase/RegisterPersonalAccountWithEmailUseCaseTest.kt
Labels: Kotlin Migration, size/XL

#2780 fix: Global database changes moved to a new migration
  storage/src/main/kotlin/com/waz/zclient/storage/db/GlobalDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/accountdata/GlobalDatabaseMigration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase127To128Migration.kt
Labels: size/M

#2785 Revert team member sync
  app/src/main/scala/com/waz/zclient/search/SearchController.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/TeamsClient.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/TeamsSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/sync/client/TeamsClientSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/sync/handler/TeamsSyncHandlerSpec.scala
Labels: size/M

#2787 Create personal account - part 10
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/di/RegistrationModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/CreatePersonalAccountViewPagerAdapter.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountEmailFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountNameFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountPasswordFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountPinCodeFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountWithEmailViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/EmailCredentialsViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/phone/CreatePersonalAccountPhoneFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/phone/CreatePersonalAccountWithPhoneFragment.kt
  app/src/main/res-migration/layout/fragment_create_personal_account_email.xml
  app/src/main/res-migration/layout/fragment_create_personal_account_name.xml
  app/src/main/res-migration/layout/fragment_create_personal_account_password.xml
  app/src/main/res-migration/layout/fragment_create_personal_account_phone.xml
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/personal/CreatePersonalAccountWithEmailViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/personal/EmailCredentialsViewModelTest.kt
Labels: Kotlin Migration, size/L

#2665 fix: Default config values
  app/build.gradle
  app/src/main/AndroidManifest.xml
  default.json
Labels: size/M

#2790 Copy change fo the enterprise login popup around linear onboarding
  app/src/main/res/values/strings.xml
Labels: size/XS

#2794 Fix: wrong target branch - Create Personal Account
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/di/RegistrationModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountEmailFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountNameFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountWithEmailViewModel.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/di/UsersModule.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/name/ValidateNameUseCase.kt
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/personal/CreatePersonalAccountWithEmailViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/user/name/ValidateNameUseCaseTest.kt
Labels: size/L

#2793 Fix false-positives in integration tests
  storage/src/androidTest/kotlin/com/waz/zclient/storage/accountdata/ActiveAccountsDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/accountdata/CacheEntryDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/accountdata/TeamsDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/globaldatabase/GlobalDatabase24to25MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetTables126to128MigrationTests.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/clients/ClientsTable126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/contact/ContactTables126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationTables126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/email/EmailAddressesTable126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/errors/ErrorsTable126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/folders/FoldersTable126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/history/EditHistoryTable126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesTables126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/notifications/NotificationsTables126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/phone/PhoneNumbersTable126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/property/PropertyTables126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/receipts/ReadReceiptsTable126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/sync/SyncJobsTable126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/users/UserTable126to128MigrationTest.kt
Labels: size/XL

#2795 Create personal account - part 12
  app/src/main/kotlin/com/waz/zclient/core/config/Config.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/di/RegistrationModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountPasswordFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountWithEmailViewModel.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/di/UsersModule.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/email/ValidateEmailUseCase.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/name/ValidateNameUseCase.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/password/ValidatePasswordUseCase.kt
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/personal/CreatePersonalAccountWithEmailViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/user/password/ValidatePasswordUseCaseTest.kt
Labels: Kotlin Migration, size/L

#2788 Large Teams: External users
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/UserData.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/AccountManager.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/TeamsClient.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/TeamsSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/UserSearchSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/UsersSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/teams/TeamsServiceSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/sync/handler/TeamsSyncHandlerSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/sync/handler/UserSearchSyncHandlerSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/sync/handler/UsersSyncHandlerSpec.scala
Labels: size/L

#2800 fix: Perform full sync after update
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/Preferences.scala
Labels: size/XS

#2791 AN-6847: Linear onboarding refactor
  app/src/main/res/layout/fragment_start_sso.xml
  app/src/main/scala/com/waz/zclient/appentry/AppEntryActivity.scala
  app/src/main/scala/com/waz/zclient/appentry/CustomBackendLoginFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/SSOFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/StartSSOFragment.scala
Labels: size/L

#2802 AN-6869: Enterprise login: registered domain + no fixed sso user cannot login
  app/src/main/scala/com/waz/zclient/appentry/SSOFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/StartSSOFragment.scala
Labels: size/S

#2804 fix: An error is JSON deserialization in team/[tid]/members
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/TeamsClient.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/TeamsSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/sync/client/TeamsClientSpec.scala
Labels: size/XS

#2805 Fix: App crash on Android 5 and 6 devices
  app/src/main/kotlin/com/waz/zclient/core/images/transformations/DarkenTransformation.kt
  app/src/main/kotlin/com/waz/zclient/core/images/transformations/ScaleTransformation.kt
Labels: size/S

#2806 Enterprise login copy change
  app/src/main/res/values/strings.xml
Labels: size/XS

#2808 Enterprise login: Enter a valid SSO code doesn't open SSO login page for registered domain+no fixed SSO code user
  app/src/main/scala/com/waz/zclient/appentry/SSOFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/StartSSOFragment.scala
Labels: size/S

#2809 fix: Bring back exact match search
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/SearchQuery.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/UserSearchClient.scala
Labels: size/S

#2811 Translations: redundant string from Tier 1 teams
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/usersearch/SearchUIAdapter.scala
Labels: size/XS

#2801 Create personal account part 13
  app/build.gradle
  app/src/main/kotlin/com/waz/zclient/core/extension/Activity.kt
  app/src/main/kotlin/com/waz/zclient/core/extension/Fragment.kt
  app/src/main/kotlin/com/waz/zclient/core/extension/View.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/CreatePersonalAccountFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/CreatePersonalAccountViewPagerAdapter.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountEmailFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountNameFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountPasswordFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountPinCodeFragment.kt
  app/src/main/res-migration/layout/fragment_create_personal_account.xml
  app/src/main/res-migration/layout/fragment_create_personal_account_email.xml
  app/src/main/res-migration/layout/fragment_create_personal_account_name.xml
  app/src/main/res-migration/layout/fragment_create_personal_account_password.xml
  app/src/main/res-migration/layout/fragment_create_personal_account_phone.xml
  app/src/main/res-migration/layout/fragment_create_personal_account_pin_code.xml
  app/src/main/res/values/dimens.xml
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/personal/CreatePersonalAccountViewPagerAdapterTest.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyMap.kt
Labels: size/L

#2812 fix: Exact match search
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/UserSearchClient.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/UsersClient.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/UserSearchSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/sync/handler/UserSearchSyncHandlerSpec.scala
Labels: size/M
