Repository wireapp/wire-android, pull requests merged in 2020-05, with the labels that each got.

#2818 AN-6883: I should see no results message on Add people page when search ends up not matching
  app/src/main/scala/com/waz/zclient/search/SearchController.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
Labels: size/S

#2819 fix: Show profiles from search + Don't show exact match search twice + Case-insensitive exact match search
  app/src/main/scala/com/waz/zclient/usersearch/SearchUIFragment.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/UsersClient.scala
Labels: size/M

#2820 AN-6876: A partner team member should not be found in Group creation
  app/src/main/scala/com/waz/zclient/conversation/creation/AddParticipantsFragment.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
Labels: size/S

#2824 fix: Show an external/partner user in the Add to Group screen
  app/src/main/scala/com/waz/zclient/conversation/creation/AddParticipantsFragment.scala
Labels: size/S

#2825 updated avs version to 5.5.11
  app/build.gradle
Labels: size/XS

#2830 Clean up Timber leftover
  app/config/lint-config-with-unused.xml
  app/opensource.txt
  app/src/main/scala/com/waz/zclient/WireContext.scala
Labels: size/XS

#2826 fix: Migrate data only if the original table exists
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/MigrationUtils.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase127To128Migration.kt
Labels: size/M

#2813 Feat: Logout functionality in Kotlin - Part 4
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/SettingsAccountFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/SettingsAccountViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/logout/LogoutUseCase.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/logout/LogoutViewModel.kt
  app/src/main/kotlin/com/waz/zclient/shared/accounts/usecase/GetActiveAccountUseCase.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/account/SettingsAccountViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/account/logout/LogoutUseCaseTest.kt
Labels: Kotlin Migration, size/L

#2810 Feat: Logout functionality in Kotlin - Part 3
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/SettingsAccountFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/SettingsAccountViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/logout/LogoutUseCase.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/logout/LogoutViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/di/SettingsModule.kt
  app/src/main/kotlin/com/waz/zclient/shared/accounts/AccountsRepository.kt
  app/src/main/kotlin/com/waz/zclient/shared/accounts/datasources/AccountsDataSource.kt
  app/src/main/kotlin/com/waz/zclient/shared/accounts/datasources/local/AccountsLocalDataSource.kt
  app/src/main/kotlin/com/waz/zclient/shared/accounts/usecase/GetActiveAccountUseCase.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/UsersRepository.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/datasources/UsersDataSource.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/datasources/local/UsersLocalDataSource.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/account/SettingsAccountViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/account/logout/LogoutUseCaseTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/accounts/datasources/AccountsDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/accounts/datasources/local/AccountsLocalDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/accounts/usecase/GetActiveAccountUseCaseTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/accountdata/ActiveAccountsDaoTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/accountdata/ActiveAccountsDao.kt
Labels: Kotlin Migration, size/L

#2797 Feat: Logout functionality in Kotlin - Part 2
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/SettingsAccountFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/SettingsAccountViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/logout/LogoutUseCase.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/logout/LogoutViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/di/SettingsModule.kt
  app/src/main/kotlin/com/waz/zclient/shared/accounts/AccountsRepository.kt
  app/src/main/kotlin/com/waz/zclient/shared/accounts/datasources/AccountsDataSource.kt
  app/src/main/kotlin/com/waz/zclient/shared/accounts/datasources/local/AccountsLocalDataSource.kt
  app/src/main/kotlin/com/waz/zclient/shared/accounts/usecase/GetActiveAccountUseCase.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/UsersRepository.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/datasources/UsersDataSource.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/datasources/local/UsersLocalDataSource.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/account/SettingsAccountViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/account/logout/LogoutUseCaseTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/accounts/datasources/AccountsDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/accounts/datasources/local/AccountsLocalDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/accounts/usecase/GetActiveAccountUseCaseTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/accountdata/ActiveAccountsDaoTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/accountdata/AccessTokenEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/accountdata/ActiveAccountsDao.kt
Labels: Kotlin Migration, size/XL

#2815 Feat: Logout functionality in Kotlin - Part 5
  wire-android-sync-engine/zmessaging/build.gradle
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/AccountsService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/GlobalModule.scala
Labels: Kotlin Migration, size/M

#2779 Feat: Logout functionality in Kotlin
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/waz/zclient/core/network/accesstoken/AccessTokenRepository.kt
  app/src/main/kotlin/com/waz/zclient/core/network/api/token/TokenApi.kt
  app/src/main/kotlin/com/waz/zclient/core/network/api/token/TokenService.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/SettingsAccountFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/SettingsAccountViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/logout/LogoutDialogFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/logout/LogoutUseCase.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/logout/LogoutViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/di/SettingsModule.kt
  app/src/main/kotlin/com/waz/zclient/shared/accounts/AccountsRepository.kt
  app/src/main/kotlin/com/waz/zclient/shared/accounts/datasources/AccountsDataSource.kt
  app/src/main/kotlin/com/waz/zclient/shared/accounts/datasources/local/AccountsLocalDataSource.kt
  app/src/main/kotlin/com/waz/zclient/shared/accounts/datasources/remote/AccountsRemoteDataSource.kt
  app/src/main/kotlin/com/waz/zclient/shared/accounts/di/AccountsModule.kt
  app/src/main/kotlin/com/waz/zclient/shared/accounts/usecase/GetActiveAccountUseCase.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/UsersRepository.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/datasources/UsersDataSource.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/datasources/local/UsersLocalDataSource.kt
  app/src/main/res-migration/layout/activity_settings_about.xml
  app/src/test/kotlin/com/waz/zclient/core/network/api/token/TokenServiceTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/account/SettingsAccountViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/account/logout/LogoutUseCaseTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/account/logout/LogoutViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/accounts/datasources/AccountsDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/accounts/datasources/local/AccountsLocalDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/accounts/datasources/remote/AccountsRemoteDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/accounts/usecase/GetActiveAccountUseCaseTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/accountdata/ActiveAccountsDaoTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/accountdata/AccessTokenEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/accountdata/ActiveAccountsDao.kt
  wire-android-sync-engine/zmessaging/build.gradle
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/AccountsService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/GlobalModule.scala
Labels: Kotlin Migration, size/XXL

#2832 Feature - OnBoarding Flow tweaks - part 1
  app/src/main/res-migration/drawable/dark_gray_circle.xml
  app/src/main/res-migration/drawable/ic_info.xml
  app/src/main/res-migration/drawable/ic_wire_logo.xml
  app/src/main/res-migration/values/colors.xml
  app/src/main/res/layout/fragment_start_sso.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/appentry/StartSSOFragment.scala
Labels: size/L

#2833 fix: Too many prekeys requests
  wire-android-sync-engine/zmessaging/build.gradle
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/MessagesClient.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/OtrClient.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/LastReadSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/otr/OtrClientsSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
Labels: size/M

#2835 Feature: onBoarding flow tweaks - part 2
  app/src/main/res-migration/drawable/start_sso_circular_progress_bar.xml
  app/src/main/res/layout/fragment_start_sso.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/appentry/StartSSOFragment.scala
Labels: size/M

#2837 Feature: on boarding flow tweaks - design reviews
  app/src/main/res/layout/fragment_start_sso.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: size/S

#2839 Feature: onBoarding tweaks - copy change
  app/src/main/res/values/strings.xml
Labels: size/XS

#2841 AN-6765: App bypasses Do Not Disturb settings
  app/src/main/scala/com/waz/zclient/common/controllers/SoundController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/NotificationManagerWrapper.scala
Labels: size/M

#2845 fix: Re-add hanfling of team.member-join events
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model/Event.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
Labels: size/S

#2846 fix: Update conversation names in real time
  app/src/main/scala/com/waz/zclient/conversationlist/ConversationListController.scala
  app/src/main/scala/com/waz/zclient/conversationlist/adapters/ConversationListAdapter.scala
  app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListRow.scala
Labels: size/S

#2848 feat: Update or delete UserData on sending messages and accessing profiles
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/messages/UsersController.scala
  app/src/main/scala/com/waz/zclient/pages/main/conversation/ConversationManagerFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantFragment.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/UserService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/otr/OtrServiceImpl.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/UsersClient.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/OpenGraphSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/UserServiceSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/teams/TeamsServiceSpec.scala
Labels: DO NOT MERGE, size/L

#2853 fix: ConversationListRow should update the subtitle and badge
  app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListRow.scala
Labels: size/S

#2857 fix: Update user data on opening the user profile
  app/src/main/scala/com/waz/zclient/pages/main/conversation/ConversationManagerFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantFragment.scala
Labels: size/L

#2856 Conversation search: Duplicated message + won't scroll when selected.
  app/src/main/scala/com/waz/zclient/collection/adapters/SearchAdapter.scala
  app/src/main/scala/com/waz/zclient/collection/fragments/CollectionFragment.scala
  app/src/main/scala/com/waz/zclient/messages/MessagePagedListController.scala
  app/src/main/scala/com/waz/zclient/messages/controllers/MessageActionsController.scala
  app/src/main/scala/com/waz/zclient/messages/parts/TextPartView.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/api/ContentSearchQuery.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/MessageIndexStorage.scala
Labels: size/M

#2855 bump version
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#2852 Fix flaky unit tests & polish some
  app/src/main/kotlin/com/waz/zclient/feature/settings/devices/detail/SettingsDeviceDetailViewModel.kt
  app/src/test/kotlin/com/waz/zclient/core/network/ApiServiceTest.kt
  app/src/test/kotlin/com/waz/zclient/core/network/pinning/CertificatePinnerFactoryTest.kt
  app/src/test/kotlin/com/waz/zclient/core/ui/backgroundasset/BackgroundAssetViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/personal/CreatePersonalAccountViewPagerAdapterTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/about/SettingsAboutViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/account/SettingsAccountViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/account/deleteaccount/SettingsAccountDeleteAccountViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/account/edithandle/SettingsAccountEditHandleViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/account/logout/LogoutViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/devices/detail/SettingsDeviceDetailViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/settings/devices/list/SettingsDeviceListViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/framework/livedata/OneTimeObserver.kt
  app/src/test/kotlin/com/waz/zclient/shared/user/datasources/local/UserLocalDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/user/handle/usecase/GetHandleUseCaseTest.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/L

#2816 Create personal account - part 14
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountEmailFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountPasswordFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountPinCodeFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountWithEmailViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/personal/CreatePersonalAccountWithEmailViewModelTest.kt
Labels: Kotlin Migration, size/L

#2860 Fixed the crash related to Android lollipop due to the API 23 minimum…
  app/src/main/scala/com/waz/zclient/common/controllers/SoundController.scala
Labels: size/M

#2844 Create personal account - part 15
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/CreateAccountFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/di/RegistrationModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountEmailFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountEmailViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/email/CreatePersonalAccountWithEmailViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/name/CreatePersonalAccountNameFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/name/CreatePersonalAccountNameViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/password/CreatePersonalAccountPasswordFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/password/CreatePersonalAccountPasswordViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/pincode/CreatePersonalAccountPinCodeFragment.kt
  app/src/main/kotlin/com/waz/zclient/feature/auth/registration/personal/pincode/CreatePersonalAccountPinCodeViewModel.kt
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/personal/CreatePersonalAccountEmailViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/personal/CreatePersonalAccountNameViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/personal/CreatePersonalAccountPasswordViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/personal/CreatePersonalAccountPinCodeViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/personal/CreatePersonalAccountWithEmailViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/auth/registration/personal/EmailCredentialsViewModelTest.kt
Labels: Kotlin Migration, size/XXL

#2866 Add timeout value to LiveData.awaitValue()
  app/src/test/kotlin/com/waz/zclient/framework/livedata/OneTimeObserver.kt
Labels: size/S
