Repository wireapp/wire-android, pull requests merged in 2020-10, with the labels that each got.

#3038 [Conference Calling] : Call degradation + AVS version bump
  app/build.gradle
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/calling/CallingActivity.scala
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
Labels: size/L

#3039 fix: TrackingService methods crash if tracking is disabled
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/conversation/ImageFragment.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/tracking/TrackingService.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
Labels: size/L

#3040 fix: (Analytics) Wrong toggles displayed on Data Usage Permission Page
  app/src/main/res/layout/data_usage_permissions_layout.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/common/controllers/UserAccountsController.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DataUsagePermissionsView.scala
Labels: size/M

#3042 [Bugfix : Call Degradation] : Call degradation popup should be displayed when Self User adds a new device
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
Labels: size/XS

#3043 AVS bump to 6.4.4
  app/build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#3045 Add locators for data usage toggles
  app/src/main/res/layout/data_usage_permissions_layout.xml
Labels: size/XS

#3046 Changes needed to work with wire-signals 0.2.4
  app/src/main/scala/com/waz/zclient/WireContext.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/AccountView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DeviceDetailsView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DevicesView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/OptionsView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/ProfilePictureView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/ProfileView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/SettingsView.scala
  buildSrc/src/main/kotlin/Dependencies.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/AccountContext.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/conversation/TypingService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/threading/Threading.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/ui/UiModule.scala
Labels: size/L

#3037 Allow for custom HTTP Proxy settings in AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/waz/zclient/KotlinServices.kt
  app/src/main/kotlin/com/waz/zclient/core/network/di/NetworkModule.kt
  app/src/main/kotlin/com/waz/zclient/core/network/proxy/HttpProxyFactory.kt
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/test/kotlin/com/waz/zclient/core/network/proxy/HttpProxyFactoryTest.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/GlobalModule.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/HttpProxy.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/MetaDataService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/ui/UiCache.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/HttpProxySpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
Labels: size/L

#3047 Bump AVS version to 6.4.9
  app/build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#3051 Fix: Android 11 UI Distortion + memory leaks along the way
  app/src/main/res/layout/main.xml
  app/src/main/scala/com/waz/zclient/LaunchActivity.scala
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/WireContext.scala
  app/src/main/scala/com/waz/zclient/appentry/AppEntryActivity.scala
  app/src/main/scala/com/waz/zclient/conversationlist/ConversationListFragment.scala
  app/src/main/scala/com/waz/zclient/security/ActivityLifecycleCallback.scala
  app/src/main/scala/com/waz/zclient/usersearch/SearchUIFragment.scala
Labels: size/M

#3034 Camera to Camera2 API Migration
  app/src/main/java/com/waz/zclient/camera/CameraPreviewObserver.java
  app/src/main/java/com/waz/zclient/camera/FlashMode.java
  app/src/main/java/com/waz/zclient/pages/extendedcursor/image/CursorCameraLayout.java
  app/src/main/java/com/waz/zclient/pages/extendedcursor/image/CursorImagesAdapter.java
  app/src/main/java/com/waz/zclient/pages/extendedcursor/image/CursorImagesLayout.java
  app/src/main/java/com/waz/zclient/pages/main/profile/camera/controls/CameraTopControl.java
  app/src/main/java/com/waz/zclient/utils/CameraParamsWrapper.java
  app/src/main/java/com/waz/zclient/utils/DeprecationUtils.java
  app/src/main/scala/com/waz/zclient/camera/CameraFragment.scala
  app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
  app/src/main/scala/com/waz/zclient/camera/controllers/GlobalCameraController.scala
  app/src/main/scala/com/waz/zclient/camera/views/CameraPreviewTextureView.scala
  app/src/main/scala/com/waz/zclient/pages/main/ImagePreviewLayout.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
Labels: Work In Progress

#3053 Switch preference automation toggles
  app/src/main/scala/com/waz/zclient/preferences/views/SwitchPreference.scala
Labels: size/S

#3023 Bump Android SDK 29
  app/build.gradle
  app/src/main/java/com/waz/zclient/camera/CameraPreviewObserver.java
  app/src/main/java/com/waz/zclient/camera/FlashMode.java
  app/src/main/java/com/waz/zclient/markdown/spans/custom/CustomQuoteSpan.kt
  app/src/main/java/com/waz/zclient/markdown/spans/custom/ListPrefixSpan.kt
  app/src/main/java/com/waz/zclient/markdown/spans/custom/MarkdownLinkSpan.kt
  app/src/main/java/com/waz/zclient/pages/extendedcursor/image/CursorCameraLayout.java
  app/src/main/java/com/waz/zclient/pages/extendedcursor/image/CursorImagesAdapter.java
  app/src/main/java/com/waz/zclient/pages/extendedcursor/image/CursorImagesLayout.java
  app/src/main/java/com/waz/zclient/pages/main/profile/camera/controls/CameraTopControl.java
  app/src/main/java/com/waz/zclient/utils/CameraParamsWrapper.java
  app/src/main/java/com/waz/zclient/utils/DeprecationUtils.java
  app/src/main/kotlin/com/waz/zclient/core/extension/Activity.kt
  app/src/main/scala/com/waz/zclient/ShareActivity.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/FirstLaunchAfterLoginFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/SetNameFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/camera/CameraFragment.scala
  app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
  app/src/main/scala/com/waz/zclient/camera/controllers/GlobalCameraController.scala
  app/src/main/scala/com/waz/zclient/camera/views/CameraPreviewTextureView.scala
  app/src/main/scala/com/waz/zclient/common/controllers/AssetsController.scala
  app/src/main/scala/com/waz/zclient/common/controllers/SharingController.scala
  app/src/main/scala/com/waz/zclient/conversation/creation/CreateConversationManagerFragment.scala
  app/src/main/scala/com/waz/zclient/messages/controllers/MessageActionsController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/CallingNotificationsController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/NotificationManagerWrapper.scala
  app/src/main/scala/com/waz/zclient/pages/main/ImagePreviewLayout.scala
  app/src/main/scala/com/waz/zclient/preferences/PreferencesActivity.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/BackupExportView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DeviceDetailsView.scala
  app/src/main/scala/com/waz/zclient/utils/BackendController.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
  build.gradle
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/Preferences.scala
Labels: size/L

#3055 Bump AVS version to 6.4.12
  app/build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#3049 Changes required to bump Android SDK to 30
  app/src/main/java/com/waz/zclient/utils/DeprecationUtils.java
  app/src/main/kotlin/com/waz/zclient/feature/settings/account/editphonenumber/EditPhoneNumberActivity.kt
  app/src/main/kotlin/com/waz/zclient/feature/settings/devices/detail/SettingsDeviceDetailActivity.kt
  app/src/main/scala/com/waz/zclient/appentry/CustomBackendLoginFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/WelcomeFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/VerifyEmailWithCodeFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/VerifyPhoneFragment.scala
  app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
  app/src/main/scala/com/waz/zclient/conversation/TypingIndicatorView.scala
  app/src/main/scala/com/waz/zclient/preferences/dialogs/ChangeHandleFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/dialogs/ChangePhoneDialog.scala
  app/src/main/scala/com/waz/zclient/preferences/dialogs/VerifyEmailPreferencesFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/dialogs/VerifyPhoneFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DevSettingsView.scala
  app/src/main/scala/com/waz/zclient/utils/ContextUtils.scala
  build.gradle
Labels: DO NOT MERGE

#2993 No unencrypted traffic to Wire
  app/src/main/res/xml/network_security_config.xml
Labels: security, size/XS

#3058 Fix AVS open source version number
  app/build.gradle
Labels: size/XS

#3061 Add legacy external storage request flag to overcome scoped storage on Android 11 devices
  app/src/main/AndroidManifest.xml
Labels: size/XS

#3054 Refactor AVS Versionning
  app/build.gradle
  avs/avs.gradle
  build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
  wire-android-sync-engine/zmessaging/build.gradle
Labels: size/L

#3063 Bugfix : AVS versioning
  avs/avs.gradle
Labels: size/S

#3066 Fix error while sharing small files
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/znet2/http/HttpClient.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/znet2/ProgressFilterSpec.scala
Labels: size/M

#3068 Fix: Sending Files through attachment button not successful when saved from Wire Chat
  app/src/main/scala/com/waz/zclient/common/controllers/AssetsController.scala
Labels: size/S

#3070 Fix: Camera crash for devices pre-API28
  app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
Labels: size/XS

#3072 Fix: auto focus now doesn't reset when tapped continually + fix for fatal crash
  app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
Labels: size/S

#3074 Fix image saving for Android Q and onwards
  app/src/main/scala/com/waz/zclient/common/controllers/AssetsController.scala
Labels: size/M

#3069 Fix : Make sure non-team users never send analytics data even if they turned analytics on
  app/src/main/scala/com/waz/zclient/MainActivity.scala
Labels: size/XS

#3075 Fixed crash related to IllegalStateException when buffer limit is exc…
  app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
Labels: size/XS

#3073 Build System Improvement - Part 1 : main build.gradle file
  app/build.gradle
  build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
  common-test/build.gradle
  custom-checkstyle/build.gradle
  macrosupport/build.gradle
  scripts/ci.gradle
  scripts/customization.gradle
  scripts/jacoco.gradle
  scripts/licensing.gradle
  storage/build.gradle
  zmessaging/build.gradle
Labels: size/XL

#3076 Additional fix : Make sure non-team users never send analytics data even if they turned analytics on
  app/src/main/scala/com/waz/zclient/tracking/GlobalTrackingController.scala
Labels: size/M

#3077 Fix: user is logged out once they upgrading to 3.58, if they're logged in on an older version
  app/src/main/scala/com/waz/zclient/utils/BackendController.scala
Labels: size/XS
