Repository wireapp/wire-android, pull requests merged in 2020-02, with the labels that each got.

#2582 Refactor Kotlin styles
  app/src/main/res-v2/layout/fragment_settings_about.xml
  app/src/main/res-v2/layout/fragment_settings_account.xml
  app/src/main/res-v2/layout/fragment_settings_support.xml
  app/src/main/res-v2/layout/item_settings.xml
  app/src/main/res-v2/values/styles.xml
  app/src/main/res-v2/values/styles_button.xml
  app/src/main/res-v2/values/styles_textview.xml
Labels: size/L

#2583 Refactor Milestone 1 - Feature onBoarding Flow
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/waz/zclient/auth/AuthenticationActivity.kt
  app/src/main/kotlin/com/waz/zclient/auth/WelcomeFragment.kt
  app/src/main/res-v2/layout/activity_authentication.xml
  app/src/main/res/layout/fragment_create_account.xml
  app/src/main/res/layout/fragment_transparent_sso.xml
  app/src/main/res/layout/fragment_welcome.xml
  app/src/main/res/layout/sign_in_email_scene.xml
  app/src/main/res/values/themes.xml
  app/src/main/scala/com/waz/zclient/LaunchActivity.scala
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/appentry/AppEntryActivity.scala
  app/src/main/scala/com/waz/zclient/appentry/CreateAccountFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/TransparentSSOActivity.scala
  app/src/main/scala/com/waz/zclient/appentry/TransparentSSOFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/WelcomeFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/SignInFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/ProfileView.scala
Labels: size/L

#2573 Handle onBackPressed on connect request screens opened with deep links
  app/src/main/scala/com/waz/zclient/conversationlist/ConversationListManagerFragment.scala
  app/src/main/scala/com/waz/zclient/deeplinks/DeepLinkService.scala
  app/src/main/scala/com/waz/zclient/pages/main/MainPhoneFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SendConnectRequestFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/UntabbedRequestFragment.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
Labels: size/L

#2587 Edit phone screen (Part 4) - Refactoring and test cases
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/waz/zclient/core/extension/Fragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/SettingsAccountFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/di/SettingsAccountModule.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/DeletePhoneDialogFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/EditPhoneNumberActivity.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/EditPhoneNumberFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/SettingsAccountPhoneNumberViewModel.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/UpdatePhoneDialogFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/VerifyPhoneFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/main/SettingsMainActivity.kt
  app/src/main/kotlin/com/waz/zclient/user/data/UsersDataSource.kt
  app/src/main/kotlin/com/waz/zclient/user/data/UsersRepository.kt
  app/src/main/kotlin/com/waz/zclient/user/data/phone/PhoneNumberDataSource.kt
  app/src/main/kotlin/com/waz/zclient/user/data/phone/PhoneNumberRepository.kt
  app/src/main/kotlin/com/waz/zclient/user/di/UsersModule.kt
  app/src/main/kotlin/com/waz/zclient/user/domain/usecase/phonenumber/ChangePhoneNumberUseCase.kt
  app/src/main/kotlin/com/waz/zclient/user/domain/usecase/phonenumber/DeletePhoneNumberUseCase.kt
  app/src/test/kotlin/com/waz/zclient/settings/account/editphonenumber/SettingsAccountPhoneNumberViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/user/data/UserRepositoryTest.kt
  app/src/test/kotlin/com/waz/zclient/user/data/phone/PhoneNumberRepositoryTest.kt
  app/src/test/kotlin/com/waz/zclient/user/domain/usecase/phonenumber/ChangePhoneNumberUseCaseTest.kt
  app/src/test/kotlin/com/waz/zclient/user/domain/usecase/phonenumber/DeletePhoneNumberUseCaseTest.kt
Labels: Kotlin Migration, size/XL

#2590 AN-6641: Settings Support Screen
  app/src/main/kotlin/com/waz/zclient/di/Injector.kt
  app/src/main/kotlin/com/waz/zclient/settings/support/SettingsSupportFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/support/SettingsSupportViewModel.kt
  app/src/main/kotlin/com/waz/zclient/settings/support/di/SettingsSupportModule.kt
  app/src/main/res-v2/layout/fragment_settings_support.xml
  app/src/test/kotlin/com/waz/zclient/settings/support/SettingsSupportViewModelTest.kt
Labels: Kotlin Migration, size/L

#2588 AN-6639: Settings about screen
  app/build.gradle
  app/src/main/kotlin/com/waz/zclient/core/config/Config.kt
  app/src/main/kotlin/com/waz/zclient/core/extension/Activity.kt
  app/src/main/kotlin/com/waz/zclient/core/extension/Fragment.kt
  app/src/main/kotlin/com/waz/zclient/di/Injector.kt
  app/src/main/kotlin/com/waz/zclient/settings/about/SettingsAboutFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/about/SettingsAboutViewModel.kt
  app/src/main/kotlin/com/waz/zclient/settings/about/di/settingsAboutModule.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/EditPhoneNumberFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/main/SettingsMainFragment.kt
  app/src/main/res-v2/layout/activity_settings_new.xml
  app/src/main/res-v2/layout/fragment_settings_about.xml
  app/src/main/res-v2/layout/toolbar_container.xml
  app/src/test/kotlin/com/waz/zclient/settings/about/SettingsAboutViewModelTest.kt
  buildSrc/src/main/kotlin/DependencyMap.kt
Labels: Kotlin Migration, size/L

#2592 Feature: Linear onBoarding flow m2
  app/src/main/AndroidManifest.xml
  app/src/main/res-v2/values/colors.xml
  app/src/main/res/layout/app_entry_scene.xml
  app/src/main/res/layout/dialog_with_input_field.xml
  app/src/main/res/layout/fragment_custom_backend_login.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/appentry/AppEntryActivity.scala
  app/src/main/scala/com/waz/zclient/appentry/AppLaunchFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/CustomBackendLoginFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/FragmentTransactionHelper.scala
  app/src/main/scala/com/waz/zclient/appentry/SSOFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/WelcomeFragment.scala
Labels: size/XL

#2596 Removed failing test
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/FoldersServiceSpec.scala
Labels: size/M

#2594 Remove Timber dependency from app
  app/build.gradle
  app/src/main/java/com/waz/zclient/ZApplication.java
  app/src/main/java/com/waz/zclient/broadcast/ReferralBroadcastReceiver.java
  app/src/main/java/com/waz/zclient/controllers/navigation/NavigationController.java
  app/src/main/java/com/waz/zclient/pages/main/conversation/AssetIntentsManager.java
  app/src/main/java/com/waz/zclient/pages/main/conversation/LocationFragment.java
  app/src/main/java/com/waz/zclient/pages/main/conversationlist/views/listview/ContextWrapperEdgeEffect.java
  app/src/main/java/com/waz/zclient/pages/main/conversationlist/views/listview/SwipeListView.java
  app/src/main/java/com/waz/zclient/pages/main/conversationpager/SlidingPaneLayout.java
  app/src/main/java/com/waz/zclient/ui/cursor/CursorEditText.java
  app/src/main/java/com/waz/zclient/ui/text/AccentColorEditText.java
  app/src/main/java/com/waz/zclient/ui/text/LinkTextView.java
  app/src/main/java/com/waz/zclient/ui/utils/DrawableUtils.java
  app/src/main/java/com/waz/zclient/ui/utils/TextViewUtils.java
  app/src/main/java/com/waz/zclient/utils/LayoutSpec.java
  app/src/main/java/com/waz/zclient/utils/WireLoggerTree.java
  app/src/main/java/com/waz/zclient/utils/keyboard/KeyboardVisibilityListener.java
  app/src/main/kotlin/com/waz/zclient/core/logging/Logger.kt
  app/src/main/kotlin/com/waz/zclient/core/network/SafeApiDataSource.kt
  app/src/main/scala/com/waz/zclient/camera/controllers/GlobalCameraController.scala
  app/src/main/scala/com/waz/zclient/camera/views/CameraPreviewTextureView.scala
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: Collective Action Item

#2593 Room Migration: Scala Compatibility
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabaseMigration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/model/UserDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/model/UserPreferenceDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/service/UserDbService.kt
  storage/src/main/kotlin/com/waz/zclient/storage/di/StorageModule.kt
Labels: Kotlin Migration, size/L

#2597 Feature onBoarding flow : milestone 1/2 design review
  app/src/main/res-v2/drawable/blue_rounded_button.xml
  app/src/main/res-v2/drawable/dark_gray_rounded_button.xml
  app/src/main/res-v2/drawable/light_gray_blue_rounded_button.xml
  app/src/main/res-v2/values/colors.xml
  app/src/main/res/layout/fragment_custom_backend_login.xml
  app/src/main/res/layout/fragment_welcome.xml
Labels: size/L

#2595 BugFix : Missing error case - onBoarding flow milestone 2
  app/src/main/scala/com/waz/zclient/appentry/SSOFragment.scala
Labels: size/S

#2599 Database classes naming refactor
  app/src/main/kotlin/com/waz/zclient/devices/data/source/ClientMapper.kt
  app/src/main/kotlin/com/waz/zclient/devices/data/source/local/ClientsLocalDataSource.kt
  app/src/main/kotlin/com/waz/zclient/user/data/mapper/UserMapper.kt
  app/src/main/kotlin/com/waz/zclient/user/data/source/local/UsersLocalDataSource.kt
  app/src/test/kotlin/com/waz/zclient/TestModels.kt
  app/src/test/kotlin/com/waz/zclient/devices/data/ClientsRepositoryTest.kt
  app/src/test/kotlin/com/waz/zclient/devices/data/source/local/ClientsLocalDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/user/data/source/local/UserLocalDataSourceTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/clients/model/ClientEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/clients/service/ClientsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/model/UserEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/model/UserPreferenceEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/service/UserDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/service/UserPreferenceDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/service/UserPreferenceDbService.kt
Labels: size/L

#2601 chore: copy change for backend config dialog
  app/src/main/res/values/strings.xml
Labels: size/XS

#2600 Kotlin cleanup + retrospective
  app/src/main/java/com/waz/zclient/ZApplication.java
  app/src/main/kotlin/com/waz/zclient/core/config/Config.kt
  app/src/main/kotlin/com/waz/zclient/core/di/Injector.kt
  app/src/main/kotlin/com/waz/zclient/core/extension/Activity.kt
  app/src/main/kotlin/com/waz/zclient/core/ui/dialog/EditTextDialogFragment.kt
  app/src/main/kotlin/com/waz/zclient/features/clients/ClientEntity.kt
  app/src/main/kotlin/com/waz/zclient/settings/about/SettingsAboutViewModel.kt
  app/src/main/kotlin/com/waz/zclient/settings/about/di/settingsAboutModule.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/SettingsAccountFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/SettingsAccountViewModel.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/di/SettingsAccountModule.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/edithandle/EditHandleFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/edithandle/SettingsAccountEditHandleViewModel.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/EditPhoneNumberActivity.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/EditPhoneNumberFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/UpdatePhoneDialogFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/di/SettingsModule.kt
  app/src/main/kotlin/com/waz/zclient/settings/main/SettingsMainFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/main/list/SettingsMainListFactory.kt
  app/src/main/kotlin/com/waz/zclient/settings/main/list/SettingsMainListItemsFactory.kt
  app/src/main/kotlin/com/waz/zclient/settings/support/SettingsSupportViewModel.kt
  app/src/main/kotlin/com/waz/zclient/settings/support/di/SettingsSupportModule.kt
  app/src/main/kotlin/com/waz/zclient/user/data/UsersDataSource.kt
  app/src/main/kotlin/com/waz/zclient/user/data/UsersRepository.kt
  app/src/main/kotlin/com/waz/zclient/user/data/handle/UserHandleDataSource.kt
  app/src/main/kotlin/com/waz/zclient/user/data/handle/UserHandleRepository.kt
  app/src/main/kotlin/com/waz/zclient/user/di/UsersModule.kt
  app/src/main/kotlin/com/waz/zclient/user/domain/usecase/handle/ChangeHandleUseCase.kt
  app/src/main/kotlin/com/waz/zclient/user/domain/usecase/handle/CheckHandleExistsUseCase.kt
  app/src/main/kotlin/com/waz/zclient/user/domain/usecase/handle/GetHandleUseCase.kt
  app/src/main/kotlin/com/waz/zclient/user/domain/usecase/phonenumber/ValidatePhoneNumberUseCase.kt
  app/src/main/res-v2/layout/dialog_fragment_edit_text.xml
  app/src/main/res-v2/layout/fragment_edit_handle_dialog.xml
  app/src/main/res-v2/layout/fragment_settings_main.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/waz/zclient/settings/about/SettingsAboutViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/settings/account/SettingsAccountViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/settings/account/edithandle/SettingsAccountEditHandleViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/user/data/UserRepositoryTest.kt
  app/src/test/kotlin/com/waz/zclient/user/data/handle/UserHandleDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/user/domain/usecase/handle/ChangeHandleUseCaseTest.kt
  app/src/test/kotlin/com/waz/zclient/user/domain/usecase/handle/CheckHandleExistsUseCaseTest.kt
Labels: Kotlin Migration

#2602 bugfix (M2 onboarding flow) : Flow should be restarted when I click on SSO link again
  app/src/main/scala/com/waz/zclient/appentry/SSOWebViewFragment.scala
Labels: size/M

#2603 Fix: Linear Onboarding - Add error message for custom backend server not found error case
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/appentry/AppEntryActivity.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/api/impl/ErrorResponse.scala
Labels: size/S

#2606 Bump major version to 3.45
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#2598 Edit Phone: Pick Country Code dialog
  app/src/main/kotlin/com/waz/zclient/core/config/Config.kt
  app/src/main/kotlin/com/waz/zclient/core/usecase/UseCase.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/di/SettingsAccountModule.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/edithandle/SettingsAccountEditHandleViewModel.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/CountryCodePickerFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/CountryCodePickerViewModel.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/CountryCodesRecyclerAdapter.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/EditPhoneNumberFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/GetCountryCodesUseCase.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/SettingsAccountPhoneNumberViewModel.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/UpdatePhoneDialogFragment.kt
  app/src/main/kotlin/com/waz/zclient/user/domain/usecase/phonenumber/Country.kt
  app/src/main/kotlin/com/waz/zclient/user/domain/usecase/phonenumber/CountryCodeAndPhoneNumberUseCase.kt
  app/src/main/res-v2/layout/fragment_dialog_country_code_picker.xml
  app/src/main/res-v2/layout/fragment_edit_phone.xml
  app/src/main/res-v2/layout/item_view_country_code.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/waz/zclient/settings/account/editphonenumber/CountryCodePickerViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/settings/account/editphonenumber/GetCountryCodesUseCaseTest.kt
  app/src/test/kotlin/com/waz/zclient/settings/account/editphonenumber/SettingsAccountPhoneNumberViewModelTest.kt
Labels: Kotlin Migration, size/XL

#2608 Refactor: Inflation logic + Settings back stack fix
  app/src/main/kotlin/com/waz/zclient/settings/about/SettingsAboutFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/SettingsAccountFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/edithandle/EditHandleDialogFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/CountryCodePickerFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/EditPhoneNumberActivity.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/EditPhoneNumberFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/advanced/SettingsAdvancedFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/main/SettingsMainActivity.kt
  app/src/main/kotlin/com/waz/zclient/settings/main/SettingsMainFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/options/SettingsOptionsFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/support/SettingsSupportFragment.kt
Labels: Kotlin Migration, size/M

#2577 A fix for backup restoration
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/appentry/fragments/FirstLaunchAfterLoginFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/PhoneSetNameFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/SetTeamPasswordFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/VerifyEmailWithCodeFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/VerifyPhoneFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/dialogs/BackupPasswordDialog.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/BackupExportView.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/AccountManager.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/AccountsService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/backup/BackupManager.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/backup/BackupManagerSpec.scala
Labels: size/L

#2609 Refactor assets to enable image rotation and avoid unnecessary creation of files
  app/src/androidTest/scala/com/waz/zclient/assets/AssetServiceTest.scala
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/assets/AndroidImageRecoder.scala
  app/src/main/scala/com/waz/zclient/assets/AndroidUriHelper.scala
  app/src/main/scala/com/waz/zclient/assets/AssetPreviewServiceImpl.scala
  app/src/main/scala/com/waz/zclient/assets/ImageCompressUtils.scala
  app/src/main/scala/com/waz/zclient/common/controllers/AssetsController.scala
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  app/src/main/scala/com/waz/zclient/drawing/DrawingFragment.scala
  app/src/main/scala/com/waz/zclient/glide/AssetRequest.scala
  app/src/main/scala/com/waz/zclient/glide/ImageAssetFetcher.scala
  app/src/main/scala/com/waz/zclient/glide/loaders/GoogleMapModelLoader.scala
  app/src/main/scala/com/waz/zclient/messages/controllers/MessageActionsController.scala
  app/src/main/scala/com/waz/zclient/messages/parts/assets/VideoAssetPartView.scala
  app/src/main/scala/com/waz/zclient/utils/LocalThumbnailCache.scala
  app/src/main/scala/com/waz/zclient/utils/package.scala
  buildSrc/src/main/kotlin/Dependencies.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/assets/AssetInput.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/assets/AssetService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/assets/AssetTransformationsService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/assets/Encryption.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/assets/ImageRecoder.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/assets/Storage.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/assets/UriHelper.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/assets/models.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/media/GoogleMapsMediaService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/utils/crypto/AESUtils.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/assets2/AssetServiceSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/utils/TestUriHelper.scala
Labels: size/XL

#2607 Feature onBoarding flow milestone 3
  app/src/main/scala/com/waz/zclient/appentry/CustomBackendLoginFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/SSOFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/SSOWebViewFragment.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model2/transport/responses/FetchSsoResponse.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/SSOService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/LoginClient.scala
Labels: size/M

#2614 Fix: Update room db version and fix migration versions
  storage/src/main/kotlin/com/waz/zclient/storage/db/GlobalDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabaseMigration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/di/StorageModule.kt
  wire-android-sync-engine/zmessaging/build.gradle
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/RoomDbCompatibilitySpec.scala
Labels: size/M

#2617 Bump internal avs version to 5.5.6
  .gitignore
  app/build.gradle
Labels: size/XS

#2618 chore: OkHttp update to 3.14.6
  app/build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#2620 Resources cleanup session - Part 3
  app/src/main/res/values-sw320dp/dimens.xml
  app/src/main/res/values-sw320dp/integers.xml
  app/src/main/res/values-sw360dp/dimens.xml
  app/src/main/res/values-sw600dp-land/colors.xml
  app/src/main/res/values-sw600dp-land/cursor.xml
  app/src/main/res/values-sw600dp-land/dimens.xml
  app/src/main/res/values-sw600dp-port/cursor.xml
  app/src/main/res/values-sw600dp-port/dimens.xml
  app/src/main/res/values-sw600dp/dimens.xml
  app/src/main/res/values-sw720dp-land/dimens.xml
  app/src/main/res/values-sw720dp-port/dimens.xml
  app/src/main/res/values-sw720dp/dimens.xml
  app/src/main/res/values-xxhdpi/dimens.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/floats.xml
  app/src/main/res/values/ids.xml
  app/src/main/res/values/integers.xml
Labels: size/XL

#2578 Refactor SafeApiDataSource: Prettify request APIs
  app/src/main/kotlin/com/waz/zclient/core/functional/FallbackOnFailure.kt
  app/src/main/kotlin/com/waz/zclient/core/network/SafeApiDataSource.kt
  app/src/main/kotlin/com/waz/zclient/devices/data/ClientsDataSource.kt
  app/src/test/kotlin/com/waz/zclient/core/functional/FallbackOnFailureTest.kt
Labels: Kotlin Migration, size/L

#2616 fix: Make WSPushService more responsive
  app/src/main/scala/com/waz/services/websocket/WebSocketService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/NetworkModeService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/push/PushService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/push/WSPushService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/queue/SyncExecutor.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/queue/SyncScheduler.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/znet2/WebSocketFactory.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/model2/transport/responses/DomainVerificationResponseSpec.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/sync/SyncRequestServiceSpec.scala
Labels: size/L

#2619 fix: A race condition when a push notification results in a new message
  app/src/main/AndroidManifest.xml
  app/src/main/scala/com/waz/services/fcm/FCMHandlerService.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/MessageNotificationsController.scala
  buildSrc/src/main/kotlin/Dependencies.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessagesContentUpdater.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/ReceiptService.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/push/PushService.scala
Labels: size/M

#2625 Migrating Room entities from Scala part 1
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/assets/AssetsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/assets/DownloadAssetsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/assets/UploadAssetsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationFoldersEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationRoleActionEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/EditHistoryEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/MessageContentIndexEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ReadReceiptsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/folders/FoldersEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/CloudNotificationStatsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/CloudNotificationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/PushNotificationEventEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/properties/PropertiesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/model/UserEntity.kt
Labels: Kotlin Migration, size/L

#2623 Scala/Room integration - Part 2 - Select Room/legacy database in runtime
  app/build.gradle
  build.gradle
  storage/build.gradle
  storage/src/main/kotlin/com/waz/zclient/storage/di/StorageModule.kt
  wire-android-sync-engine/zmessaging/build.gradle
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/Database.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/GlobalDatabase.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/Preferences.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/ZmsDatabase.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/db/DaoDB.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/db/Migration.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/backup/BackupManager.scala
Labels: Kotlin Migration, size/L

#2624 Kotlin Migration : Create account screen
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/waz/zclient/ZApplication.java
  app/src/main/kotlin/com/waz/zclient/auth/signup/CreateAccountActivity.kt
  app/src/main/kotlin/com/waz/zclient/auth/signup/CreateAccountFragment.kt
  app/src/main/res-migration/layout/activity_create_account.xml
  app/src/main/res-migration/layout/fragment_create_account.xml
  app/src/main/res-migration/values/styles_button.xml
  app/src/main/res-migration/values/styles_textview.xml
  app/src/main/res/drawable/create_account_layout_container_background.xml
  app/src/main/res/drawable/create_account_personal_image_background.xml
  app/src/main/res/drawable/create_account_pro_image_background.xml
  app/src/main/res/layout/fragment_create_account_legacy.xml
  app/src/main/res/values/dimens.xml
  app/src/main/scala/com/waz/zclient/appentry/CreateAccountFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/WelcomeFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/ProfileView.scala
  build.gradle
  storage/build.gradle
  storage/src/main/kotlin/com/waz/zclient/storage/db/accountdata/ActiveAccountsMigration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabaseMigration.kt
Labels: Kotlin Migration

#2627 Migrating Room entities from Scala - Part 2
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/assetsv1/AssetsV1Entity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/contacthashes/ContactHashesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/contacts/ContactsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/contacts/ContactsOnWireEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversationmembers/ConversationMembersEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/email/EmailAddressesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/error/ErrorsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/likes/LikesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messagedeletion/MessageDeletionEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessagesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/NotificationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/phonenumbers/PhoneNumbersEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/sync/SyncJobsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/userclients/UserClientsEntity.kt
Labels: size/L

#2630 [Kotlin Migration] Create account screen : missing icons
  app/src/main/AndroidManifest.xml
  app/src/main/res-migration/drawable/ic_personal.xml
  app/src/main/res-migration/drawable/ic_pro.xml
  app/src/main/res-migration/layout/fragment_create_account.xml
Labels: size/M

#2628 Improve kotlin migration flag calculation
  app/build.gradle
  build.gradle
  storage/build.gradle
Labels: size/S

#2631 Create initial index for all tables columns needed in Room
  storage/src/main/kotlin/com/waz/zclient/storage/db/contacts/ContactsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/contacts/ContactsOnWireEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversationmembers/ConversationMembersEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationRoleActionEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/email/EmailAddressesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessagesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/phonenumbers/PhoneNumbersEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/model/UserEntity.kt
Labels: size/M

#2634 Change nullity status of Room entity fields
  storage/src/main/kotlin/com/waz/zclient/storage/db/assets/AssetsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/assets/DownloadAssetsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/assets/UploadAssetsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/EditHistoryEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/MessageContentIndexEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ReadReceiptsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/error/ErrorsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/folders/FoldersEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessagesEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/CloudNotificationStatsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/CloudNotificationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/PushNotificationEventEntity.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/messages/MessagesContentUpdater.scala
Labels: size/L

#2635 Preparing Scala/Kotlin integration for test
  app/src/main/java/com/waz/zclient/ZApplication.java
  app/src/main/kotlin/com/waz/zclient/core/di/Injector.kt
  app/src/main/kotlin/com/waz/zclient/settings/about/di/SettingsAboutModule.kt
  app/src/main/kotlin/com/waz/zclient/settings/support/di/SettingsSupportModule.kt
  app/src/main/res-migration/drawable/ic_personal.xml
  app/src/main/res-migration/drawable/ic_pro.xml
  app/src/main/res-migration/layout/fragment_create_account.xml
  app/src/main/res/layout/preferences_about.xml
  app/src/main/res/layout/preferences_about_layout.xml
  app/src/main/res/layout/preferences_support.xml
  app/src/main/res/layout/preferences_support_layout.xml
  storage/src/main/kotlin/com/waz/zclient/storage/db/GlobalDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/cache/CacheEntryEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/teams/TeamsEntity.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/GlobalDatabase.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/content/ZmsDatabase.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/db/ZGlobalDB.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/AccountsService.scala
Labels: Kotlin Migration

#2637 Chore: Remove non-compiling tests
  app/src/androidTest/scala/com/waz/background/WorkManagerSyncRequestServiceSpec.scala
  app/src/androidTest/scala/com/waz/zclient/SSOTest.scala
  app/src/androidTest/scala/com/waz/zclient/TestUtils.scala
  app/src/androidTest/scala/com/waz/zclient/assets/AssetDetailsServiceTest.scala
  app/src/androidTest/scala/com/waz/zclient/assets/AssetServiceTest.scala
  app/src/androidTest/scala/com/waz/zclient/storage/AssetStorageTest.scala
  app/src/androidTest/scala/com/waz/zclient/storage/GeneralStorageTest.scala
  app/src/androidTest/scala/com/waz/zclient/storage/RawAssetStorageTest.scala
Labels: size/XL

#2626 feat: Full name
  app/src/main/res/layout/message_footer_like_details.xml
  app/src/main/res/layout/participant_user_name_row.xml
  app/src/main/res/layout/view_conv_list_top.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListTopToolbar.scala
  app/src/main/scala/com/waz/zclient/cursor/CursorView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/footer/LikeDetailsView.scala
Labels: size/L

#2639 Bugfix : Linear on boarding m3
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/model2/transport/responses/FetchSsoResponse.scala
Labels: size/XS

#2633 fix: Handle all exceptions when creating tones for Wire's notifications
  app/src/main/scala/com/waz/zclient/notifications/controllers/NotificationManagerWrapper.scala
Labels: size/L

#2645 Boy scout rule for ViewModel's immutable instances in Settings
  app/src/main/kotlin/com/waz/zclient/settings/account/edithandle/SettingsAccountEditHandleViewModel.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/CountryCodePickerViewModel.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/SettingsAccountPhoneNumberViewModel.kt
  app/src/main/kotlin/com/waz/zclient/settings/support/SettingsSupportViewModel.kt
Labels: Kotlin Migration, size/M

#2642 [Kotlin Migration] feature/create personal account part2
  app/src/main/kotlin/com/waz/zclient/auth/registration/di/RegistrationModule.kt
  app/src/main/kotlin/com/waz/zclient/auth/registration/personal/CreatePersonalAccountViewModel.kt
  app/src/main/kotlin/com/waz/zclient/auth/registration/personal/CreatePersonalAccountWithEmailFragment.kt
  app/src/main/kotlin/com/waz/zclient/core/di/Injector.kt
  app/src/main/kotlin/com/waz/zclient/user/domain/usecase/email/EmailValidation.kt
  app/src/main/kotlin/com/waz/zclient/user/domain/usecase/email/ValidateEmailUseCase.kt
  app/src/main/res-migration/drawable/selector_confirm_button.xml
  app/src/test/kotlin/com/waz/zclient/auth/registration/personal/CreatePersonalAccountViewModelTest.kt
  app/src/test/kotlin/com/waz/zclient/user/domain/usecase/email/ValidateEmailUseCaseTest.kt
Labels: size/L

#2641 perf: Optimize sharing many assets to many conversations
  app/src/main/scala/com/waz/zclient/common/controllers/SharingController.scala
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
Labels: size/M

#2648 fix: Small changes replacing many-line-spanning names with one line and ellipsize
  app/src/main/res/layout/fragment_collection.xml
  app/src/main/res/layout/message_user_content.xml
  app/src/main/res/layout/preference_text_button.xml
  app/src/main/res/layout/preferences_account_layout.xml
  app/src/main/res/layout/preferences_profile_layout.xml
  app/src/main/res/layout/search_text_result_row.xml
  app/src/main/res/layout/view_conv_list_top.xml
Labels: size/S

#2650 Refactor: Enhancement related to the UX around loading a video when y…
  app/src/main/scala/com/waz/zclient/common/controllers/AssetsController.scala
  app/src/main/scala/com/waz/zclient/messages/parts/assets/AssetPart.scala
  app/src/main/scala/com/waz/zclient/messages/parts/assets/VideoAssetPartView.scala
Labels: size/S

#2647 chore : add new config for qa demo
  app/src/candidate/AndroidManifest.xml
  app/src/dev/AndroidManifest.xml
  app/src/experimental/AndroidManifest.xml
  app/src/internal/AndroidManifest.xml
  app/src/main/scala/com/waz/zclient/Backend.scala
  app/src/main/scala/com/waz/zclient/qa/AbstractPreferenceReceiver.scala
Labels: size/M

#2644 Spike: Koin scoping
  app/src/main/kotlin/com/waz/zclient/auth/registration/di/RegistrationModule.kt
  app/src/main/kotlin/com/waz/zclient/core/di/Injector.kt
  app/src/main/kotlin/com/waz/zclient/core/extension/DependencyInjection.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/SettingsAccountFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/di/SettingsAccountModule.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/edithandle/EditHandleDialogFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/CountryCodePickerFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/DeletePhoneDialogFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/EditPhoneNumberFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/account/editphonenumber/UpdatePhoneDialogFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/devices/detail/SettingsDeviceDetailFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/devices/di/SettingsDevicesModule.kt
  app/src/main/kotlin/com/waz/zclient/settings/devices/list/SettingsDeviceListFragment.kt
  app/src/main/kotlin/com/waz/zclient/settings/di/SettingsModule.kt
  app/src/main/kotlin/com/waz/zclient/settings/main/SettingsMainActivity.kt
  app/src/main/kotlin/com/waz/zclient/settings/support/SettingsSupportFragment.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/GlobalDatabase.kt
Labels: Kotlin Migration, size/L
