Repository wireapp/wire-android, pull requests merged in 2020-11, with the labels that each got.

#3079 [Calling] : Disable mute, video and speaker button till the call gets properly connected
  app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
Labels: size/XS

#3080 Changes needed to make wire-android work with wire-signals:0.3.0
  app/src/main/java/com/waz/zclient/ForceUpdateActivity.scala
  app/src/main/scala/com/waz/zclient/calling/views/CallControlButtonView.scala
  app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
  app/src/main/scala/com/waz/zclient/collection/views/SingleImageViewToolbar.scala
  app/src/main/scala/com/waz/zclient/conversationlist/ConversationListController.scala
  app/src/main/scala/com/waz/zclient/messages/MessagePagedListController.scala
  buildSrc/src/main/kotlin/Dependencies.kt
  zmessaging/src/main/scala/com/waz/api/impl/RecordingLevels.scala
  zmessaging/src/main/scala/com/waz/content/Database.scala
  zmessaging/src/main/scala/com/waz/content/GlobalDatabase.scala
  zmessaging/src/main/scala/com/waz/content/MembersStorage.scala
  zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
  zmessaging/src/main/scala/com/waz/content/ReactionsStorage.scala
  zmessaging/src/main/scala/com/waz/content/ReadReceiptsStorage.scala
  zmessaging/src/main/scala/com/waz/content/ZmsDatabase.scala
  zmessaging/src/main/scala/com/waz/log/BufferedLogOutput.scala
  zmessaging/src/main/scala/com/waz/log/LogsService.scala
  zmessaging/src/main/scala/com/waz/service/MediaManagerService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/assets/MetaDataRetriever.scala
  zmessaging/src/main/scala/com/waz/service/assets/PCMPlayer.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/FoldersService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/TypingService.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
  zmessaging/src/main/scala/com/waz/service/otr/CryptoBoxService.scala
  zmessaging/src/main/scala/com/waz/service/otr/CryptoSessionService.scala
  zmessaging/src/main/scala/com/waz/service/push/PushService.scala
  zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
  zmessaging/src/main/scala/com/waz/sync/queue/SyncContentUpdater.scala
  zmessaging/src/main/scala/com/waz/threading/Threading.scala
  zmessaging/src/main/scala/com/waz/utils/CachedStorageImpl.scala
  zmessaging/src/main/scala/com/waz/znet2/http/HttpClient.scala
  zmessaging/src/test/scala/com/waz/service/UserServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/push/WSPushServiceSpec.scala
  zmessaging/src/test/scala/com/waz/specs/AndroidFreeSpec.scala
Labels: size/L

#3081 fix: Get random profile pictures from Unsplash
  app/src/main/res/layout/preferences_dev_layout.xml
  app/src/main/res/values/strings_no_translate.xml
  app/src/main/scala/com/waz/zclient/assets/AndroidUriHelper.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DevSettingsView.scala
  zmessaging/src/main/scala/com/waz/model/AssetData.scala
  zmessaging/src/main/scala/com/waz/service/AccountManager.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/assets/AssetService.scala
  zmessaging/src/main/scala/com/waz/sync/client/AssetClient.scala
Labels: size/M

#3086 fix: The unsplash picture should be used only if the user didn't provide their own
  app/src/main/scala/com/waz/zclient/appentry/fragments/FirstLaunchAfterLoginFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/PhoneSetNameFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/SetTeamPasswordFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/VerifyEmailWithCodeFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/VerifyPhoneFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DevSettingsView.scala
  zmessaging/src/main/scala/com/waz/service/AccountManager.scala
  zmessaging/src/main/scala/com/waz/service/AccountsService.scala
Labels: size/S

#3085 Bump AVS version to 6.4.16
  scripts/avs.gradle
Labels: size/XS

#3084 fix: The password dialog disappears when another person calls
  app/src/main/res/layout/password_dialog.xml
  app/src/main/scala/com/waz/zclient/BaseActivity.scala
  app/src/main/scala/com/waz/zclient/calling/CallingActivity.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallStartController.scala
  app/src/main/scala/com/waz/zclient/preferences/dialogs/RequestPasswordDialog.scala
  app/src/main/scala/com/waz/zclient/security/SecurityChecklist.scala
  app/src/main/scala/com/waz/zclient/security/checks/RequestPasswordCheck.scala
Labels: size/L

#3087 [Calling] - Bugfix : toggling video button multiple times renders white-out/black-out buttons
  app/src/main/res/drawable/selector__icon_button__background__calling.xml
  app/src/main/res/drawable/selector__icon_button__background__calling_light.xml
Labels: size/S

#3089 fix: Don't ask for the password when initiating the call
  app/src/main/scala/com/waz/zclient/calling/CallingActivity.scala
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/security/SecurityPolicyChecker.scala
Labels: size/M

#3090 [Calling] Feature : Show similar calling experience for 1:1 calls and group calls with 2 participants
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
Labels: size/S

#3091 Bump AVS version to 6.4.19
  scripts/avs.gradle
Labels: size/XS

#3096 fix: A "unit" test in AssetServiceSpec was trying to connect to the backend
  zmessaging/src/test/scala/com/waz/service/assets2/AssetServiceSpec.scala
Labels: size/M

#3099 [Calling] Design review : Missing shadow for the floating cardView in 1:1 calls / Group Calls with 2 participants
  app/src/main/res/layout/fragment_calling.xml
Labels: size/XS

#3098 wire-signals bump to 0.3.1
  app/src/main/scala/com/waz/zclient/messages/parts/ImagePartView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/ReplyPartView.scala
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/S

#3103 Bump AVS versions
  scripts/avs.gradle
Labels: size/XS

#3097 [Calling]: Feature : maximize/minimize video/screen share on double click
  app/build.gradle
  app/src/main/res/layout/fragment_calling.xml
  app/src/main/res/layout/fragment_full_screen_video.xml
  app/src/main/scala/com/waz/zclient/calling/CallParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
  app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/views/OtherVideoView.scala
  app/src/main/scala/com/waz/zclient/calling/views/SelfVideoView.scala
  app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
  build.gradle
Labels: size/XL
