Repository wireapp/wire-android, pull requests merged in 2020-08, with the labels that each got.

#2946 Feat: Back up - Part 2: Add batch reader for big database tables
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/database/BatchDatabaseIOHandler.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/database/BatchDatabaseIOHandlerTest.kt
Labels: size/L

#2947 Feat : Back up - Part 3: Add database reader which reads all items at once
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/database/SingleReadDatabaseIOHandler.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/database/SingleReadDatabaseIOHandlerTest.kt
Labels: size/M

#2951 Feat: Back up - Part 6: Add kotlinx.serialization as Json parser
  app/build.gradle
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/file/BackUpFileIOHandler.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/file/JsonConverterTest.kt
  build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/M

#2935 Make blacklist URI optional
  app/src/main/scala/com/waz/zclient/Backend.scala
  app/src/main/scala/com/waz/zclient/utils/BackendController.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/BackendConfig.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/CustomBackendClient.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/client/VersionBlacklistClient.scala
Labels: size/M

#2922 feature : Conf Calling - Limit the number of video previews to 12
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
Labels: size/S

#2948 Feat: Back up - Part 4: Add file i/o handler for backup files
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/file/BackUpFileIOHandler.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/file/BackUpFileIOHandlerTest.kt
Labels: size/L

#2950 Feat: Back up - Part 5 : Convert Iterator to suspendable one with Either
  app/build.gradle
  app/src/main/kotlin/com/waz/zclient/core/exception/Failure.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/BackUpDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/Components.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/BatchReader.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/database/BatchDatabaseIOHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/database/SingleReadDatabaseIOHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/file/BackUpFileIOHandler.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/BackUpDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/BatchReaderTestHelpers.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/BatchReaderExtensionsTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/database/BatchDatabaseIOHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/database/SingleReadDatabaseIOHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/file/BackUpFileIOHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/file/JsonConverterTest.kt
  build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XL

#2955 Conference Calling - Participant name design review
  app/src/main/res/layout/video_call_info_view.xml
  app/src/main/res/values/dimens.xml
Labels: size/S

#2957 [Conference Calling] - Sort participants in group calls by name with case-insensitive
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
Labels: size/XS

#2952 Feat: Back up : Samples
  app/src/main/kotlin/com/waz/zclient/core/di/Injector.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/keyvalues/KeyValuesBackUpDao.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/keyvalues/KeyValuesBackUpDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/messages/MessagesBackUpDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/messages/MessagesBackUpModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/messages/database/MessagesBackUpDao.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/messages/mapper/MessagesBackUpDataMapper.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/keyvalues/KeyValuesBackUpMapperTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessagesDao.kt
Labels: size/L

#2960 Bugfix : Redirection for QA Demo custom backend
  app/src/main/kotlin/com/waz/zclient/core/network/connection/ConnectionSpecsFactory.kt
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/znet2/HttpClientOkHttpImpl.scala
Labels: size/XS

#2954 Feat: Back up - Part 9: Testing + PR comments
  app/src/main/kotlin/com/waz/zclient/core/di/Injector.kt
  app/src/main/kotlin/com/waz/zclient/core/utilities/converters/JsonConverter.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/BackUpDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/BackUpRepository.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/file/BackUpFileIOHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCase.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/BackUpDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/file/BackUpFileIOHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/file/JsonConverterTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCaseTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/messages/MessagesTestDataProvider.kt
Labels: size/M

#2953 Feat: Back up - Part 8 : Reusable test data + integration tests
  app/build.gradle
  app/src/main/kotlin/com/waz/zclient/core/di/Injector.kt
  app/src/main/kotlin/com/waz/zclient/core/utilities/converters/JsonConverter.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/BackUpDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/BackUpRepository.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/database/BatchDatabaseIOHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/database/SingleReadDatabaseIOHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/file/BackUpFileIOHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/keyvalues/KeyValuesBackUpDao.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/messages/database/MessagesBackUpDao.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/messages/mapper/MessagesBackUpDataMapper.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCase.kt
  app/src/test/kotlin/com/waz/zclient/UnitTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/BackUpDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/database/BatchDatabaseIOHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/database/SingleReadDatabaseIOHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/file/BackUpFileIOHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/file/JsonConverterTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/keyvalues/KeyValuesBackUpDaoTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/keyvalues/KeyValuesBackUpMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/messages/database/MessagesBackUpDaoTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/messages/mapper/MessagesBackUpDataMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCaseTest.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  common-test/.gitignore
  common-test/build.gradle
  common-test/consumer-rules.pro
  common-test/proguard-rules.pro
  common-test/src/main/AndroidManifest.xml
  common-test/src/main/kotlin/com/waz/zclient/framework/data/TestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/messages/MessagesTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/property/KeyValueTestDataProvider.kt
  settings.gradle
  storage/build.gradle
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesTables126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/property/KeyValueDaoTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/BatchDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessagesDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/property/KeyValuesDao.kt
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/push/PushTokenServiceSpec.scala
Labels: size/XXL

#2961 [Conference Calling] - Adjust video size inside a grid view of n elements
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
Labels: size/M

#2963 [Conference Calling] - Sort video previews in gridview
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
Labels: size/M

#2956 Feat: Back up - Part 10: Single batched tables
  app/src/main/kotlin/com/waz/zclient/feature/backup/conversations/ConversationRolesBackupDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/folders/FoldersBackupDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/database/BatchDatabaseIOHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/keyvalues/KeyValuesBackUpDao.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/keyvalues/KeyValuesBackUpDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/messages/MessagesBackUpModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/messages/database/MessagesBackUpDao.kt
  app/src/test/java/com/waz/zclient/feature/backup/conversations/folders/FoldersBackupMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/conversations/ConversationRoleBackupMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/database/BatchDatabaseIOHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/keyvalues/KeyValuesBackUpDaoTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/messages/database/MessagesBackUpDaoTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/conversations/ConversationRolesTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/folders/FoldersTestDataProvider.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationRoleActionDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationTables126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/folders/FoldersDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/folders/FoldersTable126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/property/KeyValueDaoTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/BatchDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationRoleActionDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/folders/FoldersDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessagesDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/property/KeyValuesDao.kt
Labels: size/XL

#2966 New backups: Zip Handler
  app/src/main/kotlin/com/waz/zclient/feature/backup/ZipHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/ZipHandlerTest.kt
Labels: size/L

#2964 Feat: Back up - part 12: Assets table + ongoing cleanup of tests
  app/src/main/kotlin/com/waz/zclient/feature/backup/assets/AssetsBackupDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/test/java/com/waz/zclient/feature/backup/conversations/folders/FoldersBackupMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/assets/AssetsBackupMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/conversations/ConversationRoleBackupMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/database/BatchDatabaseIOHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/keyvalues/KeyValuesBackUpMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/messages/mapper/MessagesBackUpDataMapperTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/TestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/assets/AssetsTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/conversations/ConversationRolesTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/folders/FoldersTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/messages/MessagesTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/property/KeyValueTestDataProvider.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetTables126to128MigrationTests.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetsDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetsV2TableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationRoleActionDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationTables126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/folders/FoldersTable126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesTables126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/property/KeyValueDaoTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/assets/AssetsDao.kt
Labels: size/L

#2958 Backup 11: List batch readers
  app/src/main/kotlin/com/waz/zclient/core/utilities/converters/JsonConverter.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/BackUpDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/BackUpRepository.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/Components.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/ZipHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/assets/AssetsBackupDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/conversations/ConversationRolesBackupDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/folders/FoldersBackupDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/BatchReader.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/database/BatchDatabaseIOHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/database/SingleReadDatabaseIOHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/file/BackUpFileIOHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/keyvalues/KeyValuesBackUpDao.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/keyvalues/KeyValuesBackUpDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/messages/MessagesBackUpDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/messages/MessagesBackUpModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/messages/database/MessagesBackUpDao.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCase.kt
  app/src/test/java/com/waz/zclient/feature/backup/conversations/folders/FoldersBackupMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/BackUpDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/BatchReaderTestHelpers.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/ZipHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/assets/AssetsBackupMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/conversations/ConversationRoleBackupMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/BatchReaderExtensionsTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/database/BatchDatabaseIOHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/database/SingleReadDatabaseIOHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/file/BackUpFileIOHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/keyvalues/KeyValuesBackUpDaoTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/keyvalues/KeyValuesBackUpMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/messages/database/MessagesBackUpDaoTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/messages/mapper/MessagesBackUpDataMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCaseTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/TestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/assets/AssetsTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/conversations/ConversationRolesTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/folders/FoldersTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/messages/MessagesTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/property/KeyValueTestDataProvider.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetTables126to128MigrationTests.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetsDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetsV2TableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationRoleActionDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationTables126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/folders/FoldersDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/folders/FoldersTable126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/MessagesTables126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/property/KeyValueDaoTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/BatchDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/assets/AssetsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationRoleActionDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/folders/FoldersDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/MessagesDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/property/KeyValuesDao.kt
Labels: size/XXL

#2962 Backups: Liberal JSON Configuration
  app/src/main/kotlin/com/waz/zclient/core/utilities/converters/JsonConverter.kt
Labels: size/XS

#2967 [Conference Calling] - show mute/unmute status in the video grid
  app/src/main/res/drawable/ic_active.xml
  app/src/main/res/drawable/ic_muted_video_grid.xml
  app/src/main/res/drawable/ic_unmuted_video_grid.xml
  app/src/main/res/layout/video_call_info_view.xml
  app/src/main/res/values/dimens.xml
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
Labels: size/L

#2969 Feat: Back up - Part 13: Conversation folders + conversations tables
  app/src/main/kotlin/com/waz/zclient/feature/backup/conversations/ConversationFoldersBackupDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/conversations/ConversationsBackupDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/conversations/ConversationBackupMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/conversations/ConversationFoldersBackupMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/folders/FoldersBackupMapperTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/conversations/ConversationFoldersTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/conversations/ConversationsTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/messages/MessagesTestDataProvider.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationFoldersDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationsDaoTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationFoldersDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationsDao.kt
Labels: size/XL

#2972 New backups: Button table
  app/src/main/kotlin/com/waz/zclient/feature/backup/buttons/ButtonsBackupDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/buttons/ButtonsBackupMapperTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/buttons/ButtonsTestDataProvider.kt
Labels: size/L

#2968 Bump AVS version to 6.2.21
  app/build.gradle
Labels: size/XS

#2974 New backups: Likes data and missing code for ButtonsDao + renaming Button* to Buttons*.
  app/src/main/kotlin/com/waz/zclient/feature/backup/buttons/ButtonsBackupDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/messages/LikesBackUpDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/messages/MessagesBackUpDataMapper.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/buttons/ButtonsBackupMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/folders/FoldersBackupMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/messages/LikesBackupMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/messages/MessagesBackUpDataMapperTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/buttons/ButtonsTestDataProvider.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/messages/LikesTestDataProvider.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/buttons/ButtonsDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/LikesDaoTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/buttons/ButtonsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/buttons/ButtonsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/messages/LikesDao.kt
Labels: size/L

#2976 [Conference Calling] - Design review for the video grid
  app/src/main/res/values/dimens.xml
Labels: size/XS

#2975 New backups: Properties table
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/messages/MessagesBackUpDataMapper.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/properties/PropertiesBackUpDataSource.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/properties/PropertiesBackUpMapperTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/property/PropertiesTestDataProvider.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/property/PropertiesDaoTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/property/PropertiesDao.kt
Labels: size/L

#2977 [Conference Calling] - Show icons in participants list
  app/src/main/res/drawable/ic_guest_dark_theme.xml
  app/src/main/res/drawable/ic_guest_light_theme.xml
  app/src/main/res/drawable/ic_muted_dark_theme.xml
  app/src/main/res/drawable/ic_muted_light_theme.xml
  app/src/main/res/drawable/ic_partner_dark_theme.xml
  app/src/main/res/drawable/ic_partner_light_theme.xml
  app/src/main/res/drawable/ic_screenshare_dark_theme.xml
  app/src/main/res/drawable/ic_screenshare_light_theme.xml
  app/src/main/res/drawable/ic_unmuted_dark_theme.xml
  app/src/main/res/drawable/ic_unmuted_light_theme.xml
  app/src/main/res/drawable/ic_verified.xml
  app/src/main/res/drawable/ic_video_dark_theme.xml
  app/src/main/res/drawable/ic_video_light_theme.xml
  app/src/main/res/layout/single_user_row_view.xml
  app/src/main/scala/com/waz/zclient/calling/CallParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
Labels: size/L

#2978 New backups: Read Receipts table + fixing a typo
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/receipts/ReadReceiptsBackupDataSource.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/receipts/ReadReceiptsBackupMapperTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/receipts/ReadReceiptsTestDataProvider.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationTables126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationsRoleActionTableTestHelper.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/messages/LikesDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/receipts/ReadReceiptsDaoTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/receipts/ReadReceiptsDao.kt
Labels: size/L

#2980 New backups: Ignore failing unit tests
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/BatchReaderExtensionsTest.kt
Labels: size/XS

#2979 New Backups: The Users table
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/users/UsersBackUpDataMapper.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/users/UsersBackUpDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/users/UsersBackUpModel.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/datasources/local/UsersLocalDataSource.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/di/UsersModule.kt
  app/src/main/kotlin/com/waz/zclient/shared/user/mapper/UserMapper.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/users/UsersBackUpDataMapperTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/user/datasources/local/UserLocalDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/shared/user/mapper/UserMapperTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/users/UsersTestDataProvider.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/users/UserTable126to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/users/UsersDaoTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/model/UsersEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/service/UsersDao.kt
  wire-android-sync-engine/zmessaging/src/test/java/com/waz/db/migration/KotlinMigrationHelper.kt
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/db/migration/userdatabase/UsersMigrationTest.scala
Labels: size/XL

#2981 Bump AVS 6.2.23 + VideoGrid Design review
  app/build.gradle
  app/src/main/res/values/dimens.xml
Labels: size/XS

#2970 New backups: Encryption handler
  app/build.gradle
  app/src/androidTest/kotlin/com/waz/zclient/feature/backup/EncryptionHandlerTest.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/EncryptionHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/test/kotlin/com/waz/zclient/feature/FileTestHelpers.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/ZipHandlerTest.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  wire-android-sync-engine/zmessaging/build.gradle
Labels: size/L

#2986 Fix AVS test after introducing new participant parameter
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Calling.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/call/AvsSpec.scala
Labels: size/S

#2985 Fix crash in participants list page
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantHeaderFragment.scala
Labels: size/S

#2987 build : bump avs version to 6.2.27
  app/build.gradle
Labels: size/XS

#2991 Bugfix : No guest Icon is displayed in Search UI, Group Participants list and in suggested mention list
  app/src/main/res/layout/single_user_row_view.xml
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
Labels: size/M

#2995 Bugfix : fingerprint text cut off in device details screen
  app/src/main/scala/com/waz/zclient/preferences/pages/DeviceDetailsView.scala
  app/src/main/scala/com/waz/zclient/preferences/views/TextButton.scala
Labels: size/XS

#2997 Bump AVS version to 6.2.28
  app/build.gradle
Labels: size/XS

#2996 Bugfix : Unable to connect to Conf calls - newly created conversation
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  wire-android-sync-engine/zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  wire-android-sync-engine/zmessaging/src/test/scala/com/waz/service/otr/OtrSyncHandlerSpec.scala
Labels: size/S

#2983 New backups (16): Metadata handler
  app/src/main/kotlin/com/waz/zclient/feature/backup/Components.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/file/BackUpFileIOHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/BackupMetaData.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandlerDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCase.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCaseTest.kt
Labels: size/L

#2982 New backups (15): Put together backup creation in the use case
  app/src/androidTest/kotlin/com/waz/zclient/feature/backup/EncryptionHandlerTest.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/Components.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/encryption/EncryptionHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/encryption/EncryptionHandlerDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/file/BackUpFileIOHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/BackupMetaData.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandlerDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCase.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/zip/ZipHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/zip/ZipHandlerDataSource.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/ZipHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCaseTest.kt
Labels: size/XL

#3001 [AN-7048] Add msg size limit
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/cursor/CursorController.scala
Labels: size/M

#2988 New Backups (17): Create a backup from UI
  app/src/main/java/com/waz/zclient/KotlinServices.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/BackUpDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/BackUpViewModel.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/Components.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/BatchReader.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/database/BatchDatabaseIOHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/io/file/BackUpFileIOHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandlerDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCase.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/zip/ZipHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/zip/ZipHandlerDataSource.kt
  app/src/main/scala/com/waz/zclient/preferences/pages/BackupExportView.scala
  app/src/test/kotlin/com/waz/zclient/feature/backup/BackUpDataSourceTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/BatchReaderTestHelpers.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/ZipHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/io/BatchReaderExtensionsTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCaseTest.kt
Labels: size/XL

#2998 New backups (17+1r): RestoreBackUpUseCase + changes to MetadataHandler
  app/src/main/kotlin/com/waz/zclient/feature/backup/di/BackUpModule.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandler.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandlerDataSource.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCase.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCase.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/metadata/MetaDataHandlerTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/CreateBackUpUseCaseTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/usecase/RestoreBackUpUseCaseTest.kt
Labels: size/XL
