Repository wireapp/wire-android, pull requests merged in 2020-12, with the labels that each got.

#3107 Bump AVS versions
  scripts/avs.gradle
Labels: size/XS

#3101 SSO password lock
  app/src/main/java/com/waz/zclient/utils/ViewUtils.java
  app/src/main/res/drawable/ic_visibility_black_18dp.xml
  app/src/main/res/drawable/ic_visibility_off_black_18dp.xml
  app/src/main/res/drawable/ic_visibility_off_white_18dp.xml
  app/src/main/res/drawable/ic_visibility_white_18dp.xml
  app/src/main/res/drawable/visibility_black.xml
  app/src/main/res/drawable/visibility_white.xml
  app/src/main/res/layout/app_lock_layout.xml
  app/src/main/res/layout/new_password_dialog.xml
  app/src/main/res/layout/preferences_app_lock.xml
  app/src/main/res/layout/preferences_options_layout.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/common/controllers/global/PasswordController.scala
  app/src/main/scala/com/waz/zclient/common/controllers/global/SodiumHandler.scala
  app/src/main/scala/com/waz/zclient/pages/main/MainPhoneFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/dialogs/NewPasswordDialog.scala
  app/src/main/scala/com/waz/zclient/preferences/dialogs/RequestPasswordDialog.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/AccountView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/AppLockView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DeviceDetailsView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DevicesView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/OptionsView.scala
  app/src/main/scala/com/waz/zclient/security/SecurityPolicyChecker.scala
  app/src/main/scala/com/waz/zclient/security/checks/RequestPasswordCheck.scala
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/model/AESKey.scala
  zmessaging/src/main/scala/com/waz/utils/crypto/AESUtils.scala
  zmessaging/src/main/scala/com/waz/utils/crypto/RandomBytes.scala
Labels: size/XL

#3112 fix: The visibility of the "eye" icon on the "Change Passcode" dialog
  app/src/main/scala/com/waz/zclient/common/controllers/global/PasswordController.scala
Labels: size/XS

#3106 [Calling] Feature : Active speaker - part 1
  app/build.gradle
  app/src/main/res/anim/infinite_fade_in_fade_out.xml
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/views/OtherVideoView.scala
  app/src/main/scala/com/waz/zclient/calling/views/SelfVideoView.scala
  app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
  build.gradle
  zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
  zmessaging/src/main/scala/com/waz/service/call/Calling.scala
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
Labels: size/L

#3113 [Calling] Bugfix : Video calling overlay doesn't appear on the maximised video
  app/src/main/res/layout/fragment_calling.xml
Labels: size/XS

#3114 [Calling] Turn active speakers feature flag to off
  build.gradle
Labels: size/XS

#3115 [Calling] : fix for maximization feature : self user video is not maximized on double click
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
Labels: size/S

#3120 hotfix: App crashing for Android 11 when switching from wifi to cellular network
  app/src/main/AndroidManifest.xml
  zmessaging/src/main/scala/com/waz/service/NetworkModeService.scala
Labels: size/M

#3123 [Calling] Remove video maximization feature flag
  app/build.gradle
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
  build.gradle
Labels: size/S

#3124 [Calling] : turn active speaker feature flag to on
  build.gradle
Labels: size/XS
