Repository wireapp/wire-android, pull requests merged in 2021-11, with the labels that each got.

#290 Send messages: Part 11 - Handle message send failure
  app/src/main/kotlin/com/wire/android/feature/conversation/content/domain/MessageSendFailureHandler.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/content/domain/MessageSendFailureHandlerTest.kt
Labels: size/L

#291 Send messages: Part 12: Create sessions for missing clients
  app/src/main/kotlin/com/wire/android/feature/conversation/content/domain/OutgoingMessageRecipientsRetriever.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/content/domain/OutgoingMessageRecipientsRetrieverTest.kt
Labels: size/L

#294 fix: app build error on m1 macbook
  app/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/S

#295 Send messages: Part 13 - Create envelopes for sending messages
  app/src/main/kotlin/com/wire/android/feature/conversation/content/domain/MessageEnvelopeCreator.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/content/domain/MessageEnvelopeCreatorTest.kt
Labels: size/L

#288 Send messages: Part 14 - SEND IT!
  app/src/main/kotlin/com/wire/android/core/async/DispatcherProvider.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/content/SendMessageFailure.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/content/domain/MessageSender.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/content/domain/SendMessageService.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/content/worker/AndroidSendMessageWorker.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/content/worker/AndroidSendMessageWorkerScheduler.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/content/domain/MessageSenderTest.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/content/domain/SendMessageServiceTest.kt
  app/src/test/kotlin/com/wire/android/framework/coroutines/TestDispatcherProvider.kt
Labels: size/XL

#292 Send messages: Part 15 - SendTextMessageUseCase
  app/src/main/kotlin/com/wire/android/feature/conversation/content/usecase/SendTextMessageUseCase.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/content/usecase/SendTextMessageUseCaseTest.kt
Labels: size/L

#293 Send messages: Part 16 (Final) - Send messages UI
  app/src/main/kotlin/com/wire/android/core/di/Modules.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/content/ui/ConversationFragment.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/content/ui/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/di/ConversationsModule.kt
  app/src/main/res/layout/fragment_conversation.xml
  app/src/main/res/values/themes.xml
  app/src/test/kotlin/com/wire/android/feature/conversation/content/ui/ConversationViewModelTest.kt
Labels: size/L

#296 Refactor: qualified conversation id
  app/src/androidTest/kotlin/com/wire/android/feature/conversation/content/datasources/local/MessageDaoTest.kt
  app/src/androidTest/kotlin/com/wire/android/feature/conversation/data/local/ConversationDaoTest.kt
  app/src/androidTest/kotlin/com/wire/android/feature/conversation/list/datasources/local/ConversationListDaoTest.kt
  app/src/androidTest/kotlin/com/wire/android/feature/conversation/members/datasources/local/ConversationMembersDaoTest.kt
  app/src/main/kotlin/com/wire/android/core/events/handler/MessageEventsHandler.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/Conversation.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/content/navigation/ConversationNavigator.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/content/ui/ConversationActivity.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/content/ui/ConversationFragment.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/content/ui/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/content/usecase/GetConversationUseCase.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/content/usecase/SendTextMessageUseCase.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/data/ConversationDataSource.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/data/ConversationMapper.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/data/ConversationRepository.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/data/local/ConversationCache.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/data/local/ConversationEntity.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/data/local/ConversationLocalDataSource.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/data/remote/ConversationsResponse.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/di/ConversationsModule.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/list/ui/ConversationListFragment.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/members/datasources/local/ConversationMemberEntity.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/usecase/ResetCurrentConversationIdUseCase.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/usecase/UpdateCurrentConversationIdUseCase.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/content/navigation/ConversationNavigatorTest.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/content/ui/ConversationViewModelTest.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/content/usecase/GetConversationUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/content/usecase/SendTextMessageUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/data/ConversationDataSourceTest.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/data/ConversationMapperTest.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/data/local/ConversationLocalDataSourceTest.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/list/ui/ConversationListDiffCallbackTest.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/usecase/ResetCurrentConversationIdUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/usecase/UpdateCurrentConversationIdUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/feature/sync/conversation/usecase/RefineConversationNamesUseCaseTest.kt
Labels: refactor, size/XL

#297 ci: Add Jira Link workflow SQPIT-768
  .github/workflows/jira-lint-and-link.yml
Labels: size/S

#298 ci: Add semantic commit lint of PR titles workflow SQPIT-769
  .github/workflows/semantic-commit-lint.yml
Labels: size/M
