Repository wireapp/wire-android, pull requests merged in 2021-06, with the labels that each got.

#3348 Chore: Remove User-Agent header from requests
  app/src/main/kotlin/com/waz/zclient/core/config/Config.kt
  app/src/main/kotlin/com/waz/zclient/core/network/di/NetworkModule.kt
  app/src/main/kotlin/com/waz/zclient/core/network/useragent/UserAgentInterceptor.kt
  app/src/test/kotlin/com/waz/zclient/core/network/useragent/UserAgentInterceptorTest.kt
  zmessaging/src/main/scala/com/waz/service/GlobalModule.scala
  zmessaging/src/main/scala/com/waz/service/MetaDataService.scala
  zmessaging/src/main/scala/com/waz/service/push/WSPushService.scala
  zmessaging/src/main/scala/com/waz/sync/client/package.scala
  zmessaging/src/main/scala/com/waz/znet2/OkHttpUserAgentInterceptor.scala
Labels: size/L

#3350 [Chore] Add comment
  zmessaging/src/main/scala/com/waz/sync/client/OtrClient.scala
Labels: size/XS

#3351 Federation: Add federated backends for tests (#3347)
  app/src/main/scala/com/waz/zclient/Backend.scala
  app/src/main/scala/com/waz/zclient/LaunchActivity.scala
Labels: size/M

#3358 Feature: Build Config - Add a build config to keep web socket on by default
  app/build.gradle
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  default.json
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
Labels: size/S

#3359 [Calling] : Automation help - ID for participant tile
  app/src/main/res/layout/video_call_info_view.xml
Labels: size/XS

#3349 [Fix] Send anyway alert shown too often
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase132To133Migration.kt
  zmessaging/src/main/scala/com/waz/content/ConversationStorage.scala
  zmessaging/src/main/scala/com/waz/model/ConversationData.scala
  zmessaging/src/main/scala/com/waz/model/otr/Client.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/otr/OtrSyncHandlerSpec.scala
Labels: size/L

#3356 Fix by @kongpf8848: UTF-16 encoding for chinese characters
  zmessaging/src/main/scala/com/waz/model/MessageData.scala
  zmessaging/src/test/scala/com/waz/model/MessageDataSpec.scala
Labels: size/M

#3361 fix: Empty query in user search returns zero results
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldUsersAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsAdapter.scala
  zmessaging/src/main/scala/com/waz/service/SearchQuery.scala
  zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
Labels: size/S

#3362 [Calling] : Automation help - ID for participant tile - part 2
  app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
Labels: size/XS

#3363 [Fix] Legal hold system messages shown when they should not
  zmessaging/src/main/scala/com/waz/model/otr/Client.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
  zmessaging/src/test/scala/com/waz/model/ClientSpec.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
Labels: size/M

#3366 wire-signals update to 0.5.1 (and wire-signals-extensions to 0.5.1)
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#3364 Feature: Deep Link - Part 0 - Add unit tests for deep link parsing
  app/build.gradle
  app/src/test/scala/com/waz/zclient/deeplinks/DeepLinkParserTest.scala
Labels: size/L

#3357 Federation: Use the federated icon in user search entries and single user views
  app/src/main/res/drawable/ic_icon_federated_user_dark_theme.xml
  app/src/main/res/drawable/ic_icon_federated_user_light_theme.xml
  app/src/main/res/layout/participant_header_row.xml
  app/src/main/res/layout/single_user_row_view.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/common/controllers/UserAccountsController.scala
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
  app/src/main/scala/com/waz/zclient/conversation/creation/AddParticipantsFragment.scala
  app/src/main/scala/com/waz/zclient/cursor/MentionCandidatesAdapter.scala
  app/src/main/scala/com/waz/zclient/messages/UsersController.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/BaseSingleParticipantAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/UnconnectedParticipantAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/UntabbedRequestFragment.scala
  app/src/main/scala/com/waz/zclient/search/SearchController.scala
  app/src/main/scala/com/waz/zclient/usersearch/SearchUIAdapter.scala
  app/src/main/scala/com/waz/zclient/usersearch/domain/RetrieveSearchResults.scala
  app/src/main/scala/com/waz/zclient/usersearch/listitems/ConnectionViewItem.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
  zmessaging/src/main/scala/com/waz/model/UserData.scala
Labels: size/L

#3367 Feature: Deep Link - Part 1 - Parse conversation-join deep link
  app/src/main/scala/com/waz/zclient/deeplinks/DeepLink.scala
  app/src/main/scala/com/waz/zclient/deeplinks/DeepLinkService.scala
  app/src/main/scala/com/waz/zclient/pages/main/MainPhoneFragment.scala
Labels: size/M

#3370 fix: Bump down wire-signals to 0.4.3 to fix logging in
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#3369 [Calling] Bump AVS to 7.2.3
  scripts/avs.gradle
Labels: size/XS

#3371 Chore: Remove Legal Hold feature flag
  build.gradle
  zmessaging/build.gradle
  zmessaging/src/main/scala/com/waz/service/DisabledLegalHoldService.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
Labels: size/M

#3374 wire-signals version bump to 0.5.2
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  buildSrc/src/main/kotlin/Dependencies.kt
  zmessaging/src/main/scala/com/waz/service/push/PushService.scala
  zmessaging/src/main/scala/com/waz/ui/UiModule.scala
  zmessaging/src/test/scala/com/waz/permissions/PermissionsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/UserServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
Labels: size/S

#3368 Feature: Deep Link - Part 2 - Get conversation overview, open conversation if already joined
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  app/src/main/scala/com/waz/zclient/pages/main/MainPhoneFragment.scala
  zmessaging/src/main/scala/com/waz/model/GuestRoomInfo.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
Labels: size/L

#3372 Feature: Deep Link - Part 3 -Send request to join conversation, handle errors
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  app/src/main/scala/com/waz/zclient/pages/main/MainPhoneFragment.scala
  zmessaging/src/main/scala/com/waz/model/GuestRoomInfo.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
Labels: size/L

#3376 Feature: Deep Link - Part 4- Handle conversation/join response, open conversation after joining
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  app/src/main/scala/com/waz/zclient/pages/main/MainPhoneFragment.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
Labels: size/M

#3378 Feature: Deep Link - Part 5 - Update pop up texts
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/pages/main/MainPhoneFragment.scala
Labels: size/S

#3380 fix: app crashes when user types "@" in group details page search bar
  zmessaging/src/main/scala/com/waz/model/Handle.scala
Labels: size/XS

#3375 fix: Send a message to a large conversation
  zmessaging/src/main/scala/com/waz/service/otr/CryptoBoxService.scala
  zmessaging/src/main/scala/com/waz/service/otr/CryptoSessionService.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrClientsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  zmessaging/src/test/scala/com/waz/sync/handler/OtrClientsSyncHandlerSpec.scala
Labels: size/L

#3379 [Chore] Update guest room error string
  app/src/main/res/values/strings.xml
Labels: size/XS

#3373 [Calling] Feature : Large video conference calls - Pagination - part 1
  app/build.gradle
  app/src/main/res/layout/fragment_calling_grid.xml
  app/src/main/res/layout/fragment_new_calling.xml
  app/src/main/scala/com/waz/zclient/calling/ActiveParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/calling/AllParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
  app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/DependencyMap.kt
Labels: size/XL

#3381 [Calling] Feature : Large video conference calls - Pagination - part 2
  app/src/main/res/drawable/dot_default.xml
  app/src/main/res/drawable/dot_selected.xml
  app/src/main/res/drawable/pagination_tab_selector.xml
  app/src/main/res/layout/fragment_new_calling.xml
  app/src/main/res/values/colors.xml
  app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/M

#3382 fix: Search results are empty when User searches on group details page
  app/src/main/scala/com/waz/zclient/participants/ParticipantsAdapter.scala
  zmessaging/src/main/scala/com/waz/model/UserData.scala
Labels: size/M

#3383 Disable feature flags for a new release
  build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#3384 [Calling] Bugfix - Large conference calls - show profile pictures only when feature is flag is enabled
  app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
Labels: size/XS

#3385 [Calling] revert AVS version to 7.1.6
  scripts/avs.gradle
Labels: size/XS

#3386 fix: Partner inside of team can't be found
  zmessaging/src/main/scala/com/waz/model/UserData.scala
  zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
Labels: size/S

#3389 enable feature flags after release
  build.gradle
Labels: size/XS

#3365 Federation: Empty search screen and federated section title
  app/src/main/res/drawable/ic_icon_empty_search.xml
  app/src/main/res/layout/fragment_pick_user.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/usersearch/SearchUIAdapter.scala
  app/src/main/scala/com/waz/zclient/usersearch/SearchUIFragment.scala
  app/src/main/scala/com/waz/zclient/usersearch/domain/RetrieveSearchResults.scala
  app/src/main/scala/com/waz/zclient/usersearch/listitems/SectionViewItem.scala
Labels: size/L

#3392 fix: The app crashes if the user types the @ sign at the end of the user search
  zmessaging/src/main/scala/com/waz/service/SearchQuery.scala
  zmessaging/src/test/scala/com/waz/service/SearchQuerySpec.scala
Labels: size/M

#3394 Commented out a flaky unit test in SerialProcessingQueueSpec
  zmessaging/src/test/scala/com/waz/utils/SerialProcessingQueueSpec.scala
Labels: size/XS

#3397 [Calling]: Large conference calls - UI improvements - part 2
  app/src/main/scala/com/waz/zclient/calling/CallParticipantsFragment.scala
Labels: size/XS
