Repository wireapp/wire-android, pull requests merged in 2021-08, with the labels that each got.

#3418 [Calling]: Large conference calls - Enable Calling UI buttons before establishing a call
  app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
Labels: size/S

#3422 [Calling]: Large conference calls - Adjust incoming calling UI with large video conference calling
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
Labels: size/S

#3426 [Calling]: Large conference calls - Turn feature flag off for testing purposes
  build.gradle
Labels: size/XS

#3420 File sharing restrictions (part 2)
  zmessaging/src/main/scala/com/waz/model/Event.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  zmessaging/src/main/scala/com/waz/service/teams/FeatureConfigsService.scala
  zmessaging/src/test/scala/com/waz/model/EventSpec.scala
  zmessaging/src/test/scala/com/waz/service/teams/FeatureConfigsServiceSpec.scala
Labels: size/M

#3421 File sharing restrictions (part 3)
  app/src/main/scala/com/waz/zclient/cursor/CursorView.scala
Labels: size/M

#3423 File sharing restrictions (part 4)
  app/src/main/java/com/waz/zclient/views/menus/ConfirmationMenu.java
  app/src/main/res/layout/main_share.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/ShareActivity.scala
Labels: size/M

#3424 File sharing restrictions (part 5)
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/utils/ContextUtils.scala
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/service/teams/FeatureConfigsService.scala
Labels: size/M

#3431 [Calling]: Large conference calls - Bugfix : SelfVideo preview is overlapping the controls UI
  app/src/main/res/layout/fragment_new_calling.xml
  app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
  app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
Labels: size/S

#3429 [Calling]: Large conference calls - Bugfix : Caller profile picture shown after establishing a call
  app/src/main/res/layout/fragment_new_calling.xml
  app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
  app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
Labels: size/S

#3425 trying to make the app more responsive to getting offline/online
  app/src/main/scala/com/waz/services/fcm/FCMHandlerService.scala
  zmessaging/src/main/scala/com/waz/service/GenericMessageService.scala
  zmessaging/src/main/scala/com/waz/service/push/PushService.scala
  zmessaging/src/main/scala/com/waz/service/push/PushTokenService.scala
  zmessaging/src/main/scala/com/waz/service/push/WSPushService.scala
  zmessaging/src/main/scala/com/waz/sync/queue/SyncScheduler.scala
  zmessaging/src/test/scala/com/waz/service/push/WSPushServiceSpec.scala
Labels: size/M

#3436 [Calling] Bugfix : variable bitrate indication is displayed in CBR calls
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/calling/views/CallingHeader.scala
  scripts/avs.gradle
Labels: size/XS

#3437 [Calling] Bugfix : Calling UI buttons not displayed properly with light theme
  app/src/main/res/values/themes.xml
  app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
Labels: size/M

#3428 File sharing restrictions (part 7)
  app/src/main/res/layout/message_image_content.xml
  app/src/main/res/layout/message_reply_content_image.xml
  app/src/main/scala/com/waz/zclient/conversation/ReplyView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/ReplyPartView.scala
Labels: size/L

#3432 File sharing restrictions (part 9)
  app/src/main/res/layout/message_audio_asset_content.xml
  app/src/main/res/layout/message_reply_content_generic.xml
  app/src/main/res/layout/message_reply_content_image.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/messages/parts/ImagePartView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/ReplyPartView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/assets/AssetPart.scala
  app/src/main/scala/com/waz/zclient/messages/parts/assets/AudioAssetPartView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/assets/VideoAssetPartView.scala
Labels: size/L

#3434 Federation: Add the conversation domain and the sender ("from") domain to events
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationsDaoTest.kt
  zmessaging/src/main/scala/com/waz/model/Event.scala
  zmessaging/src/main/scala/com/waz/service/GenericMessageService.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationOrderEventsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrServiceImpl.scala
  zmessaging/src/main/scala/com/waz/service/push/NotificationService.scala
  zmessaging/src/main/scala/com/waz/service/push/PushService.scala
  zmessaging/src/test/scala/com/waz/model/EventSpec.scala
  zmessaging/src/test/scala/com/waz/service/EventSchedulerSpec.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
  zmessaging/src/test/scala/com/waz/service/connections/ConnectionServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationOrderEventsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/notifications/NotificationServiceSpec.scala
  zmessaging/src/test/scala/com/waz/utils/SerialProcessingQueueSpec.scala
Labels: size/XL

#3438 fix: Create a fake 1-to-1 conversation
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
Labels: size/S

#3435 File sharing restrictions (part 10)
  app/src/main/res/drawable/ic_file_blocked.xml
  app/src/main/res/layout/message_file_asset_content.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/theme_attrs.xml
  app/src/main/res/values/themes.xml
  app/src/main/scala/com/waz/zclient/conversation/ReplyView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/ReplyPartView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/assets/FileAssetPartView.scala
  app/src/main/scala/com/waz/zclient/utils/StyleKitMethods.scala
Labels: size/L

#3440 File sharing restrictions (part 11)
  app/src/main/res/layout/collection_message_file_asset_content.xml
  app/src/main/res/layout/collection_message_image_content.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/ids.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/collection/adapters/CollectionAdapter.scala
  app/src/main/scala/com/waz/zclient/collection/views/CollectionItemView.scala
Labels: size/L

#3442 File sharing restrictions (part 12)
  app/src/main/scala/com/waz/zclient/messages/MessageBottomSheetDialog.scala
Labels: size/S

#3443 File sharing restrictions (part 13)
  app/src/main/res/values/strings.xml
Labels: size/XS

#3444 [Fix] Update copy
  app/src/main/res/values/strings.xml
Labels: size/XS

#3454 Federation: fix unit tests
  zmessaging/src/test/scala/com/waz/service/UserServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/ConversationsSyncHandlerSpec.scala
Labels: size/L

#3453 [Fix] File sharing automation issues
  app/src/main/res/layout/collection_message_image_content.xml
  app/src/main/res/layout/row_collection_header.xml
  app/src/main/scala/com/waz/zclient/collection/views/CollectionItemView.scala
Labels: size/M

#3455 [Fix] File sharing design issues
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/collection/adapters/CollectionAdapter.scala
  app/src/main/scala/com/waz/zclient/utils/ContextUtils.scala
  zmessaging/src/main/scala/com/waz/service/teams/FeatureConfigsService.scala
Labels: size/M

#3456 [Fix] Alert button not working
  app/src/main/java/com/waz/zclient/views/menus/ConfirmationMenu.java
Labels: size/XS

#3449 Feature: Conference calling restrictions - part 0
  app/src/main/scala/com/waz/zclient/common/controllers/FeatureConfigsController.scala
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/model/ConferenceCallingFeatureConfig.scala
  zmessaging/src/main/scala/com/waz/service/teams/FeatureConfigsService.scala
  zmessaging/src/main/scala/com/waz/sync/client/FeatureConfigsClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/FeatureConfigsSyncHandler.scala
  zmessaging/src/test/scala/com/waz/model/ConferenceCallingFeatureConfigSpec.scala
  zmessaging/src/test/scala/com/waz/service/teams/FeatureConfigsServiceSpec.scala
Labels: size/L

#3459 Revert AVS to 7.1.6
  scripts/avs.gradle
Labels: size/XS

#3458 Feature: Conference calling restrictions - part 1
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_no_translate.xml
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/common/controllers/BrowserController.scala
  app/src/main/scala/com/waz/zclient/utils/ContextUtils.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/service/teams/FeatureConfigsService.scala
Labels: size/L

#3461 [Calling]: Large conference calls - Feature : Video participants moved to the top of the list and order tiles alphabetically
  app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
Labels: size/XS

#3460 Feature: Conference calling restrictions - part 2
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/utils/ContextUtils.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
Labels: size/M

#3464 Feature: Conference calling restrictions - part 3
  app/build.gradle
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/common/controllers/FeatureConfigsController.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
  build.gradle
Labels: size/S

#3463 [Calling]: Large conference calls - Bugfix : When the remove video is turned off, I see a frozen video instead of avatar
  app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
  app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
Labels: size/S

#3465 Fix: update dialog's title
  app/src/main/res/values/strings.xml
Labels: size/XS

#3462 Feature : Conference calling restrictions
  app/build.gradle
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_no_translate.xml
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/common/controllers/BrowserController.scala
  app/src/main/scala/com/waz/zclient/common/controllers/FeatureConfigsController.scala
  app/src/main/scala/com/waz/zclient/utils/ContextUtils.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
  build.gradle
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/model/ConferenceCallingFeatureConfig.scala
  zmessaging/src/main/scala/com/waz/service/teams/FeatureConfigsService.scala
  zmessaging/src/main/scala/com/waz/sync/client/FeatureConfigsClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/FeatureConfigsSyncHandler.scala
  zmessaging/src/test/scala/com/waz/model/ConferenceCallingFeatureConfigSpec.scala
  zmessaging/src/test/scala/com/waz/service/teams/FeatureConfigsServiceSpec.scala
Labels: size/L

#3475 [Calling] Bugfix: Design issues for calling UI
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
  app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
Labels: size/S

#3447 Feature: Enforce ephemeral messages (part 2)
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/utils/ContextUtils.scala
Labels: size/M
