Repository wireapp/wire-android, pull requests merged in 2021-05, with the labels that each got.

#3285 testfix: Removes and renames code with mentions of the migration 126 to 127
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetTables127to128MigrationTests.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/clients/ClientsTable127to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationTables127to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/errors/ErrorsTable127to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/folders/FoldersTable127to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/history/EditHistoryTable127to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/notifications/NotificationsTables127to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/property/PropertyTables127to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/receipts/ReadReceiptsTable127to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/sync/SyncJobsTable127to128MigrationTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/users/UserTable127to128MigrationTest.kt
Labels: size/L

#3270 [Feature] Legal hold controller implementation
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldController.scala
  zmessaging/src/main/scala/com/waz/model/ConversationData.scala
  zmessaging/src/main/scala/com/waz/service/DisabledLegalHoldService.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
Labels: size/L

#3272 [Feature] Process enable and disable legal hold events
  zmessaging/src/main/scala/com/waz/model/ConversationData.scala
  zmessaging/src/main/scala/com/waz/model/Event.scala
  zmessaging/src/main/scala/com/waz/service/DisabledLegalHoldService.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  zmessaging/src/test/scala/com/waz/model/EventSpec.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
Labels: size/L

#3283 [Calling] Feature : Large video conference calls - Participants list
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/calling/CallParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/calling/views/CallParticipantsView.scala
  app/src/main/scala/com/waz/zclient/calling/views/CallingMiddleLayout.scala
Labels: size/M

#3284 refactor: Changes to case classes in SyncRequest
  zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
Labels: size/L

#3279 [Feature] Add generic message legal hold status flag
  zmessaging/src/main/scala/com/waz/model/GenericContent.scala
  zmessaging/src/main/scala/com/waz/model/package.scala
  zmessaging/src/test/scala/com/waz/model/GenericMessageSpec.scala
Labels: size/L

#3289 [Calling] Bump AVS version to 7.1.4
  scripts/avs.gradle
Labels: size/XS

#3294 Feature: Change "external" icon
  app/src/main/res/drawable/ic_external.xml
  app/src/main/res/drawable/ic_external_grey.xml
  app/src/main/res/drawable/ic_external_user.xml
  app/src/main/res/drawable/ic_partner_dark_theme.xml
  app/src/main/res/drawable/ic_partner_light_theme.xml
  app/src/main/res/layout/participant_header_row.xml
  app/src/main/res/layout/single_user_row_view.xml
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
Labels: size/M

#3295 chore: remove AppLock feature flag
  app/build.gradle
  app/src/main/scala/com/waz/zclient/common/controllers/global/PasswordController.scala
  build.gradle
Labels: size/S

#3293 Disable feature flags for the new release
  build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#3296 Enable feature flags for testing
  build.gradle
Labels: size/XS

#3297 fix: A long click on the conversation list doesn't open the bottom dialog
  app/src/main/scala/com/waz/zclient/collection/views/CollectionItemView.scala
  app/src/main/scala/com/waz/zclient/collection/views/CollectionRecyclerView.scala
  app/src/main/scala/com/waz/zclient/conversationlist/ConversationListFragment.scala
  app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListRow.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldApprovalHandler.scala
  app/src/main/scala/com/waz/zclient/messages/ScrollController.scala
  app/src/main/scala/com/waz/zclient/messages/parts/ConnectRequestPartView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/EphemeralPartView.scala
Labels: size/M

#3248 version code improvements
  app/build.gradle
Labels: size/S

#3298 Fix color of new external icon
  app/src/main/res/drawable/ic_external_user.xml
  app/src/main/res/drawable/ic_partner_dark_theme.xml
  app/src/main/res/drawable/ic_partner_light_theme.xml
  app/src/main/res/layout/single_user_row_view.xml
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
Labels: size/M

#3300 [Calling] Bump AVS version to 7.1.6
  scripts/avs.gradle
Labels: size/XS

#3292 fix: Glide exception in user notifications
  app/src/main/scala/com/waz/zclient/notifications/controllers/MessageNotificationsController.scala
Labels: size/XS

#3301 fix: Syncing clients on fresh install is broken
  zmessaging/src/main/scala/com/waz/model/QualifiedId.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrClientsSyncHandler.scala
Labels: size/L

#3290 Feature: Legal Hold - Display legal hold device in my device list
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/participants/ParticipantOtrDeviceAdapter.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DeviceDetailsView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DevicesView.scala
  app/src/main/scala/com/waz/zclient/preferences/views/DeviceButton.scala
Labels: size/M

#3309 fix: Scroll to position
  app/src/main/scala/com/waz/zclient/messages/MessagePagedListController.scala
  app/src/main/scala/com/waz/zclient/messages/MessagesListView.scala
  app/src/main/scala/com/waz/zclient/messages/ScrollController.scala
  app/src/main/scala/com/waz/zclient/messages/controllers/MessageActionsController.scala
Labels: size/M

#3307 Feature: Legal Hold - Indicate legal hold on conversation share sheet
  app/src/main/res/layout/row_selectable_conversation.xml
  app/src/main/scala/com/waz/zclient/sharing/ConversationSelectorFragment.scala
Labels: size/S

#3311 Feature: Legal Hold - Show info pop ups when Legal Hold is activated & deactivated
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldController.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldStatusChangeListener.scala
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
Labels: size/M

#3312 Refactor: Legal Hold - Remove Container from LegalHoldInfoFragment
  app/src/main/scala/com/waz/zclient/legalhold/AllLegalHoldSubjectsFragment.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldInfoFragment.scala
  app/src/main/scala/com/waz/zclient/legalhold/SelfUserLegalHoldInfoActivity.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantFragment.scala
Labels: size/L

#3288 [Feature] Update legal hold status from generic message hint
  zmessaging/src/main/java/com/waz/model/sync/SyncCommand.java
  zmessaging/src/main/scala/com/waz/model/otr/Client.scala
  zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
  zmessaging/src/main/scala/com/waz/service/DisabledLegalHoldService.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldStatusUpdater.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/main/scala/com/waz/sync/handler/LegalHoldSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldStatusUpdaterSpec.scala
  zmessaging/src/test/scala/com/waz/service/otr/OtrSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/LegalHoldSyncHandlerSpec.scala
Labels: size/L

#3313 Refactor: Legal Hold - Add event to LegalHoldController for opening LH info screen
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldController.scala
  app/src/main/scala/com/waz/zclient/pages/main/conversation/ConversationManagerFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantHeaderFragment.scala
Labels: size/M

#3306 [Feature] Send legal hold hints
  zmessaging/src/main/scala/com/waz/content/ConversationStorage.scala
  zmessaging/src/main/scala/com/waz/db/migrate/MessageDataMigration.scala
  zmessaging/src/main/scala/com/waz/model/ConversationData.scala
  zmessaging/src/main/scala/com/waz/model/GenericContent.scala
  zmessaging/src/main/scala/com/waz/model/MessageData.scala
  zmessaging/src/main/scala/com/waz/model/package.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  zmessaging/src/main/scala/com/waz/service/messages/EphemeralMessagesService.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
  zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/OpenGraphSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ReactionsSyncHandler.scala
  zmessaging/src/test/scala/com/waz/model/GenericMessageSpec.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/MessagesServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationOrderEventsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/notifications/NotificationServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/otr/OtrSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/utils/crypto/ReplyHashingSpec.scala
Labels: size/XL

#3318 Add ui automation locators for LH indicator
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListTopToolbar.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantOtrDeviceAdapter.scala
Labels: size/S

#3320 [Fix] Add legal hold device description
  app/src/main/scala/com/waz/zclient/common/controllers/global/ClientsController.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantOtrDeviceAdapter.scala
Labels: size/S

#3323 [Fix] Legal hold info list out of sync
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
Labels: size/M

#3324 Chore: Add QA automation locator for legal hold icon on share sheet
  app/src/main/scala/com/waz/zclient/sharing/ConversationSelectorFragment.scala
Labels: size/S

#3326 Chore: Prepare for 3.69 release
  build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#3327 Refactor: Blocked Participant Screen - Add LinkTextView support
  app/src/main/res/layout/participant_linked_info_row.xml
  app/src/main/scala/com/waz/zclient/participants/fragments/BaseSingleParticipantAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/UnconnectedParticipantAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/UntabbedRequestFragment.scala
Labels: size/M

#3334 Refactor: Legal Hold - Simplify isLegalHoldActive method for self user
  app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListTopToolbar.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldController.scala
  zmessaging/src/main/scala/com/waz/service/DisabledLegalHoldService.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
Labels: size/S

#3337 Refactor: Legal Hold Updates - Dismiss existing dialogs when LH state changes
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldStatusChangeListener.scala
Labels: size/M

#3339 Fix: Legal Hold Status - Check whether LH is active for a user that has just logged in
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/conversations/ConversationsDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/users/UsersDaoTest.kt
  zmessaging/src/main/scala/com/waz/service/DisabledLegalHoldService.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
  zmessaging/src/main/scala/com/waz/sync/handler/LegalHoldSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/LegalHoldSyncHandlerSpec.scala
Labels: size/L

#3341 Fix: LegalHoldService unit tests
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
Labels: size/XS

#3310 [Calling] Feature : Large video conference calls - Display profile picture for participants with audio only
  app/src/main/res/layout/fragment_calling.xml
  app/src/main/res/layout/video_call_info_view.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/calling/CallParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/calling/CallingActivity.scala
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
  app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
Labels: size/L

#3340 [Fix] Send anyway alert shown when receiving a message
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ClearedSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/LastReadSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/OpenGraphSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ReactionsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/TrackingSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/otr/OtrSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/MessagesSyncHandlerSpec.scala
Labels: size/L

#3328 refactor: Remove exact match search
  zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
  zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/main/scala/com/waz/sync/client/UsersClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/UserSearchSyncHandler.scala
  zmessaging/src/test/scala/com/waz/sync/handler/UserSearchSyncHandlerSpec.scala
Labels: size/M

#3342 Chore: Enable largeVideoConferenceCalls flag back
  build.gradle
Labels: size/XS

#3345 fix: MissingFieldException: Field 'domain' is required, but it was missing
  app/src/main/kotlin/com/waz/zclient/feature/backup/users/UsersBackUpModel.kt
Labels: size/XS

#3335 Federation: Add domain to the search query
  app/build.gradle
  app/src/main/scala/com/waz/zclient/usersearch/SearchUIFragment.scala
  build.gradle
  zmessaging/build.gradle
  zmessaging/src/main/scala/com/waz/content/UsersStorage.scala
  zmessaging/src/main/scala/com/waz/model/UserData.scala
  zmessaging/src/main/scala/com/waz/service/SearchKey.scala
  zmessaging/src/main/scala/com/waz/service/SearchQuery.scala
  zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
  zmessaging/src/main/scala/com/waz/sync/client/UserSearchClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/UserSearchSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/teams/TeamsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/client/UserSearchClientSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/UserSearchSyncHandlerSpec.scala
Labels: size/L

#3343 [Fix] Display legal hold send anyway alert only once
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
Labels: size/M

#3347 Federation: Add federated backends for tests
  app/src/main/scala/com/waz/zclient/Backend.scala
  app/src/main/scala/com/waz/zclient/LaunchActivity.scala
Labels: size/M
