Repository wireapp/wire-android, pull requests merged in 2021-01, with the labels that each got.

#3126 [Calling] : Show only the loudest active speaker in participants list
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
  zmessaging/src/main/scala/com/waz/log/LogShowInstancesSE.scala
  zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
Labels: size/L

#3133 fix: Properly discover the current network mode
  zmessaging/src/main/scala/com/waz/service/NetworkModeService.scala
Labels: size/M

#3131 fix: File sharing
  app/src/main/scala/com/waz/zclient/ShareActivity.scala
  app/src/main/scala/com/waz/zclient/messages/controllers/MessageActionsController.scala
  app/src/main/scala/com/waz/zclient/utils/Time.scala
  zmessaging/src/main/scala/com/waz/content/WireContentProvider.scala
  zmessaging/src/main/scala/com/waz/service/assets/AssetService.scala
  zmessaging/src/main/scala/com/waz/utils/wrappers/URI.scala
  zmessaging/src/test/scala/com/waz/service/assets2/AssetServiceSpec.scala
  zmessaging/src/test/scala/com/waz/testutils/TestContentProvider.scala
Labels: size/L

#3134 [Calling] Bugfix : active speaker feature - part 1
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
  scripts/avs.gradle
Labels: size/S

#3135 [Calling] fix : single tap and double tap are not working after clicking on show All and after coming back from the background
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
Labels: size/XS

#3136 [Calling] : Active speaker - Design review
  app/src/main/res/anim/infinite_fade_in_fade_out.xml
  app/src/main/res/drawable/selector_toggle_button_text_color.xml
  app/src/main/res/drawable/selector_toggle_left_button_background.xml
  app/src/main/res/drawable/selector_toggle_right_button_background.xml
  app/src/main/res/layout/fragment_calling_controls.xml
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
  app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
Labels: size/L

#3137 feat: Feature Flag App Lock
  app/build.gradle
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/common/controllers/global/PasswordController.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/AppLockView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/OptionsView.scala
  app/src/main/scala/com/waz/zclient/security/SecurityPolicyChecker.scala
  build.gradle
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/model/AppLockFeatureFlag.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  zmessaging/src/main/scala/com/waz/service/teams/FeatureFlagsService.scala
  zmessaging/src/main/scala/com/waz/sync/client/FeatureFlagsClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/FeatureFlagsSyncHandler.scala
  zmessaging/src/test/scala/com/waz/model/AppLockFeatureFlagSpec.scala
  zmessaging/src/test/scala/com/waz/service/teams/FeatureFlagsServiceSpec.scala
Labels: size/L

#3142 Changes required to make wire-android work with wire-signals 0.3.2
  app/src/main/scala/com/waz/zclient/conversationlist/ConversationListController.scala
  buildSrc/src/main/kotlin/Dependencies.kt
  zmessaging/src/main/scala/com/waz/api/impl/RecordingLevels.scala
  zmessaging/src/main/scala/com/waz/content/ConvMessagesIndex.scala
  zmessaging/src/main/scala/com/waz/content/MembersStorage.scala
  zmessaging/src/main/scala/com/waz/content/ReactionsStorage.scala
  zmessaging/src/main/scala/com/waz/content/UsersStorage.scala
  zmessaging/src/main/scala/com/waz/permissions/PermissionsService.scala
  zmessaging/src/main/scala/com/waz/service/ErrorsService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/FoldersService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/TypingService.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
  zmessaging/src/main/scala/com/waz/service/otr/CryptoSessionService.scala
  zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
  zmessaging/src/main/scala/com/waz/sync/queue/SyncContentUpdater.scala
  zmessaging/src/main/scala/com/waz/utils/CachedStorageImpl.scala
Labels: size/M

#3143 [Calling] turn active speaker feature flag to false
  build.gradle
Labels: size/XS

#3144 Revert "[Calling] turn active speaker feature flag to false"
  build.gradle
Labels: size/XS

#3145 [Calling] fix : active speaker bugs
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
Labels: size/M

#3148 [Calling] bugfix : On group call when there are 2 participants, self-video turns black for a second each time the user starts speaking
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
Labels: size/XS

#3153 [Calling] Bugfix : active speaker feature shouldn't affect one one calls
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
Labels: size/XS

#3152 [Calling] Design review for active speaker pulsing microphone animation
  app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
Labels: size/S

#3150 Remove fake error messages
  app/src/main/res/layout/preferences_dev_layout.xml
  app/src/main/scala/com/waz/zclient/preferences/pages/DevSettingsView.scala
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
  zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
Labels: DO NOT MERGE, size/M

#3154 [Calling] Hide active speakers/all toggle
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
Labels: size/M

#3155 fix: The camera session may crash when released if it was closed beforehand
  app/src/main/scala/com/waz/zclient/camera/controllers/AndroidCamera2.scala
Labels: size/XS

#3156 Code Freeze for the release 3.63
  build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#3151 App Lock Feature Flag #2
  app/src/main/res/drawable/selector_alarm_confirmation_button_text_color.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/CredentialsFragment.scala
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/common/controllers/global/PasswordController.scala
  app/src/main/scala/com/waz/zclient/pages/main/MainPhoneFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/dialogs/NewPasswordDialog.scala
  app/src/main/scala/com/waz/zclient/preferences/dialogs/RemoveDeviceDialog.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/AppLockView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DevSettingsView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DeviceDetailsView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DevicesView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/OptionsView.scala
  app/src/main/scala/com/waz/zclient/security/SecurityPolicyChecker.scala
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/model/AppLockFeatureFlag.scala
  zmessaging/src/main/scala/com/waz/service/AccountManager.scala
  zmessaging/src/main/scala/com/waz/service/AccountsService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/teams/FeatureFlagsService.scala
  zmessaging/src/test/scala/com/waz/model/AppLockFeatureFlagSpec.scala
  zmessaging/src/test/scala/com/waz/service/teams/FeatureFlagsServiceSpec.scala
Labels: size/L

#3158 [Calling] Join a group call in muted stat - part 1
  build.gradle
  zmessaging/build.gradle
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
Labels: size/XS

#3159 fix: Un-throttling the networkMode signal in WebSocketService.
  app/src/main/scala/com/waz/services/websocket/WebSocketService.scala
  zmessaging/src/main/scala/com/waz/service/NetworkModeService.scala
Labels: size/M
