Repository wireapp/wire-android, pull requests merged in 2021-10, with the labels that each got.

#263 Refactor: Update Kotlin to 1.5.31
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#262 CryptoBoxClient Update: QualifiedId and easier utilization without prekeys
  app/src/androidTest/kotlin/com/wire/android/core/crypto/CryptoBoxClientIntegrationTest.kt
  app/src/main/kotlin/com/wire/android/core/crypto/CryptoBoxClient.kt
  app/src/main/kotlin/com/wire/android/core/crypto/data/CryptoBoxClientPropertyStorage.kt
  app/src/main/kotlin/com/wire/android/core/crypto/model/CryptoSessionId.kt
  app/src/main/kotlin/com/wire/android/core/di/Modules.kt
  app/src/main/kotlin/com/wire/android/core/events/Event.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/content/EncryptedMessageEnvelope.kt
  app/src/main/kotlin/com/wire/android/feature/conversation/content/mapper/MessageMapper.kt
  app/src/test/kotlin/com/wire/android/core/crypto/CryptoBoxClientTest.kt
  app/src/test/kotlin/com/wire/android/feature/conversation/content/mapper/MessageMapperTest.kt
Labels: size/L

#265 refactor: improve naming of tests in `CryptoBoxClientIntegrationTest`
  app/src/androidTest/kotlin/com/wire/android/core/crypto/CryptoBoxClientIntegrationTest.kt
Labels: size/S

#267 Start receiving messages
  app/src/main/kotlin/com/wire/android/feature/conversation/list/MainActivity.kt
  app/src/main/kotlin/com/wire/android/feature/sync/di/SyncModule.kt
  app/src/main/kotlin/com/wire/android/feature/sync/ui/SyncViewModel.kt
  app/src/test/kotlin/com/wire/android/feature/sync/ui/SyncViewModelTest.kt
Labels: size/S

#264 Refactor: Provide more control over network requests
  app/src/main/kotlin/com/wire/android/core/network/ApiService.kt
  app/src/test/kotlin/com/wire/android/core/network/ApiServiceTest.kt
  app/src/test/kotlin/com/wire/android/feature/messaging/datasource/remote/MessageRemoteDataSourceTest.kt
Labels: size/L

#260 WIP: Consider Locale when formatting date and time
  app/src/main/kotlin/com/wire/android/core/extension/OffsetDateTime.kt
  app/src/test/kotlin/com/wire/android/core/extension/OffsetDateTimeExtensionTest.kt
Labels: size/L

#266 [fix] Emitting events from different coroutines
  app/src/main/kotlin/com/wire/android/core/events/EventRepository.kt
  app/src/main/kotlin/com/wire/android/core/events/datasource/EventDataSource.kt
  app/src/main/kotlin/com/wire/android/core/events/datasource/remote/NotificationRemoteDataSource.kt
  app/src/main/kotlin/com/wire/android/core/events/di/EventModule.kt
  app/src/test/kotlin/com/wire/android/core/events/datasource/EventDataSourceTest.kt
  app/src/test/kotlin/com/wire/android/core/events/usecase/ListenToEventsUseCaseTest.kt
Labels: size/L

#274 Chore: Display version code in version name
  app/build.gradle.kts
Labels: size/XS
