Repository wireapp/wire-android, pull requests merged in 2021-07, with the labels that each got.

#3398 wire-signals bump to 1.0.0
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#3400 Prepare 3.71 release
  build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#3399 [Calling]: Large conference calls - UI improvements - part 3
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
Labels: size/XS

#3407 [Calling]: Large conference calls - UI improvements - part 4
  app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
Labels: size/XS

#3401 [Feature] Add compile time flag to force constant bitrate calls
  app/build.gradle
  app/src/main/res/layout/preferences_options_layout.xml
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallStartController.scala
  app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/OptionsView.scala
  default.json
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
Labels: size/M

#3409 [Calling]: Large conference calls - Bugfix : Pagination not disappearing
  app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
Labels: size/XS

#3406 Federation: Handle info about a new conversation started on another backend
  app/src/main/kotlin/com/waz/zclient/feature/backup/conversations/ConversationsBackupDataSource.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/conversations/ConversationBackupMapperTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/conversations/ConversationsTestDataProvider.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase133To134Migration.kt
  zmessaging/src/main/scala/com/waz/model/ConversationData.scala
  zmessaging/src/main/scala/com/waz/model/ConversationRole.scala
  zmessaging/src/main/scala/com/waz/model/Event.scala
  zmessaging/src/main/scala/com/waz/model/RConvQualifiedId.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationOrderEventsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
  zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
  zmessaging/src/test/scala/com/waz/service/connections/ConnectionServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/notifications/NotificationServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/ConversationsSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/LegalHoldSyncHandlerSpec.scala
Labels: size/XL

#3402 Federation: Fixing the user syncing of qualified and non-qualified users
  app/src/main/kotlin/com/waz/zclient/feature/backup/conversations/ConversationsBackupDataSource.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/conversations/ConversationBackupMapperTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/conversations/ConversationsTestDataProvider.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase133To134Migration.kt
  zmessaging/src/main/scala/com/waz/model/ConversationData.scala
  zmessaging/src/main/scala/com/waz/model/ConversationRole.scala
  zmessaging/src/main/scala/com/waz/model/Event.scala
  zmessaging/src/main/scala/com/waz/model/RConvQualifiedId.scala
  zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationOrderEventsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
  zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/ExpiredUsersServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
  zmessaging/src/test/scala/com/waz/service/connections/ConnectionServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/notifications/NotificationServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/ConversationsSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/LegalHoldSyncHandlerSpec.scala
Labels: size/L

#3395 Federation: Add a user from a different domain to a new group conversation
  app/src/main/kotlin/com/waz/zclient/feature/backup/conversations/ConversationsBackupDataSource.kt
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  app/src/main/scala/com/waz/zclient/conversation/creation/CreateConversationController.scala
  app/src/main/scala/com/waz/zclient/messages/UsersController.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SendConnectRequestFragment.scala
  app/src/test/kotlin/com/waz/zclient/feature/backup/conversations/ConversationBackupMapperTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/conversations/ConversationsTestDataProvider.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase133To134Migration.kt
  zmessaging/src/main/java/com/waz/model/sync/SyncCommand.java
  zmessaging/src/main/scala/com/waz/model/ConversationData.scala
  zmessaging/src/main/scala/com/waz/model/ConversationRole.scala
  zmessaging/src/main/scala/com/waz/model/Event.scala
  zmessaging/src/main/scala/com/waz/model/RConvQualifiedId.scala
  zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
  zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationOrderEventsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
  zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/ExpiredUsersServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
  zmessaging/src/test/scala/com/waz/service/UserServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/connections/ConnectionServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsUiServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/TeamConversationSpec.scala
  zmessaging/src/test/scala/com/waz/service/notifications/NotificationServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/ConversationsSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/LegalHoldSyncHandlerSpec.scala
Labels: size/L

#3393 Federation: Add users from fake 1-to-1 conversations to the results of user search
  app/src/main/kotlin/com/waz/zclient/feature/backup/conversations/ConversationsBackupDataSource.kt
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  app/src/main/scala/com/waz/zclient/conversation/creation/CreateConversationController.scala
  app/src/main/scala/com/waz/zclient/messages/UsersController.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SendConnectRequestFragment.scala
  app/src/test/kotlin/com/waz/zclient/feature/backup/conversations/ConversationBackupMapperTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/conversations/ConversationsTestDataProvider.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase133To134Migration.kt
  zmessaging/src/main/java/com/waz/model/sync/SyncCommand.java
  zmessaging/src/main/scala/com/waz/model/ConversationData.scala
  zmessaging/src/main/scala/com/waz/model/ConversationRole.scala
  zmessaging/src/main/scala/com/waz/model/Event.scala
  zmessaging/src/main/scala/com/waz/model/RConvQualifiedId.scala
  zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
  zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
  zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationOrderEventsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
  zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/ExpiredUsersServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
  zmessaging/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/UserServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/connections/ConnectionServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsUiServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/TeamConversationSpec.scala
  zmessaging/src/test/scala/com/waz/service/notifications/NotificationServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/ConversationsSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/LegalHoldSyncHandlerSpec.scala
Labels: size/M

#3354 Federation: connection requests + syncing users + adding users to conversations
  app/src/main/java/com/waz/zclient/pages/main/pickuser/controller/PickUserDataState.java
  app/src/main/kotlin/com/waz/zclient/feature/backup/conversations/ConversationsBackupDataSource.kt
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  app/src/main/scala/com/waz/zclient/conversation/creation/CreateConversationController.scala
  app/src/main/scala/com/waz/zclient/messages/UsersController.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ConnectRequestFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/PendingConnectRequestFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SendConnectRequestFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/UntabbedRequestFragment.scala
  app/src/main/scala/com/waz/zclient/usersearch/SearchUIFragment.scala
  app/src/main/scala/com/waz/zclient/usersearch/domain/RetrieveSearchResults.scala
  app/src/test/kotlin/com/waz/zclient/feature/backup/conversations/ConversationBackupMapperTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/conversations/ConversationsTestDataProvider.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/conversations/ConversationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase133To134Migration.kt
  zmessaging/src/main/java/com/waz/model/sync/SyncCommand.java
  zmessaging/src/main/scala/com/waz/model/ConversationData.scala
  zmessaging/src/main/scala/com/waz/model/ConversationRole.scala
  zmessaging/src/main/scala/com/waz/model/Event.scala
  zmessaging/src/main/scala/com/waz/model/QualifiedId.scala
  zmessaging/src/main/scala/com/waz/model/RConvQualifiedId.scala
  zmessaging/src/main/scala/com/waz/model/UserData.scala
  zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
  zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
  zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationOrderEventsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
  zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
  zmessaging/src/main/scala/com/waz/sync/client/UsersClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ConnectionsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/UsersSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/ExpiredUsersServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
  zmessaging/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/UserServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/connections/ConnectionServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsUiServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/TeamConversationSpec.scala
  zmessaging/src/test/scala/com/waz/service/notifications/NotificationServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/ConversationsSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/LegalHoldSyncHandlerSpec.scala
Labels: size/XXL

#3405 refactor: A possible performance boost to the data retrieval from the storage
  app/src/main/scala/com/waz/zclient/conversation/creation/CreateConversationController.scala
  app/src/main/scala/com/waz/zclient/conversationlist/ConversationListController.scala
  app/src/main/scala/com/waz/zclient/tracking/GlobalTrackingController.scala
  zmessaging/src/main/scala/com/waz/cache/CacheStorage.scala
  zmessaging/src/main/scala/com/waz/content/AccountsStorage.scala
  zmessaging/src/main/scala/com/waz/content/AssetsStorage.scala
  zmessaging/src/main/scala/com/waz/content/ButtonsStorage.scala
  zmessaging/src/main/scala/com/waz/content/ConversationRolesStorage.scala
  zmessaging/src/main/scala/com/waz/content/ConversationStorage.scala
  zmessaging/src/main/scala/com/waz/content/EditHistoryStorage.scala
  zmessaging/src/main/scala/com/waz/content/FoldersStorage.scala
  zmessaging/src/main/scala/com/waz/content/MembersStorage.scala
  zmessaging/src/main/scala/com/waz/content/MessageIndexStorage.scala
  zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
  zmessaging/src/main/scala/com/waz/content/MsgDeletionStorage.scala
  zmessaging/src/main/scala/com/waz/content/NotificationStorageImpl.scala
  zmessaging/src/main/scala/com/waz/content/OtrClientsStorage.scala
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/content/ReactionsStorage.scala
  zmessaging/src/main/scala/com/waz/content/ReadReceiptsStorage.scala
  zmessaging/src/main/scala/com/waz/content/TeamsStorage.scala
  zmessaging/src/main/scala/com/waz/content/UsersStorage.scala
  zmessaging/src/main/scala/com/waz/service/AccountsService.scala
  zmessaging/src/main/scala/com/waz/service/ErrorsService.scala
  zmessaging/src/main/scala/com/waz/service/ReportingService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsContentUpdater.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/FoldersService.scala
  zmessaging/src/main/scala/com/waz/service/push/NotificationService.scala
  zmessaging/src/main/scala/com/waz/service/push/PushNotificationEventsStorage.scala
  zmessaging/src/main/scala/com/waz/sync/handler/UsersSyncHandler.scala
  zmessaging/src/main/scala/com/waz/utils/CachedStorageImpl.scala
  zmessaging/src/test/scala/com/waz/service/FoldersServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/notifications/NotificationServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/UsersSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/testutils/TestPreferences.scala
  zmessaging/src/test/scala/com/waz/testutils/package.scala
Labels: size/L
