Repository wireapp/wire-android, pull requests merged in 2021-09, with the labels that each got.

#3477 custom build refactoring
  scripts/customization.gradle
Labels: size/XS

#3478 Feature: Enforce ephemeral messages (part 5)
  zmessaging/src/main/scala/com/waz/service/messages/MessagesContentUpdater.scala
  zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
  zmessaging/src/test/scala/com/waz/service/MessagesServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsUiServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/TeamConversationSpec.scala
  zmessaging/src/test/scala/com/waz/service/messages/MessagesContentUpdaterSpec.scala
Labels: size/L

#3481 Feature: Enforce ephemeral messages (part 6 - Final)
  app/src/main/scala/com/waz/zclient/cursor/CursorController.scala
  app/src/main/scala/com/waz/zclient/sharing/ConversationSelectorFragment.scala
Labels: size/M

#3482 Feature: Enforce ephemeral messages
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/common/controllers/FeatureConfigsController.scala
  app/src/main/scala/com/waz/zclient/cursor/CursorController.scala
  app/src/main/scala/com/waz/zclient/sharing/ConversationSelectorFragment.scala
  app/src/main/scala/com/waz/zclient/utils/ContextUtils.scala
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/model/SelfDeletingMessagesFeatureConfig.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessagesContentUpdater.scala
  zmessaging/src/main/scala/com/waz/service/teams/FeatureConfigsService.scala
  zmessaging/src/main/scala/com/waz/sync/client/FeatureConfigsClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/FeatureConfigsSyncHandler.scala
  zmessaging/src/test/scala/com/waz/model/SelfDeletingMessagesFeatureConfigSpec.scala
  zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
  zmessaging/src/test/scala/com/waz/service/MessagesServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsUiServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/TeamConversationSpec.scala
  zmessaging/src/test/scala/com/waz/service/messages/MessagesContentUpdaterSpec.scala
  zmessaging/src/test/scala/com/waz/service/teams/FeatureConfigsServiceSpec.scala
Labels: size/XL

#3485 fix: Creating conversation fails because of invalid payload
  zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
Labels: size/S

#3486 fix: revert to old way of adding users to conversations if the federation flag is off
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/UsersSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/ConversationsSyncHandlerSpec.scala
Labels: bug, DO NOT MERGE, size/L

#3487 [Chore] Update CBR copy
  app/src/main/res/values/strings.xml
Labels: size/XS

#3484 fix: Update email with the token and the cookie
  zmessaging/src/main/scala/com/waz/service/AccountManager.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/sync/client/AuthenticationManager.scala
  zmessaging/src/main/scala/com/waz/sync/client/CredentialsUpdateClient.scala
  zmessaging/src/main/scala/com/waz/sync/client/LoginClient.scala
Labels: size/M

#3467 Federation: prekeys
  zmessaging/src/main/scala/com/waz/model/otr/OtrClientIdMap.scala
  zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrClientsService.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrServiceImpl.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/main/scala/com/waz/sync/client/OtrClient.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrClientsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/OtrClientsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/OtrClientsSyncHandlerSpec.scala
Labels: size/L

#3457 Federation: Refactoring to use qualified ids in zmessaging (part 1)
  app/src/main/scala/com/waz/zclient/common/controllers/global/ClientsController.scala
  zmessaging/src/main/java/com/waz/model/sync/SyncCommand.java
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/model/otr/OtrClientIdMap.scala
  zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
  zmessaging/src/main/scala/com/waz/service/AccountManager.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  zmessaging/src/main/scala/com/waz/service/otr/CryptoSessionService.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrClientsService.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrServiceImpl.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/main/scala/com/waz/sync/client/OtrClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/LegalHoldSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrClientsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/OtrClientsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/UserServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/otr/OtrSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/LegalHoldSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/OtrClientsSyncHandlerSpec.scala
Labels: size/XL

#3451 Federation: Use qualified ids for encrypting, decrypting, and fingerprints
  app/src/main/scala/com/waz/zclient/common/controllers/global/ClientsController.scala
  zmessaging/src/main/java/com/waz/model/sync/SyncCommand.java
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/model/otr/OtrClientIdMap.scala
  zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
  zmessaging/src/main/scala/com/waz/service/AccountManager.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  zmessaging/src/main/scala/com/waz/service/otr/CryptoSessionService.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrClientsService.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrServiceImpl.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/main/scala/com/waz/sync/client/OtrClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/LegalHoldSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrClientsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/OtrClientsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/UserServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/otr/OtrSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/LegalHoldSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/OtrClientsSyncHandlerSpec.scala
Labels: size/XL

#3439 Federation: Add the domain to AccountData
  app/src/main/scala/com/waz/zclient/common/controllers/global/ClientsController.scala
  storage/src/main/kotlin/com/waz/zclient/storage/db/GlobalDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/MigrationUtils.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/accountdata/ActiveAccountsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/accountdata/GlobalDatabaseMigration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase127To128Migration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase128To129Migration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase129To130Migration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase130To131Migration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase131To132Migration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase133To134Migration.kt
  zmessaging/src/main/java/com/waz/model/sync/SyncCommand.java
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/log/LogShowInstancesSE.scala
  zmessaging/src/main/scala/com/waz/model/AccountData.scala
  zmessaging/src/main/scala/com/waz/model/otr/OtrClientIdMap.scala
  zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
  zmessaging/src/main/scala/com/waz/service/AccountManager.scala
  zmessaging/src/main/scala/com/waz/service/AccountsService.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrClientsService.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrServiceImpl.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/main/scala/com/waz/sync/client/OtrClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/LegalHoldSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrClientsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/OtrClientsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/UserServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/otr/OtrSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/LegalHoldSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/OtrClientsSyncHandlerSpec.scala
Labels: size/XXL

#3489 [Chore] Update copy for self-deleting messages
  app/src/main/res/values/strings.xml
Labels: size/S

#3472 Federation: basic messaging
  app/src/main/scala/com/waz/zclient/messages/UsersController.scala
  zmessaging/build.gradle
  zmessaging/src/main/scala/com/waz/model/otr/MessageResponse.scala
  zmessaging/src/main/scala/com/waz/model/otr/OtrClientIdMap.scala
  zmessaging/src/main/scala/com/waz/model/otr/OtrMessage.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrServiceImpl.scala
  zmessaging/src/main/scala/com/waz/sync/client/MessagesClient.scala
  zmessaging/src/main/scala/com/waz/sync/client/OtrClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ClearedSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/LastReadSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/OpenGraphSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ReactionsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/TrackingSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/ExpiredUsersServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/UserServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/TeamConversationSpec.scala
  zmessaging/src/test/scala/com/waz/service/otr/OtrSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/ConversationsSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/LegalHoldSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/MessagesSyncHandlerSpec.scala
Labels: size/XXL

#3491 Use new groupId for avs dependency
  scripts/avs.gradle
Labels: size/S

#3488 Federation: Use old code when the federation feature flag is off
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/UsersSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/ConversationsSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/OtrClientsSyncHandlerSpec.scala
Labels: size/L

#3483 chore: Remove PinEditTextField
  app/build.gradle
  app/src/main/res/values/styles_edittext.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/S

#3490 [Chore] Update file sharing copy
  app/src/main/res/values/strings.xml
Labels: size/XS

#3493 [Calling] Feature : Landscape mode
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout-land/calling__controls__grid.xml
  app/src/main/res/layout-land/fragment_calling_controls.xml
  app/src/main/res/layout-land/fragment_calling_grid.xml
  app/src/main/res/layout-land/fragment_calling_participants.xml
  app/src/main/res/values/dimens.xml
  app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
  app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/views/CallingMiddleLayout.scala
  app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
Labels: size/L

#3497 [Calling] Automation help - Add an ID for every page indicator
  app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
Labels: size/XS

#3499 [Calling : Bugfix - 1:1 video issues for the floating self preview
  app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
  app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
Labels: size/XS

#3501 fix: Enterprise alert is displayed when personal user tries to share a file
  zmessaging/src/main/scala/com/waz/model/ConferenceCallingFeatureConfig.scala
Labels: size/XS

#3500 Federation: Remove a federated user from the group conversation
  zmessaging/src/main/java/com/waz/model/sync/SyncCommand.java
  zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  zmessaging/src/main/scala/com/waz/service/push/PushService.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
  zmessaging/src/main/scala/com/waz/sync/client/PushNotificationsClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  zmessaging/src/test/scala/com/waz/sync/handler/ConversationsSyncHandlerSpec.scala
Labels: size/L

#3498 Federation: Disable promoting people from other backends to administrators
  app/src/main/scala/com/waz/zclient/participants/fragments/BaseSingleParticipantAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantFragment.scala
  zmessaging/src/main/java/com/waz/model/sync/SyncCommand.java
  zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  zmessaging/src/main/scala/com/waz/service/push/PushService.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
  zmessaging/src/main/scala/com/waz/sync/client/PushNotificationsClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  zmessaging/src/test/scala/com/waz/sync/handler/ConversationsSyncHandlerSpec.scala
Labels: size/L

#3495 Federation: Don't send availability status to users from other backends
  app/src/main/scala/com/waz/zclient/participants/fragments/BaseSingleParticipantAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantFragment.scala
  zmessaging/src/main/java/com/waz/model/sync/SyncCommand.java
  zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  zmessaging/src/main/scala/com/waz/service/push/PushService.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
  zmessaging/src/main/scala/com/waz/sync/client/PushNotificationsClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/UsersSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  zmessaging/src/test/scala/com/waz/sync/handler/ConversationsSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/UsersSyncHandlerSpec.scala
Labels: size/L

#3494 Federation: Use new endpoits for retrieving conversations data
  zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
  zmessaging/src/test/scala/com/waz/sync/handler/ConversationsSyncHandlerSpec.scala
Labels: size/L

#3503 Feature: display conference calling restrictions dialogs based on user type
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/utils/ContextUtils.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
Labels: size/M

#3505 [Calling] Feature : Large Conference Calls - Selective video
  scripts/avs.gradle
  zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  zmessaging/src/main/scala/com/waz/service/call/Calling.scala
Labels: size/S

#3506 [Calling] fix : Mute status is switched once the call is established
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
Labels: size/XS

#3480 Turn off packaging feature
  build.gradle
Labels: size/XS

#3510 Automation help : Increase the display duration for the calling overlay in internal builds
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
Labels: size/XS

#3511 Revert "Turn off packaging feature"
  build.gradle
Labels: size/XS

#3513 Turn off packaging feature flag
  build.gradle
Labels: size/XS

#3512 Federation: Use qualified target in conversation events
  zmessaging/src/main/scala/com/waz/model/Event.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
  zmessaging/src/test/scala/com/waz/model/EventSpec.scala
Labels: size/M

#3514 [Calling] Large Conference calls - Bugfix : tiles are ordered per page but not globally
  app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
Labels: size/S

#3507 Federation: Display the domain in the handle
  app/src/main/res/layout/preferences_account_layout.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/SetHandleFragment.scala
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
  app/src/main/scala/com/waz/zclient/common/views/UserDetailsView.scala
  app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListRow.scala
  app/src/main/scala/com/waz/zclient/messages/UsersController.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/UntabbedRequestFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/dialogs/ChangeHandleFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/AccountView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/BackupExportView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/ProfileView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/SettingsView.scala
  app/src/main/scala/com/waz/zclient/usersearch/SearchUIFragment.scala
  zmessaging/src/main/scala/com/waz/api/Credentials.scala
  zmessaging/src/main/scala/com/waz/db/DbTranslator.scala
  zmessaging/src/main/scala/com/waz/model/Handle.scala
  zmessaging/src/main/scala/com/waz/model/UserData.scala
  zmessaging/src/main/scala/com/waz/model/UserInfo.scala
  zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  zmessaging/src/main/scala/com/waz/sync/client/HandlesClient.scala
  zmessaging/src/main/scala/com/waz/utils/JsonDecoder.scala
  zmessaging/src/test/scala/com/waz/model/UserDataSpec.scala
  zmessaging/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/teams/TeamsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/OtrClientsSyncHandlerSpec.scala
Labels: size/L

#3508 Federation: Simplify post conversation
  zmessaging/src/main/java/com/waz/model/sync/SyncCommand.java
  zmessaging/src/main/scala/com/waz/model/sync/SyncRequest.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/utils/JsonDecoder.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/ConversationsSyncHandlerSpec.scala
Labels: size/L

#3515 [Calling] : Bump AVS version to 7.2.95
  scripts/avs.gradle
Labels: size/XS

#3516 [Calling] Bugfix - Calling flickering- part 1
  app/src/main/scala/com/waz/zclient/calling/AllParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/calling/NewCallingFragment.scala
Labels: size/S

#3519 Replace icu4j-shrunk dependency with native equivalent
  zmessaging/build.gradle
  zmessaging/src/main/scala/com/waz/utils/Locales.scala
Labels: size/XS

#3520 fix: User sees enterprise alert when starting 1:1 call in a non paying team
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
Labels: size/XS

#3521 chore: Switch on the feature flag for conference calling restriction
  build.gradle
Labels: size/XS
