Repository wireapp/wire-android, pull requests merged in 2021-11, with the labels that each got.

#3579 New Crowdin updates
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/XXL

#3576 Federation: Display the "federated users are present" in the conversation banner
  app/src/main/res/layout/fragment_conversation.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/participants/ParticipantsController.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/GroupParticipantsFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
Labels: size/L

#3582 fix: Users unable to send messages in some conversations
  zmessaging/src/main/scala/com/waz/model/ConversationData.scala
  zmessaging/src/main/scala/com/waz/model/UserData.scala
Labels: size/S

#3585 federation: consider domain when checking if user is a guest
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
  app/src/main/scala/com/waz/zclient/conversation/creation/CreateConversationController.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldUsersAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsController.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/UntabbedRequestFragment.scala
  zmessaging/src/main/scala/com/waz/model/UserData.scala
  zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  zmessaging/src/main/scala/com/waz/service/tracking/TrackingService.scala
Labels: size/M

#3588 Feature/version file implementation
  Jenkinsfile
  README.md
  app/build.gradle
  build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
  scripts/custombuild.gradle
Labels: size/L

#3586 federation: consider domain when checking if user is in the team
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
  app/src/main/scala/com/waz/zclient/deeplinks/DeepLinkService.scala
  zmessaging/src/main/scala/com/waz/model/UserData.scala
  zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  zmessaging/src/main/scala/com/waz/service/teams/TeamsService.scala
  zmessaging/src/main/scala/com/waz/sync/handler/UsersSyncHandler.scala
Labels: size/S

#3587 federation: consider domain when checking if the user is a external
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
  app/src/main/scala/com/waz/zclient/deeplinks/DeepLinkService.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsController.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/UntabbedRequestFragment.scala
  zmessaging/src/main/scala/com/waz/model/UserData.scala
  zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
Labels: size/S

#3591 Fix: self-deleting asset messages were not being deleted by receiver
  zmessaging/src/main/scala/com/waz/service/messages/EphemeralMessagesService.scala
Labels: size/S

#3592 fix: App crashes when trying to open group conversation details
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldUsersAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsAdapter.scala
Labels: size/XS

#3593 Fix: Timer selection still enabled when configuration is enforced by team
  app/src/main/scala/com/waz/zclient/cursor/CursorView.scala
  app/src/main/scala/com/waz/zclient/cursor/EphemeralTimerButton.scala
  app/src/main/scala/com/waz/zclient/sharing/ConversationSelectorFragment.scala
Labels: size/S

#3594 fix: consider domain only for federation
  zmessaging/src/main/scala/com/waz/model/UserData.scala
Labels: size/S

#3596 Chore: bump app version
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#3599 fix(config): Change default of conference calling enabled to true JCT-70
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
Labels: size/XS

#3601 added stage skip
  Jenkinsfile
Labels: size/XS

#3600 fix: Conference calling user preference and the enterprise alert SQSERVICES-906
  Jenkinsfile
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/model/ConferenceCallingFeatureConfig.scala
  zmessaging/src/main/scala/com/waz/model/FileSharingFeatureConfig.scala
  zmessaging/src/main/scala/com/waz/service/teams/FeatureConfigsService.scala
  zmessaging/src/main/scala/com/waz/sync/client/FeatureConfigsClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/FeatureConfigsSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsUiServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/TeamConversationSpec.scala
  zmessaging/src/test/scala/com/waz/service/teams/FeatureConfigsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/teams/TeamsServiceSpec.scala
Labels: size/L

#3602 chore: Delete PR template
  .github/pull_request_template.md
Labels: size/S

#3605 ci: Add Semantic PR title linting workflow SQPIT-769
  .github/workflows/semantic-commit-lint.yml
Labels: size/M

#3603 ci: Add Jira Link Workflow SQPIT-768
  .github/workflows/jira-lint-and-link.yml
Labels: size/S
