Repository wireapp/wire-android, pull requests merged in 2021-02, with the labels that each got.

#3160 Bump avs version to 6.6.15
  scripts/avs.gradle
Labels: size/XS

#3162 fix: Perform full sync on backup restoration and delete conversations missing on the backend
  app/src/main/scala/com/waz/zclient/appentry/fragments/FirstLaunchAfterLoginFragment.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/sync/client/ConversationsClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
  zmessaging/src/test/scala/com/waz/sync/handler/ConversationsSyncHandlerSpec.scala
Labels: size/L

#3163 fix: An unrecognized event crashes the decryption process
  zmessaging/src/main/scala/com/waz/model/Event.scala
  zmessaging/src/main/scala/com/waz/service/push/PushService.scala
Labels: size/M

#3165 [Calling] : feature : active speaker - long term and instant audio activity
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/views/OtherVideoView.scala
  app/src/main/scala/com/waz/zclient/calling/views/SelfVideoView.scala
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
  scripts/avs.gradle
  zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
Labels: size/M

#3161 [Calling] Remove disturbing join and leave sounds during a call
  app/build.gradle
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  build.gradle
Labels: size/S

#3166 fix: Backup restoration freezes the app
  app/src/main/scala/com/waz/zclient/appentry/fragments/FirstLaunchAfterLoginFragment.scala
Labels: size/XS

#3168 refactor: Removing code connected to old migrations
  zmessaging/src/main/scala/com/waz/content/AccountsStorage.scala
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/model/AccountData.scala
  zmessaging/src/main/scala/com/waz/model/AccountDataOld.scala
  zmessaging/src/main/scala/com/waz/service/AccountsService.scala
  zmessaging/src/main/scala/com/waz/service/GlobalModule.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  zmessaging/src/test/scala/com/waz/service/teams/TeamsServiceSpec.scala
Labels: size/XL

#3169 fix: NullPointerException in markdown
  app/src/main/scala/com/waz/zclient/messages/parts/TextPartView.scala
  zmessaging/src/main/scala/com/waz/utils/WhereAmI.scala
Labels: size/S

#3170 Enable the feature flag for AppLock
  build.gradle
Labels: size/XS

#3172 [Calling]: features to release with 3.64
  build.gradle
Labels: size/XS

#3175 Chore: update README.md
  README.md
Labels: size/XS

#3176 New password dialog
  app/src/main/scala/com/waz/zclient/common/controllers/global/PasswordController.scala
  app/src/main/scala/com/waz/zclient/preferences/dialogs/NewPasswordDialog.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/AppLockView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/OptionsView.scala
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/service/teams/FeatureFlagsService.scala
Labels: size/L

#3174 [Calling] : Disable active speakers/all toggle
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
Labels: size/S

#3171 [Calling] Bump AVS version to 6.7.9
  scripts/avs.gradle
Labels: size/XS

#3178 Turn calling flags to on for testing purpose
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
  build.gradle
Labels: size/S

#3179 [Calling] : fix speakers/all toggle behaviour when the app is coming from the background
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
Labels: size/XS

#3180 fix: Optimize push notifications
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings_no_translate.xml
  app/src/main/scala/com/waz/services/fcm/FCMHandlerService.scala
  app/src/main/scala/com/waz/services/websocket/WebSocketService.scala
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/security/SecurityPolicyChecker.scala
  zmessaging/src/main/scala/com/waz/service/AccountsService.scala
  zmessaging/src/main/scala/com/waz/service/NetworkModeService.scala
Labels: size/L

#3181 Changes needed for work with wire-signals-0.4.0
  app/build.gradle
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/conversation/toolbar/AudioMessageRecordingView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/EphemeralPartView.scala
  app/src/main/scala/com/waz/zclient/messages/parts/footer/FooterViewController.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
  buildSrc/src/main/kotlin/Dependencies.kt
  zmessaging/build.gradle
  zmessaging/src/main/scala/com/waz/service/assets/GlobalRecordAndPlayService.scala
  zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
Labels: size/M

#3173 Remove old code
  macrosupport/src/main/scala/com/waz/Control.scala
  macrosupport/src/main/scala/com/waz/utils/returning.scala
  zmessaging/src/main/scala/com/waz/api/AssetFactory.scala
  zmessaging/src/main/scala/com/waz/api/MemoryImageCache.scala
  zmessaging/src/main/scala/com/waz/api/impl/PlaybackControls.scala
  zmessaging/src/main/scala/com/waz/api/impl/RecordingLevels.scala
  zmessaging/src/main/scala/com/waz/api/impl/UiObservable.scala
  zmessaging/src/main/scala/com/waz/service/GlobalModule.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  zmessaging/src/main/scala/com/waz/ui/MemoryImageCache.scala
  zmessaging/src/main/scala/com/waz/ui/UiCache.scala
  zmessaging/src/main/scala/com/waz/ui/UiModule.scala
  zmessaging/src/test/scala/com/waz/api/impl/RecordingLevelsSpec.scala
Labels: size/XL

#3182 Chore : Add bintray-backup repository for Grgit
  scripts/customization.gradle
Labels: size/XS

#3183 [Calling] Active speaker view
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  scripts/avs.gradle
Labels: size/XS

#3185 Bump avs to 6.7.13
  scripts/avs.gradle
Labels: size/XS

#3186 [Calling] speakers view improvement
  app/src/main/res/values/strings.xml
  scripts/avs.gradle
Labels: size/XS

#3188 bump avs version to 6.7.15
  scripts/avs.gradle
Labels: size/XS

#3187 Code Freeze 3.65
  build.gradle
Labels: size/XS

#3189 bump avs version to 6.7.16
  scripts/avs.gradle
Labels: size/XS

#3190 Code freeze 3.65: follow up
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
  build.gradle
Labels: size/S

#3192 [Calling] : Bugfix : speakers toggle is selected after starting a new call
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
Labels: size/S
