Repository wireapp/wire-android, pull requests merged in 2021-04, with the labels that each got.

#3227 Fix: Empty layout on ParticipantFragment after opening "Create group" and coming back
  app/src/main/scala/com/waz/zclient/participants/fragments/BlockedUserFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ConnectRequestFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/PendingConnectRequestFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SendConnectRequestFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/UntabbedRequestFragment.scala
Labels: size/M

#3228 [Fix] Legal hold request event
  zmessaging/src/main/scala/com/waz/model/Event.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
  zmessaging/src/test/scala/com/waz/model/EventSpec.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
Labels: size/M

#3230 Feature : zooming for group calls
  app/build.gradle
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
  app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
  build.gradle
Labels: size/M

#3224 Feature: Legal Hold - Create a general purpose confirmation dialog with password input
  app/src/main/res/layout/confirmation_with_password_dialog.xml
  app/src/main/scala/com/waz/zclient/preferences/dialogs/ConfirmationWithPasswordDialog.scala
  app/src/main/scala/com/waz/zclient/preferences/dialogs/RemoveDeviceDialog.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/DeviceDetailsView.scala
Labels: size/L

#3225 Feature: Legal Hold - Create pop up for legal hold request
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldRequestDialog.scala
Labels: size/M

#3213 Feature: Legal Hold - Legal hold details screen for conversation
  app/src/main/res/layout/fragment_legal_hold_info.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldController.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldInfoFragment.scala
  app/src/main/scala/com/waz/zclient/legalhold/SelfUserLegalHoldInfoActivity.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantHeaderFragment.scala
Labels: size/M

#3232 fix : black screen after zooming and going back to the video grid screen
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
Labels: size/S

#3236 Disable zooming feature flag
  build.gradle
Labels: size/XS

#3235 fix: Another try at fixing the notification channel crash from Google Play Console
  app/src/main/scala/com/waz/services/websocket/WebSocketService.scala
  app/src/main/scala/com/waz/zclient/WireApplication.scala
Labels: size/M

#3237 patch version implementation
  app/build.gradle
Labels: size/XS

#3233 fix: App freeze when the backup is being restored on a new device
  app/src/main/scala/com/waz/zclient/Intents.scala
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/main/scala/com/waz/zclient/appentry/AppEntryActivity.scala
  app/src/main/scala/com/waz/zclient/appentry/SSOWebViewFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/FirstLaunchAfterLoginFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/InviteToTeamFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/PhoneSetNameFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/VerifyEmailWithCodeFragment.scala
  app/src/main/scala/com/waz/zclient/appentry/fragments/VerifyPhoneFragment.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
Labels: size/M

#3240 Fix: ActivityLifecycleCallback - onStop callback overrides currentActivity set on onStart callback
  app/src/main/scala/com/waz/zclient/security/ActivityLifecycleCallback.scala
Labels: size/XS

#3242 fix: App crash when just after the install the app is put to background
  app/src/main/scala/com/waz/services/websocket/WebSocketService.scala
Labels: size/XS

#3244 Feature: Legal Hold - Add feature flag
  build.gradle
  zmessaging/build.gradle
  zmessaging/src/main/scala/com/waz/service/DisabledLegalHoldService.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
Labels: size/M

#3241 Bugfix : Hide call controls overlay after zooming
  app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
  app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
  build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/S

#3243 Feature: Legal hold acceptance - Check whether pop up should be displayed when app comes to foreground
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/security/SecurityPolicyChecker.scala
  app/src/main/scala/com/waz/zclient/security/actions/ShowLegalHoldApprovalAction.scala
  app/src/main/scala/com/waz/zclient/security/checks/RequestLegalHoldCheck.scala
Labels: size/M

#3238 Remove feature flags for the released calling features
  app/build.gradle
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
  build.gradle
  zmessaging/build.gradle
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
Labels: size/M

#3239 Remove deprecated kotlin feature flags
  app/build.gradle
  build.gradle
  storage/build.gradle
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase126To127Migration.kt
  zmessaging/build.gradle
  zmessaging/src/main/scala/com/waz/service/GlobalModule.scala
Labels: size/M

#3245 Feature: Legal hold acceptance - Part 2 - Enhancements for dialog
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldRequestDialog.scala
  app/src/main/scala/com/waz/zclient/preferences/dialogs/ConfirmationWithPasswordDialog.scala
Labels: size/M

#3221 Removing icu4j-shrunk and fixing tests
  zmessaging/build.gradle
  zmessaging/src/main/scala/com/waz/content/UsersStorage.scala
  zmessaging/src/main/scala/com/waz/model/Handle.scala
  zmessaging/src/main/scala/com/waz/model/UserData.scala
  zmessaging/src/main/scala/com/waz/service/SearchKey.scala
  zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  zmessaging/src/main/scala/com/waz/utils/Locales.scala
  zmessaging/src/main/scala/com/waz/utils/wrappers/DBSession.scala
  zmessaging/src/test/scala/com/waz/service/SearchKeySpec.scala
  zmessaging/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/connections/ConnectionServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/notifications/NotificationServiceSpec.scala
  zmessaging/src/test/scala/com/waz/testutils/package.scala
  zmessaging/src/test/scala/org/robolectric/shadows/ShadowAlphabeticIndex.scala
  zmessaging/src/test/scala/org/robolectric/shadows/ShadowTransliterator.scala
Labels: size/L

#3251 [Calling] Feature : zooming one one call
  app/src/main/res/layout/fragment_calling.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
Labels: size/M

#3254 [Calling] fix : full screen videos are displayed in fill mode
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
Labels: size/S

#3253 [Calling] Enable zooming for videos in 1:1 calls
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
Labels: size/XS

#3256 [Calling] Fix : The self video is frozen on the remote side
  app/src/main/res/layout/fragment_calling.xml
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
  app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/views/SelfVideoView.scala
  build.gradle
Labels: size/M

#3250 refactor: Simplify SyncExecutor.execute
  zmessaging/src/main/scala/com/waz/sync/queue/SyncExecutor.scala
Labels: size/M

#3246 Feature: Legal hold acceptance - Part 3 - Show approval pop up
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldController.scala
  app/src/main/scala/com/waz/zclient/security/SecurityPolicyChecker.scala
  app/src/main/scala/com/waz/zclient/security/actions/ShowLegalHoldApprovalAction.scala
Labels: size/M

#3247 Feature: Legal hold acceptance - Part 4 - Show spinner while waiting for network response
  app/src/main/scala/com/waz/zclient/security/SecurityPolicyChecker.scala
  app/src/main/scala/com/waz/zclient/security/actions/ShowLegalHoldApprovalAction.scala
Labels: size/M

#3263 refactor: Remove contacts
  zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
  zmessaging/src/main/scala/com/waz/model/AddressBook.scala
  zmessaging/src/main/scala/com/waz/model/Contact.scala
  zmessaging/src/main/scala/com/waz/model/Uid.scala
Labels: size/L

#3262 refactor: Identifiers as newtypes
  app/src/main/scala/com/waz/jobs/PushTokenCheckJob.scala
  app/src/main/scala/com/waz/services/fcm/FCMHandlerService.scala
  app/src/main/scala/com/waz/services/fcm/FetchJob.scala
  app/src/main/scala/com/waz/services/notifications/NotificationsHandlerService.scala
  app/src/main/scala/com/waz/zclient/Intents.scala
  app/src/main/scala/com/waz/zclient/integrations/IntegrationDetailsFragment.scala
  zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
  zmessaging/src/main/scala/com/waz/model/AddressBook.scala
  zmessaging/src/main/scala/com/waz/model/Contact.scala
  zmessaging/src/main/scala/com/waz/model/Uid.scala
  zmessaging/src/main/scala/com/waz/service/push/NotificationService.scala
  zmessaging/src/main/scala/com/waz/sync/client/OtrClient.scala
  zmessaging/src/test/scala/com/waz/service/conversation/TeamConversationSpec.scala
Labels: size/L

#3214 Feature: Legal Hold - Legal hold details screen for conversation - Show user's device list
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldController.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldInfoFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantFragment.scala
Labels: size/S

#3255 [Fix] Legal hold request deserialization error
  zmessaging/src/main/scala/com/waz/sync/client/LegalHoldClient.scala
Labels: size/XS

#3257 [Refactor] LegalHoldSyncHandler
  zmessaging/src/main/scala/com/waz/service/DisabledLegalHoldService.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/main/scala/com/waz/sync/handler/LegalHoldSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/LegalHoldSyncHandlerSpec.scala
Labels: size/L

#3267 [Fix] Legal hold approval fails with correct password
  zmessaging/src/main/scala/com/waz/sync/client/LegalHoldClient.scala
Labels: size/XS

#3258 [Refactor] Store legal hold request in UserPreferences
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
Labels: size/M

#3266 chore: Remove Stetho
  app/build.gradle
  app/src/dev/AndroidManifest.xml
  app/src/dev/scala/com/waz/zclient/StethoApplication.scala
  app/src/experimental/AndroidManifest.xml
  app/src/experimental/scala/com/waz/zclient/StethoApplication.scala
  app/src/internal/AndroidManifest.xml
  app/src/internal/scala/com/waz/zclient/StethoApplication.scala
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/M

#3268 Refactor: Legal Hold Approval Pop-up - Move popup logic to another class
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldApprovalHandler.scala
  app/src/main/scala/com/waz/zclient/security/SecurityPolicyChecker.scala
  app/src/main/scala/com/waz/zclient/security/actions/ShowLegalHoldApprovalAction.scala
  zmessaging/src/main/scala/com/waz/service/DisabledLegalHoldService.scala
Labels: size/L

#3265 Feature: Legal Hold Approval Pop-up - Check sso, calculate fingerprint
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldApprovalHandler.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldController.scala
  zmessaging/src/main/scala/com/waz/service/DisabledLegalHoldService.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
Labels: size/M

#3264 Qualified ids
  app/src/main/kotlin/com/waz/zclient/feature/backup/users/UsersBackUpDataMapper.kt
  app/src/main/kotlin/com/waz/zclient/feature/backup/users/UsersBackUpModel.kt
  app/src/main/scala/com/waz/zclient/MainActivity.scala
  app/src/test/kotlin/com/waz/zclient/feature/backup/users/UsersBackUpDataMapperTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/users/UsersTestDataProvider.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase130To131Migration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/model/UsersEntity.kt
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/model/QualifiedId.scala
  zmessaging/src/main/scala/com/waz/model/UserData.scala
  zmessaging/src/main/scala/com/waz/model/UserInfo.scala
  zmessaging/src/main/scala/com/waz/model/otr/Client.scala
  zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/sync/SyncServiceHandle.scala
  zmessaging/src/test/scala/com/waz/model/UserDataSpec.scala
  zmessaging/src/test/scala/com/waz/model/UserInfoSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/TeamConversationSpec.scala
  zmessaging/src/test/scala/com/waz/service/teams/TeamsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/SyncRequestServiceSpec.scala
Labels: size/L

#3269 Feature: Legal Hold Approval - Display pending icon
  app/src/main/res/layout/view_conv_list_top.xml
  app/src/main/scala/com/waz/zclient/conversationlist/ConversationListFragment.scala
  app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListTopToolbar.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldApprovalHandler.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldController.scala
  app/src/main/scala/com/waz/zclient/security/checks/RequestLegalHoldCheck.scala
Labels: size/M

#3271 Fix: Legal Hold Request Signal update problem
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
Labels: size/XS

#3273 Feature: Legal Hold Request - Detect when legal hold is requested and show pop up immediately
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldStatusChangeListener.scala
  app/src/main/scala/com/waz/zclient/security/ActivityLifecycleCallback.scala
Labels: size/M

#3274 Enable Legal Hold feature flag
  build.gradle
Labels: size/XS

#3276 [Calling] Remove features flags for zooming and active speakers
  app/build.gradle
  app/src/main/res/layout/fragment_full_screen_video_without_zooming.xml
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
  app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
  build.gradle
Labels: size/M

#3281 [Calling] Bump AVS version to 7.1.1
  scripts/avs.gradle
Labels: size/XS

#3275 [Calling] Feature : Large video conference calls - Dark Theme
  app/build.gradle
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/views/ControlsView.scala
  build.gradle
Labels: size/M

#3280 Feature: Legal Hold info modal - Display All legal hold subjects on a separate screen
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/legalhold/AllLegalHoldSubjectsFragment.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldController.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldInfoFragment.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldUsersAdapter.scala
  app/src/main/scala/com/waz/zclient/legalhold/SelfUserLegalHoldInfoActivity.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantHeaderFragment.scala
Labels: size/L

#3282 Feature: Legal Hold - Display participant's legal hold device
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/participants/ParticipantOtrDeviceAdapter.scala
Labels: size/S

#3286 Feature: Legal Hold Info Modal - Prevent opening legal hold info screen again from participant screen
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldController.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldInfoFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantHeaderFragment.scala
Labels: size/S
