Repository wireapp/wire-android, pull requests merged in 2021-03, with the labels that each got.

#3195 [Calling] fix : The video of the self user is frozen in the remote side when it not displayed in the screen
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
Labels: size/S

#3196 [Calling] fix : hide the active speakers/all toggle for group calls with 2 participants
  app/src/main/scala/com/waz/zclient/calling/ControlsFragment.scala
Labels: size/S

#3198 [Calling] fix for video frozen in the remote side
  app/src/main/scala/com/waz/zclient/calling/CallingFragment.scala
Labels: size/S

#3199 fix: The self video is turned video off but other participants keep receiving video packages
  app/src/main/scala/com/waz/zclient/calling/views/SelfVideoView.scala
Labels: size/XS

#3200 Bump avs version to 7.0.3
  scripts/avs.gradle
Labels: size/XS

#3194 Remove bintray
  build.gradle
  buildSrc/build.gradle.kts
  scripts/avs.gradle
Labels: size/M

#3203 Bump AVS version to 7.0.5
  scripts/avs.gradle
Labels: size/XS

#3204 [Calling] turn on the feature flag for join group calls in muted status feature
  build.gradle
Labels: size/XS

#3205 Feature : Legal Hold - Indicate legal hold in Conversation title
  app/src/main/res/drawable/ic_legal_hold_active.xml
  app/src/main/res/drawable/ic_legal_hold_pending.xml
  app/src/main/res/layout/fragment_conversation.xml
  app/src/main/res/values/dimens.xml
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
  zmessaging/src/main/scala/com/waz/service/legalhold/LegalHoldController.scala
  zmessaging/src/main/scala/com/waz/service/legalhold/LegalHoldStatus.scala
Labels: size/M

#3208 [Calling]: add feature flag for zooming
  app/build.gradle
  app/src/main/res/layout/fragment_full_screen_video_without_zooming.xml
  app/src/main/scala/com/waz/zclient/calling/FullScreenVideoFragment.scala
  build.gradle
Labels: size/M

#3207 Refactor Legal Hold status
  app/src/main/res/layout/fragment_participants_header.xml
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldController.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantHeaderFragment.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
  zmessaging/src/main/scala/com/waz/service/legalhold/LegalHoldController.scala
  zmessaging/src/main/scala/com/waz/service/legalhold/LegalHoldStatus.scala
Labels: size/L

#3193 refactor: Use new protobuf 1.28.2
  app/build.gradle
  app/proguard-rules.txt
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/conversationlist/ConversationListManagerFragment.scala
  app/src/main/scala/com/waz/zclient/messages/MessagesController.scala
  app/src/main/scala/com/waz/zclient/messages/parts/WebLinkPartView.scala
  app/src/main/scala/com/waz/zclient/pages/main/MainPhoneFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleOtrClientFragment.scala
  app/src/main/scala/com/waz/zclient/quickreply/QuickReplyContentAdapter.scala
  app/src/main/scala/com/waz/zclient/usersearch/SearchUIFragment.scala
  buildSrc/src/main/kotlin/Dependencies.kt
  zmessaging/build.gradle
  zmessaging/src/main/scala/com/waz/db/Col.scala
  zmessaging/src/main/scala/com/waz/db/DbTranslator.scala
  zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
  zmessaging/src/main/scala/com/waz/db/migrate/MessageDataMigration.scala
  zmessaging/src/main/scala/com/waz/log/LogShowInstancesSE.scala
  zmessaging/src/main/scala/com/waz/model/AssetData.scala
  zmessaging/src/main/scala/com/waz/model/CompositeData.scala
  zmessaging/src/main/scala/com/waz/model/Event.scala
  zmessaging/src/main/scala/com/waz/model/GenericContent.scala
  zmessaging/src/main/scala/com/waz/model/MessageData.scala
  zmessaging/src/main/scala/com/waz/model/package.scala
  zmessaging/src/main/scala/com/waz/service/GenericMessageService.scala
  zmessaging/src/main/scala/com/waz/service/assets/models.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationOrderEventsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  zmessaging/src/main/scala/com/waz/service/media/RichMediaContentParser.scala
  zmessaging/src/main/scala/com/waz/service/messages/EphemeralMessagesService.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessagesContentUpdater.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrServiceImpl.scala
  zmessaging/src/main/scala/com/waz/service/push/NotificationService.scala
  zmessaging/src/main/scala/com/waz/sync/client/MessagesClient.scala
  zmessaging/src/main/scala/com/waz/sync/client/OtrClient.scala
  zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/OpenGraphSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrSyncHandler.scala
  zmessaging/src/main/scala/com/waz/utils/crypto/ReplyHashing.scala
  zmessaging/src/test/scala/com/waz/db/ZMessagingDBSpec.scala
  zmessaging/src/test/scala/com/waz/model/EventSpec.scala
  zmessaging/src/test/scala/com/waz/model/MessageDataSpec.scala
  zmessaging/src/test/scala/com/waz/service/MessageEventProcessorSpec.scala
  zmessaging/src/test/scala/com/waz/service/notifications/NotificationServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/UsersSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/testutils/package.scala
  zmessaging/src/test/scala/com/waz/utils/crypto/ReplyHashingSpec.scala
Labels: size/XXL

#3209 fix: Read receipts with the new protobuf
  zmessaging/src/main/scala/com/waz/model/package.scala
  zmessaging/src/main/scala/com/waz/service/GenericMessageService.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
  zmessaging/src/main/scala/com/waz/sync/queue/SyncContentUpdater.scala
  zmessaging/src/test/scala/com/waz/sync/SyncContentUpdaterSpec.scala
Labels: size/M

#3211 Feature: Legal Hold - Indicate legal hold in conversation list
  app/src/main/res/layout/view_conv_list_top.xml
  app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListTopToolbar.scala
Labels: size/M

#3212 Feature: Legal Hold - Legal hold details screen for self user
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/activity_legal_hold_info.xml
  app/src/main/res/layout/fragment_legal_hold_info.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/conversationlist/ConversationListFragment.scala
  app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListTopToolbar.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldInfoFragment.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldUsersAdapter.scala
  app/src/main/scala/com/waz/zclient/legalhold/SelfUserLegalHoldInfoActivity.scala
Labels: size/L

#3216 A revert of a part of a code changed in "Optimize push notifications (#3180)"
  app/src/main/scala/com/waz/services/websocket/WebSocketService.scala
Labels: size/S

#3217 Define legal hold request
  zmessaging/src/main/scala/com/waz/model/LegalHoldRequest.scala
  zmessaging/src/test/scala/com/waz/model/LegalHoldRequestSpec.scala
Labels: size/L

#3220 Define legal hold service
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/legalhold/LegalHoldController.scala
  zmessaging/src/main/scala/com/waz/model/Event.scala
  zmessaging/src/main/scala/com/waz/service/LegalHoldService.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  zmessaging/src/test/scala/com/waz/model/EventSpec.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
Labels: size/L

#3219 Gradle Android Scala plugin
  build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS
