Repository wireapp/wire-android, pull requests merged in 2021-12, with the labels that each got.

#3611 Notifications: Refactoring to make initialization lighter when it's triggered by a notification (SQCORE-1146)
  app/src/main/scala/com/waz/services/notifications/NotificationsHandlerService.scala
  app/src/main/scala/com/waz/services/websocket/WebSocketService.scala
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
  zmessaging/src/main/scala/com/waz/service/AccountContext.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  zmessaging/src/main/scala/com/waz/service/call/CallLoggingService.scala
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  zmessaging/src/main/scala/com/waz/service/otr/EventDecrypter.scala
  zmessaging/src/main/scala/com/waz/service/otr/NotificationParser.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrClientsService.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrEventDecoder.scala
  zmessaging/src/main/scala/com/waz/service/push/PushService.scala
  zmessaging/src/main/scala/com/waz/service/push/WSPushService.scala
  zmessaging/src/test/scala/com/waz/service/EventDecrypterSpec.scala
  zmessaging/src/test/scala/com/waz/service/NotificationParserSpec.scala
  zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
Labels: size/L

#3610 Notifications: Remove redundant and obsolete code (SQCORE-1143)
  app/src/fdroid/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/preferences_advanced_layout.xml
  app/src/main/scala/com/waz/services/notifications/NotificationsHandlerService.scala
  app/src/main/scala/com/waz/services/websocket/WebSocketService.scala
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/MessageNotificationsController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/NotificationManagerWrapper.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/AdvancedView.scala
  app/src/nonfree/scala/com/waz/services/fcm/FCMHandlerService.scala
  app/src/nonfree/scala/com/waz/services/fcm/FCMNotificationWorker.scala
  app/src/nonfree/scala/com/waz/services/fcm/FCMService.scala
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/CloudNotificationStatsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/CloudNotificationStatsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/CloudNotificationsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/CloudNotificationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/NotificationDataDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/NotificationDataEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase135To136Migration.kt
  zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
  zmessaging/src/main/scala/com/waz/content/NotificationStorageImpl.scala
  zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
  zmessaging/src/main/scala/com/waz/model/FCMNotification.scala
  zmessaging/src/main/scala/com/waz/model/NotificationData.scala
  zmessaging/src/main/scala/com/waz/repository/FCMNotificationStatsRepository.scala
  zmessaging/src/main/scala/com/waz/repository/FCMNotificationsRepository.scala
  zmessaging/src/main/scala/com/waz/service/AccountContext.scala
  zmessaging/src/main/scala/com/waz/service/FCMNotificationStatsService.scala
  zmessaging/src/main/scala/com/waz/service/ReportingService.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  zmessaging/src/main/scala/com/waz/service/call/CallLoggingService.scala
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  zmessaging/src/main/scala/com/waz/service/otr/EventDecrypter.scala
  zmessaging/src/main/scala/com/waz/service/otr/NotificationParser.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrClientsService.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrEventDecoder.scala
  zmessaging/src/main/scala/com/waz/service/push/PushService.scala
  zmessaging/src/main/scala/com/waz/service/push/WSPushService.scala
  zmessaging/src/test/java/com/waz/db/migration/KotlinMigrationHelper.kt
  zmessaging/src/test/scala/com/waz/repository/FCMNotificationsRepositorySpec.scala
  zmessaging/src/test/scala/com/waz/service/EventDecrypterSpec.scala
  zmessaging/src/test/scala/com/waz/service/FCMNotificationStatsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/NotificationParserSpec.scala
  zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
Labels: DO NOT MERGE, size/XXL

#3609 Notifications: Process the new messages when the app comes to the front + refactoring (SQCORE-1142)
  app/src/fdroid/AndroidManifest.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/preferences_advanced_layout.xml
  app/src/main/scala/com/waz/services/notifications/NotificationsHandlerService.scala
  app/src/main/scala/com/waz/services/websocket/WebSocketService.scala
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/MessageNotificationsController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/NotificationManagerWrapper.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/AdvancedView.scala
  app/src/nonfree/scala/com/waz/services/fcm/FCMHandlerService.scala
  app/src/nonfree/scala/com/waz/services/fcm/FCMNotificationWorker.scala
  app/src/nonfree/scala/com/waz/services/fcm/FCMPushHandler.scala
  app/src/nonfree/scala/com/waz/services/fcm/FCMService.scala
  app/src/test/scala/com/waz/services/fcm/FCMPushHandlerSpec.scala
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/CloudNotificationStatsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/CloudNotificationStatsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/CloudNotificationsDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/CloudNotificationsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/NotificationDataDao.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/notifications/NotificationDataEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase135To136Migration.kt
  zmessaging/src/main/scala/com/waz/content/MessagesStorage.scala
  zmessaging/src/main/scala/com/waz/content/NotificationStorageImpl.scala
  zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
  zmessaging/src/main/scala/com/waz/model/FCMNotification.scala
  zmessaging/src/main/scala/com/waz/model/MsgDeletion.scala
  zmessaging/src/main/scala/com/waz/model/NotificationData.scala
  zmessaging/src/main/scala/com/waz/repository/FCMNotificationStatsRepository.scala
  zmessaging/src/main/scala/com/waz/repository/FCMNotificationsRepository.scala
  zmessaging/src/main/scala/com/waz/service/AccountContext.scala
  zmessaging/src/main/scala/com/waz/service/FCMNotificationStatsService.scala
  zmessaging/src/main/scala/com/waz/service/GlobalModule.scala
  zmessaging/src/main/scala/com/waz/service/ReportingService.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  zmessaging/src/main/scala/com/waz/service/call/CallLoggingService.scala
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/service/messages/EphemeralMessagesService.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessagesContentUpdater.scala
  zmessaging/src/main/scala/com/waz/service/otr/EventDecrypter.scala
  zmessaging/src/main/scala/com/waz/service/otr/NotificationParser.scala
  zmessaging/src/main/scala/com/waz/service/otr/NotificationUiController.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrClientsService.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrEventDecoder.scala
  zmessaging/src/main/scala/com/waz/service/push/NotificationService.scala
  zmessaging/src/main/scala/com/waz/service/push/PushNotificationEventsStorage.scala
  zmessaging/src/main/scala/com/waz/service/push/PushService.scala
  zmessaging/src/main/scala/com/waz/service/push/WSPushService.scala
  zmessaging/src/test/java/com/waz/db/migration/KotlinMigrationHelper.kt
  zmessaging/src/test/scala/com/waz/repository/FCMNotificationsRepositorySpec.scala
  zmessaging/src/test/scala/com/waz/service/EventDecrypterSpec.scala
  zmessaging/src/test/scala/com/waz/service/FCMNotificationStatsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/NotificationParserSpec.scala
  zmessaging/src/test/scala/com/waz/service/OtrEventDecoderSpec.scala
  zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/notifications/NotificationServiceSpec.scala
Labels: DO NOT MERGE, size/XXL

#3615 chore: GRGIT update
  build.gradle
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#3616 chore: Assign sub-system tags
  app/src/test/kotlin/com/waz/zclient/core/network/connection/ConnectionSpecsFactoryTest.kt
  app/src/test/kotlin/com/waz/zclient/core/network/pinning/CertificatePinnerFactoryTest.kt
  app/src/test/kotlin/com/waz/zclient/feature/backup/crypto/decryption/DecryptionHandlerTest.kt
  zmessaging/src/test/scala/com/waz/service/otr/OtrSyncHandlerSpec.scala
Labels: size/S

#3578 chore(qa): Feature/default json refactoring
  app/build.gradle
  default.json
Labels: size/L
