Repository wireapp/wire-android, pull requests merged in 2022-05, with the labels that each got.

#552 feat(delete-message): hide edit context menu when delete action triggered [AR-923]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreenState.kt
Labels: size/XS

#554 fix(sso-login): loading server config from deep link and set staging for SSO login
  app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmail.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSO.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/LoginViewModelTest.kt
Labels: size/M

#556 fix: muting options error state and ui specs (AR-1043)
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MutingOptionsSheetContent.kt
  app/src/main/res/values/strings.xml
Labels: size/M

#557 chore: add stale bot
  .github/stale.yml
Labels: size/S

#559 fix: profile pic issue and muting options ui adjustment (AR-1413) (AR-1043)
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/ModalSheetHeaderItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetLayout.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MutingOptionsSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPickerViewModel.kt
Labels: size/M

#549 test: user profile change status tests
  app/src/androidTest/java/com/wire/android/ui/UserProfileScreenTest.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
Labels: size/L

#561 chore: add google services
  app/build.gradle.kts
  app/google-services.json
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/L

#562 fix: fixed url links not working correctly [AR-1545]
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmail.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/EmptySearchQueryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleScreen.kt
Labels: size/S

#555 fix: keyboard behavior on "remove device" screen and copy on "register device" screen [AR-1478] [AR-1532]
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDevice.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDevice.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmail.kt
  app/src/main/res/values/strings.xml
Labels: size/M

#564 chore(login): change the location of server title in login page
  app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmail.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSO.kt
Labels: size/M

#565 feat(menu): close the context menu when the back button pressed [AR-1535]
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetLayout.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
Labels: size/M

#568 chore: set up local java version for jenv
  .java-version
Labels: size/XS

#570 fix: new group button paddings [AR-1577]
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/GroupButton.kt
Labels: size/XS

#572 fix: add bottomNavigation height as padding to the main home navHost [AR-1474]
  app/src/main/kotlin/com/wire/android/ui/common/BottomNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/S

#560 chore: tune coverage settings
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  buildSrc/src/main/kotlin/scripts/quality.gradle.kts
  codecov.yml
Labels: size/S

#567 fix: remove flip camera button & close screen button from calling screen
  app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/CallOptionsControls.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallScreen.kt
Labels: size/S

#577 chore: change log file type
  app/src/main/kotlin/com/wire/android/ui/settings/SettingsScreen.kt
  app/src/main/kotlin/com/wire/android/util/KaliumFileWriter.kt
Labels: size/S

#578 fix: validate blank fields in create account details [AR-1599]
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsViewState.kt
Labels: size/XS

#569 fix: profile status buttons UI [AR-1584]
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
Labels: size/L

#573 test: device registration step
  app/src/androidTest/java/com/wire/android/ui/RegisterDeviceTest.kt
  app/src/androidTest/java/com/wire/android/ui/UserProfileScreenTest.kt
Labels: size/XS

#574 test: add create team tests
  app/src/androidTest/java/com/wire/android/ui/CreateTeamScreenTest.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
Labels: size/L

#581 test: fixed a flaky step
  app/src/androidTest/java/com/wire/android/ui/RemoveDeviceScreenTest.kt
  app/src/androidTest/java/com/wire/android/ui/UserProfileScreenTest.kt
  app/src/androidTest/java/com/wire/android/utils/Extensions.kt
Labels: size/S

#584 fix: app crash when receiving notification for unauthenticated account
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
Labels: size/M

#579 feat(conn-request): send connection request tests and list details - pt.2 (AR-1518)
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
Labels: WIP, size/L

#576 feat(conn-request): send connection request from other userprofile - pt.1 (AR-1486)
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/model/Contact.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/InternalContactSearchResultItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileState.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
Labels: size/L

#588 chore: bump core dependencies
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreateAccountOverviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/summary/CreateAccountSummaryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/attachment/AttachmentOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/L

#592 fix: fixes from design review applied
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
Labels: size/M

#594 fix: issues with MediaGalleryScreen [AR-1149]
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/ZoomableImage.kt
Labels: size/S

#590 fix: slow list rendering by execute mapping on default dispatcher (AR-1663)
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetLayout.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/GeneralConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/util/ui/AssetImageFetcher.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
Labels: size/L

#598 fix: typo in the search screen
  app/src/main/res/values/strings.xml
Labels: size/XS

#600 fix: don't send video when clicking navigation back from camera app [AR-1469]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/attachment/AttachmentOptions.kt
Labels: size/S

#593 test: add username scenario
  app/src/androidTest/java/com/wire/android/ui/LoginEmailScreenTest.kt
  app/src/androidTest/java/com/wire/android/utils/Extensions.kt
Labels: size/S

#597 fix: crash after rejecting an incoming call
  app/src/main/kotlin/com/wire/android/media/CallRinger.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModelTest.kt
Labels: size/S

#611 fix: clear the search on back press
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/AppTopBarWithSearchBarLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/SearchBarState.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleScreen.kt
Labels: size/M

#606 feat: map the user type to the ui on conversation
  app/src/main/kotlin/com/wire/android/mapper/UserTypeMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/test/kotlin/com/wire/android/mapper/UserTypeMapperTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
Labels: size/M

#613 fix: multiple notifications
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
Labels: size/S

#622 feat: add system messages UI [AR-1487]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/res/drawable/ic_minus.xml
  app/src/main/res/values/strings.xml
Labels: size/L

#614 fix: add missing calling button dimension
  app/src/main/kotlin/com/wire/android/ui/calling/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/DeclineButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/HangUpButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/M

#624 feat: display unnamed conversation when the group conversation has no name (AR-1403)
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/GeneralConversationItem.kt
  app/src/main/res/values/strings.xml
Labels: size/XS

#625 chore: simplified conversation items with other types
  app/src/main/kotlin/com/wire/android/ui/calling/OngoingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallLabel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConnectionLabel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/Call.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConnectionInfo.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/LastConversationEvent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/Mention.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
Labels: size/XL

#596 feat: Turn video on in ongoing call (AR-1146)
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/calling/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/OngoingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/CallOptionsControls.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/CameraButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/calling/OngoingCallViewModelTest.kt
Labels: size/L

#617 test: update create team test steps
  app/src/androidTest/java/com/wire/android/ui/CreateTeamScreenTest.kt
  app/src/androidTest/java/com/wire/android/utils/Extensions.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
Labels: size/M

#620 fix: download and delete from gallery [AR-1149]
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/model/ImageAsset.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationManager.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/DownloadedAssetDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SnackbarMessages.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/util/DateTimeUtil.kt
  app/src/main/kotlin/com/wire/android/util/FileManager.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/navigation/NavigationUtilsTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/ui/AssetImageFetcherTest.kt
Labels: size/XL

#626 feat: cancel connection request (AR-1526)
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
Labels: size/M

#632 fix: navigate back from muting the notification bottom sheet (AR-1622)
  app/src/main/kotlin/com/wire/android/model/ImageAsset.kt
  app/src/main/kotlin/com/wire/android/navigation/HomeNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetLayout.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/MutingOptionsSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
Labels: size/XL

#631 fix: pick group avatar colors from color palette AR-1531
  app/src/main/kotlin/com/wire/android/ui/common/Extensions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/GeneralConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/GroupConversationAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
  app/src/main/kotlin/com/wire/android/util/ColorUtil.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
Labels: size/L
