Repository wireapp/wire-android, pull requests merged in 2022-09, with the labels that each got.

#922 fix: bugs with multiple accounts
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/di/UserSessionsUseCaseProvider.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/LoginViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModelTest.kt
Labels: size/M

#919 chore: update translation strings via Crowdin
  app/src/main/kotlin/com/wire/android/ui/authentication/create/summary/CreateAccountSummaryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/AttachmentButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptionButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActionsBox.kt
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/XXL, crowdin, l10n

#911 fix: when adding participants search for known users only (AR-1064)
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/SearchBarState.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/SearchTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/AddMembersToConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/util/flow/SearchQueryStateFlow.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelTest.kt
Labels: size/XL

#930 fix: wrong orientation when uploading avatar through camera
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPickerViewModel.kt
  app/src/main/kotlin/com/wire/android/util/AvatarImageManager.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/image/AvatarPickerViewModelTest.kt
Labels: size/L

#931 fix: delete log file
  app/src/main/kotlin/com/wire/android/util/LogFileWriter.kt
Labels: size/XS

#923 refactor: split ConversationViewModel into multiple smaller ViewModels
  app/src/androidTest/java/com/wire/android/ui/ConversationScreenTest.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SnackbarMessages.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/call/ConversationCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/call/ConversationCallViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelTest.kt
Labels: size/XXL

#925 fix: new activity section scroll issue [AR-2279]
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/Extension.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/FolderHeader.kt
Labels: size/M

#932 fix: update inaccurate strings
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/XXL

#889 chore: renamed isMember argument to isSendingMessagesAllowed (AR-2275)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
Labels: size/M

#933 fix: disable group name edit option for non admins (AR-2272)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
Labels: size/S

#920 fix: map lastUnreadMessage to null when dao result is null (AR-2294)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
  app/src/main/kotlin/com/wire/android/util/ui/WireSessionImageLoader.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelTest.kt
Labels: size/L

#934 fix: crash when removing member from group conversation [AR-2038]
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
Labels: size/XS

#936 fix: notifications option text color on bottom sheet [AR-2088]
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/HomeSheetContent.kt
Labels: size/XS

#939 fix: new activity section scroll issue #2 [AR-2279]
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
Labels: size/XS

#938 fix: moved isServerConfigOnPremises lower to handle other deeplinks (AR-2328)
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
Labels: size/XS

#937 fix: display messages in case of error when deleting or leaving group conversation (AR-1556)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
Labels: size/M

#940 fix: Refresh search result in onResume (AR-2303)
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
Labels: size/M

#947 fix: UI fixes in custom BE deeplink (AR-2037) (AR-2323)
  app/src/main/kotlin/com/wire/android/ui/authentication/ServerTitle.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/common/CreateAccountBaseViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreateAccountOverviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/team/CreateTeamNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/WireCenterAlignedTopAppBar.kt
  app/src/main/res/drawable/ic_info.xml
Labels: size/L

#945 feat: retain tokens even when the session is invalid
  app/src/androidTest/java/com/wire/android/di/TestModule.kt
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/CallNotificationDismissReceiver.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/EndOngoingCallReceiver.kt
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeViewModel.kt
  app/src/main/kotlin/com/wire/android/util/lifecycle/ConnectionPolicyManager.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/lifecycle/ConnectionPolicyManagerTest.kt
Labels: size/M

#949 fix: sec task to delete credentials (SEC-197)
  app/src/androidTest/java/com/wire/android/utils/Extensions.kt
Labels: size/S

#951 fix(calling): avoid unnecessary recomposition
  app/src/main/kotlin/com/wire/android/ui/calling/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallingGridView.kt
Labels: size/L

#950 fix: slow typing
  app/src/main/kotlin/com/wire/android/model/ImageAsset.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/ConnectivityUIState.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageInputRow.kt
Labels: size/L

#943 fix: visual bugs in account switching UI
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/HighLightSubtTitle.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
Labels: size/S

#957 fix: empty avatar on status update (AR-2348)
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
Labels: size/XS

#958 fix: flickering in selfuser screen (AR-2338)
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
Labels: size/M

#959 fix: random crash when opening conversation list
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
Labels: size/XS

#966 fix: no details or slow conversation details access (AR-2380)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/test/kotlin/com/wire/android/config/TestDispatcherProvider.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelArrangement.kt
Labels: size/S

#968 chore: add basic info for logging details (AR-2331)
  app/src/main/kotlin/com/wire/android/WireApplication.kt
Labels: size/M

#955 fix: GroupConversationDetails flickering
  app/src/main/kotlin/com/wire/android/ui/common/Extensions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
Labels: size/L

#972 fix: Video freezes on a group video call (AR-2316)
  app/src/main/kotlin/com/wire/android/ui/calling/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallingGridView.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/OneOnOneCallView.kt
Labels: size/M

#977 chore: update translation strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/XXL, crowdin, l10n

#973 chore: hash device id
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/kotlin/com/wire/android/util/StringUtil.kt
Labels: size/S

#974 fix(calling): speaker state is not respecting camera state
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
Labels: size/M

#981 fix: infinite loading on avatar upload failing
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPickerState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPickerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/image/AvatarPickerViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
Labels: size/L

#992 fix: custom server deep link dialogue displaying team url instead of api
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/CustomBEDeeplinkDialog.kt
Labels: size/XS

#990 fix: execute sanitize avatar image before setting the state
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
Labels: size/XS

#994 fix: white screen ongoing call while joining (AR-2411)
  app/src/main/kotlin/com/wire/android/ui/calling/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
Labels: size/L

#986 fix: calling infinite vibration (AR-2433) (AR-2363)
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
Labels: bug, size/M

#985 fix: not marking messages as read (AR-2436)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
Labels: size/XS

#989 fix: logout does not remove the user session
  app/src/main/kotlin/com/wire/android/feature/AccountSwitchUseCase.kt
Labels: size/XS

#991 fix: Ar-2406 audio is still transmitted when user logs out while in an active call
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
Labels: size/M

#996 fix(calling): Video freezes on a group video call
  app/src/main/kotlin/com/wire/android/ui/calling/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallingGridView.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/OneOnOneCallView.kt
Labels: size/M

#997 fix: app displaying user in call when clicking add new account
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
Labels: size/XS

#1001 fix: Bottom padding in WelcomeScreen (AR-2323)
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
Labels: size/XS

#984 fix: Notification issues (AR-2373, AR-2370)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationActions.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/NotificationReplyReceiver.kt
  app/src/main/kotlin/com/wire/android/services/WireFirebaseMessagingService.kt
Labels: size/L

#1003 fix: improve performance on displaying user avatars (AR-2462)
  app/src/main/kotlin/com/wire/android/di/ImageLoadingModule.kt
  app/src/main/kotlin/com/wire/android/mapper/ContactMapper.kt
  app/src/main/kotlin/com/wire/android/model/ImageAsset.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/util/ui/AssetImageFetcher.kt
  app/src/main/kotlin/com/wire/android/util/ui/WireSessionImageLoader.kt
  app/src/test/kotlin/com/wire/android/model/ImageAssetTest.kt
  app/src/test/kotlin/com/wire/android/util/ui/AssetImageFetcherTest.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/L

#1004 chore: other user profile enhancement offloading data loading
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileInfoMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileViewModelArrangement.kt
Labels: size/L

#1005 fix: ongoing call foreground service crash
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
Labels: size/XS

#993 fix: show call notification on locked screen (AR-2410)
  app/src/main/kotlin/com/wire/android/notification/NotificationConstants.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/services/WireFirebaseMessagingService.kt
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
  app/src/main/kotlin/com/wire/android/util/NetworkStatus.kt
  app/src/main/kotlin/com/wire/android/util/NetworkUtil.kt
  app/src/main/kotlin/com/wire/android/util/ScreenStateObserver.kt
  app/src/main/kotlin/com/wire/android/util/lifecycle/ConnectionPolicyManager.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/util/ScreenStateObserverTest.kt
Labels: size/L

#1019 fix: image message issues [AR-2485]
  app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/asset/AssetMessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/image/ImageMessageParams.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/image/ImageMessageTypes.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/framework/TestMessage.kt
  app/src/test/kotlin/com/wire/android/mapper/MessageContentMapperTest.kt
Labels: size/XL

#1027 chore: enable MLS on dev and debug builds
  default.json
Labels: size/S

#1025 feat: hide UI depending on feature visibility flags
  app/src/main/kotlin/com/wire/android/navigation/NavigationGraph.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActionsBox.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/attachment/AttachmentOptions.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/util/debug/FeatureVisibilityFlags.kt
Labels: size/L

#1031 fix: Connection request notification
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
Labels: size/XS

#1032 chore: conversation list empty state [AR-2480]
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/res/drawable/ic_empty_conversation_arrow.xml
  app/src/main/res/values/strings.xml
Labels: size/L

#1033 chore: hide try again text [AR-2501]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
Labels: size/S

#1034 fix: wrong speaker state when toggling camera
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
Labels: size/S

#1029 fix: show settings, disable items inside the settings instead
  app/src/main/kotlin/com/wire/android/ui/debugscreen/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsScreen.kt
  app/src/main/kotlin/com/wire/android/util/debug/FeatureVisibilityFlags.kt
Labels: size/M

#1035 chore: AR-2522 Remove extra profile actions
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileBottomSheet.kt
Labels: size/L

#1037 fix: stop the socket onStop instead of onPause
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
Labels: size/XS

#1041 chore: add report bug button
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/debugscreen/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#1040 fix(conversation-list): show only received connection request in newActivities (AR-2540)
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
Labels: size/XS

#1050 fix(revert-me): work around because the backend is not updating the list of clients immediately
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModel.kt
Labels: size/S

#1051 chore(message): remove self deleting message action button (AR-2556)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageSendActions.kt
Labels: size/XS

#1052 feat(conversation): rank up the conversation if there is a call onGoing (AR-2558)
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
Labels: size/XS
