Repository wireapp/wire-android, pull requests merged in 2022-01, with the labels that each got.

#3632 fix: Notifications: More aggressive cancelling of notifications (SQCORE-1199)
  app/src/main/scala/com/waz/zclient/notifications/controllers/MessageNotificationsController.scala
  zmessaging/src/main/scala/com/waz/content/AccountStorage.scala
  zmessaging/src/main/scala/com/waz/service/conversation/SelectedConversationService.scala
  zmessaging/src/main/scala/com/waz/service/otr/NotificationParser.scala
  zmessaging/src/test/scala/com/waz/service/NotificationParserSpec.scala
Labels: size/M

#3629 feat: Make sure the new system works with Federation (SQCORE-1181)
  app/src/main/scala/com/waz/zclient/notifications/controllers/MessageNotificationsController.scala
  zmessaging/src/main/scala/com/waz/content/AccountStorage.scala
  zmessaging/src/main/scala/com/waz/model/NotificationData.scala
  zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/SelectedConversationService.scala
  zmessaging/src/main/scala/com/waz/service/otr/NotificationParser.scala
  zmessaging/src/test/scala/com/waz/service/NotificationParserSpec.scala
Labels: size/L

#3628 feat: Notifications: Show notifications when the app is open but on a different conversation (SQCORE-1197)
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/MessageNotificationsController.scala
  zmessaging/src/main/scala/com/waz/content/AccountStorage.scala
  zmessaging/src/main/scala/com/waz/model/NotificationData.scala
  zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/SelectedConversationService.scala
  zmessaging/src/main/scala/com/waz/service/otr/NotificationParser.scala
  zmessaging/src/main/scala/com/waz/service/otr/WsNotificationService.scala
  zmessaging/src/test/scala/com/waz/service/NotificationParserSpec.scala
Labels: size/L

#3626 fix: Ensure notifications are being cancelled (SQCORE-1199)
  app/src/main/scala/com/waz/services/notifications/NotificationsHandlerService.scala
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/AndroidNotificationsManager.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/MessageNotificationsController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/NotificationManagerWrapper.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/NotificationProps.scala
  zmessaging/src/main/scala/com/waz/content/AccountStorage.scala
  zmessaging/src/main/scala/com/waz/model/NotificationData.scala
  zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/SelectedConversationService.scala
  zmessaging/src/main/scala/com/waz/service/otr/NotificationParser.scala
  zmessaging/src/main/scala/com/waz/service/otr/WsNotificationService.scala
  zmessaging/src/test/scala/com/waz/service/NotificationParserSpec.scala
Labels: size/L

#3624 feat: Notifications: Refactor NotificationManagerWrapper (SQCORE-1199)
  app/src/main/scala/com/waz/services/notifications/NotificationsHandlerService.scala
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/AndroidNotificationsManager.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/CallingNotificationsController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/MessageNotificationsController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/NotificationManagerWrapper.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/NotificationProps.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/Span.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/SpannableWrapper.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/StyleBuilder.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/OptionsView.scala
  zmessaging/src/main/scala/com/waz/content/AccountStorage.scala
  zmessaging/src/main/scala/com/waz/log/LogShowInstancesSE.scala
  zmessaging/src/main/scala/com/waz/model/NotificationData.scala
  zmessaging/src/main/scala/com/waz/model/Uid.scala
  zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/SelectedConversationService.scala
  zmessaging/src/main/scala/com/waz/service/otr/NotificationParser.scala
  zmessaging/src/main/scala/com/waz/service/otr/WsNotificationService.scala
  zmessaging/src/test/scala/com/waz/service/NotificationParserSpec.scala
Labels: size/XXL

#3623 feat: Notifications: Fix notifications sounds (SQCORE-1182)
  app/src/main/scala/com/waz/services/notifications/NotificationsHandlerService.scala
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/common/controllers/SoundController.scala
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/AndroidNotificationsManager.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/CallingNotificationsController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/MessageNotificationsController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/NotificationManagerWrapper.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/NotificationProps.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/Span.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/SpannableWrapper.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/StyleBuilder.scala
  app/src/main/scala/com/waz/zclient/preferences/PreferencesActivity.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/OptionsView.scala
  app/src/main/scala/com/waz/zclient/qa/AbstractPreferenceReceiver.scala
  app/src/nonfree/scala/com/waz/services/fcm/FCMService.scala
  zmessaging/src/main/scala/com/waz/content/AccountStorage.scala
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/log/LogShowInstancesSE.scala
  zmessaging/src/main/scala/com/waz/model/NotificationData.scala
  zmessaging/src/main/scala/com/waz/model/Uid.scala
  zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/SelectedConversationService.scala
  zmessaging/src/main/scala/com/waz/service/otr/NotificationParser.scala
  zmessaging/src/main/scala/com/waz/service/otr/WsNotificationService.scala
  zmessaging/src/main/scala/com/waz/service/push/PushNotificationEventsStorage.scala
  zmessaging/src/main/scala/com/waz/service/push/PushService.scala
  zmessaging/src/test/scala/com/waz/service/NotificationParserSpec.scala
Labels: size/XXL

#3619 feat: Notifications: Show notifications when websockets are always on (SQCORE-1192)
  app/src/main/scala/com/waz/services/notifications/NotificationsHandlerService.scala
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/common/controllers/SoundController.scala
  app/src/main/scala/com/waz/zclient/conversation/ConversationController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/AndroidNotificationsManager.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/CallingNotificationsController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/MessageNotificationsController.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/NotificationManagerWrapper.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/NotificationProps.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/Span.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/SpannableWrapper.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/StyleBuilder.scala
  app/src/main/scala/com/waz/zclient/preferences/PreferencesActivity.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/OptionsView.scala
  app/src/main/scala/com/waz/zclient/qa/AbstractPreferenceReceiver.scala
  app/src/nonfree/scala/com/waz/services/fcm/FCMService.scala
  zmessaging/src/main/scala/com/waz/content/AccountStorage.scala
  zmessaging/src/main/scala/com/waz/content/Preferences.scala
  zmessaging/src/main/scala/com/waz/log/LogShowInstancesSE.scala
  zmessaging/src/main/scala/com/waz/model/NotificationData.scala
  zmessaging/src/main/scala/com/waz/model/PushNotificationEvents.scala
  zmessaging/src/main/scala/com/waz/model/Uid.scala
  zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  zmessaging/src/main/scala/com/waz/service/conversation/SelectedConversationService.scala
  zmessaging/src/main/scala/com/waz/service/otr/NotificationParser.scala
  zmessaging/src/main/scala/com/waz/service/otr/WsNotificationService.scala
  zmessaging/src/main/scala/com/waz/service/push/PushNotificationEventsStorage.scala
  zmessaging/src/main/scala/com/waz/service/push/PushService.scala
  zmessaging/src/test/scala/com/waz/service/NotificationParserSpec.scala
Labels: size/XXL

#3633 chore: Update README.md
  README.md
Labels: size/XS

#3598 chore: added Sha256sum to gradle-wrapper.properties file (SQCORE-1213)
  gradle/wrapper/gradle-wrapper.properties
Labels: size/XS, Fix Title or Message

#3625 chore: Pipeline/implement appcenter upload (AN-7152)
  Jenkinsfile
Labels: size/M

#3622 chore: New Crowdin updates (AN-7152)
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-uk/strings.xml
Labels: size/M

#3635 chore: bump AVS version to 8.0.5 (FS-11)
  scripts/avs.gradle
Labels: size/XS

#3642 chore: bump AVS version to 8.0.7 #FS-138
  scripts/avs.gradle
Labels: size/XS

#3644 fix(SSO): SSO webview refreshed every time the user leaves the app #SQSERVICES-1209
  app/src/main/scala/com/waz/zclient/appentry/SSOWebViewFragment.scala
Labels: size/XS

#3643 feat: Assets in Federation (FS-293)
  app/src/main/scala/com/waz/zclient/common/controllers/global/ClientsController.scala
  app/src/main/scala/com/waz/zclient/common/views/ChatHeadView.scala
  app/src/main/scala/com/waz/zclient/glide/AssetRequest.scala
  app/src/main/scala/com/waz/zclient/glide/ImageAssetFetcher.scala
  app/src/main/scala/com/waz/zclient/glide/loaders/AssetModelLoader.scala
  app/src/main/scala/com/waz/zclient/glide/loaders/MapModelLoader.scala
  app/src/main/scala/com/waz/zclient/glide/loaders/PictureModelLoader.scala
  storage/src/androidTest/kotlin/com/waz/zclient/storage/accountdata/ActiveAccountsDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetsDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/users/UsersDaoTest.kt
  zmessaging/src/main/scala/com/waz/content/UsersStorage.scala
  zmessaging/src/main/scala/com/waz/model/UserData.scala
  zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  zmessaging/src/main/scala/com/waz/service/assets/AssetService.scala
  zmessaging/src/main/scala/com/waz/sync/client/AssetClient.scala
  zmessaging/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/assets2/AssetServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/UsersSyncHandlerSpec.scala
Labels: size/L

#3641 feat(federation): add support for federated calls (FS-138)
  app/src/main/scala/com/waz/zclient/calling/CallingGridFragment.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/controllers/CallStartController.scala
  app/src/main/scala/com/waz/zclient/calling/views/OtherVideoView.scala
  app/src/main/scala/com/waz/zclient/calling/views/SelfVideoView.scala
  app/src/main/scala/com/waz/zclient/calling/views/UserVideoView.scala
  app/src/main/scala/com/waz/zclient/notifications/controllers/CallingNotificationsController.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
  zmessaging/src/main/scala/com/waz/log/LogShowInstancesSE.scala
  zmessaging/src/main/scala/com/waz/model/QualifiedId.scala
  zmessaging/src/main/scala/com/waz/model/RConvQualifiedId.scala
  zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  zmessaging/src/main/scala/com/waz/service/call/CallInfo.scala
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  zmessaging/src/main/scala/com/waz/service/call/DomainUtils.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/test/scala/com/waz/service/call/CallInfoSpec.scala
  zmessaging/src/test/scala/com/waz/service/call/CallLoggingServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
  zmessaging/src/test/scala/com/waz/specs/AndroidFreeSpec.scala
Labels: size/L

#3639 refactor: Remove old code dealing with v2 assets (FS-293)
  app/src/main/kotlin/com/waz/zclient/feature/backup/assets/AssetsBackupDataSource.kt
  app/src/main/scala/com/waz/zclient/common/controllers/global/ClientsController.scala
  app/src/main/scala/com/waz/zclient/common/views/ChatHeadView.scala
  app/src/main/scala/com/waz/zclient/glide/AssetRequest.scala
  app/src/main/scala/com/waz/zclient/glide/ImageAssetFetcher.scala
  app/src/main/scala/com/waz/zclient/glide/loaders/AssetModelLoader.scala
  app/src/main/scala/com/waz/zclient/glide/loaders/MapModelLoader.scala
  app/src/main/scala/com/waz/zclient/glide/loaders/PictureModelLoader.scala
  app/src/test/kotlin/com/waz/zclient/feature/backup/assets/AssetsBackupMapperTest.kt
  common-test/src/main/kotlin/com/waz/zclient/framework/data/assets/AssetsTestDataProvider.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/accountdata/ActiveAccountsDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetTables127to128MigrationTests.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/assets/AssetsDaoTest.kt
  storage/src/androidTest/kotlin/com/waz/zclient/storage/userdatabase/users/UsersDaoTest.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/MigrationUtils.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/UserDatabase.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/assets/AssetsEntity.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase135To136Migration.kt
  storage/src/main/kotlin/com/waz/zclient/storage/db/users/migration/UserDatabase136To137Migration.kt
  zmessaging/build.gradle
  zmessaging/src/main/scala/com/waz/content/AssetsStorage.scala
  zmessaging/src/main/scala/com/waz/content/UsersStorage.scala
  zmessaging/src/main/scala/com/waz/db/ZMessagingDB.scala
  zmessaging/src/main/scala/com/waz/log/LogShowInstancesSE.scala
  zmessaging/src/main/scala/com/waz/model/AssetData.scala
  zmessaging/src/main/scala/com/waz/model/ConversationData.scala
  zmessaging/src/main/scala/com/waz/model/GenericContent.scala
  zmessaging/src/main/scala/com/waz/model/UserData.scala
  zmessaging/src/main/scala/com/waz/model/UserInfo.scala
  zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  zmessaging/src/main/scala/com/waz/service/assets/AssetService.scala
  zmessaging/src/main/scala/com/waz/service/assets/AssetStorage.scala
  zmessaging/src/main/scala/com/waz/service/assets/models.scala
  zmessaging/src/main/scala/com/waz/sync/client/AssetClient.scala
  zmessaging/src/test/scala/com/waz/model/AssetDataSpec.scala
  zmessaging/src/test/scala/com/waz/service/LegalHoldServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/assets2/AssetServiceSpec.scala
  zmessaging/src/test/scala/com/waz/sync/client/AssetClientSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/UsersSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/utils/crypto/ReplyHashingSpec.scala
Labels: size/XXL

#3634 fix: A change in the "Maintain connection to the server" copy (SQCORE-1196)
  app/src/main/res/values/strings.xml
Labels: size/XS

#3645 fix: Make profile pictures more responsive to changes (SQCORE-1227)
  app/src/main/scala/com/waz/zclient/common/views/ChatHeadView.scala
  app/src/main/scala/com/waz/zclient/glide/ImageAssetFetcher.scala
  zmessaging/src/main/scala/com/waz/sync/client/AssetClient.scala
Labels: size/S

#3646 chore: bump AVS version to 8.0.9 (FS-138)
  scripts/avs.gradle
Labels: size/XS

#3647 chore: bump AVS version to 8.0.10 (FS-138)
  scripts/avs.gradle
Labels: size/XS

#3651 chore: upgrade AVS version to 8.0.11 (FS-138)
  scripts/avs.gradle
Labels: size/XS

#3652 test: Unit tests for checking if the other user is a guest (FS-334)
  zmessaging/src/test/scala/com/waz/model/UserDataSpec.scala
Labels: size/M

#3653 chore: upgrade AVS to 8.0.12 (FS-138)
  scripts/avs.gradle
Labels: size/XS

#3654 test: Add mapping tags to unit test for federation (FS-334)
  zmessaging/src/test/scala/com/waz/model/UserDataSpec.scala
Labels: size/XS

#3656 fix: call being dropped when receiving a 1:1 video call (FS-382)
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
Labels: size/S
