Repository wireapp/wire-android, pull requests merged in 2022-02, with the labels that each got.

#346 feat: navigate to conversation from conversation list (AR-991)
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/ConversationView.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversation.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/Calls.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/Mentions.kt
Labels: size/L

#347 fix: make user avatar click area bigger, remove sharp edge ripple effect on click (AR-965)
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/common/ConversationUserAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/common/MembershipQualifier.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversation.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/Calls.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/Mentions.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/L

#351 fix: Fix environment setup by using env instead of >> $GITHUB_ENV
  .github/workflows/semantic-commit-lint.yml
Labels: size/XS

#349 feat: display group items of conversation list
  app/src/main/kotlin/com/wire/android/ui/home/conversations/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/common/ConversationItemTemplate.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/common/GroupConversation.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversation.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/Calls.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/GeneralConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/Mentions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/AvailabilityStatus.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/Call.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/Conversation.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationFolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/EventType.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/Membership.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/Mention.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/NewActivity.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/XXL

#350 feat: add wire styled dialog [AR-862]
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireButtonDefaults.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireSecondaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireTertiaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/L

#353 feat: Cleare backstack issue fix
  app/src/main/kotlin/com/wire/android/navigation/NavigationManager.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
Labels: size/S

#354 feat: User profile screen
  app/src/main/kotlin/com/wire/android/model/UserStatus.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/Extensions.kt
  app/src/main/kotlin/com/wire/android/ui/common/SearchBar.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserStatusIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/common/ConversationUserAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/Message.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/Extension.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/AvailabilityStatus.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/userprofile/UserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileViewModel.kt
  app/src/main/res/values/strings.xml
Labels: size/XL

#355 feat: add login errors handling [AR-1004]
  app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/util/CoreFailureUtil.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#357 chore: add strings for new Crowdin updates
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
Labels: size/L

#361 chore: update translation strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/S, crowdin, l10n

#359 feat: forgot password "custom tabs" web page [AR-1005]
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
  app/src/main/res/drawable/ic_close.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/M

#364 feat: User profile status dialog
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/datastore/UserDataStore.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationGraph.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/ChangeStatusDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/SelfUserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileViewModel.kt
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/L

#366 fix: disable drawer gesture on conversations screen [AR-992]
  app/src/main/kotlin/com/wire/android/ui/home/HomeNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
Labels: size/XS

#369 feat: Fix fab styles
  app/src/main/kotlin/com/wire/android/ui/common/FloatingActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/res/values/strings.xml
Labels: size/M

#365 fix: issues on welcome and login screens [AR-1023] [AR-1024] [AR-1025] [AR-1026]
  app/src/main/kotlin/com/wire/android/ui/authentication/Auth.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/Welcome.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireSecondaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireTertiaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/L

#356 feat: add context menu for conversation list item (AR-802)
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/navigation/NavigationGraph.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/Auth.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/common/ConversationItemTemplate.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/GeneralConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/ConversationBottomSheet.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/RowItem.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/ChangeStatusDialogs.kt
  app/src/main/res/drawable/ic_block.xml
  app/src/main/res/drawable/ic_erase.xml
  app/src/main/res/drawable/ic_favourite.xml
  app/src/main/res/drawable/ic_folder.xml
  app/src/main/res/drawable/ic_leave.xml
  app/src/main/res/drawable/ic_mute.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XL

#372 feat: add proper splashscreen [AR-942]
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/Welcome.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Theme.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
  app/src/main/res/drawable-v31/ic_launcher_wire_logo.xml
  app/src/main/res/drawable/ic_launcher_wire_logo.xml
  app/src/main/res/drawable/launcher_wire_shield_logo.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values-night/flags.xml
  app/src/main/res/values/flags.xml
  app/src/main/res/values/integers.xml
  app/src/main/res/values/themes.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XL

#377 feat: basic message composer (AR-1006) (AR-1007) (AR-1008)
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/common/OnDropDownIconButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerState.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/res/drawable/ic_add.xml
  app/src/main/res/drawable/ic_collapse.xml
  app/src/main/res/drawable/ic_emoticon.xml
  app/src/main/res/drawable/ic_gif.xml
  app/src/main/res/drawable/ic_rich_text.xml
  app/src/main/res/drawable/ic_send.xml
  app/src/main/res/drawable/ic_timer.xml
  app/src/main/res/values/strings.xml
Labels: size/XL

#376 chore: update readme to help common troubleshooting
  README.md
Labels: size/XS

#375 feat: add remove device screen UI 1/2 [AR-1035]
  app/src/main/kotlin/com/wire/android/ui/authentication/Auth.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/RemoveDevice.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/RemoveDeviceState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/RemoveDeviceTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/RemoveDeviceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/model/Device.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/Welcome.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#387 feat: display list of existing clients and handle user interaction [AR-980]
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/RemoveDevice.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/RemoveDeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/RemoveDeviceState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/RemoveDeviceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/model/Device.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/Extensions.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/kotlin/com/wire/android/util/DateTimeUtil.kt
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/L

#389 chore: update app icon
  app/src/main/res/ic_launcher-web.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-ldpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/playstore-icon.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: size/S

#383 feat: profile picture picker
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/ArrowRightIcon.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/MenuBottomSheetItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/ModalSheetHeaderItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/imagepreview/BulletHoleImagePreview.kt
  app/src/main/kotlin/com/wire/android/ui/common/imagepreview/PicturePickerFlow.kt
  app/src/main/kotlin/com/wire/android/ui/common/snackbar/SwipeDismissSnackbar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/common/ConversationUserAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/ConversationBottomSheet.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/SelfUserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/image/ImagePicker.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/image/ImagePickerState.kt
  app/src/main/kotlin/com/wire/android/util/extension/Bitmap.kt
  app/src/main/kotlin/com/wire/android/util/extension/Context.kt
  app/src/main/kotlin/com/wire/android/util/permission/OpenGalleryRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/TakePictureRequestFlow.kt
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_gallery.xml
  app/src/main/res/drawable/ic_take_a_picture.xml
  app/src/main/res/values/strings.xml
Labels: size/XXL

#391 fix: disable password suggestions and allow "long-press" backspace [AR-1107]
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/RemoveDevice.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/S

#392 feat: Fix close Drawer on back click
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
Labels: size/XS

#396 feat: fill profile user profile data on screen from backend (AR-1118)
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/SelfUserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileViewModel.kt
Labels: size/L

#399 chore: add SendTextMessageUseCase to ConversationViewModel (AR-912)
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
Labels: size/S

#402 feat: send message (AR-912)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
Labels: size/M

#404 fix: center the currentuserstatus (AR-1139)
  app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileScreen.kt
Labels: size/XS, Fix PR Title or Commit message️

#405 fix: no ripple effect on item click (AR-1133)
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/RowItem.kt
Labels: size/S

#407 fix: add missing navigation to create account under construction for user profile
  app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileViewModel.kt
Labels: size/XS

#400 feat: "create personal account" - "overview" screen and navigation [AR-954]
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/OverviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeViewModel.kt
  app/src/main/res/drawable/ic_create_personal_account.xml
  app/src/main/res/values/strings.xml
Labels: size/XL
