Repository wireapp/wire-android, pull requests merged in 2022-04, with the labels that each got.

#3690 fix: display domain in handle if federation is enabled FS-506
  app/src/main/scala/com/waz/zclient/common/views/SingleUserRowView.scala
  app/src/main/scala/com/waz/zclient/common/views/UserDetailsView.scala
  app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListRow.scala
  app/src/main/scala/com/waz/zclient/messages/UsersController.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/UntabbedRequestFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/dialogs/ChangeHandleFragment.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/AccountView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/ProfileView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/SettingsView.scala
  app/src/main/scala/com/waz/zclient/usersearch/SearchUIFragment.scala
  zmessaging/src/main/scala/com/waz/model/UserData.scala
Labels: size/L

#3691 fix: remove autoconnection label FS-506
  app/src/main/scala/com/waz/zclient/messages/parts/ConnectRequestPartView.scala
  zmessaging/src/main/scala/com/waz/model/UserData.scala
Labels: size/S

#3693 fix: team creation SQSERVICES-1437
  zmessaging/src/main/scala/com/waz/client/RegistrationClient.scala
Labels: size/XS

#3694 chore: No syntax highlighting in build messages for performance (SQPIT-926)
  Jenkinsfile
Labels: size/XS

#3695 fix: live update of federation configuration FS-512
  app/src/main/scala/com/waz/zclient/conversationlist/views/ConversationListRow.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/AccountView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/ProfileView.scala
  app/src/main/scala/com/waz/zclient/preferences/pages/SettingsView.scala
  zmessaging/src/main/scala/com/waz/log/BasicLogging.scala
  zmessaging/src/main/scala/com/waz/service/ConnectionService.scala
  zmessaging/src/main/scala/com/waz/service/GlobalModule.scala
  zmessaging/src/main/scala/com/waz/service/UserSearchService.scala
  zmessaging/src/main/scala/com/waz/service/UserService.scala
  zmessaging/src/main/scala/com/waz/service/ZMessaging.scala
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsContentUpdater.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsService.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  zmessaging/src/main/scala/com/waz/service/otr/OtrServiceImpl.scala
  zmessaging/src/main/scala/com/waz/service/push/WSPushService.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ClearedSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ConversationsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/LastReadSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/MessagesSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/OpenGraphSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/PushTokenSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/ReactionsSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/handler/UsersSyncHandler.scala
  zmessaging/src/main/scala/com/waz/sync/otr/OtrClientsSyncHandler.scala
  zmessaging/src/test/scala/com/waz/service/BackendConfigSpec.scala
  zmessaging/src/test/scala/com/waz/service/UserSearchServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/UserServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/call/CallingServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/connections/ConnectionServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationsUiServiceSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/TeamConversationSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/ConversationsSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/MessagesSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/OtrClientsSyncHandlerSpec.scala
  zmessaging/src/test/scala/com/waz/sync/handler/UsersSyncHandlerSpec.scala
Labels: size/L

#3696 fix: re-fetch API information when switching backend with a deep link FS-512
  app/src/main/scala/com/waz/zclient/WireApplication.scala
  app/src/main/scala/com/waz/zclient/appentry/AppEntryActivity.scala
Labels: size/XS

#3697 chore: version bump to 3.80
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#3698 fix: make sure AVS calls use qualified/non-qualified identifiers based on federation FS-506
  zmessaging/src/main/scala/com/waz/model/RConvQualifiedId.scala
  zmessaging/src/main/scala/com/waz/service/GlobalModule.scala
  zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
Labels: size/M

#3701 fix: do not crash at startup if the backend URL is not set FS-421
  zmessaging/src/main/scala/com/waz/service/BackendConfig.scala
  zmessaging/src/main/scala/com/waz/sync/client/SupportedApiClient.scala
Labels: size/XS

#3703 fix: calling on federation has no audio FS-639
  zmessaging/src/main/scala/com/waz/model/QualifiedId.scala
  zmessaging/src/main/scala/com/waz/service/call/Avs.scala
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
Labels: size/S

#3704 fix: duplicated link previews JCT-112
  app/src/main/scala/com/waz/zclient/messages/MessageViewFactory.scala
  app/src/main/scala/com/waz/zclient/messages/parts/WebLinkPartView.scala
  zmessaging/src/main/scala/com/waz/model/GenericContent.scala
  zmessaging/src/main/scala/com/waz/model/MessageData.scala
  zmessaging/src/main/scala/com/waz/model/package.scala
  zmessaging/src/main/scala/com/waz/service/conversation/ConversationsUiService.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessageEventProcessor.scala
  zmessaging/src/main/scala/com/waz/service/messages/MessagesService.scala
  zmessaging/src/main/scala/com/waz/sync/handler/OpenGraphSyncHandler.scala
  zmessaging/src/test/scala/com/waz/model/MessageDataSpec.scala
  zmessaging/src/test/scala/com/waz/service/conversation/ConversationOrderEventsServiceSpec.scala
Labels: size/M
