Repository wireapp/wire-android, pull requests merged in 2022-10, with the labels that each got.

#1059 feat: conversation banner (AR-2378)
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/banner/ConversationBanner.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/banner/ConversationBannerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/banner/usecase/ObserveConversationMembersByTypesUseCase.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/banner/ConversationBannerViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/banner/usecase/ObserveConversationMembersByTypesUseCaseTest.kt
Labels: size/L

#1072 refactor: rearrange calling classes
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/AcceptButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CallOptionsControls.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CameraButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CameraFlipButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/DeclineButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/HangUpButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/JoinButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/MicrophoneButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/SpeakerButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantsTiles.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/VerticalPagerIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/gridview/CallingGridView.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/horizentalview/CallingHorizentalView.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/test/kotlin/com/wire/android/ui/calling/OngoingCallViewModelTest.kt
Labels: size/M

#1079 feat: my account password recovery (AR-1944)
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/AccountDetailsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountState.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModel.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#1082 refactor: cleanup reactions
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ReactionPill.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelTest.kt
Labels: size/L

#1086 chore: tests for coverage for password recovery my account context (AR-1944)
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModelTest.kt
Labels: size/L

#1085 fix: show guest banner only in group conversation (AR-2378)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/banner/ConversationBannerViewModel.kt
  app/src/test/kotlin/com/wire/android/framework/TestConnection.kt
  app/src/test/kotlin/com/wire/android/framework/TestConversation.kt
  app/src/test/kotlin/com/wire/android/framework/TestConversationDetails.kt
  app/src/test/kotlin/com/wire/android/framework/TestTeam.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/banner/ConversationBannerViewModelTest.kt
Labels: size/L

#1038 chore: block selected actions until the sync completes [AR-2443]
  app/src/main/kotlin/com/wire/android/di/ObserveSyncStateUseCaseProvider.kt
  app/src/main/kotlin/com/wire/android/model/Clickable.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/CopyButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/Extensions.kt
  app/src/main/kotlin/com/wire/android/ui/common/MoreOptionIcon.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/MenuBottomSheetItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireButtonDefaults.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryIconButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireSecondaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireSecondaryIconButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireTertiaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/menu/ConversationGroupDetailsBottomSheet.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreenTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptionButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActionsBox.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageSendActions.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/SelectParticipantsButtonsRow.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserConnectionActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileGroup.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/util/SyncStateObserver.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/L

#1078 feat: read active user data from scala app global database [AR-2382]
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/migration/MigrationMapper.kt
  app/src/main/kotlin/com/wire/android/migration/feature/MigrateActiveAccountsUseCase.kt
  app/src/main/kotlin/com/wire/android/migration/feature/MigrateServerConfigUseCase.kt
  app/src/main/kotlin/com/wire/android/migration/globalDatabase/ScalaAccountsDAO.kt
  app/src/main/kotlin/com/wire/android/migration/globalDatabase/ScalaActiveAccountsEntity.kt
  app/src/main/kotlin/com/wire/android/migration/globalDatabase/ScalaAppDataBaseProvider.kt
  app/src/main/kotlin/com/wire/android/migration/preference/ScalaBackendPreferences.kt
  app/src/main/kotlin/com/wire/android/migration/preference/ScalaServerConfigDAO.kt
  app/src/main/kotlin/com/wire/android/migration/util/DBUtil.kt
  app/src/main/kotlin/com/wire/android/migration/util/ScalaDBNameProvider.kt
  app/src/test/kotlin/com/wire/android/migration/MigrateServerConfigUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/migration/MigrationManagerTest.kt
  app/src/test/kotlin/com/wire/android/migration/ScalaServerConfigDAOTest.kt
Labels: size/L

#1047 feat: Autofill for credentials
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginError.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/AutoFillTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
Labels: size/L

#1088 fix: disable button when no members are selected (AR-2590)
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/SelectParticipantsButtonsRow.kt
Labels: size/S

#1009 feat: switch auth server when switching to the WelcomeScreen after us…
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/feature/AccountSwitchUseCase.kt
  app/src/test/kotlin/com/wire/android/feature/AccountSwitchUseCaseTest.kt
Labels: size/M

#1090 chore: Connectivity state in ongoing call screen
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
Labels: size/S

#1095 fix: add new PR template file
  .github/pull_request_template.md
Labels: size/M

#1064 feat: search conversations (AR-2538)
  app/src/main/kotlin/com/wire/android/navigation/HomeNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreateAccountOverviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/summary/CreateAccountSummaryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/JoinButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryIconButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/spacers/VerticalSpace.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/SearchBarState.kt
  app/src/main/kotlin/com/wire/android/ui/home/FeatureFlagState.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/call/ConversationCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipants.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MutingConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/all/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/call/CallLabel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/call/CallsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConnectionLabel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/MutedConversationBadge.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/mention/MentionLabel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/mention/MentionScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/search/SearchConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/SelectParticipantsButtonsRow.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupOptions/GroupOptionsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserConnectionActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/util/extension/LazyListScope.kt
  app/src/main/res/values/strings.xml
Labels: size/XXL

#1099 chore: increase the delay of register after deleting client to 2 sec
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModel.kt
Labels: size/XS

#1100 fix: disable button for group edit and enable always for creation (AR-2590)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/AddMembersToConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/SelectParticipantsButtonsRow.kt
Labels: size/L

#1101 fix: self devices screen (AR-2215)
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/SelfDevicesScreen.kt
Labels: size/L

#1097 feat: handle missing domain and add provider for scala user database
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/migration/feature/MigrateActiveAccountsUseCase.kt
  app/src/main/kotlin/com/wire/android/migration/feature/MigrateServerConfigUseCase.kt
  app/src/main/kotlin/com/wire/android/migration/userDatabase/ScalaClientDAO.kt
  app/src/main/kotlin/com/wire/android/migration/userDatabase/ScalaUserDatabaseProvider.kt
Labels: size/L

#1036 fix: adjust the debug screen according to design specs
  app/src/main/kotlin/com/wire/android/model/Clickable.kt
  app/src/main/kotlin/com/wire/android/ui/debugscreen/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/debugscreen/DebugScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsScreen.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/kotlin/com/wire/android/util/extension/LazyListScope.kt
  app/src/main/res/drawable/ic_entypo_share.xml
  app/src/main/res/drawable/ic_share.xml
  app/src/main/res/values/strings.xml
Labels: size/L

#1105 fix: group navigation crashes [AR-2589] [AR-2588]
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/model/ImageAsset.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/navigation/SavedStateViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/Extensions.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/AddMembersToConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/menu/ConversationGroupDetailsBottomSheet.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationAllParticipantsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/all/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/search/SearchConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelTest.kt
  build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/L

#1108 fix: report bug button AR-2650
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
Labels: size/S

#1110 chore: update translation strings via Crowdin [AR-2107][AR2569]
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/XXL, crowdin, l10n

#1111 fix: OngoingCall Notification does not disappear when app is killed and call ends (AR-2581)
  app/src/main/kotlin/com/wire/android/services/OngoingCallService.kt
Labels: size/M

#1112 fix: Small stupid misstake in GroupDetails menu (AR-2652)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
Labels: size/M

#1116 fix: ignore case sensivity for conversation search
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
Labels: size/XS

#1120 chore: replace app icon with beta icon
  app/src/main/AndroidManifest.xml
  app/src/main/res/drawable/ic_launcher_background_beta.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_beta.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round_beta.xml
  app/src/main/res/mipmap-hdpi/ic_launcher_beta.png
  app/src/main/res/mipmap-mdpi/ic_launcher_beta.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_beta.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_beta.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_beta.png
Labels: size/S

#1121 chore: enable datadog
  app/src/main/kotlin/com/wire/android/WireApplication.kt
Labels: size/XS

#1124 feat: migrate cryptobox and client data [AR-2591] [AR-2658]
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/migration/failure/MigrationFailure.kt
  app/src/main/kotlin/com/wire/android/migration/feature/MigrateActiveAccountsUseCase.kt
  app/src/main/kotlin/com/wire/android/migration/feature/MigrateClientsDataUseCase.kt
  app/src/main/kotlin/com/wire/android/migration/userDatabase/ScalaClientDAO.kt
  app/src/main/kotlin/com/wire/android/migration/userDatabase/ScalaUserDatabaseProvider.kt
  app/src/main/kotlin/com/wire/android/migration/util/ScalaCryptoBoxDirectoryProvider.kt
  app/src/main/kotlin/com/wire/android/util/lifecycle/ConnectionPolicyManager.kt
  app/src/test/kotlin/com/wire/android/migration/MigrationManagerTest.kt
  app/src/test/kotlin/com/wire/android/util/lifecycle/ConnectionPolicyManagerTest.kt
Labels: size/L

#1125 feat: Receiving Mentions
  app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/ui/common/LinkifyText.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypesPreview.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorPalette.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
  app/src/main/kotlin/com/wire/android/util/ui/UIText.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelTest.kt
Labels: size/L, DO NOT MERGE
