Repository wireapp/wire-android, pull requests merged in 2022-08, with the labels that each got.

#821 fix: login session crash (QualifiedIdMapper)
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
Labels: size/S

#822 fix: some Users can't register new client on RegisterDeviceScreen [AR-2029]
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceViewModelTest.kt
Labels: size/M

#826 fix: UI fix [AR-1884]
  app/src/main/kotlin/com/wire/android/ui/common/WireSwitch.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsItem.kt
Labels: size/S

#801 feat: Receive Availability status from others
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelArrangement.kt
Labels: size/M

#829 chore: add sound to incoming call notifications
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
Labels: size/S

#823 feat: change member role [AR-1603]
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/RichMenuBottomSheetItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/MutingOptionsSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileDetails.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileGroup.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileState.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
Labels: size/XL

#837 fix: AR-2121 compose slider not syncing properly in user services screen
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsState.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
Labels: size/L

#830 feat: hide the protocol selection when MLS is disabled
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupState.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
Labels: size/M

#839 fix(logout): delete invalid logout session after navigation
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
Labels: size/XS

#838 fix(calling): Self video stays paused when moving the app into foreground in video call (AR-1825)
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
Labels: size/S

#842 fix: back press after opening message notification and initial name [AR-2057]
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
Labels: size/L

#813 feat: Block user from conversation list
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/navigation/HomeNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/BlockUserDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeUIState.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationSheetState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
Labels: size/L

#820 feat: Display blocked user properly
  app/src/main/kotlin/com/wire/android/mapper/ContactMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/UIParticipantMapper.kt
  app/src/main/kotlin/com/wire/android/model/UserAvatarData.kt
  app/src/main/kotlin/com/wire/android/ui/common/BlockedLabel.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserBadge.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationMemberExt.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/model/UIParticipant.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/InternalContactSearchResultItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/EventBadge.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/EventType.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptionButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/BlockedUserMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActionsBox.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageInputRow.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageSendActions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/attachment/AttachmentOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/EditGroupRoleBottomSheet.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserConnectionActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserConnectionStatusInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/res/drawable/ic_blocked_user_avatar.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/framework/TestMessage.kt
  app/src/test/kotlin/com/wire/android/mapper/UIParticipantMapperTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
Labels: size/XXL

#847 feat: minimize ongoing call part1
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
  app/src/main/res/drawable/ic_camera_white_paused.xml
  app/src/main/res/drawable/ic_microphone_white.xml
  app/src/main/res/drawable/ic_microphone_white_muted.xml
  app/src/main/res/values/strings.xml
Labels: size/M

#849 fix: wrong bottom button on add participants screen [AR-2120]
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/BottomNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/GroupButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/SelectParticipantsButtonsRow.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
Labels: size/L

#840 fix: disable RTL
  app/src/main/AndroidManifest.xml
Labels: size/XS

#846 chore: disable guests option change for admins in certain circumstances [AR-1906]
  app/src/main/kotlin/com/wire/android/ui/common/WireSwitch.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsState.kt
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
Labels: size/L

#859 chore: video frozen state when minimized
  app/src/main/kotlin/com/wire/android/ui/calling/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
Labels: size/XS

#861 feat: display connectivity status (AR-1947)
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarBaseViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/Connectivity.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/ConnectivityUIState.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/EstablishedCallState.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/SyncViewState.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModelTest.kt
Labels: size/XL

#864 fix: avatar on conversation top bar clickable [AR-1465]
  app/src/main/kotlin/com/wire/android/ui/common/Extensions.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
Labels: size/M

#865 fix: change member role bottom sheet style [AR-1603]
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/ModalSheetHeaderItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/RichMenuBottomSheetItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetLayout.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/MutingOptionsSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/EditGroupRoleBottomSheet.kt
Labels: size/L

#868 fix: memory leaking of WireFirebaseMessagingService (AR-1812)
  app/src/main/kotlin/com/wire/android/notification/WireFirebaseMessagingService.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
Labels: size/L

#825 feat: unread inidicator
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/ui/common/BottomNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/common/ThemeExt.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/Extension.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/EventBadge.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/EventType.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/navigation/ConversationsNavigationItem.kt
  app/src/test/kotlin/com/wire/android/framework/TestMessage.kt
  app/src/test/kotlin/com/wire/android/mapper/MessageMapperTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/GetMessageForConversationsUseCaseTest.kt
Labels: size/L

#880 fix: other user devices UI [AR-1195]
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/util/ui/StyledStringUtil.kt
  app/src/main/res/values/strings.xml
Labels: size/M

#881 fix: guest label not aligned [AR-2178]
  app/src/main/kotlin/com/wire/android/ui/common/UserBadge.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/InternalContactSearchResultItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
Labels: size/S

#882 fix: separate service from admins [AR-2175]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/usecase/ObserveParticipantsForConversationUseCase.kt
Labels: size/M

#872 feat: add confermation dialog when disabling services
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsState.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
Labels: size/M

#879 feat: leave group conversation list (AR-1552)
  app/src/main/kotlin/com/wire/android/ui/common/VisibilityState.kt
  app/src/main/kotlin/com/wire/android/ui/common/visbility/VisibilityState.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/menu/ConversationGroupDetailsBottomSheet.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/menu/DeleteConversationGroupDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/menu/LeaveConversationGroupDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/ConversationSheetState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/GroupDialogState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileBottomSheet.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
Labels: size/L

#883 fix: Empty UserProfile for not connected user (AR-2190)
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileViewModelArrangement.kt
Labels: size/XL

#884 fix(conversation): detect private build and uppercase titles in group details
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/FolderHeader.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupScreen.kt
  buildSrc/src/main/kotlin/FeatureConfigs.kt
  default.json
Labels: size/M

#888 fix: laggy scrolling / collapsing search bars [AR-2160]
  app/src/main/kotlin/com/wire/android/navigation/HomeNavigation.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/CollapsingTopBarScaffold.kt
  app/src/main/kotlin/com/wire/android/ui/common/SearchBar.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/AppTopBarWithSearchBarLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/SearchBarState.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/SearchTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeUIState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelTest.kt
Labels: size/XXL

#894 fix(conversation-details): update protocol info with conv-details flow
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
Labels: size/XS

#892 fix: accept, ignore, cancel connection request errors (AR-2162)
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/res/values/strings.xml
Labels: size/S

#898 feat: Update notifications icons
  app/src/main/kotlin/com/wire/android/ui/debugscreen/PersistentWebSocketService.kt
  app/src/main/res/drawable/notification_icon_small.xml
  app/src/main/res/drawable/websocket_notification_icon_small.xml
Labels: size/M

#900 fix: add participants to group (AR-2295, AR-2296)
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
Labels: size/M

#907 fix: text ellipsis and spacing [AR-2088]
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/MenuBottomSheetItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/InternalContactSearchResultItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationTitle.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
Labels: size/M

#913 fix: conversation screen crash when user has no conversations
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
Labels: size/S

#914 fix: Can't open conversation menu during ongoing call (AR-2276)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/attachment/AttachmentOptions.kt
Labels: size/L

#915 fix: Conversation options doesn't open after sending app to background (AR-2177)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
Labels: size/S

#905 fix: Delete message from gallery (AR-1748)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SnackbarMessages.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/delete/DeleteMessageDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/delete/DeleteMessageDialogHelper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/delete/DeleteMessageDialogsState.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewState.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModelTest.kt
Labels: size/L
