Repository wireapp/wire-android, pull requests merged in 2022-11, with the labels that each got.

#1130 fix: use correct string for device id
  app/src/main/kotlin/com/wire/android/ui/debugscreen/DebugScreen.kt
Labels: size/XS

#1139 fix: update beta icon foreground [AR-2580]
  app/src/main/res/drawable/ic_launcher_foreground_beta.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_beta.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round_beta.xml
Labels: size/S

#1138 feat: Send mention
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mention/MemberItemToMention.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActionsBox.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageInputRow.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
  app/src/main/kotlin/com/wire/android/util/StringUtil.kt
  app/src/main/kotlin/com/wire/android/util/debug/FeatureVisibilityFlags.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerStateTest.kt
Labels: size/XL

#1122 feat: build flag for enabling encrypted proteus storage
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  buildSrc/src/main/kotlin/FeatureConfigs.kt
  default.json
Labels: size/XS

#1143 fix: Mention in new line bug
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
  app/src/main/kotlin/com/wire/android/util/StringUtil.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerStateTest.kt
Labels: size/M

#1140 fix: duplicate heart emojis [AR-2661]
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/res/drawable/ic_more_emojis.xml
  app/src/main/res/values/strings.xml
Labels: size/M

#1156 fix: Wrong error indicated when password is mismatching
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
Labels: size/S

#1151 feat: DropDown menu for Availability status (AR-2674)
  app/src/main/kotlin/com/wire/android/ui/common/WireDropDown.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#1158 ci: fix missing github credentials
  Jenkinsfile
Labels: size/XS

#1142 feat: rename group conversations flow (AR-1112)
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupConversationNameComponent.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupMetadataState.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupNameValidator.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupDetailsBaseViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/metadata/EditConversationMetadataViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/metadata/EditConversationNameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupScreen.kt
  app/src/main/res/values/strings.xml
Labels: size/XL

#1162 fix: Incoming call rings on silent/vibrant mode (AR-2618)
  app/src/main/kotlin/com/wire/android/media/CallRinger.kt
Labels: size/S

#1164 chore: update junit 5 plugin
  buildSrc/build.gradle.kts
Labels: size/XS

#1144 feat: clear conversation content
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/dialog/ClearConversationContentDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/menu/GroupConversationDetailsBottomSheetEventsHandler.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/GroupDialogState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileEventsHandlers.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileInfoMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/bottomsheet/OtherUserProfileBottomSheet.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileViewModelArrangement.kt
Labels: size/L

#1172 fix: various issues with Android 13 and permissions [AR-2735]
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/util/permission/RequestPushNotificationsPermissionFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/UseStorageRequestFlow.kt
Labels: size/M

#1173 feat: welcome to new android (AR-2118)
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/migration/MigrationManagerTest.kt
Labels: size/L

#1175 fix: migration from scala app adjustments
  app/src/main/kotlin/com/wire/android/migration/MigrationMapper.kt
  app/src/main/kotlin/com/wire/android/migration/userDatabase/ScalaUserDAO.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
Labels: size/S

#1176 feat: Message Details Reactions Empty State
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsReactions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsScreen.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#1179 fix: incoming call not vibrating in vibrate mode (AR-2618)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/media/CallRinger.kt
Labels: size/M

#1183 fix: Adjust Learn More text color
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsEmptyScreenText.kt
Labels: size/M

#1187 fix: adjust reply UI (AR-2484)
  app/src/main/kotlin/com/wire/android/ui/common/spacers/VerticalSpace.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/QuotedMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ReplyMessage.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/M

#1188 refactor: unify quote composables
  app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/QuotedMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypesPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ReplyMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#1189 fix: client id cutted off (AR-2322)
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
  app/src/main/kotlin/com/wire/android/util/extension/ClientId.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/extension/ClientIdTest.kt
Labels: size/L

#1191 fix: activating the inputfield works not as expected (AR-2720)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptionButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActionsBox.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageInputRow.kt
Labels: size/M

#1192 fix: calling buttons not aligned (AR-2662)
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CallOptionsControls.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CameraButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/MicrophoneButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/SpeakerButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
Labels: size/L
