Repository wireapp/wire-android, pull requests merged in 2022-03, with the labels that each got.

#401 feat: custom server config deepLink [AR-943]
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationGraph.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
Labels: size/M

#408 feat: "create personal account" - "email" and "details" UI [AR-1069]
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountViewState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/EmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/OverviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/PersonalDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/RemoveDevice.kt
  app/src/main/kotlin/com/wire/android/ui/common/Extensions.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireTypography.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireTypographyBase.kt
  app/src/main/res/values/strings.xml
Labels: size/XL

#417 ci: add adv caching
  .github/workflows/gradle-run-tests.yml
Labels: size/M

#414 feat: "create personal account" - add "code" UI and adapt to reuse steps [AR-1069]
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeViewState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsViewState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailViewState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreateAccountOverviewParams.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreateAccountOverviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreateAccountOverviewViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountViewState.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/CodeTextField.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireTypography.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireTypographyBase.kt
  app/src/main/res/values/integers.xml
  app/src/main/res/values/strings.xml
Labels: size/XL

#419 fix: drawer can be closed now by swiping from right to left [AR-1205]
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
Labels: size/XS

#428 chore: initialize kalium logger as debug mode
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
Labels: size/S

#425 feat: "create personal account" - add "username" and "summary" UI [AR-1069]
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/CreateAccountFlowType.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreateAccountOverviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/summary/CreateAccountSummaryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/summary/CreateAccountSummaryViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/summary/CreateAccountSummaryViewState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/RemoveDeviceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/WireCenterAlignedTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/res/drawable/ic_create_personal_account_success.xml
  app/src/main/res/drawable/ic_mention.xml
  app/src/main/res/values/strings.xml
Labels: size/XL

#434 fix: exif rotation image avatar (AR-1212)
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/common/imagepreview/AvatarPickerFlow.kt
  app/src/main/kotlin/com/wire/android/ui/common/imagepreview/BulletHoleImagePreview.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/image/AvatarPicker.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/image/AvatarPickerViewModel.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/kotlin/com/wire/android/util/ImageUtil.kt
  app/src/main/kotlin/com/wire/android/util/extension/ImageUtils.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/L

#443 fix: Gradle complaining about 2 google protobuf versions
  app/build.gradle.kts
Labels: size/XS

#444 feat: actually logout when clicking logout
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileViewModel.kt
Labels: size/S

#439 feat: message context menu (AR-961) (AR-1176)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeViewState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/common/CreateAccountBaseViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsViewState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailViewState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/team/CreateTeamViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/RemoveDevice.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/ModalSheetHeaderItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetLayout.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/Message.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/UserProfileViewModel.kt
  app/src/main/res/drawable/ic_attach_file.xml
  app/src/main/res/drawable/ic_copy.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_location.xml
  app/src/main/res/drawable/ic_mic_on.xml
  app/src/main/res/values/strings.xml
Labels: size/XL

#442 feat: sharing image from gallery (AR-1097)
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/AttachmentBundle.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/attachment/AttachmentOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/attachment/AttachmentOptionsViewModel.kt
  app/src/main/kotlin/com/wire/android/util/ImageUtil.kt
  app/src/main/kotlin/com/wire/android/util/StringUtil.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/L

#447 chore: config junit5 and samples for project unit testing
  .github/workflows/gradle-run-ui-tests.yml
  .github/workflows/gradle-run-unit-tests.yml
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/util/DateTimeUtil.kt
  app/src/test/kotlin/com/wire/android/config/CoroutineTestExtension.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/welcome/WelcomeViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/DateTimeUtilKtTest.kt
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/L

#451 fix: disable send button on message sent
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
Labels: size/M

#449 feat: display contact search results from kalium
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/common/AddContactButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/MoreOptionIcon.kt
  app/src/main/kotlin/com/wire/android/ui/common/RowItemTemplate.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireLabelledCheckbox.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireCheckBoxDefaults.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/AppTopBarWithSearchBarLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/SearchBarState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/Extension.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/GroupButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsState.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/ContactSearchResultItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/HighLightName.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/HighLightSubtTitle.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/InternalContactSearchResultItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleState.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/image/AvatarPickerViewModel.kt
  app/src/main/kotlin/com/wire/android/util/flow/SearchQueryStateFlow.kt
  app/src/main/res/drawable/ic_more.xml
  app/src/main/res/values/strings.xml
Labels: size/XXL

#456 feat: display all known contacts
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/common/loading/CenteredCircularProgressBarIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsState.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsViewModel.kt
Labels: size/L

#452 fix: avatar basic handling async
  .github/workflows/gradle-run-unit-tests.yml
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/common/imagepreview/AvatarPickerFlow.kt
  app/src/main/kotlin/com/wire/android/ui/common/imagepreview/BulletHoleImagePreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/attachment/AttachmentOptions.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/image/AvatarPicker.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/image/AvatarPickerState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/image/AvatarPickerViewModel.kt
  app/src/main/kotlin/com/wire/android/util/AvatarImageManager.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/kotlin/com/wire/android/util/ImageUtil.kt
  app/src/main/kotlin/com/wire/android/util/permission/CaptureVideoRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/OpenFileBrowserRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/OpenGalleryRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/RecordAudioRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/TakePictureRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/UseCameraRequestFlow.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/image/AvatarPickerViewModelTest.kt
Labels: size/XL

#450 feat: Notification UI
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/Models.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationReplyReceiver.kt
  app/src/main/kotlin/com/wire/android/ui/settings/SettingsScreen.kt
  app/src/main/res/drawable/notification_icon_small.xml
  app/src/main/res/values/strings.xml
Labels: size/L

#458 feat: link to build artefacts on successful CI runs for PR's.
  Jenkinsfile
Labels: size/M

#460 chore: add IDEA project icon
  .gitignore
  .idea/icon.png
Labels: size/XS

#448 feat: create team flow logic [AR-951]
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/common/CreateAccountBaseViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/team/CreateTeamViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/util/UsernameUtil.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/LoginViewModelTest.kt
Labels: size/L
