Repository wireapp/wire-android, pull requests merged in 2022-02, with the labels that each got.

#3657 fix: A back frame is displayed after accepting video call (SQCALL-426)
  app/src/main/scala/com/waz/zclient/calling/AllParticipantsAdapter.scala
Labels: size/XS

#3658 fix: Fix environment setup by using env instead of >> $GITHUB_ENV
  .github/workflows/semantic-commit-lint.yml
Labels: size/XS

#3662 fix(build): remove 'null' from F-Droid build version strings.
  app/build.gradle
Labels: size/XS

#3659 fix(calling): video permission not requested (FS-350)
  zmessaging/src/main/scala/com/waz/service/call/CallingServiceImpl.scala
Labels: size/XS

#3667 fix: Limit notifications reappering on the screen after they are swiped away (SQCORE-1133)
  app/src/main/scala/com/waz/zclient/notifications/controllers/AndroidNotificationsManager.scala
Labels: size/M

#3668 fix: The "reply" notification should be used only for replies to the current user (SQCORE-1249)
  zmessaging/src/main/scala/com/waz/model/MessageData.scala
  zmessaging/src/main/scala/com/waz/service/otr/NotificationParser.scala
Labels: size/M

#3671 feat: Security clearance on the call view (FS-385)
  app/src/main/res/layout/calling_header.xml
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/views/CallingHeader.scala
Labels: size/M

#3672 fix: Change in the copy of the classified conversation banner (FS-468)
  app/src/main/res/values/strings.xml
  app/src/main/scala/com/waz/zclient/calling/views/CallingHeader.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
Labels: size/XS

#3673 feat: Show the security clearance banner for unconnected users (FS-385)
  app/src/main/res/layout/fragment_participants_not_tabbed.xml
  app/src/main/res/layout/participant_user_name_row.xml
  app/src/main/scala/com/waz/zclient/calling/controllers/CallController.scala
  app/src/main/scala/com/waz/zclient/calling/views/CallingHeader.scala
  app/src/main/scala/com/waz/zclient/participants/ParticipantsController.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/BlockedUserFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ConnectRequestFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/ParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/PendingConnectRequestFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/SingleParticipantFragment.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/UnconnectedParticipantAdapter.scala
  app/src/main/scala/com/waz/zclient/participants/fragments/UntabbedRequestFragment.scala
  app/src/main/scala/com/waz/zclient/views/ConversationFragment.scala
Labels: size/L

#3675 fix: Only call setAllowBubbles() on Android Q and higher
  app/src/main/scala/com/waz/zclient/notifications/controllers/AndroidNotificationsManager.scala
Labels: size/XS

#3676 fix: The pending connect request view was blank (FS-385)
  app/src/main/scala/com/waz/zclient/participants/fragments/ConnectRequestFragment.scala
Labels: size/XS
