Repository wireapp/wire-android, pull requests merged in 2022-04, with the labels that each got.

#457 feat: another user profile - not-connected (UI) [AR-1191]
  app/src/main/kotlin/com/wire/android/ui/common/ArrowRightIcon.kt
  app/src/main/kotlin/com/wire/android/ui/common/CopyButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/MoreOptionIcon.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/MenuBottomSheetItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireIconButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/GroupButton.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#464 fix: hold the new conversation state on redirection to user profile
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/GroupButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsState.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleState.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
Labels: size/XL

#468 ci(jenkins): abort ongoing runs upon new commits
  Jenkinsfile
Labels: size/XS

#416 test: add cases for login and welcome screens
  app/build.gradle.kts
  app/src/androidTest/java/com/wire/android/ui/ConversationScreenTest.kt
  app/src/androidTest/java/com/wire/android/ui/LoginScreenTest.kt
  app/src/androidTest/java/com/wire/android/ui/MainScreenTest.kt
  app/src/androidTest/java/com/wire/android/ui/RemoveDeviceScreenTest.kt
  app/src/androidTest/java/com/wire/android/ui/UserProfileScreenTest.kt
  app/src/androidTest/java/com/wire/android/utils/Extensions.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/RemoveDevice.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/RemoveDeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
Labels: size/XL

#473 fix: ui tests isolation and datastore management
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/datastore/UserDataStore.kt
Labels: size/S

#467 fix: user avatar new flow (AR-1275)
  app/src/main/kotlin/com/wire/android/navigation/HomeNavigation.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationAnimationConfig.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/navigation/TransitionAnimations.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPickerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/res/drawable/ic_default_user_avatar.xml
Labels: size/L

#472 fix: close keyboard on action (AR-912)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
Labels: size/S

#478 ci: fix UI tests job and disable them on Jenkins
  .github/workflows/gradle-run-ui-tests.yml
  Jenkinsfile
Labels: size/XS

#477 fix: message composer going active show latest item
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
Labels: size/M

#480 feat(conversation): display 1:1 conversation title (AR-1178)
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
Labels: size/L

#487 chore: No syntax highlighting in build messages for performance (SQPIT-926)
  Jenkinsfile
Labels: size/XS

#470 feat: register client screen [AR-1110]
  app/src/androidTest/java/com/wire/android/ui/RemoveDeviceScreenTest.kt
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDevice.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDevice.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmail.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/authentication/LoginViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
Labels: size/L

#490 fix: drawer scrim size accordingly to design specs (AR-994)
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeState.kt
Labels: size/S

#483 chore: add calling assets(AR-1250)
  app/src/main/res/drawable/ic_camera_off.xml
  app/src/main/res/drawable/ic_camera_on.xml
  app/src/main/res/drawable/ic_hang_up.xml
  app/src/main/res/drawable/ic_muted.xml
  app/src/main/res/drawable/ic_speaker_off.xml
  app/src/main/res/drawable/ic_unmuted.xml
Labels: size/M

#479 test: configure di for authenticated tests
  app/build.gradle.kts
  app/src/androidTest/java/com/wire/android/di/TestModule.kt
  app/src/androidTest/java/com/wire/android/ui/LoginEmailScreenTest.kt
  app/src/androidTest/java/com/wire/android/ui/RemoveDeviceScreenTest.kt
  app/src/androidTest/java/com/wire/android/utils/Extensions.kt
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/L

#494 feat: add login SSO UI [AR-1159]
  app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmail.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSO.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireTabRow.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModelTest.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XL

#501 fix: new conversation search fix
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/SearchListNavigationHost.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/Screen.kt
Labels: size/L

#503 test: remove device screen test
  .github/workflows/gradle-run-ui-tests.yml
  app/src/androidTest/java/com/wire/android/ui/LoginEmailScreenTest.kt
  app/src/androidTest/java/com/wire/android/ui/MainScreenTest.kt
  app/src/androidTest/java/com/wire/android/ui/RemoveDeviceScreenTest.kt
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
Labels: size/M

#504 fix: login and registration UI fixes [AR-1429] [AR-1343]
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/common/CreateAccountBaseViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/common/CreateAccountFlowType.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/summary/CreateAccountSummaryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/summary/CreateAccountSummaryViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/team/CreateTeamNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/team/CreateTeamViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/CodeTextField.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#500 fix: handle message delete dialog for yourself on only the current user messages [AR-1126]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
Labels: size/M

#507 feat: display avatars (AR-897) (AR-1181)
  app/src/main/kotlin/com/wire/android/di/ImageLoadingModule.kt
  app/src/main/kotlin/com/wire/android/model/UserAvatarAsset.kt
  app/src/main/kotlin/com/wire/android/ui/common/CurrentSessionViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationMemberExt.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/common/ConversationUserAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageViewWrapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/GeneralConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsState.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/InternalContactSearchResultItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/main/kotlin/com/wire/android/util/ui/AssetImageFetcher.kt
  app/src/main/kotlin/com/wire/android/util/ui/WireSessionImageLoader.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
Labels: size/L

#506 fix: make message composer less jumpy
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/attachment/AttachmentOptions.kt
Labels: size/XL

#514 fix: hard coded STAGING BE for account creation
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
Labels: size/XS

#516 feat: initiate SSO login [AR-1160]
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDevice.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSO.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModelTest.kt
Labels: size/L

#517 feat: display message sending failure
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageViewWrapper.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
Labels: size/L

#519 fix: change the message list background color
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
Labels: size/XS

#520 fix: adjust message item paddings
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/S

#510 chore: add basic config for coverage
  .github/workflows/gradle-run-unit-tests.yml
  README.md
  buildSrc/src/main/kotlin/scripts/quality.gradle.kts
  codecov.yml
Labels: size/M

#522 fix: remove device keyboard behavior
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDevice.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModel.kt
Labels: size/S

#525 test: Update Calling UI - Part3
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallState.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModelTest.kt
Labels: size/M

#523 feat: muting conversation options - part 1 (AR-1103)
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/navigation/HomeNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/common/ArrowIcon.kt
  app/src/main/kotlin/com/wire/android/ui/common/ArrowRightIcon.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/ModalSheetHeaderItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/RichMenuBottomSheetItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/AppTopBarWithSearchBarLayout.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MutingConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MutingOptionsSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/res/drawable/ic_arrow_left.xml
  app/src/main/res/drawable/ic_arrow_left_back.xml
  app/src/main/res/drawable/ic_check_circle.xml
  app/src/main/res/values/strings.xml
Labels: size/XL

#511 test: register device cases
  app/src/androidTest/java/com/wire/android/di/TestModule.kt
  app/src/androidTest/java/com/wire/android/ui/LoginEmailScreenTest.kt
  app/src/androidTest/java/com/wire/android/ui/RegisterDeviceTest.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDevice.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupScreen.kt
Labels: size/L

#529 feat: muting conversation list details - part 2 (AR-1043)
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/MenuBottomSheetItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/RichMenuBottomSheetItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MutingConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MutingOptionsSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/MutedSetting.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
Labels: size/L

#534 feat: add audio permission check for when receiving an incoming call
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/util/permission/CallingRecordAudioRequestFlow.kt
Labels: size/M

#539 feat: add request camera permission in calling
  app/src/main/kotlin/com/wire/android/ui/calling/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/CallOptionsControls.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlButtons/CameraButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
Labels: size/M

#537 fix: set the correct message source based on the message sender [AR-1458]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationMemberExt.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageViewWrapper.kt
  app/src/main/kotlin/com/wire/android/util/ui/UIText.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
Labels: size/L

#542 fix: revert to correct speaker button icon
  app/src/main/res/drawable/ic_speaker_on.xml
Labels: size/S

#543 feat: display one to one conversation user membership
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/Membership.kt
  app/src/main/res/values/strings.xml
Labels: size/S

#530 feat(sso-login): handle sso login deeplink [AR-1354] [AR-1156] [AR-1157]
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginError.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmail.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSO.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
  app/src/main/kotlin/com/wire/android/util/deeplink/DeepLinkProcessor.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/authentication/LoginViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/DeepLinkProcessorTest.kt
Labels: size/XL

#496 feat: Subscribe to notifications
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/di/GetNotificationsUseCaseProvider.kt
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/Models.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationDismissReceiver.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/SettingsScreen.kt
  app/src/main/kotlin/com/wire/android/util/extension/Flow.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
Labels: size/L

#544 refactor: remove hardcoded things [AR-1436][AR-1343][AR-1453][AR-1410]
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreateAccountOverviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/common/ConversationUserAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/GeneralConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationTitle.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationUserAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/GroupConversationAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/UserLabel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationFolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/model/Contact.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
Labels: size/L

#541 feat: make app ring for incoming and outgoing calls (AR-1405)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/media/CallRinger.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModel.kt
  app/src/main/res/raw/ready_to_talk.m4a
  app/src/main/res/raw/ringing_from_me.m4a
  app/src/main/res/raw/ringing_from_them.m4a
  app/src/test/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModelTest.kt
Labels: size/M
