Repository wireapp/wire-android, pull requests merged in 2022-01, with the labels that each got.

#303 feat: display basic conversation list items (AR-786)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/LauncherActivity.kt
  app/src/main/kotlin/com/wire/android/ui/MainActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireApp.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/Conversation.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Color.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Theme.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#304 feat: add main navigation drawer
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/ui/common/Logo.kt
  app/src/main/kotlin/com/wire/android/ui/common/UnderConstructionScreen.kt
  app/src/main/kotlin/com/wire/android/ui/main/MainActivity.kt
  app/src/main/kotlin/com/wire/android/ui/main/MainDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/main/MainNavigationScreenItem.kt
  app/src/main/kotlin/com/wire/android/ui/main/MainTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/main/archive/ArchiveScreen.kt
  app/src/main/kotlin/com/wire/android/ui/main/convesations/ConversationsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/main/settings/SettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/main/support/SupportScreen.kt
  app/src/main/kotlin/com/wire/android/ui/main/vault/VaultScreen.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Color.kt
  app/src/main/res/drawable/ic_archive.xml
  app/src/main/res/drawable/ic_big_logo.xml
  app/src/main/res/drawable/ic_conversation.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/drawable/ic_support.xml
  app/src/main/res/drawable/ic_vault.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  config/detekt/detekt.yml
Labels: size/XL

#307 feat:display_conversation_folder_header
  app/src/main/kotlin/com/wire/android/ui/common/LegalHoldIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/common/MembershipQualifier.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/Conversation.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/ConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/model/Conversation.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Color.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Theme.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Typography.kt
Labels: size/L

#306 feat: display_legal_hold_indicator_member_ship_qualifier (AR-880) (AR-879)
  app/src/main/kotlin/com/wire/android/ui/conversation/Conversation.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/model/Conversation.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Color.kt
  app/src/main/res/values/strings.xml
Labels: size/S

#308 feat: new_conversation_activity_events (AR-870) (AR-872)
  app/src/main/kotlin/com/wire/android/ui/WireApp.kt
  app/src/main/kotlin/com/wire/android/ui/common/EventBadge.kt
  app/src/main/kotlin/com/wire/android/ui/common/Utils.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/Conversation.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/ConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/model/NewActivity.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Color.kt
  app/src/main/res/drawable/ic_missed_call.xml
  app/src/main/res/drawable/ic_unread_mention.xml
  app/src/main/res/drawable/ic_unread_reply.xml
  app/src/main/res/values/strings.xml
Labels: size/L

#314 feat: add custom text field with proper styling [AR-863]
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextFieldDefaults.kt
  app/src/main/res/drawable/ic_input_mandatory.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  config/detekt/detekt.yml
Labels: size/L

#320 fix: remove conversation items duplication
  app/src/main/kotlin/com/wire/android/ui/common/EventBadge.kt
  app/src/main/kotlin/com/wire/android/ui/common/LegalHoldIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/common/MembershipQualifier.kt
  app/src/main/kotlin/com/wire/android/ui/common/SurfaceBackgroundWrapper.kt
  app/src/main/kotlin/com/wire/android/ui/common/Utils.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/all/Conversation.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/call/Call.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/mention/Mention.kt
Labels: size/L

#317 feat: add login screen UI [AR-831]
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/ui/common/SearchBar.kt
  app/src/main/kotlin/com/wire/android/ui/common/SurfaceBackgroundWrapper.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/login/Login.kt
  app/src/main/kotlin/com/wire/android/ui/login/LoginTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/welcome/Welcome.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#321 feat: integrate conversation list into the app
  app/src/main/kotlin/com/wire/android/ui/common/BottomNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/all/Conversation.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/all/model/Conversation.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/call/Call.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/common/RowItem.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/common/UserLabel.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/mention/Mention.kt
  app/src/main/kotlin/com/wire/android/ui/main/convesations/ConversationsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/main/navigation/MainNavigationScreenItem.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Dimensions.kt
Labels: size/L

#323 feat: integrate conversation list into bottom navigation
  app/src/main/kotlin/com/wire/android/ui/common/BottomNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/common/FloatingActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/all/Conversation.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/all/ConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/all/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/call/CallState.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/call/CallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/call/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/mention/MentionState.kt
  app/src/main/kotlin/com/wire/android/ui/conversation/mention/MentionViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/CallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/ConversationRoute.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/ConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/MentionScreen.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/common/EventBadge.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/common/Extension.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/common/FolderHeader.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/common/LegalHoldIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/common/MembershipQualifier.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/common/RowItem.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/common/UserLabel.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/model/Call.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/model/Conversation.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/model/Mention.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/model/NewActivity.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/navigation/ConversationsNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/main/convesations/ConversationsNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/main/convesations/ConversationsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/main/convesations/all/AllConversationsTab.kt
  app/src/main/kotlin/com/wire/android/ui/main/convesations/calls/CallsConversationsTab.kt
  app/src/main/kotlin/com/wire/android/ui/main/convesations/mentions/MentionsConversationsTab.kt
  app/src/main/kotlin/com/wire/android/ui/main/navigation/MainNavigationScreenItem.kt
Labels: size/XL

#325 chore: deactivate legacy module
  legacy/deactivate_build.gradle.kts
Labels: size/XS

#327 fix: signing not enabled when publishing builds
  Jenkinsfile
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
Labels: size/XS

#329 chore: make `internal` the default track for publishing
  Jenkinsfile
Labels: size/XS

#331 feat: display message items (AR-968)
  app/src/main/kotlin/com/wire/android/ui/common/LegalHoldIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/common/MembershipQualifierLabel.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/CallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/ConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/MentionScreen.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/common/EventBadge.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/common/UserLabel.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/model/Call.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/model/Conversation.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/model/Mention.kt
  app/src/main/kotlin/com/wire/android/ui/main/conversation/model/NewActivity.kt
  app/src/main/kotlin/com/wire/android/ui/main/message/Message.kt
  app/src/main/kotlin/com/wire/android/ui/main/message/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/main/message/model/Message.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Dimensions.kt
  app/src/main/res/drawable/mock_message_image.png
  app/src/main/res/values/strings.xml
Labels: size/XL

#336 fix: remove test conversation emit sequence
  app/src/main/kotlin/com/wire/android/ui/main/conversation/ConversationViewModel.kt
Labels: size/S

#339 feat: Close drawer on back click
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
Labels: size/S

#334 feat: add wire styled buttons [AR-861]
  app/src/main/kotlin/com/wire/android/ui/common/CircularProgressIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/common/Extentions.kt
  app/src/main/kotlin/com/wire/android/ui/common/SurfaceBackgroundWrapper.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireButtonDefaults.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireSecondaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireTertiaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextFieldDefaults.kt
  app/src/main/kotlin/com/wire/android/ui/home/message/Message.kt
  app/src/main/kotlin/com/wire/android/ui/login/Login.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Color.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Dimensions.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Theme.kt
  app/src/main/kotlin/com/wire/android/ui/welcome/Welcome.kt
Labels: size/XXL

#340 chore: add app version name to drawer [AR-984]
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Theme.kt
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/S

#342 feat: Icon size in drawer
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
Labels: size/XS

#344 feat: Drawer color fix
  app/src/main/kotlin/com/wire/android/ui/common/BottomNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
Labels: size/XS

#335 feat: add conversation message view
  app/src/main/kotlin/com/wire/android/ui/common/BackNavigationIconButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/MembershipQualifierLabel.kt
  app/src/main/kotlin/com/wire/android/ui/common/OnDropDownIconButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/ConversationView.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/Message.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversation.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/Calls.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRoute.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/Mentions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/EventBadge.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/Extension.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/FolderHeader.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/RowItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/UserLabel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/Call.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/Conversation.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/Mention.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/NewActivity.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/navigation/ConversationsNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/message/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/login/LoginTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Dimensions.kt
  app/src/main/res/drawable/ic_dropdown_icon.xml
  app/src/main/res/drawable/ic_search_icon.xml
  app/src/main/res/drawable/ic_video_icon.xml
  app/src/main/res/values/strings.xml
Labels: size/XXL

#343 feat: support multiple screen sizes and orientations [AR-989]
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/ui/authentication/login/Login.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/Welcome.kt
  app/src/main/kotlin/com/wire/android/ui/common/BottomNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/common/MembershipQualifierLabel.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireSecondaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireTertiaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/common/MembershipQualifier.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/Calls.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/Mentions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/FolderHeader.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/RowItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/UserLabel.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Dimensions.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Theme.kt
  app/src/main/kotlin/com/wire/android/ui/theme/ThemeUtils.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorPalette.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireTypography.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireTypographyBase.kt
  app/src/main/res/values/colors.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XL
