Repository wireapp/wire-android, pull requests merged in 2022-06, with the labels that each got.

#634 chore: add proper handling of media player to stop it ringing
  app/src/main/kotlin/com/wire/android/media/CallRinger.kt
Labels: size/S

#628 chore: Notifications improve (AR-1059)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/di/GetNotificationsUseCaseProvider.kt
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/kotlin/com/wire/android/notification/WireFirebaseMessagingService.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/MessageNotificationDismissReceiver.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/NotificationReplyReceiver.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/L

#629 feat: Handle incoming/outgoing call buttons - PART 0 : move duplicate code to a shared viewModel (AR-1364)
  app/src/main/kotlin/com/wire/android/ui/calling/CallState.kt
  app/src/main/kotlin/com/wire/android/ui/calling/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/OngoingCallState.kt
  app/src/main/kotlin/com/wire/android/ui/calling/OngoingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallState.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/calling/OngoingCallViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModelTest.kt
Labels: size/XL

#639 feat: ignore accept connection request (AR-1462)
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileState.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
Labels: size/L

#643 fix: crash when displaying message from user removed from group [AR-1809]
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
Labels: size/S

#646 chore: add pr autoassigner, updates kalium ref
  .github/workflows/pr-author-assigner.yml
Labels: size/S

#648 fix: Message textColor for dark mode
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
Labels: size/XS

#650 fix: improve scroll performance with collapsable search bar
  app/src/main/kotlin/com/wire/android/navigation/HomeNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/common/extension/LazyList.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/AppTopBarWithSearchBarLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/SearchBarState.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleScreenState.kt
Labels: size/L

#637 fix: reinitiate email input from saved state
  app/src/main/kotlin/com/wire/android/ui/authentication/create/common/CreateAccountBaseViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/team/CreateTeamViewModel.kt
Labels: size/S

#652 feat: Persist self user status
  app/src/main/kotlin/com/wire/android/datastore/UserDataStore.kt
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/model/UserAvatarData.kt
  app/src/main/kotlin/com/wire/android/model/UserStatus.kt
  app/src/main/kotlin/com/wire/android/ui/calling/CallPreview.kt
  app/src/main/kotlin/com/wire/android/ui/calling/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserStatusIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationUserAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/model/Contact.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/InternalContactSearchResultItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/SearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/dialog/ChangeStatusDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/dialog/StatusDialogData.kt
  app/src/test/kotlin/com/wire/android/framework/TestMessage.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/GetMessageForConversationsUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
Labels: size/L

#659 chore: update github actions
  .github/workflows/generate-changelog.yml
  .github/workflows/gradle-run-ui-tests.yml
  .github/workflows/gradle-run-unit-tests.yml
  .github/workflows/semantic-commit-lint.yml
Labels: size/S

#660 ci: add playtest branch workflow
  .github/workflows/create-playtest-branch.yml
Labels: size/M

#658 feat: auth server config provider (AR-1464)
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/di/AuthServerConfigProvider.kt
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/notification/WireFirebaseMessagingService.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/MessageNotificationDismissReceiver.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/common/CreateAccountBaseViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreateAccountOverviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/team/CreateTeamNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/team/CreateTeamScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/test/kotlin/com/wire/android/mapper/MessageMapperTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/LoginViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/Stubs.kt
Labels: size/XL

#651 feat: 1:1 call participants view - Part 1: create layout (AR-1370)
  app/src/main/kotlin/com/wire/android/ui/calling/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
  app/src/main/res/drawable/ic_participant_muted.xml
  app/src/main/res/values/strings.xml
Labels: size/L

#661 fix: ignore connection request message (AR-1821)
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/res/values/strings.xml
Labels: size/S

#673 feat: add timestamps to messages AR-1420
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/util/DateTimeUtil.kt
  app/src/test/kotlin/com/wire/android/mapper/MessageMapperTest.kt
Labels: size/M

#675 chore: Back Navigation improve
  app/src/main/kotlin/com/wire/android/navigation/NavigationManager.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModel.kt
Labels: size/M

#680 feat: display error when failing to delete message (AR-1271)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SnackbarMessages.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelTest.kt
Labels: size/M

#679 fix: system messages design review changes [AR-1143]
  app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/test/kotlin/com/wire/android/mapper/MessageContentMapperTest.kt
Labels: size/L

#681 fix: connection issues (AR-1823) (AR-1817)
  app/src/main/kotlin/com/wire/android/ui/common/button/WireItemLabel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/EventBadge.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
Labels: size/M

#677 chore: hide conversation list search bar AR-1855
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
Labels: size/XS

#684 feat: navigation to group conversation details page [AR-1715]
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/OnDropDownIconButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelArrangement.kt
Labels: size/L

#619 feat: notification for calls
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/kotlin/com/wire/android/notification/WireFirebaseMessagingService.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/CallNotificationDismissReceiver.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/util/ui/ScreenSettingsUtil.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModelTest.kt
Labels: size/XL

#688 fix: fixed crash when sending/receiving svg images
  app/src/main/kotlin/com/wire/android/mapper/AssetsUtil.kt
  app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
  app/src/test/kotlin/com/wire/android/framework/TestMessage.kt
  app/src/test/kotlin/com/wire/android/mapper/MessageContentMapperTest.kt
Labels: size/M

#663 fix: block message bottom menu for deleted messages [AR-1661]
  app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/model/Clickable.kt
  app/src/main/kotlin/com/wire/android/ui/common/Extensions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/test/kotlin/com/wire/android/mapper/MessageContentMapperTest.kt
  app/src/test/kotlin/com/wire/android/mapper/MessageMapperTest.kt
Labels: size/L

#693 fix: truncate long names in search AR-1867
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/HighLightName.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/HighLightSubtTitle.kt
Labels: size/S

#694 fix: displayed received images with null width and height as asset messages [AR-1685]
  app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/test/kotlin/com/wire/android/framework/TestMessage.kt
  app/src/test/kotlin/com/wire/android/mapper/MessageContentMapperTest.kt
Labels: size/L

#696 chore: hide new account button in self profile AR-1883
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
Labels: size/XS

#691 fix: connection issues visual pending label (AR-1817)
  app/src/main/kotlin/com/wire/android/ui/common/button/WireItemLabel.kt
Labels: size/S

#697 feat: dysplay sync status on the home screen
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireLinearProgressIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/SyncStateViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/SyncViewState.kt
Labels: size/L

#685 feat: Group call view - Part 1 : creating the grid (AR-1148)
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/ui/calling/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallingGridView.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallingHorizentalView.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/VerticalCallingPager.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
  app/src/main/res/drawable/ic_participant_muted.xml
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/L

#692 feat: add conversation options UI and display group name [AR-1721]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsState.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
Labels: size/L

#647 feat(new-mls-conversation): add protocol to new group (AR-1775) #573
  app/src/main/kotlin/com/wire/android/ui/common/WireCheckIcon.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDropDown.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/bottomsheet/MutingOptionsSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupState.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#703 fix(calling): mute incoming group call
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
Labels: size/S

#700 feat: Group call view - Part 2 : grid indicator (AR-1148)
  app/src/main/kotlin/com/wire/android/ui/calling/common/VerticalCallingPager.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/VerticalPagerIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
  app/src/test/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModelTest.kt
Labels: size/L

#706 chore: remove vault and archive sections AR-1851
  app/src/main/kotlin/com/wire/android/navigation/HomeNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeUIState.kt
Labels: size/M

#711 fix(sso-login): add loading indicator to SSO login page (AR-1837)
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
Labels: size/XS

#712 fix(ui): follow design on displaying failure to send messages (AR-1201)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorPalette.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/M

#670 fix: snackbar message on pop (AR-1820) [AR-1821]
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/navigation/SavedStateViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
Labels: size/L

#701 test: (AR-1553) Federated search
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelTest.kt
Labels: size/L

#716 feat: group conversation details - participants list [AR-1688]
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  app/src/main/kotlin/com/wire/android/mapper/UIParticipantMapper.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/Extensions.kt
  app/src/main/kotlin/com/wire/android/ui/common/MembershipQualifierLabel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationMemberExt.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipants.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantsState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIParticipant.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/CallsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/Extension.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/MentionScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/contacts/ContactsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/HighLightName.kt
  app/src/main/kotlin/com/wire/android/util/ui/StyledStringUtil.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/mapper/UIParticipantMapperTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelTest.kt
Labels: size/XL

#719 fix: memberhip qualifier label not centered
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
Labels: size/XS

#718 fix(calling): control buttons messed up
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallingGridView.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/OneOnOneCallView.kt
Labels: size/S

#721 feat(calling): Dim video
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallVideoPreview.kt
Labels: size/XS

#724 feat: (AR-1726) Long Tap on Images doesn't bring up message option menu
  app/src/main/kotlin/com/wire/android/model/Clickable.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
Labels: size/M

#725 fix: adjust the message padding according to designs
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
Labels: size/XS

#727 fix: (AR-1725) Pressing back button on sharing files section closes the conversation instead
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
Labels: size/XS

#728 fix: make ImageAsset have a reference to image loader
  app/src/main/kotlin/com/wire/android/mapper/ContactMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/UICallParticipantMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/UIParticipantMapper.kt
  app/src/main/kotlin/com/wire/android/model/ImageAsset.kt
  app/src/main/kotlin/com/wire/android/ui/calling/CallState.kt
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallingGridView.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/OneOnOneCallView.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/VerticalCallingPager.kt
  app/src/main/kotlin/com/wire/android/ui/calling/model/UICallParticipant.kt
  app/src/main/kotlin/com/wire/android/ui/common/CurrentSessionViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationMemberExt.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/ZoomableImage.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/test/kotlin/com/wire/android/mapper/MessageMapperTest.kt
  app/src/test/kotlin/com/wire/android/mapper/UICallParticipantMapperTest.kt
  app/src/test/kotlin/com/wire/android/mapper/UIParticipantMapperTest.kt
  app/src/test/kotlin/com/wire/android/navigation/NavigationUtilsTest.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/ConversationsViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/ui/AssetImageFetcherTest.kt
Labels: size/L
