Repository wireapp/wire-android, pull requests merged in 2022-12, with the labels that each got.

#1197 fix: login/continue button is hidden under the keyboard [AR-1993]
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
Labels: size/L

#1201 fix: app not respecting auto capitalize keyboard settings [AR-2728]
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
Labels: size/XS

#1195 feat: Connect backup logic with UI
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/common/FailureDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/restore/RestoreBackupDialogStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/restore/RestoreBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/util/FileManager.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/framework/FakeKaliumFileSystem.kt
Labels: size/L

#1185 fix: phone is vibrating when starting a new call
  app/src/main/kotlin/com/wire/android/media/CallRinger.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModel.kt
Labels: size/M

#1184 feat: read receipts user setting (AR-2711)
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsState.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsViewModel.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#1208 fix: text direction for RTL languages
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
Labels: size/XS

#1210 refactor: remove the usage of Global scope in calling and notification
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/CallNotificationDismissReceiver.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/EndOngoingCallReceiver.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ProximitySensorManager.kt
Labels: size/M

#1211 fix: italic notification text is cut off [AR-1990]
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
Labels: size/S

#1178 chore: disable MLS support for dev builds
  default.json
Labels: size/XS

#1213 feat: disable create account with proxy [AR-2786]
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/DialogStates.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/FeatureDisabledWithProxyDialog.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#1219 fix: update last read message loop [AR-2804]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
Labels: size/XS

#1225 fix: add isIncomingCall as false when call is established
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModel.kt
Labels: size/XS

#1230 fix: connection issues top bar is not displayed on app start
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
Labels: size/M

#1229 fix: hide option for failed message [AR-2830]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
Labels: size/M

#1232 fix: notification badge before unread events badge
  app/src/main/kotlin/com/wire/android/ui/common/RowItemTemplate.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/MutedConversationBadge.kt
Labels: size/M

#1234 fix: missed call badge in muted conversation allowed only for mentions [AR-2832]
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
Labels: size/XS

#1235 chore: update remove device flow [AR-2350]
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/CancelLoginDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/DialogStates.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#1215 fix: support multi user notification (AR-2797)
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationConstants.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/NotificationReplyReceiver.kt
  app/src/main/kotlin/com/wire/android/services/OngoingCallService.kt
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/main/kotlin/com/wire/android/workmanager/WireWorkerFactory.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/MigrationWorker.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/NotificationFetchWorker.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/XL

#1228 fix: use compatibility build profile for the dev flavour [AR-2776]
  Jenkinsfile
  buildSrc/src/main/kotlin/ClientConfig.kt
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
Labels: size/S

#1238 chore: inherit AGP version from Kalium
  buildSrc/build.gradle.kts
  buildSrc/settings.gradle.kts
Labels: size/S

#1241 fix: Logout problem (AR-2839)
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
Labels: size/XS

#1240 fix: Block user toast is not visible (AR-2809)
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
Labels: size/XS

#1244 fix: changed last missed called event text [AR-2845]
  app/src/main/kotlin/com/wire/android/mapper/MessagePreviewContentMapper.kt
  app/src/main/res/values/strings.xml
Labels: size/XS

#1250 chore: update reset session strings
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/res/values/strings.xml
Labels: size/M

#1252 chore: include commit hash id into the build
  .gitignore
  app/src/main/assets/.gitkeep
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/ui/debugscreen/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/util/EmailComposer.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/res/values/strings.xml
  build.gradle.kts
  buildSrc/src/main/kotlin/IncludeGitBuildTask.kt
  buildSrc/src/main/kotlin/ProjectExtensions.kt
  buildSrc/src/main/kotlin/scripts/compilation.gradle.kts
Labels: size/L

#1251 fix: enable dark theme (AR-1306)
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallerDetails.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/AcceptButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CallOptionsControls.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CameraButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CameraFlipButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/HangUpButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/MicrophoneButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/SpeakerButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/WireCallControlButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/common/AttachmentButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/Logo.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDropDown.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/divider/WireDivider.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/QuotedMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/MutedConversationBadge.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageInputRow.kt
  app/src/main/kotlin/com/wire/android/ui/theme/ThemeUtils.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorPalette.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
  app/src/main/kotlin/com/wire/android/util/ui/StyledStringUtil.kt
  app/src/main/res/drawable/ic_accept.xml
  app/src/main/res/drawable/ic_call_accept.xml
  app/src/main/res/drawable/ic_call_reject.xml
  app/src/main/res/drawable/ic_camera_flip.xml
  app/src/main/res/drawable/ic_camera_off.xml
  app/src/main/res/drawable/ic_camera_on.xml
  app/src/main/res/drawable/ic_flip_camera_off.xml
  app/src/main/res/drawable/ic_flip_camera_on.xml
  app/src/main/res/drawable/ic_hang_up.xml
  app/src/main/res/drawable/ic_microphone_off.xml
  app/src/main/res/drawable/ic_microphone_on.xml
  app/src/main/res/drawable/ic_muted.xml
  app/src/main/res/drawable/ic_speaker_off.xml
  app/src/main/res/drawable/ic_speaker_on.xml
  app/src/main/res/drawable/ic_unmuted.xml
Labels: size/XL

#1245 chore: re-enable MLS on dev builds
  default.json
Labels: size/XS

#1249 fix: green calling banner displayed for short time after ending a call (AR-2864)
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
Labels: size/S

#1258 fix: call participants tile color on light mode (AR-2866)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/XS

#1257 fix(calling): Name covering microphone icon
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/XS

#1263 fix: Do not ask for external write permissions on android 13 and above
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/ui/home/conversations/DownloadedAssetDialog.kt
  app/src/main/kotlin/com/wire/android/util/permission/WriteToExternalStorageRequestFlow.kt
Labels: size/M

#1253 fix: Other user profile menu flickering
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
Labels: size/L

#1247 chore: remove device flow
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/common/ClearSessionState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/common/ClearSessionViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModel.kt
Labels: size/L

#1264 fix: Cleaning notification on conversation openning (AR-2873)
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationConstants.kt
Labels: size/S

#1265 fix: showing download confirmation snackbar message after saving assets [AR-1729]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SnackbarMessages.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelTest.kt
Labels: size/L

#1231 fix: message composer not changing state correctly when hiding keyboard [AR-2720] [AR-2723] [AR-1477]
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetLayout.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/BlockedUserComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/DeletedUserComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActionsBox.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageInputRow.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageSendActions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/attachment/AttachmentOptions.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerStateTest.kt
Labels: size/XL

#1267 fix: rename group screen UI [AR-2788]
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupConversationNameComponent.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupMetadataState.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupNameValidator.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/metadata/EditConversationMetadataViewModel.kt
Labels: size/L

#1259 fix: scroll to bottom when sending a message
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
Labels: size/S

#1266 fix: conversation item padding [AR-2874]
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/JoinButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/RowItemTemplate.kt
  app/src/main/kotlin/com/wire/android/ui/common/spacers/HorizontalSpace.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/EventBadge.kt
Labels: size/L
