Repository wireapp/wire-android, pull requests merged in 2023-05, with the labels that each got.

#1748 fix(RC): add latest translations to release/candidate
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/XXL

#1744 fix: remove system agent from kalium user agent
  app/src/main/kotlin/com/wire/android/util/UserAgentProvider.kt
Labels: size/XS

#1747 chore: update translation strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/L, crowdin, l10n

#1757 fix(rc): NPE crash after configuration changes [AR-3290]
  app/src/main/kotlin/com/wire/android/navigation/NavigationManager.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
Labels: size/M

#1755 fix(dev): NPE crash after configuration changes [AR-3290]
  app/src/main/kotlin/com/wire/android/navigation/NavigationManager.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
Labels: size/M

#1683 fix: Restrict import media for logged out user (AR-3222)
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/FeatureFlagState.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaUnauthenticatedViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
Labels: size/L

#1750 fix: allow to send knock message when offline [AR-3162]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActionsBox.kt
Labels: size/XS

#1762 fix: no self deletion status for asset saved externally
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelTest.kt
Labels: size/M

#1766 fix: missing messages after migration (#1756)
  app/src/main/kotlin/com/wire/android/migration/MigrationMapper.kt
  app/src/main/kotlin/com/wire/android/migration/feature/MigrateActiveAccountsUseCase.kt
  app/src/test/kotlin/com/wire/android/migration/MigrationMapperTest.kt
Labels: size/M

#1771 fix: Disable text content import into Wire [AR-3323]
  app/src/main/AndroidManifest.xml
Labels: size/M

#1769 fix(rc): NavBackStackEntry crash on HomeScreen [AR-3286]
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
Labels: size/M

#1768 fix(dev): NavBackStackEntry crash on HomeScreen [AR-3286]
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
Labels: size/M

#1774 fix: issue not identifying correctly already consumed intents [AR-3377] [AR-3387]
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
Labels: size/S

#1777 fix: issue with wrong text color while in dark mode [AR-3386]
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/MenuBottomSheetItem.kt
  app/src/main/kotlin/com/wire/android/ui/edit/DownloadAssetExternallyOption.kt
  app/src/main/kotlin/com/wire/android/ui/edit/ReactionOption.kt
Labels: size/L

#1775 fix: no reply action for messages [AR-3400]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
Labels: size/XS

#1781 fix: delete and remove edit options not using error color correctly [AR-3386]
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/MenuBottomSheetItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/edit/DeleteItemMenuOption.kt
  app/src/main/kotlin/com/wire/android/ui/edit/OpenAssetExternallyOption.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
Labels: size/L

#1782 fix: not observing to edit changes to enable save edit button [AR-3399]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageInputRow.kt
Labels: size/XS

#1783 fix(RC): menu options UI bugs with dark mode [AR-3386]
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/MenuBottomSheetItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/ModalSheetHeaderItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/edit/DownloadAssetExternallyOption.kt
  app/src/main/kotlin/com/wire/android/ui/edit/ReactionOption.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
Labels: size/L

#1784 fix: shared user id on manifest for custom builds
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
Labels: size/S

#1760 feat: full screen calling tiles (AR-3155)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/FullScreenTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/SelectedParticipant.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantsTiles.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/gridview/CallingGridView.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/horizentalview/CallingHorizontalView.kt
  app/src/main/kotlin/com/wire/android/ui/common/SecurityClassificationBanner.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorPalette.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/XL

#1753 ci: remove usage of deprecated ::set-output (AR-3375)
  .github/workflows/create-playtest-branch.yml
Labels: size/XS

#1787 fix: sending audio files crashes the app
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
Labels: size/XS

#1786 fix: server config crash (RC)
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
Labels: size/S

#1785 fix: server config crash (AR-3425)
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
Labels: size/S

#1800 fix: display CBR indicator for only oneOnOne calls (AR-1369)
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
Labels: size/XS

#1799 fix: logout dialog was blocked when user is offline
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
Labels: size/XS

#1790 fix: On join ringtone is played many times when the call got established (AR-3419)
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModel.kt
Labels: size/S

#1778 feat(calling): show double tap toast in an active call
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/DoubleTapToast.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/FullScreenTile.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#1792 fix: debug screen adjustment (AR-3420)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/debug/LogOptions.kt
  app/src/main/kotlin/com/wire/android/ui/debug/StartServiceReceiver.kt
  app/src/main/kotlin/com/wire/android/ui/debug/UserDebugViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/debug/dev/DevDebugContent.kt
  app/src/main/kotlin/com/wire/android/ui/debug/dev/DevDebugViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/debugscreen/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsScreen.kt
  app/src/main/res/values/strings.xml
Labels: size/XXL

#1795 fix: Notification observing on app hidden (AR-3369) (AR-3357)
  app/src/main/kotlin/com/wire/android/GlobalObserversManager.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/util/lifecycle/ConnectionPolicyManager.kt
  app/src/test/kotlin/com/wire/android/GlobalObserversManagerTest.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
Labels: size/L

#1816 fix: group self deleting messages options improvements [AR-3431]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editselfdeletingmessages/EditSelfDeletingMessagesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editselfdeletingmessages/EditSelfDeletingMessagesState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editselfdeletingmessages/EditSelfDeletingMessagesViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/editselfdeletingmessages/EditSelfDeletingMessagesViewModelTest.kt
Labels: size/S

#1820 fix: click on notification from lock screen opens app in the background (AR-3434)
  app/src/main/AndroidManifest.xml
Labels: size/XS

#1827 fix: issues after migrating to material3 [AR-3494] [AR-3497]
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/S

#1823 fix: ForgroundService crash (AR-3471)
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationConstants.kt
  app/src/main/kotlin/com/wire/android/services/OngoingCallService.kt
Labels: size/M

#1815 fix(calling): show CBR indicator for one on one calls only
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
Labels: size/XS

#1831 chore: add annotation to preview multiple themes
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/SecurityClassificationBanner.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/util/ui/PreviewMultipleThemes.kt
Labels: size/L
