Repository wireapp/wire-android, pull requests merged in 2023-10, with the labels that each got.

#2294 fix: updated user settings screen with correct copy for typing indicator [WPB-4592]
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsScreen.kt
Labels: size/XS

#2293 fix: toast crash [WPB-4937]
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/common/scaffold/WireScaffold.kt
  app/src/main/kotlin/com/wire/android/ui/common/snackbar/LocalSnackbarHostState.kt
  app/src/main/kotlin/com/wire/android/ui/common/snackbar/SwipeDismissSnackbar.kt
  app/src/main/kotlin/com/wire/android/ui/common/snackbar/SwipeableSnackbar.kt
  app/src/main/kotlin/com/wire/android/ui/common/snackbar/WireSnackbar.kt
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioComponent.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/NewConversationSearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPickerState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsScreen.kt
Labels: size/L

#2298 feat: cherry pick improvements
  .github/workflows/cherry-pick-rc-to-develop.yml
Labels: size/L

#2302 fix: attachments items arrangement [WPB-1840]
  app/src/main/kotlin/com/wire/android/ui/common/AttachmentButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AttachmentOptions.kt
  gradle/libs.versions.toml
Labels: size/L

#2303 fix: do not show confirmation dialogs when unarchiving conversations [WPB-4435]
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/SearchQuery.kt
Labels: size/S

#2304 fix: not showing dialog when archiving users from user profile screen [WPB-4993]
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileEventsHandlers.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/bottomsheet/OtherUserProfileBottomSheet.kt
Labels: size/S

#2305 chore: source updated from crowdin
  .github/workflows/crowdin-source-updater.yml
  .github/workflows/crowdin-translations-updater.yml
Labels: size/M

#2312 fix: update archiving dialog copy
  app/src/main/res/values/strings.xml
Labels: size/XS

#2311 feat(reactions): emoji picker
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/ui/edit/ReactionOption.kt
  app/src/main/kotlin/com/wire/android/ui/emoji/DraggableByHandleBottomSheetBehavior.kt
  app/src/main/kotlin/com/wire/android/ui/emoji/EmojiPicker.kt
  app/src/main/kotlin/com/wire/android/ui/emoji/HandleDraggableBottomSheetDialog.kt
  app/src/main/res/layout/dialog_bottom_sheet_custom_behavior.xml
  app/src/main/res/values-night/themes.xml
  gradle/libs.versions.toml
Labels: size/XL

#2322 fix: modify download placeholders to clarify saved and downloaded cases [WPB-4732]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/asset/AssetMessageTypes.kt
  app/src/main/res/values/strings.xml
Labels: size/S

#2319 chore(ci): include build info in tests (WPB-4505)
  AR-builder.groovy
Labels: size/S

#2320 fix: sanitize urls before displaying warning dialog [WPB-4782]
  app/src/main/kotlin/com/wire/android/util/UriUtil.kt
Labels: size/M

#2325 fix(typing): back handler and jumping screen typing indicator
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/UsersTypingIndicator.kt
Labels: size/M

#2324 fix: bypassing app lock after timeout
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/feature/ObserveAppLockConfigUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/EnterLockScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/LockCodeTimeManager.kt
  app/src/test/kotlin/com/wire/android/feature/ObserveAppLockConfigUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/appLock/LockCodeTimeManagerTest.kt
Labels: size/L

#2328 chore: update localization sources from Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/XXL, crowdin, l10n

#2321 feat: unlock app with biometrics (WPB-4696)
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/GlobalObserversManager.kt
  app/src/main/kotlin/com/wire/android/biomitric/BiometricPromptUtils.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/AppUnlockWithBiometricsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/AppUnlockWithBiometricsViewModel.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: size/L

#2330 chore: update biometrics dialog copy
  app/src/main/res/values/strings.xml
Labels: size/XS

#2326 fix: use stable compose bom version to fix video calls [WPB-4992]
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/common/snackbar/SwipeableSnackbar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  gradle/libs.versions.toml
Labels: size/L

#2331 fix: keyboard size after gifs expand [WPB-4985]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolderTest.kt
Labels: size/L

#2334 feat: add logger with userid and clientid
  app/src/beta/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/dev/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/internal/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/main/kotlin/com/wire/android/AppLogger.kt
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/ui/debug/UserDebugViewModel.kt
  app/src/staging/kotlin/com/wire/android/util/DataDogLogger.kt
Labels: size/L

#2340 feat: cherry-pick improvements
  .github/workflows/cherry-pick-rc-to-develop.yml
Labels: size/L

#2342 fix(links): embedded links with escaped chars [e.g. plus] (WPB-4402)
  app/src/main/kotlin/com/wire/android/util/UriUtil.kt
  app/src/test/kotlin/com/wire/android/util/UriUtilTest.kt
Labels: size/S

#2339 chore: update compose destinations and navigation libs
  app/src/main/kotlin/com/wire/android/navigation/style/WireDestinationStyleAnimated.kt
  gradle/libs.versions.toml
Labels: size/S

#2338 fix: muting group conversation from details screen not working [WPB-4994]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
Labels: size/S

#2343 feat: scroll bottom - jump to last message (WPB-4987) (WPB-3973)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#2344 chore: update localization strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/XL, crowdin, l10n

#2348 fix: App crash on app unlock with fingerprint (WPB-5110) (WPB-5108)
  app/src/main/kotlin/com/wire/android/biomitric/BiometricPromptUtils.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
Labels: size/M

#2353 fix: fixed issue not activating search on long click in search bar [WPB-2231]
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/SearchTopBar.kt
Labels: size/M

#2354 chore: update localization sources from Crowdin [WPB-1825]
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/L, crowdin, l10n

#2351 fix: expanded message composer improvements [WPB-5131]
  app/src/main/kotlin/com/wire/android/ui/common/AttachmentButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/UsersTypingIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/UiMention.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/L

#2360 fix: expanded message composer edit state
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/M

#2356 fix: add required permissions for calling on API 34
  app/src/main/AndroidManifest.xml
Labels: size/XS

#2362 fix: send button visibility
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
Labels: size/XS

#2364 fix: update applock copy (WPB-5093)
  app/src/main/res/values/strings.xml
Labels: size/XS

#2368 fix: design review adjustments for scroll to bottom
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/S

#2374 fix: navigating with UPDATE_EXISTED, extracting base route
  app/src/main/kotlin/com/wire/android/navigation/HomeDestination.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/test/kotlin/com/wire/android/navigation/NavigationUtilsTest.kt
Labels: size/M

#2372 fix: attachment width and android 14 crash on start [WPB-5101]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AttachmentOptions.kt
  gradle/libs.versions.toml
Labels: size/XS

#2370 feat: backup password validation [WPB-4374]
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreState.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogFlow.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogs.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/settings/home/BackupAndRestoreViewModelTest.kt
Labels: size/M

#2376 fix: navigating with UPDATE_EXISTED, extracting base route [WPB-5225]
  app/src/main/kotlin/com/wire/android/navigation/HomeDestination.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/test/kotlin/com/wire/android/navigation/NavigationUtilsTest.kt
Labels: size/M, cherry-pick

#2378 fix: remove app lock after logout
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
Labels: size/S

#2382 fix: broken build
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModel.kt
Labels: size/S
