Repository wireapp/wire-android, pull requests merged in 2023-06, with the labels that each got.

#1813 fix(calling): fill to screen video stream in preview screens (AR-3056)
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallVideoPreview.kt
Labels: size/S

#1829 fix: wrong color values for import media button on dark mode [AR-3491]
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/SelectParticipantsButtonsRow.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/M

#1830 feat: add option to retry or cancel messages that failed to send [AR-2188]
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItemComponents.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypesPreview.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Theme.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelArrangement.kt
Labels: size/XL

#1822 fix: handle asset without extension [AR-3261, AR-2929, AR-3482]
  app/src/main/kotlin/com/wire/android/mapper/RegularMessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/AssetTooLargeDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/AssetBundle.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
  app/src/main/kotlin/com/wire/android/util/FileManager.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelArrangement.kt
Labels: size/M

#1837 fix: double tap toast text style (WPB-314)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/DoubleTapToast.kt
Labels: size/XS

#1825 fix: download image removes data about the timer
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
Labels: size/M

#1836 fix: keyboard hides the Confirm Password field on sign up (WPB-398)
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
Labels: size/L, Fix PR Title or Commit message️

#1841 fix: remove from remember message to refresh bottom sheet state [WPB-773]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
Labels: size/XS

#1833 fix: do not show dialog in ImportMedia screen (AR-3274)
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/L

#1843 fix: app stuck on connecting after opening a summary notification [WPB-763]
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
  app/src/test/kotlin/com/wire/android/util/CurrentScreenManagerTest.kt
  app/src/test/kotlin/com/wire/android/util/StubLifecycle.kt
Labels: size/L

#1845 fix: Create Account form no longer visible (WPB-1689)
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
Labels: size/M

#1850 fix: correctly identify if app is visible
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
  app/src/main/kotlin/com/wire/android/util/lifecycle/ConnectionPolicyManager.kt
  app/src/test/kotlin/com/wire/android/util/CurrentScreenManagerTest.kt
  app/src/test/kotlin/com/wire/android/util/lifecycle/ConnectionPolicyManagerTest.kt
Labels: size/M

#1849 fix: extend debug options screen
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/debug/LogOptions.kt
  app/src/main/kotlin/com/wire/android/ui/debug/UserDebugViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/debug/dev/DevDebugContent.kt
  app/src/main/kotlin/com/wire/android/ui/debug/dev/DevDebugViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/RowItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsScreen.kt
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/XL

#1848 fix: conversation failed to add error grouped by domain annotated string (WPB-263)
  app/src/main/kotlin/com/wire/android/mapper/SystemMessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/res/values/strings.xml
Labels: size/M

#1851 fix: wrong context menu when long-clicking on a message content [WPB-773]
  app/src/main/kotlin/com/wire/android/ui/common/LinkifyText.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
Labels: size/S

#1854 fix: start UI self delete timer countdown after the message is sent
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
Labels: size/XS

#1855 feat: pending and error message status indicator [WPB-975]
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/ui/common/spacers/HorizontalSpace.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItemComponents.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageStatusIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypesPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/res/drawable/ic_message_delivered.xml
  app/src/main/res/drawable/ic_message_error.xml
  app/src/main/res/drawable/ic_message_read.xml
  app/src/main/res/drawable/ic_message_sending.xml
  app/src/main/res/drawable/ic_message_sent.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/framework/TestMessage.kt
  app/src/test/kotlin/com/wire/android/mapper/MessageMapperTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelArrangement.kt
Labels: size/L

#1856 refactor: remove NavigationItem dependencies and provide screen modes [WPB-360]
  app/proguard-rules.pro
  app/src/main/kotlin/com/wire/android/navigation/Extras.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationGraph.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationStyleConfig.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/navigation/OtherDirections.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/common/CreateAccountBaseViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallNavArgs.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallNavArgs.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallNavArgs.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/banner/ConversationBannerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/AccountDetailsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/appsettings/AppSettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
  app/src/main/kotlin/com/wire/android/util/ui/ScreenSettingsUtil.kt
  app/src/test/kotlin/com/wire/android/config/NavigationTestExtension.kt
  app/src/test/kotlin/com/wire/android/feature/AccountSwitchUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/email/VerifyEmailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsViewModelTest.kt
Labels: size/XXL

#1861 refactor: fix broken unit test (WPB-360)
  app/src/main/kotlin/com/wire/android/navigation/Extras.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/connection/ConnectionActionButtonViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/banner/ConversationBannerViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/displayname/ChangeDisplayNameViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/email/VerifyEmailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsViewModelTest.kt
  buildSrc/src/main/kotlin/scripts/quality.gradle.kts
  config/detekt/detekt.yml
Labels: size/L

#1863 refactor: replace NavigationManager with Navigator - Part 1 [WPB-384]
  app/src/main/kotlin/com/wire/android/feature/AccountSwitchUseCase.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationGraph.kt
  app/src/main/kotlin/com/wire/android/navigation/Navigator.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/common/ClearSessionViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeState.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/test/kotlin/com/wire/android/feature/AccountSwitchUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/welcome/WelcomeViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/DeepLinkProcessorTest.kt
Labels: size/XL

#1865 fix: do not start countdown when the message is enqueued for self delete
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageExpiration.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
Labels: size/S

#1871 fix(RC): start timer when receiving messages
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
Labels: size/XS

#1869 fix: hide three dots when conversation not found [WPB-774]
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserConnectionActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileEventsHandlers.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileViewModelArrangement.kt
Labels: size/L

#1876 chore: bump develop to 4.3.x
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#1866 refactor: replace NavigationManager with Navigator - Part 2 [WPB-384]
  app/src/main/kotlin/com/wire/android/navigation/Extras.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationManager.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/navigation/SavedStateViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButtonViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/AddMembersToConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchServicesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/displayname/ChangeDisplayNameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/displayname/ChangeDisplayNameViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/email/updateEmail/ChangeEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/email/updateEmail/ChangeEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/email/verifyEmail/VerifyEmailNavArgs.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/email/verifyEmail/VerifyEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/email/verifyEmail/VerifyEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/handle/ChangeHandleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/handle/ChangeHandleViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPickerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileEventsHandlers.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/connection/ConnectionActionButtonViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/displayname/ChangeDisplayNameViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/email/ChangeEmailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/email/VerifyEmailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/handle/ChangeHandleViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/home/BackupAndRestoreViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/image/AvatarPickerViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsViewModelTest.kt
Labels: size/XL

#1839 ci: support multi build pipeline
  .gitignore
  AR-builder.groovy
  Jenkinsfile
Labels: WIP, size/XL

#1870 fix(RC): backup dialog can be dismissed
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/CustomBEDeeplinkDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/restore/RestoreBackupDialogs.kt
Labels: size/M

#1875 refactor(RC): unify asset edit options
  app/src/main/kotlin/com/wire/android/model/ImageAsset.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/AssetEditMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/TextMessageEditMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewState.kt
  app/src/test/kotlin/com/wire/android/navigation/NavigationUtilsTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModelTest.kt
Labels: size/L

#1882 chore: remove empty files
  app/src/main/kotlin/com/wire/android/ExternalLoggerManager.kt
  app/src/main/kotlin/com/wire/android/navigation/TrackingNavController.kt
  app/src/main/kotlin/com/wire/android/util/DataDogLogger.kt
Labels: size/S

#1885 style: remove addressed detekt infringements
  config/detekt/baseline.xml
Labels: size/L

#1886 chore: building params jenkins branch adj
  Jenkinsfile
Labels: size/S

#1877 fix: start timer when receiving messages (#1871)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
Labels: size/XS

#1887 refactor: replace NavigationManager with Navigator - Part 4 [WPB-384]
  app/src/main/kotlin/com/wire/android/navigation/HomeNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceState.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/call/ConversationCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/delete/DeleteMessageDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/delete/DeleteMessageDialogHelper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editselfdeletingmessages/EditSelfDeletingMessagesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editselfdeletingmessages/EditSelfDeletingMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/metadata/EditConversationMetadataViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/metadata/EditConversationNameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationAllParticipantsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/all/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaUnauthenticatedViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/call/ConversationCallViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/editselfdeletingmessages/EditSelfDeletingMessagesViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModelTest.kt
Labels: size/XXL

#1889 refactor: replace NavigationManager with Navigator - Part 5 - last [WPB-384]
  app/src/main/kotlin/com/wire/android/GlobalObserversManager.kt
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationCommand.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreatePersonalAccountOverviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/summary/CreateAccountSummaryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/summary/CreateAccountSummaryViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/util/ui/ScreenSettingsUtil.kt
  app/src/test/kotlin/com/wire/android/GlobalObserversManagerTest.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModelTest.kt
Labels: size/XL

#1893 refactor: login and new conversation nested graphs [WPB-385]
  app/src/main/kotlin/com/wire/android/navigation/NavigationCommand.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationGraph.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationStyleConfig.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/AddMembersSearchScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchAllPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchContactsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/NewConversationNavGraph.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupOptions/GroupOptionsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupNameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/newgroup/NewGroupScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/NewConversationSearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/util/ui/ScreenSettingsUtil.kt
Labels: size/XL

#1895 fix: message timer counts down before message is sent
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
Labels: size/XS

#1897 refactor: nested navigation graph on home screen [WPB-385]
  app/src/main/kotlin/com/wire/android/di/LogWriterModule.kt
  app/src/main/kotlin/com/wire/android/navigation/HomeDestination.kt
  app/src/main/kotlin/com/wire/android/navigation/HomeNavigation.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/navigation/OtherDestinations.kt
  app/src/main/kotlin/com/wire/android/ui/common/BottomNavigation.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeNavGraph.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeState.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/archive/ArchiveScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/all/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/call/CallsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/mention/MentionScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/vault/VaultScreen.kt
  app/src/main/kotlin/com/wire/android/util/CustomTabsHelper.kt
  app/src/main/kotlin/com/wire/android/util/LogFileWriter.kt
Labels: size/XL
