Repository wireapp/wire-android, pull requests merged in 2023-04, with the labels that each got.

#1608 fix: (RC) personal user settings group read receipt (AR-3168)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
Labels: size/L

#1620 fix(rc): banner padding issue and classified banners for calls (AR-3244)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
Labels: size/S

#1624 fix(develop): fixed text color for both self and other users mentions [AR-3011]
  app/src/main/kotlin/com/wire/android/ui/common/LinkifyText.kt
Labels: size/XS

#1621 fix(dev): banner padding issue and classified banners for calls (AR-3244)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
Labels: size/S

#1613 fix(rc): attachment options not appearing on android 8 [AR-3033]
  app/src/main/kotlin/com/wire/android/ui/common/KeyboardHelper.kt
Labels: size/XS

#1612 fix(dev): attachment options not appearing on android 8 [AR-3033]
  app/src/main/kotlin/com/wire/android/ui/common/KeyboardHelper.kt
Labels: size/XS

#1626 fix: disabled development api for staging environment [AR-3277]
  default.json
Labels: size/XS

#1618 fix: remove read messages after migration [AR-3237] develop
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/test/kotlin/com/wire/android/migration/MigrationManagerTest.kt
Labels: size/M

#1627 fix: show deleted regular message [AR-3278]
  app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/test/kotlin/com/wire/android/mapper/EncodedMessageContentMapperTest.kt
Labels: size/M

#1629 fix(rc): federation classified banner displayed after leaving or user deleted (AR-3264)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/BlockedUserComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/DeletedUserComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerClassifiedBanner.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
Labels: size/M

#1630 fix(dev): federation classified banner displayed after leaving or user deleted (AR-3264)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/BlockedUserComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/DeletedUserComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerClassifiedBanner.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
Labels: size/M

#1592 fix: call still ringing despite that the caller already ended the call (AR-3046) (RC)
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
Labels: size/M

#1642 fix: ANR caused by workManager (AR-3279) (RC)
  app/src/main/kotlin/com/wire/android/workmanager/worker/MigrationWorker.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/SingleUserMigrationWorker.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#1632 fix(conversation): hide conversation protocol info when MLS is disabled
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsState.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
Labels: size/S

#1638 fix: proximity sensor crash (AR-3204)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/ui/calling/ProximitySensorManager.kt
Labels: size/S

#1637 chore: update dependencies
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/S

#1646 chore: add advanced stale config for issues and labels
  .github/workflows/stale-issues-and-pr.yml
Labels: size/M

#1622 feat: display connectivity top bar on all screens
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/test/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModelTest.kt
Labels: size/L

#1633 fix(conversation): hide conversation protocol info when mls is disabled
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsState.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
Labels: size/S

#1644 fix: initialize datadog on worker thread
  app/src/main/kotlin/com/wire/android/WireApplication.kt
Labels: size/M

#1636 feat: Restrict import media for users that are not allowed to share (AR-3223) (AR-3222)
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/FileSharingRestrictedDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/FeatureFlagState.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
Labels: size/XXL

#1657 fix: ForegroundServiceDidNotStartInTimeException (AR-3285) (RC)
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
Labels: size/S

#1652 refactor: customization file support
  .github/workflows/gradle-run-unit-tests.yml
  app/src/main/kotlin/com/wire/android/di/AuthServerConfigProvider.kt
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  buildSrc/src/main/kotlin/Customization.kt
  buildSrc/src/main/kotlin/customization/ClientConfig.kt
  buildSrc/src/main/kotlin/customization/ConfigurationFileImporter.kt
  buildSrc/src/main/kotlin/customization/Customization.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  buildSrc/src/main/kotlin/customization/FeatureFlags.kt
  buildSrc/src/main/kotlin/customization/NormalizedFlavorSettings.kt
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
  buildSrc/src/test/kotlin/customization/ConfigurationFileImporterTest.kt
  buildSrc/src/test/kotlin/customization/CustomizationTest.kt
  default.json
Labels: size/XL

#1658 feat: [RC] crash app on migration erorrs
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/migration/MigrationReport.kt
  app/src/main/kotlin/com/wire/android/migration/failure/UserMigrationStatus.kt
  app/src/main/kotlin/com/wire/android/migration/userDatabase/ShouldTriggerMigrationForUserUserCase.kt
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/MigrationWorker.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/SingleUserMigrationWorker.kt
  app/src/test/kotlin/com/wire/android/migration/MigrationManagerTest.kt
  app/src/test/kotlin/com/wire/android/migration/ShouldTriggerMigrationForUserUserCaseTest.kt
Labels: size/L

#1660 refactor: customization file support
  .github/workflows/gradle-run-unit-tests.yml
  app/src/main/kotlin/com/wire/android/di/AuthServerConfigProvider.kt
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  buildSrc/src/main/kotlin/Customization.kt
  buildSrc/src/main/kotlin/customization/ClientConfig.kt
  buildSrc/src/main/kotlin/customization/ConfigurationFileImporter.kt
  buildSrc/src/main/kotlin/customization/Customization.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  buildSrc/src/main/kotlin/customization/FeatureFlags.kt
  buildSrc/src/main/kotlin/customization/NormalizedFlavorSettings.kt
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
  buildSrc/src/test/kotlin/customization/ConfigurationFileImporterTest.kt
  buildSrc/src/test/kotlin/customization/CustomizationTest.kt
  default.json
Labels: size/XL

#1661 feat: Show Loader while logout (AR-2419)
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/ProgressDialog.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/main/res/values/strings.xml
Labels: size/M

#1667 fix: missing SUPPORT_URL from compatRelease builds
  buildSrc/src/main/kotlin/customization/ClientConfig.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
  default.json
Labels: size/M

#1650 fix: ar 2368 design changes
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/model/Device.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireSwitch.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsItem.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/M

#1669 chore: disable back button for incoming and outgoing call screens (AR-3298) (RC)
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallScreen.kt
Labels: size/S

#1670 fix: default config for firebaseAppId [AR-3304]
  default.json
Labels: size/XS

#1671 fix: default config for firebaseAppId [AR-3304]
  default.json
Labels: size/XS

#1672 fix: IndexOutOfBoundsException on mention span [AR-3303]
  app/src/main/kotlin/com/wire/android/ui/common/LinkifyText.kt
Labels: size/XS

#1675 feat(RC): support building with custom backends
  app/src/main/kotlin/com/wire/android/di/AuthServerConfigProvider.kt
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/EmptySearchQueryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
Labels: size/M

#1684 chore: bump develop version to next release 4.2.0
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#1651 fix: ForegroundServiceDidNotStartInTimeException (AR-3285)
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
Labels: size/S

#1682 fix: share logs to Wire users (AR-3213)
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaViewModel.kt
Labels: size/S

#1674 feat: support building with custom backends
  app/src/main/kotlin/com/wire/android/di/AuthServerConfigProvider.kt
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/EmptySearchQueryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
Labels: size/M

#1656 feat: merge messages from same sender [AR-3077]
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/ui/common/LinkifyText.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypesPreview.kt
Labels: size/L

#1690 chore: build dev flavour in addition to staging on PRs
  .github/workflows/build-app.yml
  .github/workflows/gradle-run-unit-tests.yml
Labels: size/M

#1662 feat: [DEV] crash app on migration erorrs (#1658)
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/migration/MigrationReport.kt
  app/src/main/kotlin/com/wire/android/migration/failure/UserMigrationStatus.kt
  app/src/main/kotlin/com/wire/android/migration/userDatabase/ShouldTriggerMigrationForUserUserCase.kt
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/MigrationWorker.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/SingleUserMigrationWorker.kt
  app/src/test/kotlin/com/wire/android/migration/MigrationManagerTest.kt
  app/src/test/kotlin/com/wire/android/migration/ShouldTriggerMigrationForUserUserCaseTest.kt
Labels: size/L

#1692 fix(dev): connectivityState doesn't change after session update [AR-3324]
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
Labels: size/M

#1680 fix: view model state update [AR-3300]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
Labels: size/S

#1697 fix(rc): mentions are lost after edit [AR-3299]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerStateTest.kt
Labels: size/S

#1695 fix(dev): mentions are lost after edit [AR-3299]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerStateTest.kt
Labels: size/S

#1664 feat: provide ui related custom configuration
  app/src/main/kotlin/com/wire/android/config/CustomUiConfigurationProvider.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  default.json
Labels: size/L

#1699 feat(rc): provide ui related custom configuration
  app/src/main/kotlin/com/wire/android/config/CustomUiConfigurationProvider.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  default.json
Labels: size/L

#1701 chore: cleanup build flags
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
Labels: size/L

#1686 fix: run ShouldTriggerMigrationForUserUserCase on worker thread
  app/src/main/kotlin/com/wire/android/migration/userDatabase/ShouldTriggerMigrationForUserUserCase.kt
  app/src/test/kotlin/com/wire/android/migration/ShouldTriggerMigrationForUserUserCaseTest.kt
Labels: size/M

#1706 fix: ar 2368 design changes (#1650)
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/model/Device.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireSwitch.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsItem.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/L

#1713 fix: stuck in 2fa when account has too many devices (AR-3317)
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailVerificationCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/verificationcode/VerificationCodeState.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
Labels: size/M

#1715 fix: Not receiving notifications after logout login
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
Labels: size/M

#1702 fix(calling): fit VideoPreview (AR-2089)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
Labels: size/XS

#1712 fix: animate progress bar
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/audio/AudioMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/restore/RestoreBackupDialogs.kt
Labels: size/S

#1720 feat: support application id customization (AR-3334)
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
  default.json
Labels: size/M

#1721 ci(rc): enable instrumented test
  .github/workflows/gradle-run-ui-tests.yml
  Jenkinsfile
  app/src/androidTest/java/com/wire/android/HiltAwareTestRunner.kt
  app/src/androidTest/java/com/wire/android/di/TestCoroutinesDispatchersModule.kt
  app/src/androidTest/java/com/wire/android/di/TestModule.kt
  app/src/androidTest/java/com/wire/android/ui/ConversationScreenTest.kt
  app/src/androidTest/java/com/wire/android/ui/CreatePersonalAccountScreenTest.kt
  app/src/androidTest/java/com/wire/android/ui/CreateTeamScreenTest.kt
  app/src/androidTest/java/com/wire/android/ui/LoginEmailScreenTest.kt
  app/src/androidTest/java/com/wire/android/ui/MainScreenTest.kt
  app/src/androidTest/java/com/wire/android/ui/RegisterDeviceTest.kt
  app/src/androidTest/java/com/wire/android/ui/RemoveDeviceScreenTest.kt
  app/src/androidTest/java/com/wire/android/ui/UserProfileScreenTest.kt
  app/src/androidTest/java/com/wire/android/utils/Extensions.kt
  app/src/androidTest/java/com/wire/android/utils/WorkManagerTestRule.kt
  app/src/test/kotlin/com/wire/android/media/ConversationAudioMessagePlayerTest.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XXL

#1723 ci: fix kalium checkout race condition
  Jenkinsfile
Labels: size/S

#1722 fix: DEV Not receiving notifications after logout login
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
Labels: size/S

#1704 feat: respect update email build flag
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModel.kt
Labels: size/XS

#1727 fix: [RC] obfuscate ids from navigation destination
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
Labels: size/XS

#1728 fix: [DEV] obfuscate ids from navigation destination
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
Labels: size/XS

#1730 fix: remove audio animation for the slider (RC)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/audio/AudioMessageType.kt
Labels: size/XS

#1732 chore: adding readme section for contributing to language support
  README.md
Labels: size/S

#1729 fix: remove audio animation for the slider(develop)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/audio/AudioMessageType.kt
Labels: size/XS

#1734 chore: raise minSdk to Android 8 API 26 (RC)
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#1735 chore: raise minSdk to Android 8 (API 26) (develop)
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#1737 fix(rc): reset media player state when fetching new audio
  app/src/main/kotlin/com/wire/android/media/audiomessage/ConversationAudioMessagePlayer.kt
Labels: size/S

#1726 fix(dev): handle role edit option for federated users (AR-3347)
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/Membership.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileGroup.kt
Labels: size/S

#1739 feat: support resource customization
  buildSrc/src/main/kotlin/customization/BuildTimeConfiguration.kt
  buildSrc/src/main/kotlin/customization/Customization.kt
  buildSrc/src/main/kotlin/customization/FeatureFlags.kt
  buildSrc/src/main/kotlin/customization/ResourcesOverrider.kt
  buildSrc/src/main/kotlin/flavor/ProductFlavors.kt
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
  buildSrc/src/test/kotlin/customization/CustomizationTest.kt
Labels: size/L

#1740 fix: [AR-3364]When device was used on another account, we see a random string,…
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
Labels: size/XS

#1738 ci: hardening of github workflows (AR-2928)
  .github/workflows/check-kalium-commitish.yml
  .github/workflows/codestyle.yml
  .github/workflows/create-playtest-branch.yml
  .github/workflows/generate-changelog.yml
Labels: size/M

#1741 fix: [DEV] When device was used on another account, we see a random string,…
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
Labels: size/XS
