Repository wireapp/wire-android, pull requests merged in 2023-03, with the labels that each got.

#1516 fix: not receiving incoming calls
  app/src/main/kotlin/com/wire/android/GlobalObserversManager.kt
  app/src/test/kotlin/com/wire/android/GlobalObserversManagerTest.kt
Labels: size/M

#1501 feat: federation, offline backends message sending (AR-3122)
  app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/framework/TestMessage.kt
  app/src/test/kotlin/com/wire/android/mapper/EncodedMessageContentMapperTest.kt
Labels: size/L

#1517 fix: not receiving incoming calls (RC)
  app/src/main/kotlin/com/wire/android/GlobalObserversManager.kt
  app/src/test/kotlin/com/wire/android/GlobalObserversManagerTest.kt
Labels: size/M

#1514 chore: hide share and delete logs options (develop)
  app/src/main/kotlin/com/wire/android/ui/debugscreen/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
Labels: size/M

#1513 chore: set max message length to type to 8000 characters (AR-2716) (develop)
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
Labels: size/M

#1520 fix: text field not cleared after sending message (RC)
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
Labels: size/S

#1521 fix: text field not cleared after sending message (develop)
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
Labels: size/S

#1523 fix: stuck on connecting when disabling persistent web socket (AR-3186) (RC)
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
Labels: size/XS

#1522 fix: stuck on connecting when disabling persistent web socket (AR-3186)
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
Labels: size/XS

#1525 feat: add ping sound (AR-3121)
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
Labels: size/M

#1531 fix(dev): more NavBackStackEntry crashes (hopefully) [AR-3137][AR-3193]
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelTest.kt
Labels: size/L

#1530 fix(rc): more NavBackStackEntry crashes (hopefully) [AR-3137][AR-3193]
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelTest.kt
Labels: size/L

#1529 fix: empty bottom sheet remains open after closing message details screen [AR-3145]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
Labels: size/M

#1528 feat: Notification opening for multiple accounts [AR-2261][AR-3089][AR-3161]
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/feature/AccountSwitchUseCase.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationManager.kt
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationActions.kt
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaViewModel.kt
  app/src/main/kotlin/com/wire/android/util/deeplink/DeepLinkProcessor.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/DeepLinkProcessorTest.kt
Labels: size/XL

#1532 fix: [RC] Messages sender client id column not found during migration
  app/src/main/kotlin/com/wire/android/migration/userDatabase/ScalaConversationDAO.kt
  app/src/main/kotlin/com/wire/android/migration/userDatabase/ScalaMessageDAO.kt
  app/src/main/kotlin/com/wire/android/migration/util/DBUtil.kt
Labels: size/M

#1535 fix: DeepLink handling (AR-3202)
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/L

#1534 fix: German translations for adding, removing and leaving groups [AR-3190][AR-3192]
  app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/MessagePreviewContentMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/mapper/MessagePreviewContentMapperTest.kt
Labels: size/L

#1542 fix: initialize DataDog fully before logger
  app/src/main/kotlin/com/wire/android/WireApplication.kt
Labels: size/XS

#1539 fix: audio playing design review
  app/src/main/kotlin/com/wire/android/media/audiomessage/AudioState.kt
  app/src/main/kotlin/com/wire/android/media/audiomessage/ConversationAudioMessagePlayer.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/QuotedMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/AttachmentBundle.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/audio/AudioMessageType.kt
Labels: size/L

#1544 fix: incremental sync state flow buffer being overflowed [AR-3181]
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
Labels: size/M

#1543 fix: Plurals translations
  app/src/main/kotlin/com/wire/android/mapper/MessagePreviewContentMapper.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/mapper/MessagePreviewContentMapperTest.kt
Labels: size/M

#1533 fix(RC): app stuck on migration screen when a crash happen
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/MigrationWorker.kt
Labels: size/M

#1546 fix(DEV): app stuck on migration screen when a crash happen
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/MigrationWorker.kt
Labels: size/M

#1548 fix: file restricted team sharing assets crash [AR-2061]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptionButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActionsBox.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageInputRow.kt
  app/src/main/res/values/strings.xml
Labels: size/M

#1553 fix: images sent from Xiaomi devices not returning correct mimeType [AR-3143]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/DownloadedAssetDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaViewModel.kt
  app/src/main/kotlin/com/wire/android/util/FileManager.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/home/BackupAndRestoreViewModelTest.kt
Labels: size/L

#1549 chore: increase VS-NFD banner visibility (AR-2610)
  app/src/main/kotlin/com/wire/android/ui/common/SecurityClassificationBanner.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/L

#1554 feat: support 2fa on login (AR-3088)
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginError.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailVerificationCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/verificationcode/ResendCodeText.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/verificationcode/VerificationCode.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/verificationcode/VerificationCodeState.kt
  app/src/main/kotlin/com/wire/android/ui/common/Logo.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModelTest.kt
Labels: size/XL

#1558 fix: new group guest link creation AR-3188
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupOptions/GroupOptionState.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
Labels: size/M

#1560 fix: infinite call vibration (AR-3214)
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
Labels: size/XS

#1561 fix: do not send empty 2fa code on client registration
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
Labels: size/S

#1559 feat: display clients details for other users
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/model/Device.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/model/DeviceDetailsState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileEventsHandlers.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileState.kt
Labels: size/L

#1565 fix: ANR when creating new conversation (AR-3233)
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupMetadataState.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
Labels: size/S

#1564 fix: member joined system message is missing after joining conversati…
  app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/mapper/EncodedMessageContentMapperTest.kt
Labels: size/S

#1566 fix: missing gallery edit options [AR-3180]
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/edit/MessageDetailsMenuOption.kt
  app/src/main/kotlin/com/wire/android/ui/edit/ReactionOption.kt
  app/src/main/kotlin/com/wire/android/ui/edit/ReplyMessageOption.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/asset/AssetMessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/HighLightName.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/usecase/GetMessagesForConversationUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModel.kt
  app/src/test/kotlin/com/wire/android/mapper/MessageMapperTest.kt
Labels: size/XL

#1570 chore: handle snackbar using UIText for connection requests
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationRouter.kt
Labels: size/M

#1509 chore: update translation strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/XXL, crowdin, l10n

#1578 fix: wrong German wordings [AR-3239][AR-3240]
  app/src/main/kotlin/com/wire/android/mapper/MessagePreviewContentMapper.kt
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/mapper/MessagePreviewContentMapperTest.kt
Labels: size/XXL

#1580 fix: add vibration pattern for notification channel
  app/src/main/kotlin/com/wire/android/media/CallRinger.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
Labels: size/S

#1589 fix(rc): showing attachment options on Android 8 and items ripple effect [AR-3033] [AR-3070]
  app/src/main/kotlin/com/wire/android/ui/common/AttachmentButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/KeyboardHelper.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
Labels: size/M

#1588 fix(dev): showing attachment options on Android 8 and items ripple effect [AR-3033] [AR-3070]
  app/src/main/kotlin/com/wire/android/ui/common/AttachmentButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/KeyboardHelper.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
Labels: size/M

#1577 fix(rc): message edit issues [AR-3241]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
Labels: size/M

#1576 fix(dev): message edit issues [AR-3241]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
Labels: size/M

#1594 chore: add IntelliJ's automatic copyright
  .gitignore
  .idea/copyright/profiles_settings.xml
  .idea/copyright/wire_swiss_gmbh.xml
Labels: size/XS

#1595 chore: disable back button for incoming and outgoing call screens
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallScreen.kt
Labels: size/S

#1591 fix: crash when putting an ongoing call in background (AR-3201) (RC)
  app/src/main/kotlin/com/wire/android/services/OngoingCallService.kt
  app/src/main/kotlin/com/wire/android/services/ServicesManager.kt
Labels: size/S

#1579 chore: crash the migration worker if there is an error
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/migration/MigrationReport.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/MigrationWorker.kt
Labels: size/L

#1584 feat: redo migration on app update when failure
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/migration/failure/UserMigrationStatus.kt
  app/src/main/kotlin/com/wire/android/migration/userDatabase/ShouldTriggerMigrationForUserUserCase.kt
  app/src/test/kotlin/com/wire/android/migration/ShouldTriggerMigrationForUserUserCaseTest.kt
Labels: WIP, size/L

#1606 fix: exit animation for ongoing call screen
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
Labels: size/XS

#1607 fix: check if user is logged in after migraion error
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationViewModel.kt
Labels: size/S

#1604 fix(rc): federated user data is not refreshed (AR-3249)
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileState.kt
Labels: size/XS

#1581 fix: remove read messages after migration [AR-3237]
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/test/kotlin/com/wire/android/migration/MigrationManagerTest.kt
Labels: size/M

#1598 fix: camera is turned on by default after leaving and re-joing a call (AR-3194)
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
Labels: size/M

#1601 fix: crash when putting an ongoing call in background (AR-3260) (RC)
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
Labels: size/XS

#1615 fix: crash when putting ongoing call in background (cycle-4.0)
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
Labels: size/XS

#1600 fix: crash when putting an ongoing call in background (AR-3260)
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
Labels: size/XS

#1617 fix: camera is turned on by default after leaving and re-joing a call (AR-3194) (release)
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
Labels: size/M
