Repository wireapp/wire-android, pull requests merged in 2023-09, with the labels that each got.

#2161 fix: normalize asset file name when exporting to external storage
  app/src/main/kotlin/com/wire/android/util/FileManager.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/kotlin/com/wire/android/util/StringUtil.kt
  app/src/test/kotlin/com/wire/android/util/StringUtilTest.kt
Labels: size/S

#2162 chore: update localization strings via Crowdin
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv/strings.xml
Labels: size/XS, crowdin, l10n

#2164 fix: mention highlight [WPB-3507]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mention/MemberItemToMention.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/HighLightName.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/HighLightSubtTitle.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/QueryExtension.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/DropDownMentionsSuggestions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/UiMention.kt
  app/src/main/kotlin/com/wire/android/util/QueryMatchExtractor.kt
Labels: size/L

#2138 fix: adjust transition animations according to the design documentation [WPB-1817]
  app/src/main/kotlin/com/wire/android/navigation/NavigationAnimationConfig.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationGraph.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationStyleConfig.kt
  app/src/main/kotlin/com/wire/android/navigation/TransitionAnimations.kt
  app/src/main/kotlin/com/wire/android/navigation/style/DefaultNavGraphAnimations.kt
  app/src/main/kotlin/com/wire/android/navigation/style/NavigationAnimationStyles.kt
  app/src/main/kotlin/com/wire/android/navigation/style/ScreenModeStyle.kt
  app/src/main/kotlin/com/wire/android/navigation/style/TransitionAnimations.kt
  app/src/main/kotlin/com/wire/android/navigation/style/WireDestinationStyleAnimated.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/NewConversationSearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/util/ui/ScreenSettingsUtil.kt
  app/src/main/res/values-night/colors.xml
Labels: size/XL

#2170 fix: enable translations in plurals for failed to add and failed to send messages (WPB-3788)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItemComponents.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/res/values/strings.xml
Labels: size/M

#2174 chore: upgrade hilt to use ksp
  app/build.gradle.kts
  build-logic/plugins/src/main/kotlin/HiltConventionPlugin.kt
  gradle/libs.versions.toml
Labels: size/S

#2168 fix: share text to wire (WPB-1872)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
Labels: size/L

#2169 fix(RC): adjust transition animations according to the design documentation [WPB-1817]
  app/src/main/kotlin/com/wire/android/navigation/NavigationAnimationConfig.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationGraph.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationStyleConfig.kt
  app/src/main/kotlin/com/wire/android/navigation/TransitionAnimations.kt
  app/src/main/kotlin/com/wire/android/navigation/style/DefaultNavGraphAnimations.kt
  app/src/main/kotlin/com/wire/android/navigation/style/NavigationAnimationStyles.kt
  app/src/main/kotlin/com/wire/android/navigation/style/ScreenModeStyle.kt
  app/src/main/kotlin/com/wire/android/navigation/style/TransitionAnimations.kt
  app/src/main/kotlin/com/wire/android/navigation/style/WireDestinationStyleAnimated.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/NewConversationSearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/util/ui/ScreenSettingsUtil.kt
  app/src/main/res/values-night/colors.xml
Labels: size/XL

#2179 fix: adjust message partial delivery failure and assets (WPB-4450)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
Labels: size/M

#2167 chore: update localization strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/XL, crowdin, l10n

#2182 fix: update call permission dialog copy
  app/src/main/kotlin/com/wire/android/ui/calling/common/MicrophoneBTPermissionsDeniedDialog.kt
  app/src/main/res/values/strings.xml
Labels: size/S

#2183 fix: app crash when clicking next on create account screen
  app/src/main/kotlin/com/wire/android/ui/authentication/create/common/handle/UsernameTextField.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceDialog.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/ProxyScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/AutoFillTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/restore/RestoreBackupDialogs.kt
Labels: size/L

#2181 chore: add app startup benchmark and baseline profiler (WPB-274)
  app/build.gradle.kts
  app/src/main/baseline-prof.txt
  benchmark/build.gradle.kts
  benchmark/consumer-rules.pro
  benchmark/proguard-rules.pro
  benchmark/src/androidTest/java/com/wire/benchmark/BaselineGenerator.kt
  benchmark/src/androidTest/java/com/wire/benchmark/StartupBenchmark.kt
  benchmark/src/main/AndroidManifest.xml
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
  gradle/libs.versions.toml
Labels: size/XXL

#2185 chore: update localization strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/L, crowdin, l10n

#2186 fix: app crash when clicking next on create account screen (#2183)
  app/src/main/kotlin/com/wire/android/ui/authentication/create/common/handle/UsernameTextField.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceDialog.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/ProxyScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/AutoFillTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/createPasswordProtectedGuestLink/CreatePasswordProtectedGuestLinkScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/restore/RestoreBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/joinConversation/JoinConversationViaDeepLinkDialog.kt
Labels: size/L

#2190 fix: crash related to request focus when clicking on last name EditTe…
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
Labels: size/S

#2192 fix(2fa): login button disabled after verifiction backpress [WPB-3590]
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
Labels: size/S

#2191 fix: crash related to request focus when clicking on last name EditTe…
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
Labels: size/S

#2196 chore: update localization strings via Crowdin
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-ru/strings.xml
Labels: size/S, crowdin, l10n

#2184 fix: blinking placeholder avatar on profile screen [WPB-3917]
  app/src/main/kotlin/com/wire/android/model/ImageAsset.kt
  app/src/main/kotlin/com/wire/android/model/UserAvatarData.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserConnectionStatusInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/main/kotlin/com/wire/android/util/ui/WireSessionImageLoader.kt
Labels: size/L

#2200 chore: update localization strings via Crowdin
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-tr/strings.xml
Labels: size/M, crowdin, l10n

#2194 chore: benchmark app startup with login (WPB-274)
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/AutoFillTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  benchmark/src/androidTest/java/com/wire/benchmark/StartupBenchmark.kt
  benchmark/src/androidTest/java/com/wire/benchmark/StartupBenchmarkWithLogin.kt
Labels: size/L

#2204 chore: report fully drawn (WPB-274)
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
Labels: size/XS

#2195 fix: conversation screen top bar spacing [WPB-971]
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/JoinButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/AddContactButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserStatusIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryIconButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireSecondaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireSecondaryIconButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireTertiaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireTertiaryIconButton.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItemComponents.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/createPasswordProtectedGuestLink/GeneratePasswordButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/audio/AudioMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchAllPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/GroupConversationAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/MutedConversationBadge.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/search/SearchConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioButtons.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileGroup.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsNotFoundScreen.kt
Labels: size/XL

#2221 fix(calling): scrolling the grid is not possible when every one have camera enabled (WPB-4530) (RC)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/FullScreenTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
Labels: size/S

#2220 fix(calling): scrolling the grid is not possible when every one have camera enabled (WPB-4530)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/FullScreenTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
Labels: size/S

#2222 fix: invisible buttons after changes in WireButton size parameters
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/JoinButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/AddContactButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryIconButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireSecondaryButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireSecondaryIconButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireTertiaryIconButton.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItemComponents.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/audio/AudioMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchAllPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/MutedConversationBadge.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/search/SearchConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioButtons.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileGroup.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
Labels: size/L

#2226 chore: update localization strings via Crowdin (rc)
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/XL, crowdin, l10n

#2216 feat: prevent accidental calls in large groups (WPB-4293)
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/calling/ConfirmStartCallDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreenDialogType.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/call/ConversationCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/call/ConversationCallViewState.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/call/ConversationCallViewModelTest.kt
Labels: size/L

#2211 fix: not switching to proper conversation when navigating from notification [WPB-4294]
  app/src/main/kotlin/com/wire/android/navigation/HomeDestination.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
Labels: size/XS

#2228 fix: scrolling in calling grid is not smooth (WPB-4531)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/horizentalview/CallingHorizontalView.kt
Labels: size/XS

#2230 fix: crash when opening service details screen [WPB-4586]
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallerDetails.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/banner/SecurityClassificationArgs.kt
  app/src/main/kotlin/com/wire/android/ui/common/banner/SecurityClassificationBanner.kt
  app/src/main/kotlin/com/wire/android/ui/common/banner/SecurityClassificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/banner/SecurityClassificationViewModelTest.kt
Labels: size/L

#2205 feat: add whats new section (WPB-3777)
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/navigation/HomeDestination.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/navigation/OtherDestinations.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewViewModel.kt
  app/src/main/kotlin/com/wire/android/util/DateTimeUtil.kt
  app/src/main/res/drawable/ic_star.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
  gradle/libs.versions.toml
Labels: size/XL

#2218 fix: scaffold window insets [WPB-4683]
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreatePersonalAccountOverviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/summary/CreateAccountSummaryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/CollapsingTopBarScaffold.kt
  app/src/main/kotlin/com/wire/android/ui/common/SettingUpWireScreenContent.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireBottomSheetScaffold.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupConversationNameComponent.kt
  app/src/main/kotlin/com/wire/android/ui/common/scaffold/WireScaffold.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/createPasswordProtectedGuestLink/CreatePasswordProtectedGuestLinkScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editselfdeletingmessages/EditSelfDeletingMessagesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationAllParticipantsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioComponent.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupOptions/GroupOptionsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/NewConversationSearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/about/licenses/LicensesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/displayname/ChangeDisplayNameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/email/updateEmail/ChangeEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/email/verifyEmail/VerifyEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/handle/ChangeHandleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/appsettings/networkSettings/NetworkSettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/SelfDevicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPickerState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileDetails.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsScreen.kt
Labels: size/XL

#2241 fix: memory leak related to video renderer (WPB-3953)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
Labels: size/L

#2243 feat: setup app lock screen
  app/src/main/kotlin/com/wire/android/ui/home/appLock/SetLockCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/SetLockCodeViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/SetLockScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/appLock/SetLockScreenViewModelTest.kt
Labels: size/L

#2247 chore: cleanup CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/di/accountScoped/CallsModule.kt
  app/src/main/kotlin/com/wire/android/di/accountScoped/ClientModule.kt
  app/src/main/kotlin/com/wire/android/di/accountScoped/ConnectionModule.kt
  app/src/main/kotlin/com/wire/android/di/accountScoped/ConversationModule.kt
  app/src/main/kotlin/com/wire/android/di/accountScoped/MessageModule.kt
  app/src/main/kotlin/com/wire/android/di/accountScoped/ServicesModule.kt
  app/src/main/kotlin/com/wire/android/di/accountScoped/TeamModule.kt
  app/src/main/kotlin/com/wire/android/di/accountScoped/UserModule.kt
Labels: size/XXL

#2246 fix: Self video disappears when scrolling through video grid (WPB-4651)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/FullScreenTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/SelectedParticipant.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantsTiles.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/gridview/CallingGridView.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/horizentalview/CallingHorizontalView.kt
Labels: size/L

#2244 chore: update localization strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/L, crowdin, l10n

#2249 feat: store app lock password securely [WPB-4695]
  app/src/androidTest/java/com/wire/android/datastore/EncryptionManagerTest.kt
  app/src/main/kotlin/com/wire/android/datastore/EncryptionManager.kt
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/feature/ObserveAppLockConfigUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/SetLockCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/SetLockScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsState.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/feature/ObserveAppLockConfigUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/appLock/SetLockScreenViewModelTest.kt
Labels: size/L

#2251 chore: enable penalty death on strict mode
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/ui/common/imagepreview/BulletHoleImagePreview.kt
Labels: size/M

#2248 chore: update compose to version 1.5
  app/src/beta/kotlin/com/wire/android/ExternalLoggerManager.kt
  app/src/dev/kotlin/com/wire/android/ExternalLoggerManager.kt
  app/src/internal/kotlin/com/wire/android/ExternalLoggerManager.kt
  app/src/main/kotlin/com/wire/android/navigation/OtherDestinations.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/staging/kotlin/com/wire/android/ExternalLoggerManager.kt
  build-logic/plugins/src/main/kotlin/AndroidCoordinates.kt
  gradle/libs.versions.toml
Labels: size/M

#2260 fix: max accounts dialog prevent dismiss (WPB-4818)
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/MaxAccountsReachedDialog.kt
Labels: size/XS

#2263 chore: revert changes of #2245
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/FullScreenTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/SelectedParticipant.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantsTiles.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/gridview/CallingGridView.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/horizentalview/CallingHorizontalView.kt
Labels: size/L

#2254 fix(calling): observe self camera state in full screen mode (WPB-4719)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/FullScreenTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/SelectedParticipant.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/gridview/CallingGridView.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/horizentalview/CallingHorizontalView.kt
Labels: size/S

#2267 fix: join call on back facing camera (WPB-3454)
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
Labels: size/L

#2268 fix(links): embedded links with escaped chars [e.g. plus] (WPB-4402)
  app/src/main/kotlin/com/wire/android/util/UriUtil.kt
  app/src/test/kotlin/com/wire/android/util/UriUtilTest.kt
Labels: size/S

#2265 chore: revert changes of #2246
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantsTiles.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/gridview/CallingGridView.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/horizentalview/CallingHorizontalView.kt
Labels: size/S

#2270 fix: ignore mention with negative index [WPB-4854]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/model/MessageTypesTest.kt
Labels: size/L

#2274 fix: ignore negative mention index
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
Labels: size/S

#2258 fix: blinking keyboard [WPB-4797]
  app/src/internal/kotlin/com/wire/android/ExternalLoggerManager.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/attachments/AdditionalOptionButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
  gradle/libs.versions.toml
Labels: size/L

#2279 fix: audio messages partial delivery missing (WPB-4886)
  app/src/main/kotlin/com/wire/android/mapper/RegularMessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
Labels: size/M

#2282 feat: [RC] feature flag passowrd guest link (WPB-1531)
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/CreateGuestLinkBottomSheet.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/PasswordProtectedLinkBanner.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/createPasswordProtectedGuestLink/GeneratePasswordButton.kt
  app/src/main/kotlin/com/wire/android/ui/joinConversation/JoinConversationViaDeepLinkDialog.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessViewModelTest.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
Labels: WIP, size/L, DO NOT MERGE

#2285 feat: add unarchiving logic [WPB-4435][WPB-4436]
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetState.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeSnackbarState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/menu/GroupConversationDetailsBottomSheetEventsHandler.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/GroupDialogState.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileEventsHandlers.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileInfoMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/bottomsheet/OtherUserProfileBottomSheet.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
Labels: size/L
