Repository wireapp/wire-android, pull requests merged in 2023-08, with the labels that each got.

#2034 fix: create conversation button crash [WPB-3538]
  app/src/main/kotlin/com/wire/android/ui/common/button/WireButton.kt
Labels: size/S

#2029 fix: Audio Message not being send with correct mimeType (WPB-3534)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/AudioMediaRecorder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
  app/src/main/kotlin/com/wire/android/util/FileManager.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelTest.kt
Labels: size/L

#2033 chore: update resaca to 2.4.6
  gradle/libs.versions.toml
Labels: size/XS

#2031 fix: inconsistent audio message length [WPB-3334]
  app/src/main/kotlin/com/wire/android/media/audiomessage/AudioState.kt
  app/src/main/kotlin/com/wire/android/media/audiomessage/ConversationAudioMessagePlayer.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
Labels: size/M

#2028 fix: show unblock user confirmation dialog (WPB-2427)
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
Labels: size/M

#2043 fix: line break unhandled event (WPB-3320)
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownComposer.kt
  app/src/main/kotlin/com/wire/android/util/ui/StyledStringUtil.kt
Labels: size/XS

#2050 chore: replace deprecated pager
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantsTiles.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/VerticalPagerIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireTabRow.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  gradle/libs.versions.toml
Labels: size/L

#2023 chore: simplify passing arguments to scoped ViewModels
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/di/ViewModelScoped.kt
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButtonArgs.kt
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButtonViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/CompositeMessageViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/CompositeMessageArgs.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/test/kotlin/com/wire/android/config/ScopedArgsTestExtension.kt
  app/src/test/kotlin/com/wire/android/ui/connection/ConnectionActionButtonViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/CompositeMessageViewModelTest.kt
  gradle/libs.versions.toml
Labels: size/L

#2053 fix: mention crashing on select after sending message
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerStateHolderTest.kt
Labels: size/XS

#2051 fix: duplicated Classification label (WPB-3626)
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallerDetails.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/SecurityClassificationBanner.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerClassifiedBanner.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
Labels: size/L

#2056 fix: Keep screen active when user is recording audio (WPB-3479)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioButtons.kt
Labels: size/S

#2062 fix: display learn more federation link always when error expanded (WPB-3391)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItemComponents.kt
Labels: size/XS

#2060 feat(CI): display conflicts on cherry-pick action PRs
  .github/workflows/cherry-pick-rc-to-develop.yml
Labels: size/S

#2052 fix: duplicated Classification label (RC) (WPB-3626)
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallerDetails.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/SecurityClassificationBanner.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerClassifiedBanner.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
Labels: size/L

#2069 fix: join call button height not matching design
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/JoinButton.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/XS

#2076 fix(rc-message): handle invalid embedded link in messages (WPB-3554)
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/InvalidLinkDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownParagraph.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownText.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/NodeData.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#2073 fix: attachment options in chat not working on android 14 (WPB-1846)
  app/src/main/kotlin/com/wire/android/ui/common/KeyboardHelper.kt
Labels: size/XS

#2057 fix: crash when stopping OngoingCallService [WPB-2320] [WPB-1836] [WPB-3457]
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/services/OngoingCallService.kt
  app/src/main/kotlin/com/wire/android/services/ServicesManager.kt
  app/src/test/kotlin/com/wire/android/notification/CallNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/services/ServicesManagerTest.kt
Labels: size/XXL

#2085 fix: adjust call join button dimensions to spec
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/JoinButton.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/S

#2092 fix: app crash when download asset
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
Labels: size/XS

#2079 feat: add more message status icons
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageStatusIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/test/kotlin/com/wire/android/framework/TestMessage.kt
  app/src/test/kotlin/com/wire/android/mapper/MessageMapperTest.kt
Labels: size/L

#2096 fix: remove You/null from self deleting notification (WPB-3553)
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
  app/src/main/res/values/strings.xml
Labels: size/S

#2102 fix: change the connectivity message (RC)
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
  app/src/main/res/values/strings.xml
Labels: size/M

#2105 feat: adding participants adjustment strings and simplified (WPB-2297)
  app/src/main/kotlin/com/wire/android/mapper/SystemMessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/res/values/strings.xml
Labels: size/M

#2107 fix(uri-util): refactor uri scheme checker (WPB-3554) (#2090)
  app/src/main/kotlin/com/wire/android/util/UriUtil.kt
  app/src/test/kotlin/com/wire/android/TestUtil.kt
  app/src/test/kotlin/com/wire/android/util/UriUtilTest.kt
Labels: size/M

#2106 fix(CD): generate changelog GH action fails when tagging from same hash
  .github/workflows/generate-changelog.yml
Labels: size/XS

#2109 fix: release action by grepping last matched result on tags
  .github/workflows/generate-changelog.yml
Labels: size/XS

#2095 fix: use correct colors for the import send button
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/SelectParticipantsButtonsRow.kt
Labels: size/XS

#2108 fix: remove conversations title on import media screen [WPB-1860]
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationFolder.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/util/extension/LazyListScope.kt
Labels: size/M

#2113 fix(cherry-pick): Unblock button is no longer visible when we block someone (WPB-2427) (RC)
  app/src/main/kotlin/com/wire/android/model/ActionableState.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButtonViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/connection/ConnectionActionButtonViewModelTest.kt
Labels: size/L

#2114 fix(cherry-pick): show unblock user confirmation dialog (WPB-2427) (RC)
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
Labels: size/M

#2125 fix: missing username and avatar for first message after creating goup [WPB-3557]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/AuthorHeaderHelper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/AuthorHeaderHelperTest.kt
Labels: size/L

#2130 fix: alignment of reactions [AR-3874]
  app/src/main/kotlin/com/wire/android/ui/edit/ReactionOption.kt
Labels: size/S

#2128 feat(debug): migration progress [WPB-3523]
  app/src/main/kotlin/com/wire/android/mapper/UIParticipantMapper.kt
  app/src/main/kotlin/com/wire/android/ui/common/StatusBox.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/ConversationParticipantItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipants.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantsState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/model/ConversationParticipantsData.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/model/UIParticipant.kt
Labels: size/L

#2123 chore: bump compose-activity dependency from 1.6.1 to 1.7.2
  gradle/libs.versions.toml
Labels: size/XS

#2101 feat: show connecting indicator if user has bad/lost connection during a call (WPB-1125)
  app/src/main/kotlin/com/wire/android/mapper/UICallParticipantMapper.kt
  app/src/main/kotlin/com/wire/android/ui/calling/model/UICallParticipant.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/gridview/CallingGridView.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/horizentalview/CallingHorizontalView.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/mapper/UICallParticipantMapperTest.kt
  app/src/test/kotlin/com/wire/android/ui/calling/OngoingCallViewModelTest.kt
Labels: size/L

#2140 fix: missed activity icon size (WPB-3896)
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/EventBadge.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/MutedConversationBadge.kt
Labels: size/M

#2139 fix: Always allow avatar changeing [WPB-2247]
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
Labels: size/S

#2137 chore: config crowdin action
  .github/workflows/localization-crowdin-updater.yml
  README.md
  crowdin.yml
Labels: size/M

#2151 chore: cherry pick action to update strings from crowdin
  .github/workflows/localization-crowdin-updater.yml
  README.md
  crowdin.yml
Labels: size/M

#2153 chore(reactions): remove "More coming soon" label [WPB-4328]
  app/src/main/kotlin/com/wire/android/ui/edit/ReactionOption.kt
Labels: size/XS
