Repository wireapp/wire-android, pull requests merged in 2023-02, with the labels that each got.

#1395 feat: edit message menu option and handling its UI state [AR-2717]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActionsBox.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageInputRow.kt
  app/src/main/kotlin/com/wire/android/util/debug/FeatureVisibilityFlags.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInnerStateTest.kt
Labels: size/L

#1400 chore: update translation strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/XXL, crowdin, l10n

#1386 fix: saving files to downloads folder and empty asset names on older Androids [AR-2985] [AR-2984]
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/ui/home/conversations/DownloadedAssetDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModel.kt
  app/src/main/kotlin/com/wire/android/util/FileManager.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/kotlin/com/wire/android/util/permission/WriteStorageRequestFlow.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/FileUtilTest.kt
Labels: size/L

#1401 feat: remove devices from settings screen (AR-2963)
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/SelfDevicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/SelfDevicesViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/settings/devices/SelfDevicesViewModelTest.kt
Labels: size/L

#1417 fix: crash when starting a foreground service(AR-3028)
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
  app/src/main/kotlin/com/wire/android/services/OngoingCallService.kt
  app/src/main/kotlin/com/wire/android/workmanager/WireWorkerFactory.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/MigrationWorker.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/NotificationFetchWorker.kt
Labels: size/M

#1419 fix: [RC] Open conversation on notification tap (AR-2999)
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/notification/Models.kt
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/util/deeplink/DeepLinkProcessor.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/DeepLinkProcessorTest.kt
Labels: size/L

#1418 fix: crash when starting a foreground service (develop)
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
  app/src/main/kotlin/com/wire/android/services/OngoingCallService.kt
  app/src/main/kotlin/com/wire/android/workmanager/WireWorkerFactory.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/MigrationWorker.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/NotificationFetchWorker.kt
Labels: size/M

#1420 fix: DEV open conversation on notification tap
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/util/deeplink/DeepLinkProcessor.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/DeepLinkProcessorTest.kt
Labels: size/L

#1416 feat: export media [AR-2445][AR-3008]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModel.kt
  app/src/main/res/drawable/ic_share_file.xml
  app/src/main/res/values/strings.xml
Labels: size/M

#1294 feat: Join a conversation with a guest link [AR-2703]
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/joinConversation/JoinConversationViaDeepLinkDialog.kt
  app/src/main/kotlin/com/wire/android/util/deeplink/DeepLinkProcessor.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/XL

#1422 fix(rc): perform migration right after the app update [AR-3075]
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/GlobalObserversManager.kt
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/migration/UpdateReceiver.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/MigrationWorker.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/NotificationFetchWorker.kt
  app/src/test/kotlin/com/wire/android/GlobalObserversManagerTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/XL

#1424 fix(dev): perform migration right after the app update [AR-3075]
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/GlobalObserversManager.kt
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/migration/UpdateReceiver.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/MigrationWorker.kt
  app/src/test/kotlin/com/wire/android/GlobalObserversManagerTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/XL

#1432 fix: removed english strings to use source strings as default ones
  app/src/main/res/values-en/strings.xml
Labels: size/XL

#1429 fix(calling): can't turn on camera in preview screen (AR-3057)
  app/src/main/kotlin/com/wire/android/ui/calling/CallState.kt
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallVideoPreview.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
Labels: size/M

#1434 fix: notification duplicates (AR-3016)
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
Labels: size/M

#1435 fix: (dev) call hang up button from notification (AR-2982)
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/EndOngoingCallReceiver.kt
Labels: size/S

#1442 fix: animation not smooth when expanding a system message
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
Labels: size/M

#1440 refactor: move logging flag to the ar
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/debugscreen/DebugScreenViewModel.kt
Labels: size/M

#1438 fix: not receiving messages on second account [AR-2867]
  app/src/main/kotlin/com/wire/android/util/lifecycle/ConnectionPolicyManager.kt
  app/src/test/kotlin/com/wire/android/util/lifecycle/ConnectionPolicyManagerTest.kt
Labels: size/M

#1447 fix(mls): pick selected value in dropdown after getting back to the screen
  app/src/main/kotlin/com/wire/android/ui/common/WireDropDown.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupConversationNameComponent.kt
Labels: size/M

#1449 fix(mls): pick selected value in dropdown after getting back to the s…
  app/src/main/kotlin/com/wire/android/ui/common/WireDropDown.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupConversationNameComponent.kt
Labels: size/M

#1450 fix: Missed notifications on spamming (AR-2867)
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
Labels: size/L

#1443 chore: update firebase Bom version
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#1453 fix(dev): saved files are not visible in downloads folder on lower Androids [AR-3120]
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
Labels: size/S

#1451 fix: [DEV] Missed notifications on spamming
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
Labels: size/L

#1452 fix(rc): saved files are not visible in downloads folder on lower Androids [AR-3120]
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
Labels: size/S

#1381 feat: asset download retry when coil fails
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/di/ImageLoadingModule.kt
  app/src/main/kotlin/com/wire/android/model/ImageAsset.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/util/ui/AssetImageFetcher.kt
  app/src/main/kotlin/com/wire/android/util/ui/WireSessionImageLoader.kt
  app/src/test/kotlin/com/wire/android/util/ui/AssetImageFetcherTest.kt
Labels: size/L

#1457 fix: not receiving notifications on second account [AR-2867]
  app/src/main/kotlin/com/wire/android/util/lifecycle/ConnectionPolicyManager.kt
  app/src/test/kotlin/com/wire/android/util/lifecycle/ConnectionPolicyManagerTest.kt
Labels: size/M

#1465 fix: [RC] check if the logging file exists before clearing its content
  app/src/main/kotlin/com/wire/android/util/LogFileWriter.kt
Labels: size/S

#1467 feat: update compose libraries
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/XS

#1464 fix: [DEV] clicking delete log files, crashing the app if logs were never enabled
  app/src/main/kotlin/com/wire/android/util/LogFileWriter.kt
Labels: size/S

#1466 feat: update compose libraries [AR-3137]
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/S

#1455 fix: request video steam for screen share (AR-3132) (RC)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantsTiles.kt
  app/src/test/kotlin/com/wire/android/ui/calling/OngoingCallViewModelTest.kt
Labels: size/M

#1454 fix: request video steam for screen sharing ( AR-3132)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantsTiles.kt
  app/src/test/kotlin/com/wire/android/ui/calling/OngoingCallViewModelTest.kt
Labels: size/M

#1437 feat: create a guest link - Part 1 : Move guest access config to separate screen (AR-2706)
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessParams.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/GuestOption.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsState.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessViewModelTest.kt
Labels: size/XL

#1474 refactor: [RC] migrate messages per conversation instead of all at once
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/migration/feature/MigrateMessagesUseCase.kt
Labels: size/M

#1479 chore: add debug setting for enabling encrypted proteus storage
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  app/src/main/kotlin/com/wire/android/ui/debugscreen/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/debugscreen/DebugScreenViewModel.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#1481 style(system-message): fix wording in conversation history message
  app/src/main/res/values/strings.xml
Labels: size/XS

#1483 fix: [RC] crash when there is a session reset system message with device s…
  app/src/main/res/values-de/strings.xml
Labels: size/XS

#1484 fix: [DEV] crash when there is a session reset system message with device s…
  app/src/main/res/values-de/strings.xml
Labels: size/XS

#1476 chore(rc): add tracking compose screens in datadog
  app/build.gradle.kts
  app/src/beta/kotlin/com/wire/android/ExternalLoggerManager.kt
  app/src/dev/kotlin/com/wire/android/ExternalLoggerManager.kt
  app/src/internal/kotlin/com/wire/android/ExternalLoggerManager.kt
  app/src/main/kotlin/com/wire/android/navigation/HomeNavigation.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/team/CreateTeamNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/team/CreateTeamScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/NewConversationNavigationItem.kt
  app/src/staging/kotlin/com/wire/android/ExternalLoggerManager.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/L

#1475 chore(dev): add tracking compose screens in datadog
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/navigation/HomeNavigation.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/team/CreateTeamNavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/team/CreateTeamScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/NewConversationNavigationItem.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/L

#1486 fix: [RC] self user is missing when scala DB have no domain
  app/src/main/kotlin/com/wire/android/migration/feature/MigrateUsersUseCase.kt
Labels: size/XS

#1477 fix: initial status bar color
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBar.kt
Labels: size/XS

#1491 chore: reduce StrictMode detection scope
  app/src/main/kotlin/com/wire/android/WireApplication.kt
Labels: size/XS

#1494 feat: Archive results of unit and integration tests (SQPIT-1621)
  Jenkinsfile
Labels: size/XS

#1497 fix: Fix crash when no logged in user
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/FeatureFlagState.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
Labels: size/L

#1503 refactor: [RC] start migration automatically if it was done in and older version and add manual trigger
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/ui/debugscreen/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/debugscreen/DebugScreenViewModel.kt
  app/src/main/res/values/strings.xml
Labels: size/M

#1504 fix: [RC] unresolved reference on prod builds
  app/src/beta/kotlin/com/wire/android/navigation/TrackingNavControler.kt
  app/src/dev/kotlin/com/wire/android/navigation/TrackingNavControler.kt
  app/src/internal/kotlin/com/wire/android/navigation/TrackingNavControler.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/navigation/TrackingNavControler.kt
  app/src/prod/kotlin/com/wire/android/navigation/TrackingNavControler.kt
  app/src/staging/kotlin/com/wire/android/navigation/TrackingNavControler.kt
Labels: size/L

#1500 fix: wrong wording for enable receipts in German [AR-2980]
  app/src/main/kotlin/com/wire/android/mapper/MessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreViewModel.kt
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/M

#1508 fix: [RC] migration after update is not starting after update from 4.0.1
  app/src/main/kotlin/com/wire/android/migration/userDatabase/ShouldTriggerMigrationForUserUserCase.kt
  app/src/test/kotlin/com/wire/android/migration/ShouldTriggerMigrationForUserUserCaseTest.kt
Labels: size/M

#1505 fix: [DEV] unresolved reference on prod builds
  app/src/beta/kotlin/com/wire/android/navigation/TrackingNavController.kt
  app/src/dev/kotlin/com/wire/android/navigation/TrackingNavController.kt
  app/src/internal/kotlin/com/wire/android/navigation/TrackingNavController.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/navigation/TrackingNavController.kt
  app/src/prod/kotlin/com/wire/android/navigation/TrackingNavController.kt
  app/src/staging/kotlin/com/wire/android/navigation/TrackingNavController.kt
Labels: size/L

#1506 chore: [DEV] production build
  Jenkinsfile
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
Labels: size/M

#1511 fix: last remaining issues from import media features [AR-2445][AR-2198][AR-2198]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaViewModel.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/res/values/strings.xml
Labels: size/M
