Repository wireapp/wire-android, pull requests merged in 2023-01, with the labels that each got.

#1275 fix: snack bar not displayed after resetting session (AR-2885)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewState.kt
Labels: size/S

#1274 chore(notification): remove call action button (AR-2896)
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationActions.kt
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/M

#1277 fix: Crash when restoring backup after failed attempt [AR-2891]
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreViewModel.kt
Labels: size/M

#1273 fix: Open conversation menu for user that i have no conversation with (AR-2880)
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileEventsHandlers.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/bottomsheet/OtherUserBottomSheetState.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileViewModelArrangement.kt
Labels: size/L

#1282 chore: configure detekt to include formatting and wire rules (AR-2878)
  app/build.gradle.kts
  app/detekt-baseline.xml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/IncludeGitBuildTask.kt
  buildSrc/src/main/kotlin/ProjectExtensions.kt
  buildSrc/src/main/kotlin/scripts/quality.gradle.kts
  config/detekt/baseline.xml
  config/detekt/detekt.yml
Labels: size/XXL

#1278 fix: After hanging up the call from notification the ongoing call screen is still visible (AR-2890)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallViewModel.kt
Labels: size/XS

#1288 chore: prevent lock screen when there is a call (AR-2846)
  app/src/main/kotlin/com/wire/android/util/ui/ScreenSettingsUtil.kt
Labels: size/XS

#1284 feat: handle received data actions [AR-2901]
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/DialogStates.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/FileSharingRestrictedDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/FeatureFlagState.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportedMediaTypes.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/kotlin/com/wire/android/util/extension/Context.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#1292 fix: notifications being handled on the main thread (AR-2924)
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/test/kotlin/com/wire/android/common/TestsCommon.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
Labels: size/L

#1293 fix: (RC) notifications being handled on the main thread (AR-2924)
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/test/kotlin/com/wire/android/common/TestsCommon.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
Labels: size/L

#1295 fix(notification): refactor connections notifications to prevent ANR (AR-2898)
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
Labels: size/M

#1285 fix: Doubled notification for attachment message (AR-2894)
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/L

#1286 chore: Enable strict mode (ACOL-72)
  app/src/main/kotlin/com/wire/android/WireApplication.kt
Labels: size/S

#1301 chore: [DO NOT MERGE] Internal
  Jenkinsfile
  buildSrc/src/main/kotlin/FeatureFlags.kt
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
  default.json
Labels: size/XL, DO NOT MERGE

#1302 chore: Internal build flavor
  Jenkinsfile
  buildSrc/src/main/kotlin/FeatureFlags.kt
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
  default.json
Labels: size/L

#890 ci: fix kalium reference check job syntax
  .github/workflows/check-kalium-commitish.yml
Labels: size/M

#1307 chore: Enbale strict mode (RC)
  app/src/main/kotlin/com/wire/android/WireApplication.kt
Labels: size/S

#1305 chore: build staging flavor when pushing to develop
  Jenkinsfile
Labels: size/XS

#1306 chore: clean up default.json
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  buildSrc/src/main/kotlin/FeatureConfigs.kt
  default.json
Labels: size/L

#1312 chore: update secondaryText color in Dark mode (AR-2919)
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/XS

#1311 feat: user display name change (AR-1068)
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/AccountDetailsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/displayname/ChangeDisplayNameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/displayname/ChangeDisplayNameViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/displayname/DisplayNameState.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/displayname/ChangeDisplayNameViewModelTest.kt
  config/detekt/detekt.yml
Labels: size/XL

#1314 chore: update translation strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/XXL, crowdin, l10n

#1315 chore: adjust test coverage settings
  buildSrc/src/main/kotlin/scripts/quality.gradle.kts
  codecov.yml
Labels: enhancement, size/M, proof of concept

#1319 chore: set development_api_enabled to true for staging builds
  default.json
Labels: size/XS

#1323 chore: update translation strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/XXL, crowdin, l10n

#1321 fix: Updated translations issues
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupOptions/GroupOptionsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
Labels: size/XL

#1329 chore: update translation strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/XL, crowdin, l10n

#1333 fix(mls): disable mls everywhere and only considering the BE flags (AR-2653)
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupConversationNameComponent.kt
  default.json
Labels: size/S

#1338 fix: dark links and mentions popup [AR-2935] [AR-2932]
  app/src/main/kotlin/com/wire/android/ui/common/LinkifyText.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/DropDownMentionsSuggestions.kt
Labels: size/S

#1337 fix: dark mode mentions and links [AR-2932] [AR-2935]
  app/src/main/kotlin/com/wire/android/ui/common/LinkifyText.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/DropDownMentionsSuggestions.kt
Labels: size/S

#1341 chore: support beta build configs
  buildSrc/src/main/kotlin/FeatureConfigs.kt
Labels: size/XS

#1331 chore: [RC] cleanup default.json
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  buildSrc/src/main/kotlin/FeatureConfigs.kt
  default.json
Labels: size/M, DO NOT MERGE

#1340 feat: horizontal pager solution to paddings and scroll (AR-2949)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/asset/AssetMessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
Labels: size/L

#1344 chore: support beta build
  buildSrc/src/main/kotlin/FeatureConfigs.kt
Labels: size/XS

#1349 fix: Add missing parameter for conversation read receipt mode changed
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
Labels: size/XS

#1353 chore: Assemble staging flavour for PRs
  Jenkinsfile
Labels: size/XS

#1351 fix(rc): broken session after migration [AR-2941]
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/migration/feature/MigrateActiveAccountsUseCase.kt
  app/src/main/kotlin/com/wire/android/migration/feature/MigrateClientsDataUseCase.kt
  app/src/main/kotlin/com/wire/android/migration/preference/ScalaBackendPreferences.kt
  app/src/main/kotlin/com/wire/android/migration/userDatabase/ScalaMessageDAO.kt
  app/src/test/kotlin/com/wire/android/migration/MigrateClientsDataUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/migration/ScalaBackendPreferencesTest.kt
Labels: size/L

#1352 fix(dev): broken session after migration [AR-2941]
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/migration/feature/MigrateActiveAccountsUseCase.kt
  app/src/main/kotlin/com/wire/android/migration/feature/MigrateClientsDataUseCase.kt
  app/src/main/kotlin/com/wire/android/migration/preference/ScalaBackendPreferences.kt
  app/src/main/kotlin/com/wire/android/migration/userDatabase/ScalaMessageDAO.kt
  app/src/test/kotlin/com/wire/android/migration/MigrateClientsDataUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/migration/ScalaBackendPreferencesTest.kt
Labels: size/L

#1354 fix(mls): disable mls everywhere and only considering the BE flags (AR-2653)
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupConversationNameComponent.kt
Labels: size/S

#1357 chore: revert me - disable minifier
  app/src/main/AndroidManifest.xml
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
Labels: size/S

#1359 chore: [RC] Internal build flavor (#1302)
  Jenkinsfile
  buildSrc/src/main/kotlin/FeatureFlags.kt
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
Labels: size/M

#1366 fix: exit backup dialog crash [AR-2987]
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreViewModel.kt
Labels: size/XS

#1368 ci: switch ui and unit tests to buildjet
  .github/workflows/gradle-run-ui-tests.yml
  .github/workflows/gradle-run-unit-tests.yml
Labels: size/M

#1369 ci: switch ui and unit tests to buildjet (#1368)
  .github/workflows/gradle-run-ui-tests.yml
  .github/workflows/gradle-run-unit-tests.yml
Labels: size/M

#1370 ci: run tests only after deteket succeeds
  .github/workflows/codestyle.yml
  .github/workflows/gradle-run-ui-tests.yml
  .github/workflows/gradle-run-unit-tests.yml
Labels: size/S

#1374 fix: dark mode system messages icons (rc)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/res/drawable/ic_ping.xml
Labels: size/S

#1375 fix: apply colors to system msg icons for dark mode (dev)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/res/drawable/ic_ping.xml
Labels: size/M

#1371 ci: build & attach APK to PR
  .github/workflows/gradle-run-unit-tests.yml
  gradle.properties
Labels: size/M

#1378 ci: remove build on push and beef up runners
  .github/workflows/codestyle.yml
  .github/workflows/gradle-run-ui-tests.yml
  .github/workflows/gradle-run-unit-tests.yml
Labels: size/S

#1393 fix: missing proguard rules
  app/proguard-rules.pro
Labels: size/S

#1391 chore: update translation strings via Crowdin
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogs.kt
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/L, crowdin, l10n

#1390 fix: update strings to match state in `develop` branch
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupOptions/GroupOptionsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values/arrays.xml
  app/src/main/res/values/strings.xml
Labels: size/XL

#1396 chore: update translation strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/M, crowdin, l10n

#1397 fix(rc): handle migration progress and network errors [AR-3013]
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/ui/common/SettingUpWireScreenContent.kt
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationState.kt
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/MigrationWorker.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#1398 fix(dev): handle migration progress and network errors [AR-3013]
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/ui/common/SettingUpWireScreenContent.kt
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationState.kt
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/MigrationWorker.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#1376 chore: update some used dependencies
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/S

#1403 fix: skip annotations with negative offsets
  app/src/main/kotlin/com/wire/android/ui/common/LinkifyText.kt
Labels: size/XS

#1377 fix: mention suggestion list does not follow cursor position (AR-2936)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/DropDownMentionsSuggestions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
Labels: size/M

#1409 fix: support prod release
  app/src/main/AndroidManifest.xml
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
Labels: size/M
