Repository wireapp/wire-android, pull requests merged in 2023-12, with the labels that each got.

#2487 fix: display the app lock enforce dialogue when it is enforced but no…
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
Labels: size/M

#2493 fix: Second search query not updating and infinite loading icon (WPB-5744)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesViewModel.kt
Labels: size/XS

#2492 fix: Mute Icon blocks click event
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/MutedConversationBadge.kt
Labels: size/XS

#2482 fix: app lock not disabled when team enforce is lifted (#2466)
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/feature/AppLockSource.kt
  app/src/main/kotlin/com/wire/android/feature/DisableAppLockUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/set/SetLockScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/test/kotlin/com/wire/android/feature/DisableAppLockUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/appLock/set/SetLockScreenViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
Labels: size/L

#2499 fix: App lock does not show up after fresh install (WPB-5609)
  app/src/main/kotlin/com/wire/android/feature/ObserveAppLockConfigUseCase.kt
  app/src/test/kotlin/com/wire/android/feature/ObserveAppLockConfigUseCaseTest.kt
Labels: size/M

#2491 fix: display the app lock enforce dialogue when it is enforced but no…
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
Labels: size/M, cherry-pick

#2508 feat: Remove nearby devices permission for calling (WPB-4583)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/ui/calling/common/MicrophonePermissionDeniedDialog.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/JoinButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/StartCallButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/util/permission/CallingRecordAudioRequestFlow.kt
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/L

#2512 fix: set cert pinning for all app flavours
  default.json
Labels: size/S

#2516 fix: breaking lines title location (WPB-5483)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/location/LocationMessageType.kt
Labels: size/S

#2517 fix: app not locked after timeout when screen turned off [WPB-5682] [WPB-5832]
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/LockCodeTimeManager.kt
  app/src/test/kotlin/com/wire/android/ui/home/appLock/LockCodeTimeManagerTest.kt
Labels: size/M

#2513 fix: set cert pinning for all app flavours
  default.json
Labels: size/S, cherry-pick

#2507 feat: media files tab - Part 1 (WPB-5378)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/ConversationMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/EmptyMediaContentScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/ImageAssetsContent.kt
  app/src/main/res/values/strings.xml
Labels: size/XXL, DO NOT MERGE

#2514 feat: Use enroll mls use case (WPB-5756)
  app/src/main/kotlin/com/wire/android/feature/e2ei/GetE2EICertificateUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/home/E2EIDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/FeatureFlagState.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/EndToEndIdentityCertificateItem.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/model/DeviceDetailsState.kt
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModelTest.kt
Labels: size/L

#2521 fix: app not locked after timeout when screen turned off [WPB-5682] [WPB-5832]
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/LockCodeTimeManager.kt
  app/src/test/kotlin/com/wire/android/ui/home/appLock/LockCodeTimeManagerTest.kt
Labels: size/M, cherry-pick

#2524 fix: wrong url for conversation creation in conflicting backends case (WPB-5014)
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/CreateGroupErrorDialog.kt
Labels: size/XS

#2526 fix: dialog for max accounts reached (WPB-1862)
  app/src/main/kotlin/com/wire/android/ui/WireActivityDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/MaxAccountsReachedDialog.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/MaxAccountReachedDialog.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#2527 chore: update localization strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/XXL, crowdin, l10n

#2529 feat: video call icon [WPB-3667]
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/StartCallButton.kt
  app/src/main/res/drawable/ic_phone.xml
  app/src/main/res/drawable/ic_video_call.xml
Labels: size/M

#2530 fix: Remove reportDrawnWhen api due to crash on Android 9
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
Labels: size/XS

#2537 fix: Show verification icons in Calls flow (WPB-5792)
  app/src/main/kotlin/com/wire/android/ui/calling/CallState.kt
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallerDetails.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/VerifiedIcons.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
Labels: size/L

#2540 fix: enabling app lock manually displays the dialog turn off (#2454)
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsScreen.kt
Labels: size/S

#2533 fix: Remove reportDrawnWhen api due to crash on Android 9
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
Labels: size/XS, cherry-pick

#2545 fix: Hiding E2EI dialogs on logout
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
Labels: size/L

#2548 chore: update localization strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/L, crowdin, l10n

#2551 fix: reactions padding [WPB-5855]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownParagraph.kt
Labels: size/XS

#2553 fix: message item long tap action [WPB-5952]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
Labels: size/XS

#2550 fix: focus input after rich text option [WPB-4254]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
Labels: size/XS

#2554 feat: scrollable dialogs [WPB-1681]
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
Labels: size/XS
