Repository wireapp/wire-android, pull requests merged in 2023-07, with the labels that each got.

#1909 chore: fix wrong logic test
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModelTest.kt
Labels: size/M

#1902 fix: correct sizing of images in replies WPB-1864
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/QuotedMessage.kt
Labels: size/L

#1912 fix: properly map flowStatus for decryption failures WPB-2428
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/test/kotlin/com/wire/android/framework/TestMessage.kt
  app/src/test/kotlin/com/wire/android/mapper/MessageMapperTest.kt
Labels: size/M

#1906 feat(RC): SSO email login
  .gitignore
  app/src/main/kotlin/com/wire/android/di/AuthServerConfigProvider.kt
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/common/CreateAccountBaseViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/personalaccount/CreatePersonalAccountViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/team/CreateTeamViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/MicrophoneButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/CustomBEDeeplinkDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/CustomServerDialog.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/LoginViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModelTest.kt
Labels: size/XL

#1908 feat: licenses screen design update
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/about/licenses/LicenseDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/about/licenses/LicensesItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/about/licenses/LicensesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/about/licenses/LicensesState.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/about/licenses/LicensesViewModel.kt
  app/src/main/res/values/strings.xml
Labels: size/L

#1910 fix: message timer counts down before message is sent #1895
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
Labels: size/XS

#1918 fix: crash when web client send message with broken mentions [WPB-3044]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
Labels: size/S

#1921 feat: save backup file locally [WPB-1827] [WPB-762]
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreState.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogFlow.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/util/FileManager.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/kotlin/com/wire/android/util/permission/CreateFileRequestFlow.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/settings/home/BackupAndRestoreViewModelTest.kt
Labels: size/L

#1880 refactor: message composer
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetState.kt
  app/src/main/kotlin/com/wire/android/ui/common/button/WireSecondaryIconButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/FeatureFlagState.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editselfdeletingmessages/EditSelfDeletingMessagesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editselfdeletingmessages/EditSelfDeletingMessagesState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editselfdeletingmessages/EditSelfDeletingMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/EditMessageBundle.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/SendMessageBundle.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/selfdeletion/SelfDeletionMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/selfdeletion/SelfDeletionMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptionButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AttachmentOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/BlockedUserComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/DeletedUserComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActionsBox.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposeActions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageInputRow.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageSendActions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/RichTextOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/SelfDeletionDuration.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/UiMention.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/AdditionalOptionMenuState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposeInputState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/restore/RestoreBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
  app/src/main/kotlin/com/wire/android/util/ui/KeyboardHeight.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/editselfdeletingmessages/EditSelfDeletingMessagesViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerStateHolderTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerStateTest.kt
Labels: size/XXL

#1914 feat(calling): end call on member leave or conversation deleted (WPB-2955)
  app/src/main/kotlin/com/wire/android/GlobalObserversManager.kt
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/call/ConversationCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/call/ConversationCallViewModelTest.kt
Labels: size/M

#1928 ci: support PRs from forks
  .github/workflows/gradle-run-unit-tests.yml
  .github/workflows/jira-lint-and-link.yml
  .github/workflows/pr-author-assigner.yml
  .github/workflows/publish-test-results.yml
  .github/workflows/semantic-commit-lint.yml
Labels: size/L

#1932 fix: update copy for delete account dialog
  app/src/main/res/values/strings.xml
Labels: size/XS

#1930 fix: missing self deleting content description
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposeActions.kt
Labels: size/XS

#1931 ci: disable dev builds when pushing to dev and separate the by-branch builds
  AR-builder.groovy
  Jenkinsfile
Labels: size/S

#1929 feat: send self deleting pings and clean up
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editselfdeletingmessages/EditSelfDeletingMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/selfdeletion/SelfDeletionMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposeInputState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerState.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/SelectParticipantsButtonsRow.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelTest.kt
Labels: size/M

#1942 fix: make the full text visible in the wire labeled checkbox
  app/src/main/kotlin/com/wire/android/ui/common/WireLabelledCheckbox.kt
Labels: size/XS

#1945 fix: backup dialog can be dismissed
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/CustomServerDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/restore/RestoreBackupDialogs.kt
Labels: size/M

#1917 feat: sending audio message (WPB-252)
  app/src/main/kotlin/com/wire/android/media/audiomessage/AudioState.kt
  app/src/main/kotlin/com/wire/android/media/audiomessage/RecordAudioMessagePlayer.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/audio/AudioMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AttachmentOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/AudioMediaRecorder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioButtons.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioComponent.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioInfoMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordedAudioDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/AdditionalOptionMenuState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
  app/src/main/kotlin/com/wire/android/util/debug/FeatureVisibilityFlags.kt
  app/src/main/kotlin/com/wire/android/util/permission/RecordAudioRequestFlow.kt
  app/src/main/res/drawable/ic_stop.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModelTest.kt
Labels: size/XXL

#1951 chore: cherry pick from rc to develop
  .github/workflows/cherry-pick-rc-to-develop.yml
Labels: size/M

#1957 fix: ignore kalium for cherry pick
  .github/workflows/cherry-pick-rc-to-develop.yml
Labels: size/XS

#1960 docs: update JDK pre-requisite to 17
  README.md
Labels: size/XS

#1961 docs: improve wording
  README.md
Labels: size/XS

#1962 docs(readme): reword the required software section
  README.md
Labels: size/XS

#1964 fix: remove unnecessary values for custom saver of rememberSaveable
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
Labels: size/M

#1968 fix: do not transition to active when clicking on message list
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
Labels: size/XS

#1969 fix: send text formatting logic
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolderTest.kt
Labels: size/L

#1965 chore: upgrade compose to fix NavBackStackEntry crashes [WPB-2321]
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  gradle/libs.versions.toml
Labels: size/S

#1971 chore: upgrade compose to fix NavBackStackEntry crashes [RC] [WPB-2321]
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  buildSrc/src/main/kotlin/Dependencies.kt
Labels: size/S

#1970 fix: sending reply does not clear the quoted message
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerStateHolderTest.kt
Labels: size/S

#1974 fix: release mic from audio component
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioComponent.kt
Labels: size/XS

#1981 fix: hide sender name from notification if message is ephemeral (WPB-2431)
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
Labels: size/XS

#1986 fix: change audio extension from .mp3 to .m4a
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/AudioMediaRecorder.kt
Labels: size/XS

#1988 fix: client to UI model mapping
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/model/Device.kt
Labels: size/S

#1978 fix: missing self deleting text label and enabled button state[WPB-3312]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposeActions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
Labels: size/M

#1913 feat: Indicate MLS validated conversations
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewState.kt
  app/src/main/res/drawable/ic_certificate_valid_mls.xml
  app/src/main/res/drawable/ic_certificate_valid_proteus.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelTest.kt
Labels: size/L

#1980 feat: display if a button is selected [part-3]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
Labels: size/S

#1993 ci: internal app is not publishing to store
  AR-builder.groovy
Labels: size/XS

#2004 fix: license item not expanding for long text
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/RowItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/about/licenses/LicensesItem.kt
Labels: size/M

#2010 ci: build dev builds when merging to dev
  Jenkinsfile
Labels: size/XS

#2006 chore: Upload unit tests reports to DataDog (WPB-3489)
  .github/workflows/publish-test-results.yml
Labels: size/S

#2007 fix: disabled interaction availibility is not displaying message history
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
Labels: size/L

#2012 chore: Unblock button is no longer visible when we block someone (WPB-2427)
  app/src/main/kotlin/com/wire/android/model/ActionableState.kt
  app/src/main/kotlin/com/wire/android/navigation/NavigationItem.kt
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButtonViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/connection/ConnectionActionButtonViewModelTest.kt
Labels: size/L

#2013 fix: E2EI required dialog cancelable
  app/src/main/kotlin/com/wire/android/ui/home/HomeDialogs.kt
Labels: size/XS

#2017 chore: Improve DD JUnit upload command (WPB-3489)
  .github/workflows/publish-test-results.yml
Labels: size/XS

#2021 fix: wrong pointerInput invoked on scroll inside message list [WPB-3525]
  app/src/main/kotlin/com/wire/android/ui/common/ClickableText.kt
Labels: size/XS

#2020 fix: hide connectivity banner on authentications screens
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
Labels: size/M

#2018 chore: add configuration to force websocket (WPB-3311)
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/appsettings/networkSettings/NetworkSettingsScreen.kt
  app/src/main/kotlin/com/wire/android/util/WebsocketHelper.kt
  buildSrc/src/main/kotlin/Dependencies.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
Labels: size/M

#2025 fix: wrong pointerInput invoked on scroll inside message list (cherry-pick WPB-3525)
  app/src/main/kotlin/com/wire/android/ui/common/LinkifyText.kt
Labels: size/XS
