Repository wireapp/wire-android, pull requests merged in 2023-11, with the labels that each got.

#2385 ci: remove runner os
  .github/workflows/gradle-run-ui-tests.yml
Labels: size/XS

#2384 fix: message padding [WPB-5059]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/M

#2379 feat: selectable app theme [WPB-4483]
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/appearance/AppearanceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/appearance/AppearanceState.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/appearance/AppearanceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/theme/ThemeOption.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/appearance/AppearanceViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/home/BackupAndRestoreViewModelTest.kt
Labels: size/XL

#2381 fix: removed fixed height to adapt to grid view [WPB-5101]
  app/src/main/kotlin/com/wire/android/ui/common/AttachmentButton.kt
Labels: size/XS

#2396 fix: crash when saving file - duplicate names [WPB-5026]
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/test/kotlin/com/wire/android/util/FileUtilTest.kt
Labels: size/M

#2390 feat: Handle app dialogs with team applock (WPB -2388)
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/ui/AppLockActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
Labels: size/L

#2410 chore: update localization sources from Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/XXL, crowdin, l10n

#2402 fix: crash when saving file - duplicate names [WPB-5026]
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/test/kotlin/com/wire/android/util/FileUtilTest.kt
Labels: size/M, cherry-pick

#2415 chore: show e2ei certificate item on debug mode only
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModel.kt
Labels: size/M

#2407 fix: Rejoining call can't be completed (WPB-5111)
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/all/AllConversationScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
Labels: size/L

#2418 chore: update dependencies
  gradle/libs.versions.toml
Labels: size/S

#2420 chore: Adjust minimum characters to search to 1 (WPB-4915)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/usecase/GetConversationMessagesFromSearchUseCase.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/usecase/GetConversationMessagesFromSearchUseCaseTest.kt
Labels: size/XS

#2414 chore: provide a way to make previews with scoped view models
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/di/ViewModelScoped.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/ProxyScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/banner/SecurityClassificationBanner.kt
  app/src/main/kotlin/com/wire/android/ui/common/banner/SecurityClassificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButtonViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/edit/ReactionOption.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockCodeResetDeviceDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/set/SetLockCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/unlock/EnterLockCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/CompositeMessageViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationAllParticipantsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/attachments/AdditionalOptionButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/attachments/IsFileSharingEnabledViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/TurnAppLockOffDialog.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Theme.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/CompositeMessageViewModelTest.kt
  gradle/libs.versions.toml
  ksp/build.gradle.kts
  ksp/src/main/kotlin/com/wire/android/di/ViewModelScopedPreview.kt
  ksp/src/main/resources/META-INF/services/com.google.devtools.ksp.processing.SymbolProcessorProvider
Labels: size/L

#2423 fix: update applock forgot passcode copy [WPB-5461]
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/L

#2424 chore: hide search messages button (WPB-5419)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesButton.kt
  app/src/main/kotlin/com/wire/android/util/debug/FeatureVisibilityFlags.kt
Labels: size/S

#2421 feat: legal hold UI - create all related dialogs [WPB-5446]
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/common/LearnMoreAboutLegalHoldButton.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/deactivated/LegalHoldDeactivatedDialog.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/requested/LegalHoldRequestedDialog.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/requested/LegalHoldRequestedState.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/requested/LegalHoldRequestedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/subject/LegalHoldSubjectBaseDialog.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/subject/LegalHoldSubjectConnectionDialog.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/subject/LegalHoldSubjectConversationDialog.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/subject/LegalHoldSubjectMessageDialog.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/subject/LegalHoldSubjectProfileDialog.kt
  app/src/main/res/values/strings.xml
Labels: size/XL, DO NOT MERGE

#2413 fix: Conversation verification changed message showing
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
Labels: size/XS

#2427 fix: persistent web socket service crashing when started in android 14
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
Labels: size/XS

#2425 chore: bump develop to v4.6.x
  build-logic/plugins/src/main/kotlin/AndroidCoordinates.kt
Labels: size/XS

#2426 feat: search message highlight [WPB-5163]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/HighLightName.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/HighLightSubtTitle.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesResultsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownComposer.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/NodeData.kt
  app/src/main/kotlin/com/wire/android/util/QueryMatchExtractor.kt
  app/src/main/kotlin/com/wire/android/util/debug/FeatureVisibilityFlags.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/SearchConversationMessagesViewModelTest.kt
Labels: size/L

#2428 feat: avatar border and message padding improvements [WPB-5059]
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/AuthorHeaderHelper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/res/drawable/ic_call_end.xml
Labels: size/L

#2434 fix(applock): app navigates to biometrics screen after entering passcode
  app/src/main/kotlin/com/wire/android/ui/home/appLock/unlock/AppUnlockWithBiometricsScreen.kt
Labels: size/XS

#2430 fix: persistent web socket service crashing when started in android 14 (#2427)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
Labels: size/XS

#2436 fix(applock): app navigates to biometrics screen after entering passcode RC - cherrypick
  app/src/main/kotlin/com/wire/android/ui/home/appLock/unlock/AppUnlockWithBiometricsScreen.kt
Labels: size/XS

#2443 chore: rename project references as android, deprecating scala repo (rc)
  .github/workflows/build-app.yml
  .github/workflows/codestyle.yml
  .github/workflows/gradle-run-ui-tests.yml
  .github/workflows/gradle-run-unit-tests.yml
  .github/workflows/publish-test-results.yml
  AR-builder.groovy
  Jenkinsfile
  README.md
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
Labels: size/S

#2433 chore: add message item box click (WPB-4986)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesResultsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownComposer.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownParagraph.kt
Labels: size/M

#2440 fix: white screen after splash screen (WPB-5439) - cherrypick
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
Labels: size/S

#2444 chore: rename project references as android, deprecating scala repo (dev)
  .github/workflows/publish-test-results.yml
  AR-builder.groovy
  Jenkinsfile
  README.md
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
Labels: size/S

#2452 fix: Show all participants sticky button (WPB-5602)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
Labels: size/L

#2431 feat: avatar border and message padding improvements [WPB-5059]
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/AuthorHeaderHelper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  app/src/main/res/drawable/ic_call_end.xml
Labels: size/L, cherry-pick

#2457 fix: messages list IndexOutOfBoundsException [WPB-5612]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/AuthorHeaderHelper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/AuthorHeaderHelperTest.kt
Labels: size/L

#2458 chore: Update README to use the new name of Android project
  README.md
Labels: size/XS

#2447 fix: reset passcode dialog state when empty input or sso user [WPB-5094]
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockCodeResetDeviceDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockCodeViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockScreenViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockScreenViewModelTest.kt
Labels: size/L

#2459 fix: messages list IndexOutOfBoundsException [WPB-5612]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/AuthorHeaderHelper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/AuthorHeaderHelperTest.kt
Labels: size/L, cherry-pick

#2460 feat: remove required nearby devices permission for calling (WPB-4583)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/ui/calling/common/MicrophonePermissionDeniedDialog.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/JoinButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/StartCallButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/util/permission/CallingRecordAudioRequestFlow.kt
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/L

#2463 fix: closing keyboard or back pressing when editing a message
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
Labels: size/XS

#2466 fix: app lock not disabled when team enforce is lifted
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/feature/AppLockSource.kt
  app/src/main/kotlin/com/wire/android/feature/DisableAppLockUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/set/SetLockScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/test/kotlin/com/wire/android/feature/DisableAppLockUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/appLock/set/SetLockScreenViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolderTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
Labels: size/L

#2465 fix: reset passcode dialog state when empty input or sso user [WPB-5094]
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockCodeResetDeviceDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockCodeViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockScreenViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockScreenViewModelTest.kt
Labels: size/L, cherry-pick

#2467 fix: closing keyboard or back pressing when editing a message
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
Labels: size/XS, cherry-pick

#2464 fix: app lock dialog blinking (WPB-5610)
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
Labels: size/S

#2441 feat: Highlight selected searched message (WPB-5506)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/M

#2477 fix: typo variable assign in cherry-pick
  .github/workflows/cherry-pick-rc-to-develop.yml
Labels: size/XS

#2470 fix: app lock dialog blinking (WPB-5610)
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
Labels: size/S, cherry-pick

#2478 fix: typo variable assign in cherry-pick
  .github/workflows/cherry-pick-rc-to-develop.yml
Labels: size/XS, cherry-pick

#2473 chore(ci): addresses issue about archiving in releases the APK (cycle 4.4)
  AR-builder.groovy
  Jenkinsfile
Labels: size/M

#2480 chore: update localization strings via Crowdin (RC)
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/XL, crowdin, l10n

#2474 fix: disable back press when app lock team enforced (WPB-5644)
  app/src/main/kotlin/com/wire/android/ui/home/appLock/set/SetLockCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/set/SetLockCodeViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/set/SetLockScreenViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/appLock/set/SetLockScreenViewModelTest.kt
Labels: size/M
