Repository wireapp/wire-android, pull requests merged in 2024-05, with the labels that each got.

#2952 fix: start CallActivity in a new task (WPB-6437)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/ui/calling/CallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
Labels: size/XS

#2955 feat: allow swipe to reply (WPB-982)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/FileAssetsContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageContainerItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageItemTemplate.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesResultsScreen.kt
Labels: size/S

#2956 fix: incoming call screen is not shown on second account
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationActions.kt
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/CallActivity.kt
Labels: size/XS

#2958 fix: start CallActivity in a new task (WPB-6437) (#2952) - cherrypick
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/ui/calling/CallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
Labels: size/XS

#2960 fix: incoming call screen is not shown on second account - cherrypick
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationActions.kt
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/CallActivity.kt
Labels: size/XS

#2965 fix: Crash after fresh install
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/XS

#2963 fix: finish CallActivity and remove task when call is terminated (WPB-6437)
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/outgoing/OutgoingCallScreen.kt
Labels: size/XS

#2969 fix: keep the composed message when replying [WPB-982]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerStateHolderTest.kt
Labels: size/XS

#2964 feat: grouping message dates (WPB-1733)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageContainerItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/util/DateTimeUtil.kt
  app/src/main/res/values-af/strings.xml
  app/src/test/kotlin/com/wire/android/mapper/MessageMapperTest.kt
  app/src/test/kotlin/com/wire/android/util/DateTimeUtilKtTest.kt
Labels: size/M

#2971 fix: divider thickness [WPB-3985]
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/divider/WireDivider.kt
Labels: size/XS

#2975 fix: revert launch mode to singleTask (WPB-9014)
  app/src/main/AndroidManifest.xml
Labels: size/XS

#2977 fix: No red shields visible on devices list from other users [WPB-8677]
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
Labels: size/XS

#2983 fix: disable swiping in some extra cases [WPB-9044]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/FileAssetsContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageContainerItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesResultsScreen.kt
Labels: size/XS

#2985 fix: improve swipe detection and animation [WPB-9046]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageContainerItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
Labels: size/S

#2980 fix: group messages date | design changes (WPB-1733)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/util/DateTimeUtil.kt
Labels: size/XS

#2992 fix: heavy sketch file
  features/sketch/src/main/java/com/wire/android/feature/sketch/DrawingCanvasViewModel.kt
Labels: size/XS

#2994 chore: file access crashes [WPB-7368]
  app/src/beta/kotlin/com/wire/android/ExternalLoggerManager.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPickerViewModel.kt
  app/src/main/kotlin/com/wire/android/util/DeviceUtil.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/res/values/strings.xml
Labels: size/S

#2988 fix: crashing message composer input [WPB-8727]
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CameraButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CameraFlipButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/DeclineButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/MicrophoneButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/SpeakerButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/AppExtensions.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/StateSyncingModifier.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField2.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  core/ui-common/build.gradle.kts
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/snackbar/SwipeableSnackbar.kt
  features/sketch/build.gradle.kts
  features/template/build.gradle.kts
  gradle/libs.versions.toml
Labels: size/M

#3001 feat: add privacy policy (WPB-8846)
  app/src/main/kotlin/com/wire/android/navigation/OtherDestinations.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/about/AboutThisAppScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/about/AboutThisAppState.kt
  app/src/main/kotlin/com/wire/android/ui/settings/about/AboutThisAppViewModel.kt
  app/src/main/res/values/strings.xml
Labels: size/M

#3002 fix: GetE2EICertificate button when no certificate
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/EndToEndIdentityCertificateItem.kt
Labels: size/XS

#2991 refactor: introduce BasicTextField2 [WPB-8779] [WPB-8727]
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceDialog.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/ProxyScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CameraButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CameraFlipButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/DeclineButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/MicrophoneButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/SpeakerButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/AppExtensions.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/AutoFillTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/CodeTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/CodeTextFieldLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/InputTransformations.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/Label.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/StateSyncingModifier.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextFieldAutoFill.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextFieldLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextFieldState.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockCodeResetDeviceDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/joinConversation/JoinConversationViaDeepLinkDialog.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/requested/LegalHoldRequestedDialog.kt
  core/ui-common/build.gradle.kts
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/snackbar/SwipeableSnackbar.kt
  features/sketch/build.gradle.kts
  features/template/build.gradle.kts
  gradle/libs.versions.toml
Labels: size/XL

#2999 fix: Websocket toggle always off [WBP-8669]
  app/src/main/kotlin/com/wire/android/ui/home/settings/appsettings/networkSettings/NetworkSettingsScreen.kt
Labels: size/XS

#3008 feat: add toggle to opt-out analytics (WPB-8922)
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsState.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsViewModelTest.kt
Labels: size/S

#2998 refactor: remove rememberRipple, unify calling icon buttons
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/AcceptButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CameraButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CameraFlipButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/DeclineButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/HangUpButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/JoinButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/MicrophoneButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/SpeakerButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/StartCallButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/WireCallControlButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/outgoing/OutgoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/AppExtensions.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WireButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WireButtonDefaults.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryIconButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WireTertiaryIconButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/L

#3011 chore: add new verified string for opt-out toggle description (WPB-8922)
  app/src/main/res/values/strings.xml
Labels: size/XS

#3007 ci: github acceptance improvements [WPB-8666] [WPB-9133]
  .editorconfig
  .github/workflows/build-app.yml
  .github/workflows/gradle-run-ui-tests.yml
  .github/workflows/gradle-run-unit-tests.yml
  app/src/test/kotlin/com/wire/android/ui/CallActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/XS

#3017 fix: bring back 'show password' button on password text input
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
Labels: size/XS

#3018 fix: markdown support link reference [WPB-9220]
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownHelper.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownNode.kt
Labels: size/XS

#3024 fix: jumping keyboard behavior (WPB-9357)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
Labels: size/XS

#3027 chore: update localization strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/L, crowdin, l10n

#3028 fix: top bar not centered when on-premises backend is visible [WPB-9383]
  app/src/main/kotlin/com/wire/android/ui/authentication/ServerTitle.kt
Labels: size/XS

#3032 fix: multiple undo tap for drawing, unnecessary recompositions (WPB-8810)
  features/sketch/src/main/java/com/wire/android/feature/sketch/DrawingCanvasViewModel.kt
  features/sketch/src/main/java/com/wire/android/feature/sketch/model/DrawingPathProperties.kt
  features/sketch/src/main/java/com/wire/android/feature/sketch/model/DrawingState.kt
  features/sketch/src/test/java/com/wire/android/feature/sketch/DrawingCanvasViewModelTest.kt
Labels: size/XS

#3034 fix: swipe to reply activated too early
  app/lint-baseline.xml
  app/src/main/kotlin/com/wire/android/ui/common/textfield/StateSyncingModifier.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField2.kt
  gradle/libs.versions.toml
Labels: size/XS

#3037 fix: 1:1 calls can not be established on staging environment (WPB-9359) - approach 3
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
  app/src/test/kotlin/com/wire/android/ui/calling/OngoingCallViewModelTest.kt
  gradle/libs.versions.toml
Labels: size/XS

#3004 feat: multiple image preview [WPB-8801]
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/ui/common/imagepreview/AvatarPickerFlow.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/AssetTooLargeDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationNavArgs.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/CheckAssetRestrictionsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/preview/AssetFilePreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/preview/AssetTilePreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/preview/ImagesPreviewNavArgs.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/preview/ImagesPreviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/preview/ImagesPreviewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/preview/ImagesPreviewViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageTypesPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/AssetBundle.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/asset/AssetMessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AttachmentOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/model/MessageBundle.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaSnackbarMessages.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportedMediaAsset.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportedMediaTypes.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/SendMessagesSnackbarMessages.kt
  app/src/main/kotlin/com/wire/android/util/DeviceUtil.kt
  app/src/main/kotlin/com/wire/android/util/permission/OpenFileBrowserRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/OpenGalleryRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/UseStorageRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/ui/WireSessionImageLoader.kt
  app/src/main/res/drawable/ic_attention.xml
  app/src/main/res/drawable/mock_message_image.png
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModelTest.kt
  build-logic/plugins/src/main/kotlin/com/wire/android/gradle/KotlinAndroidConfiguration.kt
  core/ui-common/build.gradle.kts
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/error/ErrorIcon.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/image/WireImage.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/preview/MultipleThemePreviews.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/remove/RemoveIcon.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireTypography.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireTypographyBase.kt
  core/ui-common/src/main/res/drawable/ic_attention.xml
  core/ui-common/src/main/res/drawable/ic_close.xml
  core/ui-common/src/main/res/drawable/mock_image.jpeg
Labels: size/XL

#3039 fix: send button disabled after writing message [WPB-9421]
  app/src/main/kotlin/com/wire/android/ui/common/textfield/StateSyncingModifier.kt
Labels: size/XS

#3041 fix: crash when no browser available (WPB-9436)
  app/src/main/kotlin/com/wire/android/util/CustomTabsHelper.kt
Labels: size/XS

#3043 fix: crash on code screen while requesting focus (WPB-6876)
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeScreen.kt
Labels: size/XS

#3014 ci: Setup workflows to build all variants in the app (WPB-8644)
  .github/workflows/build-app.yml
  .github/workflows/build-beta-app.yml
  .github/workflows/build-develop-app.yml
  .github/workflows/build-prod-app.yml
  .github/workflows/build-rc-app.yml
  .github/workflows/gradle-run-ui-tests.yml
  .github/workflows/gradle-run-unit-tests.yml
Labels: size/M

#3030 chore: update localization strings via Crowdin
  app/src/main/kotlin/com/wire/android/navigation/OtherDestinations.kt
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/S, crowdin, l10n

#3048 fix(ci): github action deadlock in merge_group
  .github/workflows/gradle-run-ui-tests.yml
Labels: size/XS

#3045 fix: proximity sensor keeps turning the screen off even when there is no call (WPB-9215)
  app/src/main/kotlin/com/wire/android/ui/calling/ProximitySensorManager.kt
Labels: size/XS

#3051 ci: add env variables for key store path
  .github/workflows/build-rc-app.yml
Labels: size/XS

#3050 fix(ci): build fdroid with Compatrelease build type
  Jenkinsfile
Labels: size/XS

#3055 fix: run UI logic on the main thread [WPB-9458]
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
Labels: size/XS

#3054 refactor: update text input logic to v2 TextFieldState, part 3 [WPB-8779]
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceDialog.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockCodeResetDeviceDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockCodeViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/set/SetLockCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/set/SetLockCodeViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/set/SetLockScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/unlock/EnterLockCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/unlock/EnterLockCodeViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/unlock/EnterLockScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockScreenViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/appLock/set/SetLockScreenViewModelTest.kt
Labels: size/L
