Repository wireapp/wire-android, pull requests merged in 2024-02, with the labels that each got.

#2654 ci: fix cherry pick action when last commit message contains special characters
  .github/workflows/cherry-pick-rc-to-develop.yml
Labels: size/XS

#2657 fix: make SelfDeletionTimerTest unit instead of instrumented
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageExpiration.kt
  app/src/test/kotlin/com/wire/android/SelfDeletionTimerTest.kt
Labels: size/S

#2652 fix: responding to clicks right after navigating [WPB-5468]
  app/src/main/kotlin/com/wire/android/navigation/style/TransitionAnimations.kt
Labels: size/XS

#2653 fix: self-deleting msg in doze mode on ConversationScreen [WPB-5894]
  app/src/androidTest/java/com/wire/android/SelfDeletionTimerTest.kt
  app/src/main/kotlin/com/wire/android/GlobalObserversManager.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageExpiration.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/test/kotlin/com/wire/android/GlobalObserversManagerTest.kt
  app/src/test/kotlin/com/wire/android/SelfDeletionTimerTest.kt
Labels: size/XL, cherry-pick

#2660 fix: remove trim of spaces when searching for messages inside a conversation (WPB-5834)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/SearchConversationMessagesViewModelTest.kt
Labels: size/XS

#2666 chore(ci): base64 encoding adding a new line after 76 char
  .github/workflows/cherry-pick-rc-to-develop.yml
Labels: size/XS

#2662 chore(tests): support vintage engine (junit4) and add robolectric (ACOL-139)
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessViewModel.kt
  app/src/test/kotlin/com/wire/android/mapper/UserTypeMapperTest.kt
  app/src/test/kotlin/com/wire/android/migration/MigrationMapperTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerHelperTest.kt
  gradle/libs.versions.toml
Labels: size/M

#2665 fix: not possible to search for services [WPB-5943] (#2648)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
Labels: size/XS, cherry-pick

#2670 chore: remove jacoco and migrate to kover (ACOL-139)
  .github/workflows/gradle-run-unit-tests.yml
  AR-builder.groovy
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/scripts/quality.gradle.kts
Labels: size/S

#2673 fix: crash when uploading avatar [WPB-5965]
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPickerViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/image/AvatarPickerViewModelTest.kt
Labels: size/XS

#2676 fix: add fully qualified handle for external results (WPB-6256)
  app/src/main/kotlin/com/wire/android/mapper/ContactMapper.kt
Labels: size/XS

#2675 chore: enable MLS for beta build flavour (ACOL-146)
  default.json
Labels: size/XS

#2677 fix: add fully qualified handle for external results (WPB-6256)
  app/src/main/kotlin/com/wire/android/mapper/ContactMapper.kt
Labels: size/XS, cherry-pick

#2647 feat: support remote search by handle
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  app/src/main/kotlin/com/wire/android/di/accountScoped/SearchModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/QueryExtension.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUserViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/search/SearchUserViewModelTest.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
Labels: size/S

#2680 fix: text highlight colors [WPB-5940]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/HighLightName.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/HighLightSubtTitle.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownComposer.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorPalette.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/XS

#2681 fix: text highlight colors [WPB-5940]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/HighLightName.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/HighLightSubtTitle.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownComposer.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorPalette.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/XS, cherry-pick

#2685 fix(e2ei): remove E2EI shield from remove device screen (WPB-6519)
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/SelfDevicesScreen.kt
Labels: size/XS

#2687 fix: NotificationChannelGroup crash (WPB-6233)
  app/src/main/kotlin/com/wire/android/GlobalObserversManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockScreenViewModelTest.kt
Labels: size/XS

#2684 fix: serverConfig and notification crashes right after user becomes invalid [WPB-6552] [WPB-6233]
  app/src/main/kotlin/com/wire/android/GlobalObserversManager.kt
  app/src/main/kotlin/com/wire/android/feature/ObserveAppLockConfigUseCase.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ProximitySensorManager.kt
  app/src/test/kotlin/com/wire/android/GlobalObserversManagerTest.kt
  app/src/test/kotlin/com/wire/android/feature/ObserveAppLockConfigUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
Labels: size/S

#2692 fix: serverConfig and notification crashes right after user becomes invalid [WPB-6552] [WPB-6233]
  app/src/main/kotlin/com/wire/android/GlobalObserversManager.kt
  app/src/main/kotlin/com/wire/android/feature/ObserveAppLockConfigUseCase.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ProximitySensorManager.kt
  app/src/test/kotlin/com/wire/android/GlobalObserversManagerTest.kt
  app/src/test/kotlin/com/wire/android/feature/ObserveAppLockConfigUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
Labels: size/S, cherry-pick

#2697 fix: 2FA support dark mode
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailVerificationCodeScreen.kt
Labels: size/XS

#2693 fix: message background highlight colors [WPB-5940]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/XS

#2696 fix: long click on deleted message (WPB-6290)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
Labels: size/XS

#2683 fix: Use idp client id from remote (WPB-6494)
  app/src/main/kotlin/com/wire/android/feature/e2ei/OAuthUseCase.kt
  app/src/main/kotlin/com/wire/android/util/UriUtil.kt
  app/src/test/kotlin/com/wire/android/util/UriUtilTest.kt
Labels: size/S

#2702 fix: long click on deleted message (WPB-6290)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
Labels: size/XS, cherry-pick

#2705 fix: crash when answering a call (WPB-6183) - cherrypick
  app/src/main/kotlin/com/wire/android/ui/calling/model/UICallParticipant.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
  app/src/main/res/values/strings.xml
Labels: size/XS

#2703 fix: Use idp client id from remote (WPB-6494)
  app/src/main/kotlin/com/wire/android/feature/e2ei/OAuthUseCase.kt
  app/src/main/kotlin/com/wire/android/util/UriUtil.kt
  app/src/test/kotlin/com/wire/android/util/UriUtilTest.kt
Labels: size/S, cherry-pick

#2701 fix: message background highlight colors [WPB-5940]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/XS, cherry-pick

#2700 feat: allow http calls when checking Certificate Revocation List (WPB-6493)
  app/src/main/AndroidManifest.xml
Labels: size/XS

#2710 fix: remove browser allow list and skip of https check (WPB-6609)
  app/src/main/kotlin/com/wire/android/feature/e2ei/OAuthUseCase.kt
Labels: size/XS

#2713 fix: leaking UI context GetE2EICertificateUseCase (WPB-6648)
  app/src/main/kotlin/com/wire/android/di/GetE2EICertificateUseCaseProvider.kt
  app/src/main/kotlin/com/wire/android/feature/e2ei/GetE2EICertificateUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/E2EIEnrollmentScreen.kt
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/E2EIEnrollmentViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModelTest.kt
Labels: size/S

#2694 fix: welcome screen large screen [WPB-6427]
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
Labels: size/XS, cherry-pick

#2691 fix: NotificationChannelGroup crash (WPB-6233)
  app/src/main/kotlin/com/wire/android/GlobalObserversManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockScreenViewModelTest.kt
Labels: size/XS, cherry-pick

#2699 fix: 2FA support dark mode
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailVerificationCodeScreen.kt
Labels: size/XS, cherry-pick

#2709 feat: legal hold indicators on group details screens [WPB-4569]
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/mapper/UIParticipantMapper.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsTopBarCollapsing.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/ConversationParticipantItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/model/UIParticipant.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/usecase/ObserveParticipantsForConversationUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/subject/LegalHoldSubjectConversationDialog.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/participants/usecase/ObserveParticipantsForConversationUseCaseTest.kt
Labels: size/S

#2729 chore: add git commit hash to external logger
  app/src/beta/kotlin/com/wire/android/ExternalLoggerManager.kt
Labels: size/XS

#2734 chore: add structured logs to location and fix permission handling (WPB-6358)
  app/src/main/kotlin/com/wire/android/AppLogger.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerHelper.kt
Labels: size/XS

#2736 chore: add structured logs to location and fix permission handling (WPB-6358)
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/AppLogger.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerHelper.kt
  app/src/nonfree/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerHelperFlavor.kt
Labels: size/XS, cherry-pick

#2733 chore: fix tag logging
  app/src/beta/kotlin/com/wire/android/util/DataDogLogger.kt
Labels: size/XS, cherry-pick

#2718 fix: show connection request with unavailable name [WPB-6247]
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
Labels: size/XS, cherry-pick

#2739 chore: fix tag logging for internal and staging flavors
  app/src/internal/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/staging/kotlin/com/wire/android/util/DataDogLogger.kt
Labels: size/XS

#2742 fix(e2ei): force login to idp to update certificate (WPB-6877)
  app/src/main/kotlin/com/wire/android/feature/e2ei/OAuthUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/GetE2EICertificateUI.kt
Labels: size/XS

#2746 feat: Remove third party library for certificate decoding (WPB-6765)
  app/src/main/kotlin/com/wire/android/ui/settings/devices/EndToEndIdentityCertificateItem.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/model/DeviceDetailsState.kt
Labels: size/XS

#2745 fix: crash about persistent websocket being started from background [WPB-6551]
  app/src/main/kotlin/com/wire/android/feature/ShouldStartPersistentWebSocketServiceUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/debug/StartServiceReceiver.kt
  app/src/test/kotlin/com/wire/android/feature/ShouldStartPersistentWebSocketServiceUseCaseTest.kt
Labels: size/S

#2749 fix: Do not show waiting network in CertDetails screen (RC) (WPB-6638)
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
Labels: size/XS

#2741 fix: release: Enrolling E2EI crash [WPB-6788]
  app/src/main/kotlin/com/wire/android/di/GetE2EICertificateUseCaseProvider.kt
  app/src/main/kotlin/com/wire/android/feature/e2ei/GetE2EICertificateUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/E2EIEnrollmentScreen.kt
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/E2EIEnrollmentViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/GetE2EICertificateUI.kt
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/GetE2EICertificateViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/E2EIDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/FeatureFlagState.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/model/DeviceDetailsState.kt
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModelTest.kt
Labels: size/L, cherry-pick
