Repository wireapp/wire-android, pull requests merged in 2024-01, with the labels that each got.

#2552 feat: scrollable dialogs [WPB-1681]
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
Labels: size/XS

#2565 fix: Whole conversation TopBar clickable (WPB-4833)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
Labels: size/XS

#2563 feat: App soft lock when E2EI is required (WPB-5876)
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
Labels: size/XS

#2568 chore: remove deprecated accompanist-navigation dependency
  app/build.gradle.kts
  app/src/beta/kotlin/com/wire/android/navigation/TrackingNavController.kt
  app/src/dev/kotlin/com/wire/android/navigation/TrackingNavController.kt
  app/src/internal/kotlin/com/wire/android/navigation/TrackingNavController.kt
  app/src/prod/kotlin/com/wire/android/navigation/TrackingNavController.kt
  app/src/staging/kotlin/com/wire/android/navigation/TrackingNavController.kt
  gradle/libs.versions.toml
Labels: size/S

#2574 fix: remove E2EI indication(shield) from conversations list (WPB-6070)
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/UserLabel.kt
Labels: size/XS

#2575 chore: update baseline profiler file
  app/src/main/baseline-prof.txt
Labels: size/XL

#2577 feat(e2ei): pass ignore ssl certs for apis in dev build
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
Labels: size/XS

#2583 chore: remove (beta) string from protocol details label string (WPB-6112)
  app/src/main/res/values/strings.xml
Labels: size/XS

#2586 chore: update localization strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/XL, crowdin, l10n

#2590 fix: OtherUserProfile snapshot crash
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
Labels: size/XS

#2582 feat: sending location messages (WPB-1732)
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/di/accountScoped/MessageModule.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/EditMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/TextMessageMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AttachmentOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/GeoLocatedAddress.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerComponent.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/AdditionalOptionMenuState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
  app/src/main/kotlin/com/wire/android/util/debug/FeatureVisibilityFlags.kt
  app/src/main/kotlin/com/wire/android/util/permission/CurrentLocationRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/PermissionsDeniedRequestDialog.kt
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelTest.kt
  gradle/libs.versions.toml
Labels: size/L

#2592 chore(deps): upgrade Gradle to 8.5
  gradle/wrapper/gradle-wrapper.properties
Labels: size/XS

#2591 fix: set modifier of LazyColumn to fillMaxSize (WPB-6121)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/FileAssetsContent.kt
Labels: size/XS

#2595 fix: download asset dialog button order (WPB-5378)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/DownloadedAssetDialog.kt
  app/src/main/res/values/strings.xml
Labels: size/XS

#2598 fix: add correct colors for dark mode when recording audio (WPB-4534)
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/XS

#2599 fix: add correct colors for dark mode when recording audio (WPB-4534)
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/XS

#2602 chore: update source location strings english
  app/src/main/res/values/strings.xml
Labels: size/XS

#2601 fix: sharing location crash when device location off (WPB-6182)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerComponent.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerViewModel.kt
  app/src/main/res/values/strings.xml
Labels: size/S

#2603 chore: source strings new translations (dev)
  app/src/main/res/values/strings.xml
Labels: size/XS, cherry-pick

#2604 fix: original image path was used images when sharing from share extension
  app/src/main/kotlin/com/wire/android/model/ImageAsset.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportedMediaTypes.kt
  app/src/main/kotlin/com/wire/android/util/ui/AssetImageFetcher.kt
  app/src/main/kotlin/com/wire/android/util/ui/WireSessionImageLoader.kt
  app/src/test/kotlin/com/wire/android/model/ImageAssetTest.kt
  app/src/test/kotlin/com/wire/android/util/ui/AssetImageFetcherTest.kt
Labels: size/XS

#2607 fix: changes to hopefully improve startup and ANRs [WPB-6048]
  app/build.gradle.kts
  app/src/dev/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/internal/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/initializer/FirebaseInitializer.kt
  app/src/main/kotlin/com/wire/android/initializer/InitializerEntryPoint.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ProximitySensorManager.kt
  app/src/main/res/drawable/ic_launcher_wire_logo.xml
  app/src/staging/kotlin/com/wire/android/util/DataDogLogger.kt
  gradle/libs.versions.toml
Labels: size/M

#2610 feat: improve enrollment dialog (WPB-4372)
  app/src/main/kotlin/com/wire/android/ui/WireActivityDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/ServerTitle.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/CustomServerDialog.kt
  app/src/main/res/values/strings.xml
Labels: size/M

#2611 fix: changes to hopefully improve startup and ANRs [WPB-6048]
  app/build.gradle.kts
  app/src/dev/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/internal/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/initializer/FirebaseInitializer.kt
  app/src/main/kotlin/com/wire/android/initializer/InitializerEntryPoint.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ProximitySensorManager.kt
  app/src/main/res/drawable/ic_launcher_wire_logo.xml
  app/src/staging/kotlin/com/wire/android/util/DataDogLogger.kt
  gradle/libs.versions.toml
Labels: size/M, cherry-pick

#2617 chore: update localization strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/L, crowdin, l10n

#2620 test: add sharing location coverage for viewmodel
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerComponent.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerHelper.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerViewModelTest.kt
  gradle/libs.versions.toml
Labels: size/S

#2622 test: add sharing location coverage for viewmodel
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerComponent.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerHelper.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerViewModelTest.kt
  gradle/libs.versions.toml
Labels: size/S, cherry-pick

#2628 chore: update localization strings via Crowdin (rc)
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/L, crowdin, l10n

#2594 feat: Show a dialog when current client's certificate is revoked (WPB-6145)
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireLabelledCheckbox.kt
  app/src/main/kotlin/com/wire/android/ui/home/E2EIDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/FeatureFlagState.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/dialog/LogoutOptionsDialog.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
Labels: size/S

#2629 fix: preserve Original Author in Cherry-Picked Commits
  .github/workflows/cherry-pick-rc-to-develop.yml
Labels: size/XS

#2626 fix: original image path was used images from share extension
  app/src/main/kotlin/com/wire/android/model/ImageAsset.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportedMediaTypes.kt
  app/src/main/kotlin/com/wire/android/util/ui/AssetImageFetcher.kt
  app/src/main/kotlin/com/wire/android/util/ui/WireSessionImageLoader.kt
  app/src/test/kotlin/com/wire/android/model/ImageAssetTest.kt
  app/src/test/kotlin/com/wire/android/util/ui/AssetImageFetcherTest.kt
Labels: size/XS

#2634 chore: remove un-needed changes
  app/src/main/AndroidManifest.xml
  build-logic/plugins/src/main/kotlin/AndroidCoordinates.kt
Labels: size/XS

#2635 feat: Show a dialog when current client's certificate is revoked (WPB-6145) - cherrypick
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireLabelledCheckbox.kt
  app/src/main/kotlin/com/wire/android/ui/home/E2EIDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/FeatureFlagState.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/dialog/LogoutOptionsDialog.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
Labels: size/S

#2643 fix: setting items clickable area [WPB-6225]
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/SelfDevicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
Labels: size/S

#2645 fix: logging level does not reflect in datadog
  app/src/beta/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/dev/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/internal/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/staging/kotlin/com/wire/android/util/DataDogLogger.kt
Labels: size/XS

#2646 fix: logging level does not reflect in datadog
  app/src/beta/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/dev/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/internal/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/staging/kotlin/com/wire/android/util/DataDogLogger.kt
Labels: size/XS, cherry-pick

#2642 fix: self-deleting msg in doze mode on ConversationScreen [WPB-5894]
  app/src/androidTest/java/com/wire/android/SelfDeletionTimerTest.kt
  app/src/main/kotlin/com/wire/android/GlobalObserversManager.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageExpiration.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/test/kotlin/com/wire/android/GlobalObserversManagerTest.kt
Labels: size/L

#2648 fix: not possible to search for services [WPB-5943]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
Labels: size/XS

#2644 fix: setting items clickable area [WPB-6225]
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/SelfDevicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
Labels: size/S, cherry-pick
