Repository wireapp/wire-android, pull requests merged in 2024-09, with the labels that each got.

#3409 feat(calling): Floating view for self user (WPB-10652) - Part 2
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/FullScreenTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/FloatingSelfUserTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantsTiles.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/gridview/CallingGridView.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/horizentalview/CallingHorizontalView.kt
  default.json
Labels: size/S, echoes: features

#3416 feat: support sending GIFs from keyboard [WPB-1715]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/CheckAssetRestrictionsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/preview/ImagesPreviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/kotlin/com/wire/android/util/ImageUtil.kt
Labels: size/S, echoes: features

#3412 fix: handling deeplinks not working everytime
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
Labels: size/XS, DO NOT CHERRY PICK

#3418 fix: bottom buttons hidden underneath keyboard on Androids 8 to 10 [WPB-10868]
  app/src/main/AndroidManifest.xml
Labels: size/XS, echoes: bugs

#3417 refactor: deeplink handling [WPB-10182]
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/main/kotlin/com/wire/android/util/deeplink/DeepLinkProcessor.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/DeepLinkProcessorTest.kt
  docs/adr/0004-deeplink-handling-refactor.md
Labels: size/L, echoes: bugs

#3422 chore: update analytics dialog string (WPB-9973)
  app/src/main/res/values/strings.xml
Labels: size/XS, echoes/initiative: product-metrics-in-countly

#3421 fix: some files not visible in downloads folder [WPB-1854]
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/test/kotlin/com/wire/android/util/FileUtilTest.kt
Labels: size/S, echoes: bugs

#3410 feat(calling): Adapt the floating self user view in PiP mode (WPB-10652) - Part 3
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/FloatingSelfUserTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantsTiles.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/gridview/CallingGridView.kt
Labels: size/S, echoes: features

#3424 feat: Disable services for MLS conversation [WPB-10777]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessViewModel.kt
  app/src/test/kotlin/com/wire/android/framework/TestConversation.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessViewModelTest.kt
Labels: size/S, echoes/initiative: federation-wire-cloud

#3426 feat(calling): Floating view not visible on top of all UI elements (WPB-10652) - Part 4
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantsTiles.kt
Labels: size/XS, echoes: features

#3427 chore: update dependencies
  app/build.gradle.kts
  core/ui-common/build.gradle.kts
  features/sketch/build.gradle.kts
  gradle/libs.versions.toml
Labels: size/XS

#3425 fix: empty dependencies section [WPB-10929]
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
  app/src/main/res/values/strings.xml
Labels: size/XS, echoes: bugs

#3431 fix: import asset intent handling [WPB-11036]
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/util/deeplink/DeepLinkProcessor.kt
  app/src/test/kotlin/com/wire/android/util/DeepLinkProcessorTest.kt
Labels: size/XS

#3433 fix: initials avatar use regex instead and add content description (WPB-10896)
  app/src/main/kotlin/com/wire/android/model/UserAvatarData.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
Labels: size/XS

#3428 feat: add analytics initial events (WPB-10589)
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModelTest.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/model/AnalyticsEvent.kt
Labels: size/M, echoes/initiative: product-metrics-in-countly

#3430 ci: publish edge app on each push to internal [WPB-11060]
  .github/workflows/build-edge-env.yml
  .github/workflows/build-prod-app.yml
Labels: size/S

#3439 fix: force lowercase letters on user handle (WPB-4820)
  app/src/main/kotlin/com/wire/android/ui/authentication/create/common/handle/UsernameTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/InputTransformations.kt
Labels: size/XS, echoes: bugs

#3438 feat: updated ux for adding participants [WPB-6294]
  app/src/main/kotlin/com/wire/android/mapper/ContactMapper.kt
  app/src/main/kotlin/com/wire/android/ui/common/AddContactButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/InternalContactSearchResultItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchAllPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUserViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/FolderHeader.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/SelectParticipantsButtonsRow.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/model/Contact.kt
  app/src/main/kotlin/com/wire/android/util/extension/LazyListScope.kt
  app/src/main/kotlin/com/wire/android/util/ui/ScrollUtil.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/search/SearchUserViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/search/adddembertoconversation/AddMembersToConversationViewModelTest.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WireButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryIconButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WireSecondaryIconButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WireTertiaryIconButton.kt
Labels: size/L, echoes: features

#3443 fix: change vibration pattern for ping (WPB-10804)
  app/src/main/kotlin/com/wire/android/media/PingRinger.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
Labels: size/XS, echoes: bugs

#3442 fix: App is showing a notification when starting a new call (WPB-11094)
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
Labels: size/XS, echoes: bugs

#3440 fix: Long usernames are not displayed correctly when calling in a group conversation (WPB-992)
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallerDetails.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/outgoing/OutgoingCallScreen.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/S, echoes: features

#3444 fix: Hide sketch button on asset restricted [WPB-10180]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposeActions.kt
Labels: size/XS, echoes: bugs

#3446 feat: add call rating analytics (WPB-11082)
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/model/AnalyticsEvent.kt
Labels: size/S

#3420 fix: Read receipts not generated when responding from notification (WPB-8756)
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/NotificationReplyReceiver.kt
Labels: size/XS, echoes: features

#3449 fix: move colliding file is prohibited text to new line (WPB-10181)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/asset/AssetMessageTypes.kt
Labels: size/XS, echoes: bugs

#3415 feat: display error when creating link a guest with password [WPB-10385]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/createPasswordProtectedGuestLink/CreatePasswordGuestLinkState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/createPasswordProtectedGuestLink/CreatePasswordGuestLinkViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/createPasswordProtectedGuestLink/CreatePasswordProtectedGuestLinkScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/CreatePasswordGuestLinkViewModelTest.kt
  config/detekt/detekt.yml
Labels: size/M, echoes: features

#3448 fix: wav to mp4 conversion [WPB-11095]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/AudioMediaRecorder.kt
Labels: size/XS, echoes: bugs

#3450 fix: crash on starting global analytics was not ready (WPB-11111)
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerImpl.kt
Labels: size/XS, echoes/initiative: product-metrics-in-countly

#3454 fix: add on change audio position from view model to ui (WPB-9664)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/ConversationMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/FileAssetsContent.kt
Labels: size/XS, echoes: bugs

#3435 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  core/ui-common/src/main/res/values-de/strings.xml
  core/ui-common/src/main/res/values-es/strings.xml
  core/ui-common/src/main/res/values-fr/strings.xml
  core/ui-common/src/main/res/values-hr/strings.xml
  core/ui-common/src/main/res/values-hu/strings.xml
  core/ui-common/src/main/res/values-it/strings.xml
  core/ui-common/src/main/res/values-ja/strings.xml
  core/ui-common/src/main/res/values-pl/strings.xml
  core/ui-common/src/main/res/values-pt/strings.xml
  core/ui-common/src/main/res/values-ru/strings.xml
  core/ui-common/src/main/res/values-si/strings.xml
  core/ui-common/src/main/res/values-sv/strings.xml
  core/ui-common/src/main/res/values-tr/strings.xml
Labels: size/S, crowdin, l10n, echoes: maintenance

#3456 fix: crash when starting foreground service for calling from background (WPB-11112)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationConstants.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/services/CallService.kt
  app/src/main/kotlin/com/wire/android/services/ServicesManager.kt
  app/src/test/kotlin/com/wire/android/notification/CallNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/services/ServicesManagerTest.kt
Labels: size/L, echoes: bugs

#3457 fix: crash on removing images on preview screen [WPB-11147]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/preview/ImagesPreviewScreen.kt
Labels: size/XS, echoes: bugs

#3460 fix: missing user status next to avatar [WPB-11191]
  app/src/androidTest/kotlin/com/wire/android/ui/common/UserProfileAvatarTest.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserStatusIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/ConversationParticipantItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItemLeading.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/FolderHeader.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/GroupConversationAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsNotFoundScreen.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/L, echoes: bugs

#3464 fix: Crash on starting foreground service for calling (WPB-11112)
  app/src/main/kotlin/com/wire/android/services/CallService.kt
  app/src/main/kotlin/com/wire/android/services/ServicesManager.kt
  app/src/test/kotlin/com/wire/android/services/ServicesManagerTest.kt
Labels: size/XS, echoes: bugs

#3467 fix: audio converting error on lower APIs [WPB-11242]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/AudioMediaRecorder.kt
Labels: size/XS

#3461 fix: message item click and long click areas [WPB-9077]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/ConversationMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/FileAssetsContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/InterceptClickable.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageClickActions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageContainerItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageItemComponents.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageTypesPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItemLeading.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/audio/AudioMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesResultsScreen.kt
Labels: size/L, echoes: features

#3468 feat: Hide Service switcher on creating MLS group [WPB-11156]
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupMetadataState.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupOptions/GroupOptionState.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupOptions/GroupOptionsScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelTest.kt
Labels: size/XS, echoes: maintenance, echoes/initiative: federation-wire-cloud

#3463 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-de/strings.xml
Labels: size/XS, crowdin, l10n, echoes: maintenance

#3476 fix: wrong service opens when clicking on search result [WPB-11330]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchAllServicesScreen.kt
Labels: size/XS
