Repository wireapp/wire-android, pull requests merged in 2024-10, with the labels that each got.

#3478 fix: showing user statuses on participants list [WPB-11191]
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/ConversationParticipantItem.kt
Labels: size/XS, echoes: bugs

#3481 feat: enable countly performance metrics (WPB-8842)
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModelTest.kt
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerImpl.kt
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorderImpl.kt
  core/analytics-enabled/src/test/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerTest.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManager.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerStub.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorder.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorderStub.kt
Labels: size/S, echoes/initiative: product-metrics-in-countly

#3487 refactor: update designs for QR button (WPB-10539)
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
Labels: size/S, echoes: features

#3492 fix: conversation search not working [WPB-11473]
  app/src/main/kotlin/com/wire/android/ui/home/HomeStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationsScreenContent.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
Labels: size/XS

#3482 feat: Add debug button send FCM token #WPB-9476
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptionsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/debug/LogOptions.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/res/values/strings.xml
  app/src/nonfree/kotlin/com/wire/android/services/WireFirebaseMessagingService.kt
  app/src/test/kotlin/com/wire/android/ui/settings/debug/DebugDataOptionsViewModelTest.kt
Labels: size/M

#3494 fix: status bar colour during theme change #WPB-11158
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBar.kt
Labels: size/S

#3486 feat: display error dialog when handling deeplinks #WPB-282
  app/src/main/kotlin/com/wire/android/ui/WireActivityDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/CustomServerDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/CustomServerInvalidJsonDialog.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModelTest.kt
Labels: size/S, echoes: bugs

#3489 chore: Update app version name #WPB-11429
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/migration/UpdateReceiver.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/about/AboutThisAppScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/about/AboutThisAppState.kt
  app/src/main/kotlin/com/wire/android/ui/settings/about/AboutThisAppViewModel.kt
  app/src/main/kotlin/com/wire/android/util/AppNameUtil.kt
  app/src/main/kotlin/com/wire/android/util/EmailComposer.kt
  app/src/main/kotlin/com/wire/android/util/UserAgentProvider.kt
  build-logic/plugins/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  build-logic/plugins/src/main/kotlin/AndroidCoordinates.kt
  build-logic/plugins/src/main/kotlin/AppVersionPlugin.kt
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
Labels: size/S, echoes: technical-debt

#3498 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/S, crowdin, l10n, echoes: maintenance

#3496 fix: disable autocorrect for all email text fields #WPB-11485
  app/src/main/kotlin/com/wire/android/ui/authentication/create/common/handle/UsernameTextField.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/ProxyScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/email/updateEmail/ChangeEmailScreen.kt
Labels: size/S

#3491 fix: Audio message slider style #WPB-11384
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/audio/AudioMessageType.kt
Labels: size/XS, echoes: bugs

#3500 fix: Avatar cancel button not working #WPB-6679
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPickerViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/image/AvatarPickerViewModelTest.kt
Labels: size/XS, echoes: bugs

#3508 fix: home screen transition issues [WPB-11580]
  app/src/main/kotlin/com/wire/android/ui/home/HomeStateHolder.kt
Labels: size/XS, echoes: bugs

#3504 fix: transition for share QR screen (WPB-10539)
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeScreen.kt
Labels: size/XS, echoes: features

#3506 fix: learn more link color [WPB-11189]
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreatePersonalAccountOverviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/TextWithLearnMore.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageItemComponents.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/EmptySearchQueryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesEmptyScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
Labels: size/S, echoes: bugs

#3499 fix: Do not display copy option for ephemeral messages #WPB-6678
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/MessageOptionsModalSheetLayout.kt
Labels: size/XS, echoes: bugs

#3483 fix: create a new group with guests disabled [WPB-10847]
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelTest.kt
Labels: size/XS, echoes: bugs

#3503 fix: restore quoted message from draft [WPB-11563]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/draft/MessageDraftViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
Labels: size/XS, echoes: bugs

#3514 ci: fix for frdroid build and gh action for deps (WPB-8645)
  .github/dependabot.yml
  .github/workflows/build-fdroid-app.yml
Labels: size/XS, echoes: throughput/ci-maintenance

#3529 chore: add icon and promo banner for f-droid client [WPB-11464]
  app/src/main/play/listings/en-US/graphics/feature-graphic/brandBanner.png
  app/src/main/play/listings/en-US/graphics/icon/brandLogo.png
Labels: size/XS, echoes: bugs, echoes: throughput/ci-maintenance

#3522 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-hu/strings.xml
Labels: size/S, crowdin, l10n, echoes: maintenance

#3495 feat: Add accessibility strings to conversation details [WPB-9784]
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/AppExtensions.kt
  app/src/main/kotlin/com/wire/android/ui/common/ArrowIcon.kt
  app/src/main/kotlin/com/wire/android/ui/common/MoreOptionIcon.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireCheckIcon.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireSwitch.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireTabRow.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/RichMenuBottomSheetItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/MutingOptionsSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/E2EIEnrollmentScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/set/SetLockCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/CreateGuestLinkBottomSheet.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editselfdeletingmessages/EditSelfDeletingMessagesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/ConversationParticipantItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationAllParticipantsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/ConversationMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/preview/ImagesPreviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/QuotedMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/location/LocationMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUsersAndServicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/RowItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreenTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupOptions/GroupOptionsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsOptionSwitch.kt
  app/src/main/kotlin/com/wire/android/ui/settings/about/AboutThisAppScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/e2ei/E2eiCertificateDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/util/extension/LazyListScope.kt
  app/src/main/res/values/strings.xml
  core/ui-common/src/main/kotlin/com/wire/android/model/Clickable.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/Extensions.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/bottomsheet/MenuBottomSheetItem.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/bottomsheet/ModalSheetHeaderItem.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WireSecondaryButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/topappbar/NavigationIconButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/topappbar/WireCenterAlignedTopAppBar.kt
  features/sketch/src/main/java/com/wire/android/feature/sketch/DrawingCanvasScreen.kt
Labels: size/M, echoes: features

#3534 other: localize some strings for a custom build (WPB-11703)
  app/src/main/kotlin/com/wire/android/navigation/OtherDestinations.kt
  app/src/main/res/values/strings.xml
Labels: size/XS

#3516 fix: Failed image message are not visible on chat #WPB-11035
  app/src/main/kotlin/com/wire/android/mapper/RegularMessageContentMapper.kt
Labels: size/XS, echoes: bugs

#3530 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-ru/strings.xml
  core/ui-common/src/main/res/values-hu/strings.xml
  features/sketch/src/main/res/values-hu/strings.xml
Labels: size/XS, crowdin, l10n, echoes: maintenance

#3515 fix: Draft message issue #WPB-11565
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/draft/MessageDraftViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerStateHolderTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolderTest.kt
Labels: size/XS, echoes: bugs

#3538 feat: screenshot tests [WPB-983]
  .gitattributes
  .github/workflows/generate-screenshots.yml
  app/build.gradle.kts
  app/src/screenshotTest/kotlin/com/wire/android/kotlin/ui/home/conversations/messages/item/PreviewMessageTypes.kt
  app/src/screenshotTest/kotlin/com/wire/android/kotlin/ui/home/conversations/messages/item/PreviewSystemMessageItem.kt
  gradle.properties
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: size/S, echoes: throughput/ci-maintenance

#3536 feat: add feature flag for displaying release notes sections (WPB-11702)
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewScreen.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
Labels: size/XS

#3517 feat: Create team upgrade flow (WPB-11268)
  app/src/main/kotlin/com/wire/android/navigation/TeamMigrationDestination.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/BottomLineButtons.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/BulletList.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/PersonalToTeamMigrationNavGraph.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step1/TeamMigrationTeamPlanStepScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step2/TeamMigrationTeamNameStepScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step3/TeamMigrationConfirmationStepScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step4/TeamMigrationDoneStepScreen.kt
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/values/strings.xml
  core/navigation/src/main/kotlin/com/wire/android/navigation/style/DefaultNavGraphAnimations.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/XL, echoes/initiative: personal-users-to-team-users...

#3549 chore: update compose bom to 2024.10.00 [WPB-11816]
  gradle/libs.versions.toml
Labels: size/XS

#3547 fix: Wrap persistent connection service in try Cherry-pick [WPB-11113]
  app/src/main/kotlin/com/wire/android/feature/StartPersistentWebsocketIfNecessaryUseCase.kt
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
  app/src/main/kotlin/com/wire/android/services/ServicesManager.kt
  app/src/test/kotlin/com/wire/android/feature/StartPersistentWebsocketIfNecessaryUseCaseTest.kt
Labels: size/XS, echoes: bugs, DO NOT CHERRY PICK

#3531 feat: Add accessibility string to OtherUserProfile and search participants [WPB-9784]
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/CopyButton.kt
  app/src/main/kotlin/com/wire/android/ui/common/SearchBar.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextFieldLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/SearchTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/ConversationMediaButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/InternalContactSearchResultItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchAllPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchAllServicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUsersAndServicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/FolderHeader.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/SelfDevicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileDetails.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileGroup.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/util/ui/StyledStringUtil.kt
  app/src/main/res/values/strings.xml
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WireButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WireSecondaryButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WireTertiaryButton.kt
Labels: size/S, echoes: features

#3554 fix: screenshot tests [WPB-983]
  .github/workflows/generate-screenshots.yml
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
Labels: size/XS, echoes: throughput/ci-maintenance

#3523 chore: add more debug information for sync #WPB-11603
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
Labels: size/XS, echoes: bugs

#3556 fix: can't change email #WPB-11676
  app/src/main/kotlin/com/wire/android/ui/common/textfield/InputTransformations.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/email/updateEmail/ChangeEmailScreen.kt
  app/src/main/kotlin/com/wire/android/util/Patterns.kt
Labels: size/XS, echoes: bugs

#3563 Update Jenkinsfile #WPB-11902
  Jenkinsfile
Labels: size/XS

#3524 fix: Ensure proper resource management by using .use for file operations [WPB-11908]
  ksp/src/main/kotlin/com/wire/android/di/ViewModelScopedPreview.kt
Labels: size/XS

#3569 feat: disable QR code by feature flag (WPB-11921)
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/util/debug/FeatureVisibilityFlags.kt
Labels: size/XS, echoes: features

#3568 feat: Add Accessibility strings to YourProfile [WPB-9826]
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreatePersonalAccountOverviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/AppExtensions.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDropDown.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireLabelledCheckbox.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/RichMenuBottomSheetItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupConversationNameComponent.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/QuotedMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/location/LocationMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUsersAndServicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesEmptyScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/FolderHeader.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/RowItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/common/LearnMoreAboutLegalHoldButton.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/res/values/strings.xml
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/Extensions.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/bottomsheet/MenuBottomSheetItem.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/topappbar/WireCenterAlignedTopAppBar.kt
  core/ui-common/src/main/res/values/strings.xml
Labels: size/S, echoes: features

#3564 fix: Location services availability crash #WPB-11304
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerHelper.kt
Labels: size/XS

#3565 feat: Track qr-code analytics #WPB-11679
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModelArrangement.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/model/AnalyticsEvent.kt
Labels: size/S, echoes: features

#3552 feat: Report Metric of Personal User creating a team in Countly (WPB-11318)
  app/src/main/kotlin/com/wire/android/datastore/UserDataStore.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/PersonalToTeamMigrationNavGraph.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step1/TeamMigrationTeamPlanStepScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step2/TeamMigrationTeamNameStepScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step3/TeamMigrationConfirmationStepScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step4/TeamMigrationDoneStepScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/HomeViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModelTest.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/model/AnalyticsEvent.kt
Labels: size/L, echoes/initiative: personal-users-to-team-users...

#3573 fix: wrong calling label used in outgoing screen (WPB-992)
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallerDetails.kt
  app/src/main/kotlin/com/wire/android/ui/calling/outgoing/OutgoingCallScreen.kt
Labels: size/XS, echoes: features
