Repository wireapp/wire-android, pull requests merged in 2024-03, with the labels that each got.

#2664 fix(e2ei): loading e2ei state during the app initialisation
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/XS

#2753 fix: unexpected scrolling on selected message [WPB-6932]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
Labels: size/XS

#2750 fix: Do not show waiting network in CertDetails screen(WPB-6638)
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
Labels: size/XS, cherry-pick

#2756 fix: unexpected scrolling on selected message [WPB-6932]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
Labels: size/XS, cherry-pick

#2757 fix: crash when checking audio file size limit (WPB-5961)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/AudioMediaRecorder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModelTest.kt
Labels: size/XS

#2761 chore(ci): Keep builds on Jenkins if certain branches were build
  AR-builder.groovy
Labels: size/XS

#2755 fix(e2ei): loading e2ei state during the app initialisation
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/XS, cherry-pick

#2762 fix: e2e webview close [WPB-6788]
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/GetE2EICertificateUI.kt
Labels: size/XS

#2760 fix: network screen is empty on graphene os
  app/src/main/kotlin/com/wire/android/ui/home/settings/appsettings/networkSettings/NetworkSettingsScreen.kt
Labels: size/XS

#2768 chore: explicitly restrict the app to be installed internally
  app/src/main/AndroidManifest.xml
Labels: size/XS

#2770 fix: persistent ws not reflected in UI (WPB-7020)
  app/src/main/kotlin/com/wire/android/ui/home/settings/appsettings/networkSettings/NetworkSettingsScreen.kt
Labels: size/XS

#2772 fix: crash when stopping recording audio [WPB-5961]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/AudioMediaRecorder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioInfoMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModelTest.kt
Labels: size/XS

#2752 feat: filter markdown by query [5164]
  app/src/main/kotlin/com/wire/android/mapper/RegularMessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/FileAssetsContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypesPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownBlockQuote.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownCodeBlock.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownComposer.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownHeading.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownHelper.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownList.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownNode.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownParagraph.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownTable.kt
  app/src/test/kotlin/com/wire/android/ui/markdown/MarkdownHelperTest.kt
  ksp/src/main/kotlin/com/wire/android/di/ViewModelScopedPreview.kt
Labels: size/XL

#2759 fix: user pic is not editable for scim users
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
Labels: size/XS

#2774 fix: Remove autologin in Keycloak in E2EI [WPB-7061]
  app/src/main/kotlin/com/wire/android/feature/e2ei/OAuthUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/GetE2EICertificateViewModel.kt
Labels: size/XS

#2778 fix: breaking changes from kalium
  app/src/main/kotlin/com/wire/android/ui/settings/devices/EndToEndIdentityCertificateItem.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/model/DeviceDetailsState.kt
Labels: size/XS

#2780 fix(calling): microphone restricted when the app goes into background on Android 14 (WPB-6307)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/services/OngoingCallService.kt
Labels: size/XS

#2771 fix: persistent ws not reflected in UI (WPB-7020)
  app/src/main/kotlin/com/wire/android/ui/home/settings/appsettings/networkSettings/NetworkSettingsScreen.kt
Labels: size/XS, cherry-pick

#2776 fix: user pic is not editable for scim users
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
Labels: size/XS, cherry-pick

#2775 fix: legal hold dialogs content [WPB-6469]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/subject/LegalHoldSubjectBaseDialog.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/subject/LegalHoldSubjectMessageDialog.kt
  app/src/main/res/values/strings.xml
Labels: size/XS

#2777 fix: Remove autologin in Keycloak in E2EI [WPB-7061]
  app/src/main/kotlin/com/wire/android/feature/e2ei/OAuthUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/GetE2EICertificateViewModel.kt
Labels: size/XS, cherry-pick

#2786 feat: show accent-colored user names in conversations [WPB-6891]
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/model/ImageAsset.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypesPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Accent.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/S

#2790 fix: Create Group protocol not editable anymore [WPB-7109]
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupConversationNameComponent.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupMetadataState.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelTest.kt
Labels: size/XS

#2773 fix: periodic checks for ws service to start if necessary (WPB-6343)
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/feature/StartPersistentWebsocketIfNecessaryUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/debug/StartServiceReceiver.kt
  app/src/main/kotlin/com/wire/android/workmanager/WireWorkerFactory.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/PersistentWebsocketCheckWorker.kt
  app/src/test/kotlin/com/wire/android/feature/StartPersistentWebsocketIfNecessaryUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/S

#2792 fix: periodic checks for ws service to start if necessary (WPB-6343)
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/feature/StartPersistentWebsocketIfNecessaryUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/debug/StartServiceReceiver.kt
  app/src/main/kotlin/com/wire/android/workmanager/WireWorkerFactory.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/PersistentWebsocketCheckWorker.kt
  app/src/test/kotlin/com/wire/android/feature/StartPersistentWebsocketIfNecessaryUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/S, cherry-pick

#2787 chore: update localization strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/XL, crowdin, l10n

#2791 fix: Create Group protocol not editable anymore [WPB-7109]
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupConversationNameComponent.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupMetadataState.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelTest.kt
Labels: size/XS, cherry-pick

#2795 fix: stay in call screen after back button from fullscreen [WPB-640]
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/FullScreenTile.kt
Labels: size/XS

#2805 fix: misleading dialog copy when certificate enrolling fails (WPB-7129)
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/E2EIEnrollmentScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/E2EIDialogs.kt
Labels: size/XS

#2798 fix: unnecessarily calls to updateVideoState function (WPB-6747)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
Labels: size/XS

#2807 fix: misleading dialog copy when certificate enrolling fails (WPB-7129)
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/E2EIEnrollmentScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/E2EIDialogs.kt
Labels: size/XS, cherry-pick

#2823 chore: move remove message to conv messages view model
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelTest.kt
Labels: size/M

#2818 fix: attachment options visible when navigating after searching [WPB-2425]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolderTest.kt
Labels: size/S

#2826 fix: input is hiding when searching and scrolling [WPB-271]
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesScreen.kt
Labels: size/XS

#2827 chore: handle uri asset
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/AssetBundle.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/usecase/HandleUriAssetUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportedMediaAsset.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportedMediaTypes.kt
  app/src/main/kotlin/com/wire/android/util/FileManager.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/usecase/HandleUriAssetUseCaseTest.kt
Labels: size/L

#2824 chore: extract send message to viemodel
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/ConversationMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/AssetBundle.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/usecase/HandleUriAssetUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportedMediaAsset.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportedMediaTypes.kt
  app/src/main/kotlin/com/wire/android/util/FileManager.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/usecase/HandleUriAssetUseCaseTest.kt
Labels: size/XL

#2825 fix: disable name change when e2ei is enabled
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountState.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModelTest.kt
Labels: size/XS

#2828 fix: update 2FA code and E2EI enrollment screens UI [WPB-6772]
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailVerificationCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/E2EIEnrollmentScreen.kt
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/S

#2833 feat: enable encrypted proteus storage for internal builds
  default.json
Labels: size/XS

#2837 fix: init temp writable uri
  app/src/main/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModelArrangement.kt
Labels: size/XS

#2731 chore: add git commit hash to external logger
  app/src/beta/kotlin/com/wire/android/ExternalLoggerManager.kt
Labels: size/XS, cherry-pick

#2720 chore: add Technolinator config for dependencytrack, setting the correct java version (SEC-598)
  .github/technolinator.yml
Labels: size/XS
