Repository wireapp/wire-android, pull requests merged in 2024-06, with the labels that each got.

#3060 fix: errors in fdroid build script causeing it to build DevDebug instead of FdroidRelease
  build.gradle.kts
  buildSrc/src/main/kotlin/scripts/infrastructure.gradle.kts
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
  docker-agent/builder.sh
Labels: size/XS

#3061 fix: swipe to reply not working on first try
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
Labels: size/XS

#3070 ci: use Android Bob GH token for cherrypicks
  .github/workflows/cherry-pick-pr-to-newer-release-cycle.yml
Labels: size/XS

#3072 ci: use Android Bob GH token for cherrypicks 🍒
  .github/workflows/cherry-pick-pr-to-newer-release-cycle.yml
Labels: size/XS

#3059 refactor: update text input logic to v2 TextFieldState, part 4 [WPB-8779]
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/common/PreviewWireDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupConversationNameComponent.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupMetadataState.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupNameValidator.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/createPasswordProtectedGuestLink/CreatePasswordGuestLinkState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/createPasswordProtectedGuestLink/CreatePasswordGuestLinkViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/createPasswordProtectedGuestLink/CreatePasswordProtectedGuestLinkScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/metadata/EditConversationMetadataViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/metadata/EditConversationNameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupname/NewGroupNameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogFlow.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/restore/RestoreBackupDialogFlow.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/restore/RestoreBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/joinConversation/JoinConversationViaCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/joinConversation/JoinConversationViaDeepLinkDialog.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/requested/LegalHoldRequestedDialog.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/requested/LegalHoldRequestedState.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/requested/LegalHoldRequestedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/CreatePasswordGuestLinkViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerHelperTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/home/BackupAndRestoreViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/joinDeepLink/JoinConversationViaCodeViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/legalhold/dialog/requested/LegalHoldRequestedViewModelTest.kt
Labels: size/XL

#3065 fix: bottom sheet state [WPB-9045]
  app/src/main/kotlin/com/wire/android/navigation/HomeDestination.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/PreviewWireModalSheetLayout.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeSnackBarMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeSnackbarState.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/archive/ArchiveScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/call/ConversationListCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/ConversationMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationCallListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/all/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/call/CallLabel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/call/CallsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/mention/MentionScreen.kt
  app/src/main/kotlin/com/wire/android/util/ui/SnackBarMessageHandler.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/call/ConversationListCallViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationCallListViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetLayout.kt
Labels: size/XL

#3074 fix: asset preview tile name [WPB-8801]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/preview/AssetTilePreview.kt
Labels: size/XS

#3040 fix: OtherUser devices: wrong MLS data [WPB-8908]
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/model/Device.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/SelfDevicesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/settings/devices/SelfDevicesViewModelTest.kt
Labels: size/XS

#3076 feat: add anonymous analytics (WPB-8933)
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  build-logic/plugins/src/main/kotlin/AndroidLibraryConventionPlugin.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  core/analytics-disabled/.gitignore
  core/analytics-disabled/build.gradle.kts
  core/analytics-disabled/consumer-rules.pro
  core/analytics-disabled/lint-baseline.xml
  core/analytics-disabled/proguard-rules.pro
  core/analytics-disabled/src/main/AndroidManifest.xml
  core/analytics-disabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerImpl.kt
  core/analytics-disabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorderImpl.kt
  core/analytics-disabled/src/main/res/values/strings.xml
  core/analytics-enabled/.gitignore
  core/analytics-enabled/build.gradle.kts
  core/analytics-enabled/consumer-rules.pro
  core/analytics-enabled/lint-baseline.xml
  core/analytics-enabled/proguard-rules.pro
  core/analytics-enabled/src/main/AndroidManifest.xml
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerImpl.kt
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorderImpl.kt
  core/analytics-enabled/src/main/res/values/strings.xml
  core/analytics-enabled/src/test/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerTest.kt
  core/analytics/.gitignore
  core/analytics/build.gradle.kts
  core/analytics/consumer-rules.pro
  core/analytics/lint-baseline.xml
  core/analytics/proguard-rules.pro
  core/analytics/src/main/AndroidManifest.xml
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManager.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerStub.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorder.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorderStub.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/model/AnalyticsEvent.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/model/AnalyticsSettings.kt
  core/analytics/src/main/res/values/strings.xml
  default.json
  features/template/lint-baseline.xml
  gradle/libs.versions.toml
Labels: size/XL

#3068 chore: update localization sources from Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/S, crowdin, l10n

#3078 fix: dividers in privacy settings [WPB-3985]
  app/lint-baseline.xml
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreatePersonalAccountOverviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/summary/CreateAccountSummaryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/register/RegisterDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/SettingUpWireScreenContent.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireTabRow.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupOptions/GroupOptionsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownThematicBreak.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/divider/WireDivider.kt
Labels: size/XL

#3077 fix: issues with sharing media [WPB-9550]
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
Labels: size/S

#3080 refactor: update text input logic to v2 TextFieldState, part 5 [WPB-8779]
  app/src/main/kotlin/com/wire/android/ui/common/CollapsingTopBarScaffold.kt
  app/src/main/kotlin/com/wire/android/ui/common/SearchBar.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/SearchBarState.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/search/SearchTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchAllPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchAllServicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchBarViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchServicesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUserViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/adddembertoconversation/AddMembersSearchScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupsearch/NewGroupConversationSearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/NewConversationSearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/SearchConversationMessagesViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/search/SearchBarViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/search/SearchUserViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
Labels: size/L

#3058 ci: upload the app to Play Store (WPB-8729)
  .github/workflows/build-beta-app.yml
  .github/workflows/build-prod-app.yml
Labels: size/XS

#3088 fix: more issues with sharing media [WPB-9550]
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
Labels: size/XS

#3086 chore: update dependencies
  gradle/libs.versions.toml
Labels: size/XS

#3063 chore: Upload build to S3 [WPB-8730]
  .github/actions/deploy-to-s3/action.yml
  .github/workflows/build-beta-app.yml
  .github/workflows/build-develop-app.yml
  .github/workflows/build-prod-app.yml
  .github/workflows/build-rc-app.yml
Labels: size/S

#3085 fix: After sending a reaction, keyboard opens automatically (WPB-9358)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
Labels: size/XS

#3089 fix: remove brackets from build file name
  build-logic/plugins/src/main/kotlin/AndroidApplicationConventionPlugin.kt
Labels: size/XS

#3090 refactor: update text input logic to v2 TextFieldState, part 6 [WPB-8779]
  app/src/main/kotlin/com/wire/android/ui/common/textfield/CodeTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/CodeTextFieldLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/StateSyncingModifier.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextFieldAutoFill.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextFieldLayout.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/draft/MessageDraftViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/model/MessageComposition.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/draft/MessageDraftViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerStateHolderTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolderTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolderTest.kt
Labels: size/XL

#3095 fix: change default lineLimits for text fields to be single-line
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
Labels: size/XS

#3093 chore: add compose-runtime to Benchmark module
  benchmark/build.gradle.kts
  gradle/libs.versions.toml
Labels: size/XS

#3064 fix: make learn more links clickable for automation v2 [WPB-5888]
  app/src/main/kotlin/com/wire/android/ui/common/PreviewTextWithLinkSuffix.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/TextWithLinkSuffix.kt
Labels: size/S

#3096 fix: inject usecases lazily in WireActivityViewModel (WPB-6874)
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/S

#3094 fix: change display name state [WPB-9653]
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/displayname/ChangeDisplayNameViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/displayname/ChangeDisplayNameViewModelTest.kt
Labels: size/XS

#3098 chore: unify external logger code
  app/build.gradle.kts
  app/src/beta/kotlin/com/wire/android/navigation/TrackingNavController.kt
  app/src/beta/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/dev/kotlin/com/wire/android/ExternalLoggerManager.kt
  app/src/internal/kotlin/com/wire/android/ExternalLoggerManager.kt
  app/src/internal/kotlin/com/wire/android/navigation/TrackingNavController.kt
  app/src/internal/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/private/kotlin/com/wire/android/ExternalLoggerManager.kt
  app/src/private/kotlin/com/wire/android/navigation/TrackingNavController.kt
  app/src/private/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/public/kotlin/com/wire/android/ExternalLoggerManager.kt
  app/src/public/kotlin/com/wire/android/navigation/TrackingNavController.kt
  app/src/public/kotlin/com/wire/android/util/DataDogLogger.kt
  app/src/staging/kotlin/com/wire/android/ExternalLoggerManager.kt
  app/src/staging/kotlin/com/wire/android/navigation/TrackingNavController.kt
  app/src/staging/kotlin/com/wire/android/util/DataDogLogger.kt
Labels: size/L

#3099 fix: hide speaker button from IncomingCallScreen (WPB-9031)
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CallOptionsControls.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
Labels: size/XS

#3100 fix: run WireViewModel usecases on worker thread (WPB-6874)
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/S

#3101 fix: exception when executing multiple fetches of the same avatar [WPB-9640]
  app/src/main/kotlin/com/wire/android/util/ui/AssetImageFetcher.kt
Labels: size/XS

#3109 fix: breaking changes from kalium
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
Labels: size/XS

#3112 ci: configure jira linking action to run on all PRs [WPB-9779]
  .github/workflows/jira-lint-and-link.yml
Labels: size/XS

#3116 ci: add DataDog tokens to GitHub workflows [WPB-9788]
  .github/workflows/build-beta-app.yml
  .github/workflows/build-develop-app.yml
  .github/workflows/build-rc-app.yml
  app/build.gradle.kts
Labels: size/XS

#3104 chore: remove any mention to maven local repo [WPB-2799]
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/build.gradle.kts
Labels: size/XS

#3066 fix: ANR when recording an audio (WPB-9528)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModelTest.kt
Labels: size/XS

#2930 feat(config): separate lower KeyPackage limit and set to false (WPB-8685)
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
Labels: size/XS, cherry-pick

#3110 fix: missing remove device button [WPB-8819]
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/SelfDevicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/SelfDevicesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/model/SelfDevicesState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/TestUtil.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/settings/devices/SelfDevicesViewModelTest.kt
Labels: size/M

#3121 fix: camera on/off button when in fullscreen [WPB-9815]
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
Labels: size/XS

#3127 fix: audio converting time [WPB-9705]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/AudioMediaRecorder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/GenerateAudioFileWithEffectsUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioButtons.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioComponent.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModel.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModelTest.kt
Labels: size/M

#3129 fix: wrong caller name in outgoing call (WPB-9758)
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/ConnectivityUIState.kt
Labels: size/XS

#3132 fix: audio converting time - rc 4.7 [WPB-9705]
  app/lint-baseline.xml
  app/src/main/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/AudioMediaRecorder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/GenerateAudioFileWithEffectsUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioButtons.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioComponent.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModel.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModelTest.kt
Labels: size/L

#3130 fix: crash when loading what's new section [WPB-9810]
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewViewModelTest.kt
  default.json
Labels: size/S

#3131 ci: s3 path for artifacts adjustment (WPB-8730)
  .github/actions/deploy-to-s3/action.yml
Labels: size/XS

#3137 fix: device list dividers [WPB-8829]
  app/src/main/kotlin/com/wire/android/ui/WireActivityDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/SelfDevicesScreen.kt
Labels: size/XS

#3140 ci: allow parallel merge queue builds [WPB-9914]
  .github/workflows/build-develop-app.yml
  .github/workflows/build-rc-app.yml
Labels: size/XS
