Repository wireapp/wire-android, pull requests merged in 2024-07, with the labels that each got.

#3144 ci: adjust flavors built for QA automation (WPB-8730)
  .github/workflows/build-develop-app.yml
  .github/workflows/build-rc-app.yml
Labels: size/XS

#3148 chore: update compose libs to get rid of rendering crashes [WPB-9666]
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  gradle/libs.versions.toml
Labels: size/XS

#3154 fix: cherrypick terms of use copy (WPB-8846)
  app/src/main/kotlin/com/wire/android/navigation/OtherDestinations.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/XS

#3152 feat: Enable running end to end automation on Android PR (WPB-9676)
  Jenkinsfile
Labels: size/S

#3158 chore: externalize all wire links to support custom builds (WPB-9811)
  app/src/main/kotlin/com/wire/android/navigation/OtherDestinations.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/EmptySearchQueryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesEmptyScreen.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/S

#3161 docs: improve customization documentation [WPB-10019]
  CUSTOMIZATION.md
  README.md
  buildSrc/src/main/kotlin/customization/Customization.kt
Labels: size/S

#3142 chore: Move Analytics to user-level (WPB-9584)
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/datastore/UserDataStore.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsViewModelTest.kt
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorderImpl.kt
Labels: size/XS

#3162 fix: self deleting option refreshing [WPB-9419]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/selfdeletion/SelfDeletionMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AttachmentOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposeActions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/actions/SelfDeletingMessageActionArgs.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/actions/SelfDeletingMessageActionViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/restore/RestoreBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/composer/actions/SelfDeletingMessageActionViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerStateHolderTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolderTest.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WireSecondaryIconButton.kt
Labels: size/L

#3163 fix: handling ActivityNotFoundExceptions [WPB-9794]
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CallOptionsControls.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/CameraButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/JoinButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/StartCallButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/outgoing/OutgoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/imagepreview/AvatarPickerFlow.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/DownloadedAssetDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/all/AllConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/search/SearchConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AttachmentOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/location/LocationPickerComponent.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioComponent.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogFlow.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/restore/RestoreBackupDialogFlow.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/restore/RestoreBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPickerState.kt
  app/src/main/kotlin/com/wire/android/util/permission/CallingCameraRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/CallingRecordAudioRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/CaptureVideoRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/CreateFileRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/CurrentLocationRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/IntentPermissionsRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/IntentPermissionsRequestFlows.kt
  app/src/main/kotlin/com/wire/android/util/permission/OpenFileBrowserRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/OpenGalleryRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/PermissionDenialType.kt
  app/src/main/kotlin/com/wire/android/util/permission/PermissionsRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/PermissionsRequestFlows.kt
  app/src/main/kotlin/com/wire/android/util/permission/RecordAudioRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/RequestLauncher.kt
  app/src/main/kotlin/com/wire/android/util/permission/RequestPushNotificationsPermissionFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/TakePictureRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/UseCameraAndWriteStorageRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/UseStorageRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/WriteStorageRequestFlow.kt
  app/src/main/res/values/strings.xml
Labels: size/XL

#3167 fix: unfocus message composer when keyboard hides [WPB-9722]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
Labels: size/XS

#3169 fix: Better error messages on github action or smoke run failures (WPB-9676)
  Jenkinsfile
Labels: size/XS

#3172 chore: include crowdin translations updater for modules (WPB-10073)
  core/analytics-disabled/src/main/res/values/strings.xml
  core/analytics-enabled/src/main/res/values/strings.xml
  core/analytics/src/main/res/values/strings.xml
  crowdin.yml
  features/sketch/src/main/res/values/strings.xml
  features/template/src/main/res/values/strings.xml
Labels: size/XS

#3173 fix: fix notification by preventing countly form blocking the app start [WPB-10072]
  app/src/main/kotlin/com/wire/android/WireApplication.kt
Labels: size/XS

#3177 fix: Make smoke tests not report if github actions are aborted (WPB-9676)
  Jenkinsfile
Labels: size/XS

#3175 fix: self clients slow loading [WPB-9919]
  app/src/main/kotlin/com/wire/android/ui/settings/devices/SelfDevicesViewModel.kt
Labels: size/XS

#3176 fix: anonymous analytics manager initialisation [WPB-10063]
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerImpl.kt
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorderImpl.kt
  core/analytics-enabled/src/test/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerTest.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManager.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerStub.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorder.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorderStub.kt
Labels: size/S

#3184 fix: analytics initialization crash (WPB-10063)
  app/src/main/kotlin/com/wire/android/WireApplication.kt
Labels: size/XS

#3185 feat: enable password protected guest links WPB-9529
  default.json
Labels: size/XS

#3186 fix: double ringing on incoming call screen and swipeable notifications [WPB-9963]
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/CallNotificationDismissedReceiver.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/DeclineIncomingCallReceiver.kt
  app/src/main/kotlin/com/wire/android/services/OngoingCallService.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
  app/src/test/kotlin/com/wire/android/notification/CallNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModelTest.kt
Labels: size/M, echoes: bugs

#3188 fix: flickering call other participants video (WPB-9617)
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  gradle/libs.versions.toml
Labels: size/XS, echoes: bugs

#3187 fix: "All Android Release Notes" item is not clickable [WPB-10125]
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/RowItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/about/dependencies/DependenciesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewViewModel.kt
Labels: size/S

#3203 ci: upload apk to latest release after uploading to playstore (WPB-8645)
  .github/workflows/build-prod-app.yml
  .github/workflows/generate-changelog.yml
Labels: size/XS

#3202 fix: call participants tiles UI [WPB-10149]
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/FullScreenTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantsTiles.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/gridview/CallingGridView.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/horizentalview/CallingHorizontalView.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/UsersTypingIndicator.kt
  app/src/main/kotlin/com/wire/android/util/extension/LazyListScope.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/XL

#3211 fix: "All Android Release Notes" item is not clickable - 🍒 v4.6 [WPB-10125]
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/RowItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewViewModel.kt
Labels: size/S

#3214 fix: "All Android Release Notes" item is not clickable - 🍒 v4.7 [WPB-10125]
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/RowItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewViewModel.kt
Labels: size/S

#3209 fix: keep screen on during ongoing call [WPB-9033]
  app/src/main/kotlin/com/wire/android/ui/calling/CallActivity.kt
Labels: size/XS, echoes: bugs

#3212 fix: typo in a system message (WPB-9776)
  app/src/main/res/values/strings.xml
Labels: size/XS

#3215 fix: user logged out listener [WPB-10114]
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/XS, echoes: bugs

#3219 ci: codecov fix and rc workflow tweak (WPB-8645)
  .github/workflows/build-rc-app.yml
  .github/workflows/gradle-run-unit-tests.yml
Labels: size/XS, echoes: throughput/ci-maintenance

#3229 chore: use manifest placeholder to get rid of playstore error (WPB-8645)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/util/extension/Context.kt
  app/src/nonfree/kotlin/com/wire/android/initializer/FirebaseInitializer.kt
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
Labels: size/XS, echoes: throughput/ci-maintenance

#3227 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-si/strings.xml
Labels: size/XS, crowdin, l10n

#3217 fix: sharing button is disabled [WPB-9947]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/attachments/IsFileSharingEnabledViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/attachments/IsFileSharingEnabledViewModelTest.kt
Labels: size/S

#3228 chore: disable countly [WPB-10293]
  default.json
Labels: size/XS, echoes/initiative: product-metrics-in-countly

#3239 fix: multiline topbar title not centered [WPB-9608]
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/WireCenterAlignedTopAppBar.kt
Labels: size/XS

#3238 ci: build fdroid for regression testing [WPB-10367]
  .github/workflows/build-fdroid-app.yml
Labels: size/XS

#3249 chore: update strings copies by content writer (WPB-9776)
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantTile.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBar.kt
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/XS

#3253 fix: empty backup file name [WPB-10210]
  app/src/main/kotlin/com/wire/android/util/permission/IntentPermissionsRequestFlow.kt
  app/src/main/kotlin/com/wire/android/util/permission/PermissionsRequestFlow.kt
Labels: size/XS, echoes: bugs

#3255 fix: disable clicks under record audio [WPB-9619]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioComponent.kt
Labels: size/XS, echoes: bugs

#3248 ci: upload fdroid builds from the correct folder [WPB-10367]
  .github/workflows/build-fdroid-app.yml
Labels: size/XS
