Repository wireapp/wire-android, pull requests merged in 2024-04, with the labels that each got.

#2822 fix: update last read message on conversation opening [WPB-7208]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
Labels: size/XS, cherry-pick

#2840 fix: conversation options divider [WPB-3985]
  app/src/main/kotlin/com/wire/android/ui/common/divider/WireDivider.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsScreen.kt
Labels: size/XS

#2843 chore: local navigator [ACOL-153]
  app/src/main/kotlin/com/wire/android/navigation/Navigator.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/theme/Theme.kt
Labels: size/XS

#2844 fix: padding for single asset in import media [WPB-1839]
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
Labels: size/XS

#2841 fix: disable sound and vibration for notification reply [WPB-4741]
  app/src/main/kotlin/com/wire/android/notification/MessageNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationConstants.kt
Labels: size/XS

#2847 fix: audio message filter toggle (WPB-6406)
  app/src/main/kotlin/com/wire/android/media/audiomessage/RecordAudioMessagePlayer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/GenerateAudioFileWithEffectsUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioButtons.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioComponent.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModelTest.kt
Labels: size/S

#2849 refactor: simplify dependency version resource generation
  buildSrc/src/main/kotlin/DependenciesVersionTask.kt
  buildSrc/src/main/kotlin/WriteKeyValuesToFileTask.kt
  buildSrc/src/main/kotlin/scripts/compilation.gradle.kts
  settings.gradle.kts
Labels: size/S

#2842 fix: message content padding [WPB-987]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/FileAssetsContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageContainerItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageItemComponents.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageItemTemplate.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageStatusIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageTypesPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/PreviewSystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItemLeading.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/SystemMessageItemLeading.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesResultsScreen.kt
Labels: size/XL

#2852 fix: crash when checking audio file size limit (WPB-5961) (#2757)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/AudioMediaRecorder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioInfoMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModelTest.kt
Labels: size/S

#2853 fix: Revoked Certificate dialog undismissable [WPB-7226]
  app/src/main/kotlin/com/wire/android/ui/home/E2EIDialogs.kt
Labels: size/XS

#2858 fix: lintVitalAnalyze failing because of dependenciesVersionTask
  buildSrc/src/main/kotlin/scripts/compilation.gradle.kts
Labels: size/XS

#2854 fix: RevokedCertificate dialog undismissable RC [WPB-7226]
  app/src/main/kotlin/com/wire/android/ui/home/E2EIDialogs.kt
Labels: size/XS

#2856 fix: Remove NotificationDot for some notifications RC
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
Labels: size/XS

#2857 fix: run observers on workers thread to avoid ANRs (WPB-6051)
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
Labels: size/XS

#2864 fix: crash on GrapheneOS when downloading certificate (WPB-7407)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/AudioMediaRecorder.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/e2ei/E2eiCertificateDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/e2ei/E2eiCertificateDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/util/DateTimeUtil.kt
Labels: size/XS

#2865 refactor: update SwipeableSnackbar
  app/src/main/kotlin/com/wire/android/ui/common/snackbar/SwipeableSnackbar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/XS

#2866 feat: test and detekt run on ci for modules - sketch pt4
  app/build.gradle.kts
  build-logic/plugins/build.gradle.kts
  build-logic/plugins/src/main/kotlin/KoverConventionPlugin.kt
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/scripts/infrastructure.gradle.kts
  buildSrc/src/main/kotlin/scripts/quality.gradle.kts
  config/detekt/baseline.xml
  core/ui-common/build.gradle.kts
  features/sketch/build.gradle.kts
  features/template/build.gradle.kts
  gradle/libs.versions.toml
Labels: size/S

#2851 refactor: simplify dependency version resource generation
  buildSrc/src/main/kotlin/DependenciesVersionTask.kt
  buildSrc/src/main/kotlin/WriteKeyValuesToFileTask.kt
  buildSrc/src/main/kotlin/scripts/compilation.gradle.kts
  settings.gradle.kts
Labels: size/S, cherry-pick

#2873 fix: test for multimodule
  build-logic/plugins/src/main/kotlin/AndroidLibraryConventionPlugin.kt
  buildSrc/src/main/kotlin/scripts/infrastructure.gradle.kts
Labels: size/XS

#2872 fix: close properly keyboard in conversation screen [WPB-7630]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/AdditionalOptionMenuState.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolderTest.kt
Labels: size/S

#2876 fix: read conversation on short list [WPB-7432]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
Labels: size/XS

#2863 fix: Remove NotificationDot for some notifications RC
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
Labels: size/XS, cherry-pick

#2868 fix: Display verified E2EI icon other user devices list [WPB-6974]
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
Labels: size/XS

#2850 feat: image preview [WPB-6733]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/preview/ImagesPreviewNavArgs.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/preview/ImagesPreviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/preview/ImagesPreviewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/preview/ImagesPreviewViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AttachmentOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
Labels: size/M

#2883 fix: misleading e2ei certificate error dialog (WPB-7129)
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/E2EIEnrollmentScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/E2EIDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/res/values/strings.xml
Labels: size/XS

#2885 fix: misleading e2ei certificate error dialog (WPB-7129)
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/E2EIEnrollmentScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/E2EIDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/res/values/strings.xml
Labels: size/XS, cherry-pick

#2816 feat: add fdroid to jenkins script
  AR-builder.groovy
  Jenkinsfile
Labels: size/XS, cherry-pick

#2877 fix: read conversation on short list [WPB-7432]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/AuthorHeaderHelper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
Labels: size/XS, cherry-pick

#2887 fix: remove dot from title string
  app/src/main/res/values/strings.xml
Labels: size/XS

#2888 fix: remove dot from title string
  app/src/main/res/values/strings.xml
Labels: size/XS, cherry-pick

#2804 feat: add a crl revocation list to debug screen
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugScreen.kt
Labels: size/XS, cherry-pick

#2845 fix: startup crash with fdroid [WPB-7286]
  app/build.gradle.kts
  app/src/fdroid/AndroidManifest.xml
Labels: size/XS

#2890 fix: error in deciding whether the current build should use open source only dependencies or not
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/src/main/kotlin/scripts/infrastructure.gradle.kts
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
Labels: size/XS

#2870 refactor: update participants list to new designs [WPB-986]
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/CollapsingTopBarScaffold.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireTabRow.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipants.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantsState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/ConversationMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/util/extension/LazyListScope.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantsViewModelTest.kt
Labels: size/M

#2869 fix: add last backup date (WPB-1897)
  app/src/main/kotlin/com/wire/android/datastore/UserDataStore.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreState.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/BackupAndRestoreViewModel.kt
  app/src/main/kotlin/com/wire/android/util/time/LocalTimeFormater.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/settings/home/BackupAndRestoreViewModelTest.kt
Labels: size/S

#2894 feat: display avs and CC version on all builds
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptionsState.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptionsViewModel.kt
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/scripts/compilation.gradle.kts
Labels: size/L

#2904 feat: reply markdown [WPB-3558]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/QuotedMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/LastMessageSubtitle.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownInline.kt
Labels: size/XS

#2899 fix: not possible to accept legal hold as SSO user [WPB-8719]
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/requested/LegalHoldRequestedViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/legalhold/dialog/requested/LegalHoldRequestedViewModelTest.kt
Labels: size/S

#2900 feat: display avs and CC version on all builds
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptionsState.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptionsViewModel.kt
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/scripts/compilation.gradle.kts
Labels: size/L, cherry-pick

#2882 refactor: Move calling to a separate activity (WPB-6437)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/navigation/style/NavigationAnimationStyles.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationActions.kt
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/ui/AppLockActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/CallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/CallScreenType.kt
  app/src/main/kotlin/com/wire/android/ui/calling/CallingNavArgs.kt
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallerDetails.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/unlock/EnterLockCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
  app/src/main/kotlin/com/wire/android/util/deeplink/DeepLinkProcessor.kt
  app/src/main/kotlin/com/wire/android/util/ui/ScreenSettingsUtil.kt
  app/src/test/kotlin/com/wire/android/feature/AccountSwitchUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/calling/OngoingCallViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/calling/initiating/InitiatingCallViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/DeepLinkProcessorTest.kt
Labels: size/XL

#2902 fix: local image bad quality [WPB-1839]
  app/src/main/kotlin/com/wire/android/model/ImageAsset.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/image/ImageMessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/ZoomableImage.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportedMediaAsset.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportedMediaTypes.kt
  app/src/main/kotlin/com/wire/android/util/ui/AssetImageFetcher.kt
  app/src/main/kotlin/com/wire/android/util/ui/DrawableResultWrapper.kt
  app/src/main/kotlin/com/wire/android/util/ui/WireSessionImageLoader.kt
  app/src/test/kotlin/com/wire/android/model/ImageAssetTest.kt
  app/src/test/kotlin/com/wire/android/util/ui/AssetImageFetcherTest.kt
Labels: size/S

#2891 fix: error in deciding whether the current build should use open source only dependencies or not
  app/build.gradle.kts
  build.gradle.kts
  buildSrc/src/main/kotlin/scripts/infrastructure.gradle.kts
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
Labels: size/XS, cherry-pick

#2909 fix: bottom-sheet-dividers [WPB-3985]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/bottomsheet/MenuBottomSheetItem.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/bottomsheet/ModalSheetHeaderItem.kt
Labels: size/XS

#2911 feat: update dependencies
  gradle/libs.versions.toml
Labels: size/XS

#2914 fix: message details tab counter [WPB-8798]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsScreen.kt
Labels: size/XS

#2906 fix: secure switching to invalid account and disable composer [WPB-7369]
  app/src/main/kotlin/com/wire/android/feature/AccountSwitchUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModel.kt
  app/src/test/kotlin/com/wire/android/feature/AccountSwitchUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewModelTest.kt
Labels: size/S

#2916 fix: create group contacts selection, hide show less button [WPB-6975] [WPB-8813]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchAllPeopleScreen.kt
Labels: size/XS

#2919 fix: sketch general issues (WPB-8810) (WPB-8811) (WPB-8812)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  features/sketch/src/main/java/com/wire/android/feature/sketch/DrawingCanvasBottomSheet.kt
  features/sketch/src/main/java/com/wire/android/feature/sketch/DrawingCanvasComponent.kt
  features/sketch/src/main/java/com/wire/android/feature/sketch/DrawingToolPicker.kt
Labels: size/XS

#2920 fix: prevent screenshots when it's enabled in CallActivity
  app/src/main/kotlin/com/wire/android/ui/calling/CallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/CallActivityViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/CallActivityViewModelTest.kt
Labels: size/S

#2927 feat(config): separate lower KeyPackage limit and set to false (WPB-8685)
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
Labels: size/XS

#2923 refactor: make learn more links clickable for automation [WPB-5888]
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/PreviewTextWithLinkSuffix.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/CreateGroupErrorDialog.kt
  app/src/main/kotlin/com/wire/android/util/CoreFailureUtil.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/TextWithLinkSuffix.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
Labels: size/M, cherry-pick

#2926 fix: remove duplicated debug id in settings screen [WPB-8626]
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
Labels: size/XS

#2921 fix: message reaction details crash [WPB-8802]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsReactions.kt
Labels: size/XS

#2933 fix: remove duplicated debug id in settings screen [WPB-8626]
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
Labels: size/XS, cherry-pick

#2935 chore: update wrong copy
  app/src/main/res/values/strings.xml
Labels: size/XS

#2931 chore: replace deprecated functions
  app/src/main/kotlin/com/wire/android/mapper/SystemMessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/ProxyScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDropDown.kt
  app/src/main/kotlin/com/wire/android/ui/common/banner/SecurityClassificationBanner.kt
  app/src/main/kotlin/com/wire/android/ui/emoji/HandleDraggableBottomSheetDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipants.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/call/CallsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/mention/MentionScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/ZoomableImage.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/AdditionalOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/DropDownMentionsSuggestions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MembersMentionList.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/create/CreateBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/backup/dialog/restore/RestoreBackupDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/SelfDevicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
Labels: size/S

#2937 fix(calling): pause the video feed when the lifecycle is paused and resume it when the lifecycle is resumed (WPB-7304)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/calling/OngoingCallViewModelTest.kt
Labels: size/S

#2929 fix: show incoming call screen for second account
  app/src/main/kotlin/com/wire/android/feature/AccountSwitchUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/calling/CallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/CallActivityViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/CallActivityViewModelTest.kt
Labels: size/XS

#2898 chore: update localization strings via Crowdin
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/XL, crowdin, l10n

#2879 fix: Display verified E2EI icon other user devices list [WPB-6974]
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserDevicesScreen.kt
Labels: size/XS, cherry-pick

#2939 fix: request video streams after creating renderers (WPB-8808)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/ParticipantsTiles.kt
Labels: size/XS

#2943 fix: empty html message
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownHelper.kt
Labels: size/XS

#2947 fix: text changes for the new group creation flow [WPB-1630]
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/SelectParticipantsButtonsRow.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/NewConversationSearchPeopleScreen.kt
  app/src/main/res/values/strings.xml
Labels: size/XS
