Repository wireapp/wire-android, pull requests merged in 2024-08, with the labels that each got.

#3252 refactor: use proper ids for notifications ids (improvement) (WPB-9965)
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationConstants.kt
  app/src/main/kotlin/com/wire/android/services/OngoingCallService.kt
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/MigrationWorker.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/NotificationFetchWorker.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/SingleUserMigrationWorker.kt
Labels: size/XS, DO NOT MERGE, echoes: bugs

#3251 fix: can not interact with second incoming call (WPB-9965)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/migration/MigrationManager.kt
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationConstants.kt
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/kotlin/com/wire/android/services/OngoingCallService.kt
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/CallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/StartingCallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/StartingCallScreenType.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallState.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationRouter.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/MigrationWorker.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/NotificationFetchWorker.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/SingleUserMigrationWorker.kt
  app/src/test/kotlin/com/wire/android/notification/CallNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModelTest.kt
Labels: size/L, echoes: bugs

#3260 fix: add loading screen when importing asset (WPB-10217)
  app/src/main/kotlin/com/wire/android/ui/home/FeatureFlagState.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
Labels: size/XS, echoes: bugs

#3269 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
Labels: size/XS, crowdin, l10n

#3263 ci: fix workflow runs against target branches rc and develop (WPB-8645)
  Jenkinsfile
Labels: size/XS, echoes: throughput/ci-maintenance

#3271 ci: missing codecov token (WPB-8645)
  .github/workflows/build-beta-app.yml
  .github/workflows/build-develop-app.yml
  .github/workflows/build-fdroid-app.yml
  .github/workflows/build-prod-app.yml
  .github/workflows/build-rc-app.yml
  .github/workflows/gradle-run-unit-tests.yml
Labels: size/XS, echoes: throughput/ci-maintenance

#3273 ci: missing codecov token (WPB-8645) 🍒
  .github/workflows/build-beta-app.yml
  .github/workflows/build-develop-app.yml
  .github/workflows/build-fdroid-app.yml
  .github/workflows/build-prod-app.yml
  .github/workflows/build-rc-app.yml
  .github/workflows/gradle-run-unit-tests.yml
Labels: size/XS, echoes: throughput/ci-maintenance

#3274 fix: Shields not shown in group participants list [WPB-10255]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/usecase/ObserveParticipantsForConversationUseCase.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/participants/usecase/ObserveParticipantsForConversationUseCaseTest.kt
Labels: size/XS, echoes: bugs

#3279 fix: direct usage from Lazy<CoreLogic> (WPB-10304)
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/deactivated/LegalHoldDeactivatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/requested/LegalHoldRequestedViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/legalhold/dialog/deactivated/LegalHoldDeactivatedViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/legalhold/dialog/requested/LegalHoldRequestedViewModelTest.kt
Labels: size/XS, echoes: bugs

#3278 fix: multiline topbar title still sometimes not centered [WPB-9608]
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/WireCenterAlignedTopAppBar.kt
Labels: size/XS, echoes: bugs

#3280 fix: connection button not shown when partial metadata (WPB-10342)
  app/src/androidTest/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileGroupTest.kt
  app/src/androidTest/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenTest.kt
  app/src/androidTest/kotlin/com/wire/android/ui/userprofile/other/OtherUserStubs.kt
  app/src/main/kotlin/com/wire/android/mapper/ContactMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/UIParticipantMapper.kt
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/model/UIParticipant.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/model/Contact.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UsernameMapper.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileGroup.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileState.kt
Labels: size/M, echoes: bugs

#3277 chore: add debug label in Wire icon (WPB-8645)
  app/src/debug/res/drawable/ic_launcher_foreground.xml
Labels: size/XS, echoes: throughput/ci-maintenance

#3285 fix: weird overscroll that makes conversation list disappear [WPB-9035]
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationList.kt
  gradle/libs.versions.toml
Labels: size/XS, echoes: bugs

#3261 fix: improve audio file size [WPB-10001]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/AssetBundle.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/AudioMediaRecorder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/GenerateAudioFileWithEffectsUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModel.kt
Labels: size/S

#3283 fix: delete button appears briefly when opening account screen (WPB-7426)
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountState.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModelTest.kt
Labels: size/XS, echoes: bugs

#3293 fix: delete button appears briefly when opening account screen - cherrypick (WPB-7426)
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountState.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModelTest.kt
Labels: size/XS, echoes: bugs

#3294 chore: Do not send data to Analytics on custom backend (WPB-10020)
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/analytics/ObserveCurrentSessionAnalyticsUseCase.kt
  app/src/test/kotlin/com/wire/android/analytics/ObserveCurrentSessionAnalyticsUseCaseTest.kt
Labels: size/S, echoes/initiative: product-metrics-in-countly

#3297 feat: generate effects file on demand [WPB-9713]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/AudioMediaRecorder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModelTest.kt
Labels: size/S

#3300 fix: keep OngoingCallService always running during call [WPB-10467]
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
Labels: size/S, echoes: bugs

#3303 fix: typos in compatrelease artifacts (WPB-8645)
  .github/workflows/build-fdroid-app.yml
  .github/workflows/build-prod-app.yml
Labels: size/XS, echoes: throughput/ci-maintenance

#3298 fix: Remove Reset Session for MLS conversations
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageItemComponents.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/FileAssetsContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypesPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/messages/SearchConversationMessagesResultsScreen.kt
Labels: size/S

#3305 feat: delete old log files [WPB-9439]
  app/src/main/kotlin/com/wire/android/util/LogFileWriter.kt
Labels: size/XS

#3306 feat: Add Analytics Usage opt-in dialog (WPB-9970) & (WPB-9973)
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/datastore/UserDataStore.kt
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/ui/analytics/AnalyticsConfiguration.kt
  app/src/main/kotlin/com/wire/android/ui/analytics/AnalyticsUsageState.kt
  app/src/main/kotlin/com/wire/android/ui/analytics/AnalyticsUsageViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/analytics/AnalyticsUsageViewModelTest.kt
  gradle/libs.versions.toml
Labels: size/M, echoes/initiative: product-metrics-in-countly

#3311 fix: Remove direct usage of Lazy<CoreLogic> (WPB-10304)
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/deactivated/LegalHoldDeactivatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/requested/LegalHoldRequestedViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/legalhold/dialog/deactivated/LegalHoldDeactivatedViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/legalhold/dialog/requested/LegalHoldRequestedViewModelTest.kt
Labels: size/XS, echoes: bugs

#3316 chore: Set analytics enabled for beta builds (WPB-10293)
  default.json
Labels: size/XS, echoes/initiative: product-metrics-in-countly

#3315 fix: typos in compatrelease artifacts (WPB-8645)
  .github/workflows/build-fdroid-app.yml
  .github/workflows/build-prod-app.yml
Labels: size/XS, echoes: throughput/ci-maintenance

#3308 feat: confirmation dialog for sending ping messages (WPB-2898)
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/ConfirmSendingPingDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreenDialogType.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModelArrangement.kt
Labels: size/S

#3296 ci: create 'beta' builds for nightly tests suite (WPB-10408)
  .github/actions/deploy-to-s3/action.yml
  .github/workflows/build-rc-app.yml
Labels: size/XS, echoes: throughput/ci-maintenance

#3320 fix: Small grey rect appears on the bottom of other user profile screen (WPB-10453)
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
Labels: size/XS, echoes: bugs

#3323 fix: ensure request focus is called once after the first composition is done [WPB-10571]
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
Labels: size/XS, echoes: bugs

#3319 chore: show hide analytics toggle (WPB-10587)
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsScreen.kt
Labels: size/XS, echoes/initiative: product-metrics-in-countly

#3322 feat: handle temporary guest users details (WPB-10454)
  .github/workflows/deploy-adr-docs.yml
  app/src/androidTest/kotlin/com/wire/android/ui/common/UserProfileAvatarTest.kt
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/ConversationParticipantItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItemLeading.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/HighLightSubtTitle.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UsernameMapper.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/userprofile/common/UsernameMapperTest.kt
  docs/adr/0003-introducing-junit5-parametrizable-tests.md
Labels: size/M, echoes: features

#3326 ci: cherrypicks leftovers (WPB-8645)
  .github/workflows/build-fdroid-app.yml
  .github/workflows/generate-changelog.yml
Labels: size/XS, echoes: throughput/ci-maintenance

#3317 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/S, crowdin, l10n

#3336 chore: Improve Analytics dialog (WPB-10601)
  app/src/main/kotlin/com/wire/android/ui/analytics/AnalyticsUsageViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeDialogs.kt
  app/src/main/res/values/strings.xml
Labels: size/XS

#3329 fix: builds for QA nightly builds missing folder (WPB-10408)
  .github/workflows/build-rc-app.yml
Labels: size/XS, echoes: throughput/ci-maintenance

#3341 ci: final final final adjust builds for rc branch (WPB-8645)
  .github/workflows/build-rc-app.yml
  default.json
Labels: size/XS, echoes: throughput/ci-maintenance

#3347 fix: hiding bottom sheet when editing message [WPB-10679]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/MessageOptionsModalSheetLayout.kt
Labels: size/XS, echoes: bugs

#3344 ci: final final final adjust builds for rc branch (WPB-8645) 🍒
  .github/workflows/build-rc-app.yml
  default.json
Labels: size/XS, echoes: throughput/ci-maintenance

#3356 ci: generate version.txt file and upload it to GH for new releases [WPB-7289]
  .github/workflows/build-prod-app.yml
Labels: size/XS

#3353 fix: Crash when starting starting PersistentWebsocketService (WPB-10712) - cherrypick RC
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
Labels: size/XS

#3355 ci: add gradle task to generate app version [WPB-7289]
  .github/workflows/build-prod-app.yml
  .gitignore
  app/build.gradle.kts
  build-logic/plugins/build.gradle.kts
  build-logic/plugins/src/main/kotlin/AndroidApplicationConventionPlugin.kt
  build-logic/plugins/src/main/kotlin/AndroidCoordinates.kt
  build-logic/plugins/src/main/kotlin/AppVersionPlugin.kt
  build-logic/plugins/src/main/kotlin/Extention.kt
  build-logic/plugins/src/main/kotlin/com/wire/android/gradle/version/Versionizer.kt
  build-logic/plugins/src/test/kotlin/VersionizerTest.kt
  build-logic/plugins/src/test/resources/version.txt
  gradle/libs.versions.toml
Labels: size/S

#3354 fix: remove unnecessary actions check as it's already declared in AppManifest (WPB-10712)
  app/src/main/kotlin/com/wire/android/ui/debug/StartServiceReceiver.kt
Labels: size/XS

#3359 fix: time not displayed correctly on Samsung devices [WPB-10598]
  app/src/main/kotlin/com/wire/android/util/DateAndTimeParsers.kt
Labels: size/XS, echoes: bugs

#3364 feat: enable password guest link in prod
  default.json
Labels: size/XS

#3365 chore: bump compose to 1.7.0-rc01
  gradle/libs.versions.toml
Labels: size/XS

#3366 fix: Add missing staging backend verification for analytics (WPB-10736)
  app/src/main/kotlin/com/wire/android/analytics/ObserveCurrentSessionAnalyticsUseCase.kt
  app/src/test/kotlin/com/wire/android/analytics/ObserveCurrentSessionAnalyticsUseCaseTest.kt
Labels: size/XS

#3335 feat: QR code support in profiles - pt2 (WPB-10534)
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/QRCodeIntents.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQrCodeNavArgs.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeViewModelTest.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/L, echoes: features

#3334 ci: support custom app version for fdroid [WPB-10569]
  build-logic/plugins/src/main/kotlin/com/wire/android/gradle/version/Versionizer.kt
  build.gradle.kts
  gradle.properties
Labels: size/XS, echoes: technical-debt, echoes: throughput/ci-maintenance

#3342 feat(qr): support qr code sharing for connection requests and profiles - epic (WPB-10535)
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/QRCodeIntents.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQrCodeNavArgs.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/util/deeplink/DeepLinkProcessor.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeViewModelTest.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  gradle/libs.versions.toml
Labels: size/L, echoes: features

#3374 fix: app asking for notification permission on each navigation to the HomeScreen[WPB-10750]
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/util/permission/PermissionsDeniedRequestDialog.kt
Labels: size/XS, echoes: bugs

#3378 fix: missing verification for analytics toggle (WPB-10587)
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsViewModel.kt
Labels: size/XS, echoes/initiative: product-metrics-in-countly

#3381 ci: set the correct version name for fdroid updates [WPB-10569]
  build-logic/plugins/src/main/kotlin/AppVersionPlugin.kt
Labels: size/XS, echoes: technical-debt

#3372 fix: button keeps spinning when user starts a conversation and back (WPB-5862)
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButtonViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/connection/ConnectionActionButtonViewModelTest.kt
Labels: size/XS, echoes: bugs

#3383 chore: disable guest link with password
  default.json
Labels: size/XS

#3382 ci: fix apk path when uploading release apk to gh releases (WPB-8645)
  .github/workflows/build-prod-app.yml
Labels: size/XS, echoes: throughput/ci-maintenance

#3380 chore: add new store screen shots for fdroid [WPB-10569]
  app/src/main/play/contact-email.txt
  app/src/main/play/contact-website.txt
  app/src/main/play/listings/en-US/full-description.txt
  app/src/main/play/listings/en-US/graphics/phone-screenshots/screenshot 1.png
  app/src/main/play/listings/en-US/graphics/phone-screenshots/screenshot 2.png
  app/src/main/play/listings/en-US/graphics/phone-screenshots/screenshot 3.png
  app/src/main/play/listings/en-US/graphics/phone-screenshots/screenshot 4.png
  app/src/main/play/listings/en-US/graphics/phone-screenshots/screenshot 5.png
  app/src/main/play/listings/en-US/short-description.txt
  app/src/main/play/listings/en-US/title.txt
  app/src/main/play/listings/en-US/video-url.txt
  app/src/main/play/release-notes/en-US/default.txt
Labels: size/XS, echoes: technical-debt

#3349 fix(conversation): disable addMember on a one-on-one conversation with deleted account (WPB-10259)
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsTopBarCollapsing.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipants.kt
  app/src/test/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContentTest.kt
Labels: size/S, echoes: bugs

#3362 feat: Ask User for call quality feedback [WPB-9452]
  app/src/main/kotlin/com/wire/android/di/accountScoped/UserModule.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/analytics/IsAnalyticsAvailableUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/analytics/IsAnalyticsAvailableUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
Labels: size/M

#3397 chore: limit release notes to 500 char limit release notes to 500 char [WPB-10569]
  app/src/main/play/release-notes/en-US/default.txt
Labels: size/XS, echoes: technical-debt

#3393 fix: Analytics toggle not showing properly (WPB-10587)
  app/src/main/kotlin/com/wire/android/ui/home/settings/privacy/PrivacySettingsViewModel.kt
Labels: size/XS, echoes/initiative: product-metrics-in-countly

#3400 fix: empty conversation list on import media [WPB-10483]
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
Labels: size/XS, echoes: bugs

#3405 fix: Fresh install crash [WPB-9452]
  app/src/main/kotlin/com/wire/android/ui/analytics/IsAnalyticsAvailableUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/analytics/IsAnalyticsAvailableUseCaseTest.kt
Labels: size/XS

#3404 fix: add new analytics dialog copy and remove redundant (link) (WPB-10803)
  app/src/main/res/values/strings.xml
Labels: size/XS, echoes/initiative: product-metrics-in-countly
