Repository wireapp/wire-android, pull requests merged in 2024-12, with the labels that each got.

#3686 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  app/src/main/res/values/strings.xml
  core/ui-common/src/main/res/values-de/strings.xml
  core/ui-common/src/main/res/values-ru/strings.xml
Labels: size/S, crowdin, l10n, echoes: technical-roadmap

#3682 chore: enable cc proteus [WPB-14658]
  default.json
Labels: size/XS

#3681 chore: enable paginated conversation list [WPB-14657]
  default.json
Labels: size/XS

#3689 fix: crash when saving bottom sheet state for message with reply [WPB-14433]
  app/src/main/kotlin/com/wire/android/model/ImageAsset.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIQuotedMessage.kt
  app/src/main/kotlin/com/wire/android/util/ui/UIText.kt
  core/ui-common/build.gradle.kts
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetState.kt
  core/ui-common/src/main/kotlin/com/wire/android/util/AnyPrimitiveAsStringSerializer.kt
  core/ui-common/src/test/kotlin/com/wire/android/ui/common/ExampleUnitTest.kt
  core/ui-common/src/test/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetStateTest.kt
Labels: size/S, echoes: unplanned

#3699 fix: update api version on startup [WPB-14730]
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/AppSyncViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/AppSyncViewModelTest.kt
Labels: size/XS, echoes/initiative: federation-wire-cloud

#3700 fix: revert of #3670 (WPB-14433)
  app/src/main/kotlin/com/wire/android/mapper/ContactMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/ConversationMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/OtherAccountMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/RegularMessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/SystemMessageContentMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/UICallParticipantMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/UIParticipantMapper.kt
  app/src/main/kotlin/com/wire/android/model/ImageAsset.kt
  app/src/main/kotlin/com/wire/android/model/UserAvatarData.kt
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationMemberExt.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/SystemMessageItemLeading.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIQuotedMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/usecase/GetConversationsFromSearchUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/BadgeEventType.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/util/ui/LocalizedStringResource.kt
  app/src/main/kotlin/com/wire/android/util/ui/UIText.kt
  app/src/test/kotlin/com/wire/android/mapper/MessageMapperTest.kt
  app/src/test/kotlin/com/wire/android/mapper/OtherAccountMapperTest.kt
  app/src/test/kotlin/com/wire/android/mapper/RegularMessageContentMapperTest.kt
  app/src/test/kotlin/com/wire/android/mapper/UICallParticipantMapperTest.kt
  app/src/test/kotlin/com/wire/android/mapper/UIParticipantMapperTest.kt
  app/src/test/kotlin/com/wire/android/model/ImageAssetTest.kt
  app/src/test/kotlin/com/wire/android/navigation/NavigationUtilsTest.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/connection/ConnectionActionButtonViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/HomeViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/participants/usecase/ObserveParticipantsForConversationUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/usecase/GetConversationsFromSearchUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/gallery/MediaGalleryViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/service/ServiceDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/ui/AssetImageFetcherTest.kt
  core/ui-common/build.gradle.kts
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetState.kt
  core/ui-common/src/main/kotlin/com/wire/android/util/AnyPrimitiveAsStringSerializer.kt
  core/ui-common/src/test/kotlin/com/wire/android/ui/common/ExampleUnitTest.kt
  core/ui-common/src/test/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetStateTest.kt
Labels: size/XL, echoes: unplanned

#3703 fix: wrong error message background color [WPB-11475]
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/XS, echoes: product-roadmap

#3698 chore: update dependencies (WPB-6394)
  gradle/libs.versions.toml
Labels: size/XS

#3708 fix: disabling countly on prod (WPB-14829)
  build-logic/plugins/src/main/kotlin/AndroidCoordinates.kt
  default.json
Labels: size/XS, echoes: unplanned

#3712 fix: image loading with multiple accounts from different backends [WPB-14433]
  app/src/main/kotlin/com/wire/android/model/ImageAsset.kt
Labels: size/XS, echoes: unplanned

#3711 chore: bump countly to latest version (WPB-14829)
  default.json
  gradle/libs.versions.toml
Labels: size/XS, echoes: unplanned/incident

#3710 fix: scroll to bottom arrow color [WPB-11475]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
Labels: size/XS, echoes: product-roadmap

#3688 feat: show correct error message when a user login with handle when 2 is enabled [WPB-1813]
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
Labels: size/XS, echoes: product-roadmap

#3692 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-ru/strings.xml
  core/ui-common/src/main/res/values-hu/strings.xml
Labels: size/XS, crowdin, l10n, echoes: technical-roadmap

#3719 fix: Crash on typing after sending mention (WPB-14897)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
Labels: size/XS, echoes: unplanned

#3721 fix: not able to open some conversations [WPB-11325]
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/CallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/CallActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/util/SwitchAccountObserver.kt
  app/src/test/kotlin/com/wire/android/notification/CallNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/ui/CallActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/M, echoes: unplanned

#3728 chore: revert highlight mentions while typing (WPB-1895) - RC
  app/src/main/kotlin/com/wire/android/ui/common/textfield/CodeTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/CodeTextFieldLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextFieldLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/mention/MentionAdjuster.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/mention/MentionSelectionManager.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/mention/MentionUpdateCoordinator.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
  app/src/test/kotlin/com/wire/android/ui/common/textfield/mention/MentionAdjusterTest.kt
  app/src/test/kotlin/com/wire/android/ui/common/textfield/mention/MentionSelectionManagerTest.kt
  app/src/test/kotlin/com/wire/android/ui/common/textfield/mention/MentionUpdateCoordinatorTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerStateHolderTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolderTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolderTest.kt
Labels: size/XL, echoes: product-roadmap, echoes: unplanned

#3732 fix: countly general implementation fixes (WPB-14941)
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerImpl.kt
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorderImpl.kt
  core/analytics-enabled/src/test/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerTest.kt
Labels: size/XS, echoes/initiative: product-metrics-in-countly

#3731 chore: wrong url when opening team management after migration - RC (WPB-14872)
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step4/TeamMigrationDoneStepScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModelTest.kt
Labels: size/XS, echoes/initiative: personal-users-to-team-users...

#3687 feat: Add Mentions to draft messages #WPB-12062
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
Labels: size/XS, echoes: product-roadmap

#3704 feat: Deleted users adjustments [WPB-1655]
  app/src/main/kotlin/com/wire/android/mapper/ConversationMapper.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileState.kt
  app/src/test/kotlin/com/wire/android/framework/TestConversationItem.kt
  app/src/test/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContentTest.kt
Labels: size/S, echoes: product-roadmap

#3543 feat: Custom server no network dialog #WPB-11627
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/CustomServerNoNetworkDialog.kt
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
Labels: size/S, echoes: unplanned

#3746 fix: harden countly sdk integration (WPB-15007)
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorderImpl.kt
Labels: size/XS, echoes/initiative: product-metrics-in-countly

#3747 fix: non-paginated conversation list is not loading [WPB-15066]
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
Labels: size/XS, echoes: unplanned

#3743 fix: add signature used by mls client (WPB-15040)
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/model/DeviceDetailsState.kt
Labels: size/XS, echoes: unplanned

#3754 fix: new line can not be added to message composer
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
Labels: size/XS

#3763 fix: allowing empty team name when migrating [WPB-15092]
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step2/TeamMigrationTeamNameStepScreen.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModelTest.kt
Labels: size/XS, echoes/initiative: personal-users-to-team-users...

#3770 fix: call controls visibility after closing PiP mode [#WPB-15142]
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
Labels: size/XS

#3768 fix: adjustments for short signature names (WPB-15188)
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModel.kt
Labels: size/XS, echoes: unplanned

#3769 fix: group protocol info is not shown when it is Proteus [WPB-15205]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
Labels: size/XS, echoes: unplanned

#3739 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-ru/strings.xml
Labels: size/XS, crowdin, l10n, echoes: technical-roadmap

#3775 fix: condition not needed for protocol display in group conversation (WPB-15205)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
Labels: size/XS, echoes: unplanned

#3727 chore: revert highlight mentions while typing (WPB-1895)
  app/src/main/kotlin/com/wire/android/ui/common/textfield/CodeTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/CodeTextFieldLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextFieldLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/mention/MentionAdjuster.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/mention/MentionSelectionManager.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/mention/MentionUpdateCoordinator.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
  app/src/test/kotlin/com/wire/android/ui/common/textfield/mention/MentionAdjusterTest.kt
  app/src/test/kotlin/com/wire/android/ui/common/textfield/mention/MentionSelectionManagerTest.kt
  app/src/test/kotlin/com/wire/android/ui/common/textfield/mention/MentionUpdateCoordinatorTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerStateHolderTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolderTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolderTest.kt
Labels: size/XL, echoes: product-roadmap, echoes: unplanned

#3780 fix: Keyboard overlapping attachments [#WPB-11039]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
Labels: size/XS, echoes: unplanned
