Repository wireapp/wire-android, pull requests merged in 2024-11, with the labels that each got.

#3575 feat Add Accessibility strings to WhatsNew #WPB-9835
  app/src/main/kotlin/com/wire/android/ui/common/AppExtensions.kt
  app/src/main/kotlin/com/wire/android/ui/common/Logo.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/InternalContactSearchResultItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/drawer/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewScreen.kt
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/XS, echoes: features

#3581 chore: apply QR profile feature flag to deeplink processing (WPB-11921)
  app/src/main/kotlin/com/wire/android/util/deeplink/DeepLinkProcessor.kt
Labels: size/XS, echoes: features

#3591 feat: Remove mls enabled build config field #WPB-10119
  app/src/main/kotlin/com/wire/android/di/KaliumConfigsModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/ConversationParticipantItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipants.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
Labels: size/XS, echoes/initiative: federation-wire-cloud

#3588 feat: Try testTagsAsResourceId to improve UI tests [WPB-9284]
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/StartingCallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallActivity.kt
Labels: size/XS

#3594 feat: Try testTagsAsResourceId to improve UI tests: RC [WPB-9284]
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/StartingCallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallActivity.kt
Labels: size/XS, DO NOT CHERRY PICK

#3597 fix: TestTag for DeviceItem #WPB-9784
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
Labels: size/XS, echoes: features

#3605 fix: Username index out of bounds exception #WPB-12143
  app/src/main/kotlin/com/wire/android/ui/common/textfield/InputTransformations.kt
Labels: size/XS

#3583 fix: showing multiple calls at the same time [WPB-10430]
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationConstants.kt
  app/src/main/kotlin/com/wire/android/notification/WireNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/CallNotificationDismissedReceiver.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/DeclineIncomingCallReceiver.kt
  app/src/main/kotlin/com/wire/android/services/CallService.kt
  app/src/main/kotlin/com/wire/android/ui/calling/StartingCallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/outgoing/OutgoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/ConnectivityUIState.kt
  app/src/main/kotlin/com/wire/android/util/LogUtil.kt
  app/src/test/kotlin/com/wire/android/notification/CallNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/notification/WireNotificationManagerTest.kt
  app/src/test/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModelTest.kt
Labels: size/L, echoes: bugs

#3603 fix: Username index out of bounds exception [WPB-12143]
  app/src/main/kotlin/com/wire/android/ui/common/textfield/InputTransformations.kt
Labels: size/XS

#3590 feat: strip metadata from profile pictures (WPB-11170)
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPicker.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/avatarpicker/AvatarPickerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/main/kotlin/com/wire/android/util/ExifHandler.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
  app/src/main/kotlin/com/wire/android/util/ImageUtil.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/image/AvatarPickerViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/util/ImageUtilTest.kt
  app/src/test/resources/rich-exif-sample.jpg
Labels: size/M, echoes: features

#3607 feat(personal-to-team): remove password field from confirmation step (WPB-11268)
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step3/TeamMigrationConfirmationStepScreen.kt
  app/src/main/res/values/strings.xml
Labels: size/XS, echoes/initiative: personal-users-to-team-users...

#3614 fix: Accessibility strings issues #WPB-9827
  app/src/main/kotlin/com/wire/android/ui/common/WireDropDown.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/RichMenuBottomSheetItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/MutingOptionsSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/InternalContactSearchResultItem.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/common/UserProfileInfo.kt
  app/src/main/res/values/strings.xml
Labels: size/XS, echoes: features

#3593 chore: setForegroundServiceBehavior for persistent websocket service [WPB-11113]
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
Labels: size/XS, echoes: bugs

#3617 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  core/ui-common/src/main/res/values-de/strings.xml
  core/ui-common/src/main/res/values-hu/strings.xml
  core/ui-common/src/main/res/values-ru/strings.xml
Labels: size/L, crowdin, l10n, echoes: maintenance

#3620 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-ru/strings.xml
Labels: size/XS, crowdin, l10n, echoes: maintenance

#3616 feat: enabling QR codes for users (WPB-12115)
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/UserNotFoundDialog.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/util/debug/FeatureVisibilityFlags.kt
  app/src/main/kotlin/com/wire/android/util/deeplink/DeepLinkProcessor.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/DeepLinkProcessorTest.kt
Labels: size/S, echoes: features

#3622 feat: enabling QR codes for users (WPB-12115) 🍒
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/UserNotFoundDialog.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/util/debug/FeatureVisibilityFlags.kt
  app/src/main/kotlin/com/wire/android/util/deeplink/DeepLinkProcessor.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/DeepLinkProcessorTest.kt
Labels: size/S, echoes: features

#3626 chore: enable conversation list pagination for internal app [WPB-14295]
  .github/workflows/build-edge-env.yml
  default.json
Labels: size/XS

#3627 fix: blank lists or flickering on Home Destinations - wrong lazyListStates [WPB-14276]
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/archive/ArchiveScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/all/AllConversationsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewScreen.kt
Labels: size/XS

#3632 fix: lateinit property selfUserId has not been initialized in ConversationInfoViewModel [WPB-14317]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelTest.kt
Labels: size/XS, echoes: unplanned

#3604 fix: show proper empty user search screens [WPB-6257] 🍒 (v4.7)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchAllPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchAllServicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchServicesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUserViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/widget/SearchFailureWidget.kt
Labels: size/M, echoes: product-roadmap, DO NOT CHERRY PICK

#3606 fix: show proper empty user search screens [WPB-6257] 🍒 (v4.8)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchAllPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchAllServicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchPeopleRouter.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchServicesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUserViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/widget/SearchFailureWidget.kt
Labels: size/M, echoes: product-roadmap, DO NOT CHERRY PICK

#3592 fix: Push notification on top of calling UI shown (WPB-11632)
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationActions.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationConstants.kt
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/CallNotificationDismissedReceiver.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/IncomingCallActionReceiver.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/notification/CallNotificationManagerTest.kt
Labels: size/M, echoes: unplanned

#3613 refactor: AudioMediaRecorder to improve readability and resource management
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/AudioMediaRecorder.kt
Labels: size/M

#3631 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-ru/strings.xml
Labels: size/XS, crowdin, l10n, echoes: technical-roadmap

#3629 docs: add contributing file and readme link (WPB-12192)
  CONTRIBUTING.md
  README.md
Labels: size/XS

#3637 fix: hide LH indicators on conversations when self user is under LH [WPB-6391]
  app/src/main/kotlin/com/wire/android/mapper/ConversationMapper.kt
  app/src/main/kotlin/com/wire/android/mapper/MessageMapper.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationTitle.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/UserLabel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/test/kotlin/com/wire/android/framework/TestMessage.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
Labels: size/M, echoes: unplanned

#3647 fix: qr code link to user as text is incorrect, was wrongly cherrypicked (WPB-14416)
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeScreen.kt
Labels: size/XS, echoes: product-roadmap

#3642 feat: Highlight mentions in TextInputs (WPB-1895)
  app/src/main/kotlin/com/wire/android/ui/common/textfield/CodeTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/CodeTextFieldLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/MentionDeletionHandler.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/MentionVisualTransformation.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WirePasswordTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextFieldLayout.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/HighLightName.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MembersMentionList.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
  app/src/test/kotlin/com/wire/android/ui/common/textfield/MentionDeletionHandlerTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerStateHolderTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolderTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolderTest.kt
Labels: size/L, echoes: product-roadmap

#3649 fix: Countly crash [WPB-14415]
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorderImpl.kt
Labels: size/XS, echoes: unplanned

#3651 feat: adjust accessibility strings for personal to team migration feature (WPB-14347)
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/CreateTeamInfoCard.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/common/BottomLineButtons.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step1/TeamMigrationTeamPlanStepScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step2/TeamMigrationTeamNameStepScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step3/TeamMigrationConfirmationStepScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step4/TeamMigrationDoneStepScreen.kt
  app/src/main/res/values/strings.xml
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/XS, echoes/initiative: personal-users-to-team-users...

#3639 fix: Listen few audios at the same time [WPB-11180]
  app/src/main/kotlin/com/wire/android/media/audiomessage/ConversationAudioMessagePlayer.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/test/kotlin/com/wire/android/media/ConversationAudioMessagePlayerTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelArrangement.kt
Labels: size/S, echoes: unplanned

#3657 fix: Accessibility strings founded issues #WPB-9784
  app/src/main/kotlin/com/wire/android/model/UserAvatarData.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreateAccountOverviewParams.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreatePersonalAccountOverviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/DeviceItem.kt
  app/src/main/kotlin/com/wire/android/ui/common/UserProfileAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireDropDown.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/ConversationParticipantItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/HighLightSubtTitle.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUsersAndServicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageActions.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioButtons.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/dialog/LogoutOptionsDialog.kt
  app/src/main/res/values/strings.xml
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/WireDialog.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/bottomsheet/ModalSheetHeaderItem.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WireButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WireItemLabel.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WirePrimaryButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WireSecondaryButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WireTertiaryButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/topappbar/NavigationIconButton.kt
  core/ui-common/src/main/res/values/strings.xml
Labels: size/S, echoes: product-roadmap

#3664 feat: Track qr-code analytics #WPB-11679 🍒 (#3565)
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModelArrangement.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/model/AnalyticsEvent.kt
Labels: size/S, echoes: product-roadmap

#3652 feat: Allow admins to remove groups [WPB-11559]
  app/src/main/kotlin/com/wire/android/mapper/ConversationMapper.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/usecase/GetConversationsFromSearchUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/test/kotlin/com/wire/android/framework/TestConversationItem.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/usecase/GetConversationsFromSearchUseCaseTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
Labels: size/S

#3600 feat: disable x86 support [WPB-11427]
  .github/workflows/gradle-run-ui-tests.yml
  app/build.gradle.kts
  buildSrc/src/main/kotlin/scripts/variants.gradle.kts
Labels: size/XS, echoes: technical-roadmap/throughput

#3665 fix: Links color #WPB-14249
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsEmptyScreenText.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsReactions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsReadReceipts.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/TextWithLinkSuffix.kt
Labels: size/XS, echoes: unplanned

#3666 fix: set Foreground Service Behavior IMMEDIATE (WPB-5512)
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/services/PersistentWebSocketService.kt
Labels: size/XS, echoes: unplanned

#3663 feat: add username in settings #WPB-4368
  app/src/main/kotlin/com/wire/android/navigation/HomeDestination.kt
  app/src/main/kotlin/com/wire/android/ui/common/RowItemTemplate.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsState.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsViewModel.kt
Labels: size/S, echoes: product-roadmap

#3643 fix: big padding around reaction pills #WPB-12094 #WPB-14269
  app/src/main/kotlin/com/wire/android/ui/edit/ReactionOption.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsEmptyScreenText.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ReactionPill.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageContentAndStatus.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/SwipableToReplyBox.kt
Labels: size/L

#3680 ci: Update Jenkinsfile (WPB-8645)
  Jenkinsfile
Labels: size/XS

#3668 feat: support Proteus federation if MLS not supported by backend (WPB-14456)
  app/src/main/kotlin/com/wire/android/di/accountScoped/SearchModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUserViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/search/SearchUserViewModelTest.kt
Labels: size/XS, DO NOT MERGE, echoes/initiative: federation-wire-cloud
