Repository wireapp/wire-android, pull requests merged in 2025-07, with the labels that each got.

#4091 fix: correct base date initialization in DateAndTimeParsersTest for UTC timezone [WPB-8645]
  app/src/test/kotlin/com/wire/android/util/DateAndTimeParsersTest.kt
Labels: size/XS

#4092 feat: add team management access from main navigation (WPB-17721)
  app/src/main/kotlin/com/wire/android/navigation/HomeDestination.kt
  app/src/main/kotlin/com/wire/android/navigation/OtherDestinations.kt
  app/src/main/kotlin/com/wire/android/ui/home/drawer/HomeDrawer.kt
  app/src/main/kotlin/com/wire/android/ui/home/drawer/HomeDrawerState.kt
  app/src/main/kotlin/com/wire/android/ui/home/drawer/HomeDrawerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/res/drawable/ic_team_management.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/drawer/HomeDrawerViewModelTest.kt
Labels: size/S

#4093 fix: reply from notification (#WPB-18533)
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/CoroutineReceiver.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/NotificationReplyReceiver.kt
Labels: size/S

#4080 feat(cells): rename a folder/file (WPB-18314)
  app/src/main/kotlin/com/wire/android/di/accountScoped/CellsModule.kt
  app/src/main/kotlin/com/wire/android/navigation/WireMainNavGraph.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/common/handle/UsernameTextField.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupConversationNameComponent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/folder/NewConversationFolderScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/displayname/ChangeDisplayNameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/displayname/ChangeDisplayNameViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/displayname/ChangeDisplayNameViewModelTest.kt
  core/ui-common/src/main/kotlin/com/wire/android/model/DisplayNameState.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/animation/ShakeAnimation.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/AllFilesScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellScreenContent.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellViewModel.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/ConversationFilesScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/model/NodeBottomSheetAction.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/recyclebin/RecycleBinScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/rename/RenameNodeNavArgs.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/rename/RenameNodeScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/rename/RenameNodeViewModel.kt
  features/cells/src/main/res/drawable/ic_rename.xml
  features/cells/src/main/res/values/strings.xml
  features/cells/src/test/kotlin/com/wire/android/feature/cells/ui/rename/RenameNodeViewModelTest.kt
Labels: size/L

#4097 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-ru/strings.xml
  features/cells/src/main/res/values-ru/strings.xml
Labels: size/XS, crowdin, l10n

#4094 fix: channel history indicator alignment and flickering [WPB-15859]
  app/src/main/kotlin/com/wire/android/ui/common/PageLoadingIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
Labels: size/XS

#4100 feat: hide MLS read Receipts in UI [WPB-17670]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/FolderHeader.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupOptions/GroupOptionsScreen.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
Labels: size/L

#4104 fix: analytics registration are sent with secondary account if available, when it shouldn't (WPB-18606)
  app/src/main/kotlin/com/wire/android/analytics/RegistrationAnalyticsManagerUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/registration/code/CreateAccountVerificationCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/registration/details/CreateAccountDataDetailViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/registration/details/CreateAccountDataDetailViewModelTest.kt
Labels: size/S

#4103 chore(l10n): update localization strings via Crowdin (WPB-9776)
  features/cells/src/main/res/values-de/strings.xml
Labels: size/XS, crowdin, l10n

#4109 fix: add WireRootNavGraph annotation to PersonalToTeamMigrationNavGraph [WPB-18673]
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/PersonalToTeamMigrationNavGraph.kt
Labels: size/XS

#4099 feat(cells): Filter files by tags (WPB-18467)
  app/src/main/kotlin/com/wire/android/di/accountScoped/CellsModule.kt
  app/src/main/kotlin/com/wire/android/navigation/HomeDestination.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeTopBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/cell/GlobalCellsScreen.kt
  app/src/main/res/values/strings.xml
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/WireChipDefaults.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/chip/WireDisplayChipWithOverFlow.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/chip/WireFilterChip.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/search/SearchBarState.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
  core/ui-common/src/main/res/drawable/ic_filter.xml
  features/cells/src/main/java/com/wire/android/feature/cells/ui/AllFilesScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellViewModel.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/filter/FilterBottomSheet.kt
  features/cells/src/main/res/drawable/ic_chevron_up.xml
  features/cells/src/main/res/values/strings.xml
Labels: size/M

#4102 feat: script to organize the apk [WPB-18583]
  scripts/README_APK_WRAPPER.md
  scripts/wire_apk_wrapper.sh
Labels: size/L

#4041 chore: app start time improvement (#WPB-14874)
  app/src/main/kotlin/com/wire/android/navigation/LoginTypeSelector.kt
  app/src/main/kotlin/com/wire/android/ui/CallFeedbackViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/analytics/AnalyticsUsageViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/drawer/HomeDrawerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/deactivated/LegalHoldDeactivatedViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/legalhold/dialog/requested/LegalHoldRequestedViewModel.kt
  app/src/test/kotlin/com/wire/android/navigation/LoginTypeSelectorTest.kt
  app/src/test/kotlin/com/wire/android/ui/CallFeedbackViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/analytics/AnalyticsUsageViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/drawer/HomeDrawerViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/sync/FeatureFlagNotificationViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/legalhold/dialog/deactivated/LegalHoldDeactivatedViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/legalhold/dialog/requested/LegalHoldRequestedViewModelTest.kt
Labels: size/S

#4098 feat(cells): Add and remove tags (WPB-18468)
  app/src/main/kotlin/com/wire/android/di/accountScoped/CellsModule.kt
  app/src/main/kotlin/com/wire/android/navigation/WireMainNavGraph.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/chip/WireFilterChip.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/AllFilesScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellScreenContent.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellViewModel.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/ConversationFilesScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/model/NodeBottomSheetAction.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/recyclebin/RecycleBinScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/tags/AddRemoveTagsNavArgs.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/tags/AddRemoveTagsScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/tags/AddRemoveTagsViewModel.kt
  features/cells/src/main/res/drawable/ic_tags.xml
  features/cells/src/main/res/values/strings.xml
  features/cells/src/test/kotlin/com/wire/android/feature/cells/ui/CellViewModelTest.kt
  features/cells/src/test/kotlin/com/wire/android/feature/cells/ui/tags/AddRemoveTagsViewModelTest.kt
Labels: size/L

#4118 fix: keep conversation options sheet when rotating [WPB-18248]
  app/src/androidTest/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileGroupTest.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationMainSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationOptionsData.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationOptionsMenuViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationOptionsModalSheetLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetState.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/folder/ChangeConversationFavoriteStateArgs.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/folder/ChangeConversationFavoriteVM.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/ArchiveConversationDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/BlockUserDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/DialogStates.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/UnblockUserDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeSnackBarMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsTopBarCollapsing.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/dialog/ClearConversationContentDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/menu/DeleteConversationGroupDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/menu/DeleteConversationGroupLocallyDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/menu/LeaveConversationGroupDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/MessageOptionsModalSheetLayout.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/folder/RemoveConversationFromFolderVM.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationsDialogsState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationsScreenContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/GroupDialogState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/group/RemoveConversationMemberState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileEventsHandlers.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileGroup.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/RemoveConversationMemberDialog.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/bottomsheet/EditGroupRoleBottomSheet.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/bottomsheet/OtherUserBottomSheetState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/bottomsheet/OtherUserProfileBottomSheet.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/framework/TestConversationDetails.kt
  app/src/test/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationOptionsDataTest.kt
  app/src/test/kotlin/com/wire/android/ui/common/bottomsheet/folder/ChangeConversationFavoriteVMTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileViewModelArrangement.kt
  config/detekt/detekt.yml
Labels: size/XL

#4122 feat: Show valid icon by file type (WPB-18883)
  features/cells/src/main/java/com/wire/android/feature/cells/domain/model/AttachmentFileType.kt
Labels: size/XS

#4126 feat: hide bottom sheet actions on search (WPB-18892)
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellViewModel.kt
Labels: size/XS

#4124 feat: Fix padding of file preview header (WPB-18889)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/standalone/VideoAssetPreview.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellScreenContent.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/ConversationFilesScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/dialog/NodeActionsBottomSheet.kt
Labels: size/XS

#4139 feat: disable read recipt for mls [WPB-18896]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupOptions/GroupOptionsScreen.kt
Labels: size/XS

#4115 feat: Show folder in global view (WPB-18783)
  features/cells/src/main/java/com/wire/android/feature/cells/ui/AllFilesScreen.kt
  features/cells/src/main/res/values-ru/strings.xml
  features/cells/src/main/res/values-si/strings.xml
Labels: size/XS
