Repository wireapp/wire-android, pull requests merged in 2025-02, with the labels that each got.

#3853 fix: In call video flickering on opening emojy drawer #WPB-15549
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
Labels: size/XS, echoes: product-roadmap/feature

#3839 feat: enter to sent message part-1 [WPB-15369]
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/ui/common/textfield/WireTextField.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModelArrangement.kt
Labels: size/S, echoes: product-roadmap/feature

#3845 feat: enter to sent message UI part-2 [WPB-15369]
  app/src/main/kotlin/com/wire/android/ui/common/WireLabelledCheckbox.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/appearance/CustomizationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/appearance/CustomizationState.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/appearance/CustomizationViewModel.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/appearance/AppearanceViewModelTest.kt
Labels: size/S, echoes: product-roadmap/feature

#3861 feat: deeplink parameter to select login flow [WPB-15982]
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityDialogs.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/CustomServerDialog.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/CustomServerNoNetworkDialog.kt
  app/src/main/kotlin/com/wire/android/util/deeplink/DeepLinkProcessor.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/DeepLinkProcessorTest.kt
Labels: size/S, echoes/initiative: scale

#3856 fix: Crash on inserting mention #WPB-15717
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolderTest.kt
Labels: size/XS

#3860 fix: MLS with unknown signature shown for other users devices RC #WPB-15268
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModel.kt
  app/src/main/res/values/strings.xml
Labels: size/XS, DO NOT CHERRY PICK, echoes: product-roadmap/bug

#3865 fix: mention draft update [WPB-12062]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionHolder.kt
Labels: size/XS

#3866 fix: disable folders options for archived conversation [WPB-15888]
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/HomeSheetContent.kt
Labels: size/XS

#3864 feat: Disable Performance tracking #WPB-15791
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorderImpl.kt
Labels: size/XS

#3869 fix: FileSharing menu - no gaps #WPB-15276
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
Labels: size/XS

#3858 feat: handle 2fa code in new login flow [WPB-15853]
  app/src/main/kotlin/com/wire/android/navigation/MainNavHost.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailVerificationCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/verificationcode/ResendCodeText.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/verificationcode/VerificationCode.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/code/NewLoginVerificationCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginContainer.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/password/NewLoginPasswordScreen.kt
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
  app/src/main/res/values/strings.xml
Labels: size/M, echoes/initiative: scale

#3859 fix: Crash on call to non-currentUser WPB-15804
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationActions.kt
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/res/values/strings.xml
Labels: size/XS, echoes: product-roadmap/bug

#3873 feat: Disable Performance tracking RC #WPB-15791
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorderImpl.kt
Labels: size/XS, DO NOT CHERRY PICK

#3872 fix: Pause AudioMessage on recording new #WPB-15852
  app/src/main/kotlin/com/wire/android/media/audiomessage/AudioFocusHelper.kt
  app/src/main/kotlin/com/wire/android/media/audiomessage/RecordAudioMessagePlayer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModelTest.kt
Labels: size/XS

#3877 feat: Migrate to Team analytics update WPB-16050
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step1/TeamMigrationTeamPlanStepScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step2/TeamMigrationTeamNameStepScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step3/TeamMigrationConfirmationStepScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step4/TeamMigrationDoneStepScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/HomeViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModelTest.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/model/AnalyticsEvent.kt
Labels: size/M

#3883 fix: Crash on scroll pager in Call #WPB-16064
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/participantsview/VerticalCallingPager.kt
Labels: size/XS

#3878 fix: CallControlButtons shape #WPB-16054
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/WireCallControlButton.kt
Labels: size/XS

#3881 fix: cancel btn not working on the sso redirect from domain [WPB-15673]
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
Labels: size/XS

#3884 fix: UI issues for newly created group [WPB-15380]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageContainerItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/SystemMessageItem.kt
  app/src/main/res/values/strings.xml
Labels: size/XS

#3875 feat: open ongoing call screen when answering an incoming call (WPB-15555)
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/IncomingCallActionReceiver.kt
  app/src/main/kotlin/com/wire/android/ui/calling/CallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallActivity.kt
Labels: size/XS

#3886 fix: Back button not working on closing conversation after editing a message (WPB-15770)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerInput.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageComposerStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposerStateHolderTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolderTest.kt
Labels: size/XS
