Repository wireapp/wire-android, pull requests merged in 2025-03, with the labels that each got.

#3894 fix: When enabling video before accepting a call, call does not connect to user (WPB-15719)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallViewModel.kt
Labels: size/XS

#3892 feat: new sso login error handling [WPB-14342]
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginErrorDialog.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/SSOUrlConfigHolder.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/DomainCheckupState.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginAction.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginFlowState.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/password/NewLoginPasswordScreen.kt
  app/src/main/kotlin/com/wire/android/util/CommonIntentUtil.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/newauthentication/login/NewLoginViewModelTest.kt
Labels: size/XL

#3896 feat: claimed domain dialog after successful login [WPB-14339]
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/EmailAlreadyInUseClaimedDomainDialog.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/password/NewLoginPasswordScreen.kt
Labels: size/XS

#3902 chore(logging): guarantee app metadata in log files [WPB-8645]
  app/src/main/kotlin/com/wire/android/ui/debug/UserDebugViewModel.kt
  app/src/main/kotlin/com/wire/android/util/LogFileWriter.kt
Labels: size/XS

#3903 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-uk/strings.xml
Labels: size/XS, crowdin, l10n

#3909 fix: GitHib action not finding APK to upload for releases [WPB-16443]
  .github/workflows/build-prod-app.yml
Labels: size/XS

#3893 chore: update baseline profile (WPB-14283)
  app/src/main/baseline-prof.txt
  benchmark/build.gradle.kts
  benchmark/src/androidTest/java/com/wire/benchmark/BaselineGenerator.kt
Labels: size/XL

#3897 feat(channels): Add the New Channel button (WPB-15870)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUsersAndServicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/adddembertoconversation/AddMembersSearchScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/ContinueWithParticipantsCountButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/CreateGroupOrChannelButtons.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/SendContentButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupsearch/NewGroupConversationSearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/NewConversationSearchPeopleScreen.kt
  app/src/main/res/drawable/ic_channel.xml
  app/src/main/res/drawable/ic_group.xml
  app/src/main/res/values/strings.xml
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/M

#3911 feat(channels): dynamically generate channel avatars (WPB-15857)
  app/src/main/kotlin/com/wire/android/ui/common/AppThemeExt.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ChannelConversationAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/GroupConversationAvatar.kt
  app/src/main/res/drawable/ic_lock.xml
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/AvatarColors.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/S

#3916 fix: disable in-call reactions while connecting [WPB-16372]
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/InCallReactionsButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/controlbuttons/WireCallControlButton.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
Labels: size/XS

#3918 fix: broken compilation on AnonymousAnalyticsManagerTest and ExternalLoggerManager (WPB-16121)
  app/build.gradle.kts
  app/src/public/kotlin/com/wire/android/ExternalLoggerManager.kt
  core/analytics-enabled/src/test/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerTest.kt
Labels: size/XS

#3921 fix: update "email already in use" dialog to current design specs [WPB-14339]
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/EmailAlreadyInUseClaimedDomainDialog.kt
  app/src/main/res/values/strings.xml
Labels: size/XS

#3925 chore: run connected tests on dev flavour [WPB-16596]
  buildSrc/src/main/kotlin/scripts/infrastructure.gradle.kts
Labels: size/XS

#3919 feat(channels): Create channel flow (WPB-15874)
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupConversationNameComponent.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupMetadataState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUsersAndServicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/ContinueWithParticipantsCountButton.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/CreateRegularGroupOrChannelButtons.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupOptions/GroupOptionsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupsearch/NewGroupConversationSearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/ChannelNotAvailableDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/NewConversationSearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/appearance/CustomizationScreen.kt
  app/src/main/res/drawable-night/ic_upgrade.xml
  app/src/main/res/drawable/ic_upgrade.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
  app/src/screenshotTest/kotlin/com/wire/android/kotlin/ui/home/conversations/messages/item/PreviewMessageTypes.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/WirePromotionDialog.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
  core/ui-common/src/main/res/drawable/ic_wave.xml
Labels: size/L

#3924 feat(channels): distinguish channels in conversation list [WPB-15865]
  app/src/main/kotlin/com/wire/android/mapper/ConversationMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/test/kotlin/com/wire/android/framework/TestConversationItem.kt
Labels: size/XS

#3937 fix: new login path 4 - invalid sso code [WPB-16673] [WPB-16674]
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModelExtension.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/newauthentication/login/NewLoginViewModelTest.kt
Labels: size/XS

#3940 fix: analytics should be disabled for c-builds (WPB-16675)
  app/build.gradle.kts
  buildSrc/src/main/kotlin/customization/Customization.kt
Labels: size/XS

#3928 ci: run critical flows tests on each PR (WPB-8645)
  Jenkinsfile
Labels: size/XS

#3913 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
Labels: size/S, crowdin, l10n

#3945 fix: keep showing user email after handling SSO url [WPB-14340]
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/SSOUrlConfigHolder.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/newauthentication/login/NewLoginViewModelTest.kt
Labels: size/XS

#3946 feat: new conversation - hide bottom buttons when search is active [WPB-15881]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUsersAndServicesScreen.kt
Labels: size/XS

#3943 feat(channels): Change group creation continue button (WPB-15937)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUsersAndServicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/ContinueButton.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/XS

#3914 feat(channels): browse public channels UI (WPB-15866)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/channels/BrowseChannelsEmptyScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/channels/BrowseChannelsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationsScreenContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/all/AllConversationsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/all/ConversationsEmptyContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationFolder.kt
  app/src/main/res/values/strings.xml
Labels: size/M
