Repository wireapp/wire-android, pull requests merged in 2025-04, with the labels that each got.

#3933 refactor: replace thread with coroutine Job on `AudioMediaRecorder`
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/AudioMediaRecorder.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModelTest.kt
Labels: size/XS

#3953 fix: too many devices response crashing new login flow [WPB-16833]
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
Labels: size/XS

#3954 feat: add clear trailing btn to group conversation name [WPB-16813 ]
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupConversationNameComponent.kt
Labels: size/XS

#3957 feat(channels): show or hide channel creation as needed [WPB-16634]
  app/src/main/kotlin/com/wire/android/di/accountScoped/ChannelsModule.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupMetadataState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUsersAndServicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/NewConversationSearchPeopleScreen.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelTest.kt
Labels: size/XS

#3959 feat(channels): display channel avatar within conversation top app bar [WPB-15857]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewState.kt
Labels: size/XS

#3963 fix: adjust tests for changes related to cells [WPB-15386]
  app/src/androidTest/kotlin/com/wire/android/ui/debug/DebugScreenComposeTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/drawer/HomeDrawerViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelTest.kt
  features/cells/lint-baseline.xml
Labels: size/XS

#3960 fix: app crashing when opening sketch [WPB-16937]
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
Labels: size/XS

#3970 fix(channels): properly show channel promotion button [WPB-16979]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUsersAndServicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/adddembertoconversation/AddMembersSearchScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/CreateRegularGroupOrChannelButtons.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/groupsearch/NewGroupConversationSearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/NewConversationSearchPeopleScreen.kt
Labels: size/XS

#3966 feat: disable browsing public channels based on compile time flag [WPB-16933]
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/all/ConversationsEmptyContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/filter/ConversationFiltersSheetContent.kt
  app/src/main/kotlin/com/wire/android/util/debug/FeatureVisibilityFlags.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
Labels: size/XS

#3962 fix: search result are cleared when all results are selected [WPB-15100]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchAllPeopleScreen.kt
Labels: size/XS

#3969 chore(channels): adapt text to suit both regular groups and channels [WPB-16636]
  app/src/main/kotlin/com/wire/android/mapper/MessagePreviewContentMapper.kt
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/common/groupname/GroupConversationNameComponent.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeSnackBarMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsTopBarCollapsing.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/menu/DeleteConversationGroupDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/menu/DeleteConversationGroupLocallyDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/menu/LeaveConversationGroupDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationAllParticipantsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchUsersAndServicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/common/CreateGroupErrorDialog.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileGroup.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/bottomsheet/EditGroupRoleBottomSheet.kt
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/L

#3974 feat(channels): hide access settings from members (WPB-16954)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptions.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsState.kt
Labels: size/XS

#3961 feat(channels): update conversation avatar in more places [WPB-16636]
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetState.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsTopBarCollapsing.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContentTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModelTest.kt
Labels: size/S

#3978 feat: show create account button for on-prem and hide it with compile flag
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/password/NewLoginPasswordScreen.kt
Labels: size/XS

#3976 fix(channels): display icon lock on private channels [WPB-16931]
  app/src/main/kotlin/com/wire/android/mapper/ConversationMapper.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/PreviewWireModalSheetLayout.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetState.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsTopBarCollapsing.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ChannelConversationAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/RegularGroupConversationAvatar.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/test/kotlin/com/wire/android/framework/TestConversationItem.kt
  app/src/test/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContentTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupParticipantsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/usecase/GetConversationsFromSearchUseCaseTest.kt
Labels: size/L

#3975 fix: disable entering username for enterprise login flow [WPB-17025]
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/password/NewLoginPasswordScreen.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
Labels: size/S

#3977 fix: make sure coroutine is init before using it on analytics manager [WPB-17078]
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerImpl.kt
  core/analytics-enabled/src/test/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerTest.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManager.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerStub.kt
Labels: size/XS

#3981 feat: update system messages composables to match channel designs [WPB-15858]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/SystemMessageItemLeading.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/util/ui/LocalizedStringResource.kt
  app/src/main/kotlin/com/wire/android/util/ui/StyledStringUtil.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values/strings.xml
  app/src/screenshotTest/kotlin/com/wire/android/kotlin/ui/home/conversations/messages/item/PreviewMessageTypes.kt
  app/src/screenshotTest/kotlin/com/wire/android/kotlin/ui/home/conversations/messages/item/PreviewSystemMessageItem.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/TextWithLinkSuffix.kt
Labels: size/XL

#3983 fix(channels): allow team admins to do admin tasks [WPB-17100]
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/usecase/ObserveConversationRoleForUserUseCase.kt
Labels: size/XS

#3982 ci: update Jenkinsfile to use android_develop again due to recent changes for group buttons and texts [WPB-8645]
  Jenkinsfile
Labels: size/XS

#3989 feat: disable preview for PDF files (WPB-17203)
  features/cells/src/main/java/com/wire/android/feature/cells/domain/model/AttachmentFileType.kt
Labels: size/XS

#3990 fix: old login flow does not continue after entering verification code [WPB-17234]
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/verificationcode/VerificationCode.kt
Labels: size/XS

#3992 feat: File names are not aligned to bottom in file asset card (WPB-17175)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/standalone/FileAssetPreview.kt
Labels: size/XS

#3993 feat: GIFs from keyboard must be sent directly to conversation (WPB-17176)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
Labels: size/XS

#3994 fix: app crashing on navigation [WPB-17263]
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityActionsHandler.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/initialsync/InitialSyncScreen.kt
  app/src/main/kotlin/com/wire/android/ui/initialsync/InitialSyncViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/WireActivityViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/initialsync/InitialSyncViewModelTest.kt
Labels: size/L

#3996 fix: wrong sorting of tags when generating release change log [WPB-17307]
  .github/workflows/generate-changelog.yml
Labels: size/XS

#3999 fix: home requirements navigation crashing [WPB-17263]
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/HomeViewModelTest.kt
Labels: size/XS

#3997 fix: navigation crashes during login or registration [WPB-17263]
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsViewState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailViewState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewState.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/newauthentication/login/NewLoginViewModelTest.kt
Labels: size/L

#3998 feat: open team migration on creating channel upgrade [WPB-17057]
  app/src/main/kotlin/com/wire/android/navigation/MainNavHost.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/search/NewConversationSearchPeopleScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/PersonalToTeamMigrationNavGraph.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/common/BottomLineButtons.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/common/TeamMigrationContainer.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step1/TeamMigrationTeamPlanStepScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step2/TeamMigrationTeamNameStepScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step3/TeamMigrationConfirmationStepScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step4/TeamMigrationDoneStepScreen.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModelTest.kt
Labels: size/L

#4004 fix(channels): allow team admins to edit guests and self-deleting settings [WPB-17100]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/editselfdeletingmessages/EditSelfDeletingMessagesViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/editguestaccess/EditGuestAccessViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/editselfdeletingmessages/EditSelfDeletingMessagesViewModelTest.kt
Labels: size/S

#3979 chore: Cell unit tests [WPB-15386]
  features/cells/build.gradle.kts
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellViewModel.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/publiclink/PublicLinkViewModel.kt
  features/cells/src/test/kotlin/com/wire/android/config/NavigationTestExtension.kt
  features/cells/src/test/kotlin/com/wire/android/feature/cells/ui/CellViewModelTest.kt
  features/cells/src/test/kotlin/com/wire/android/feature/cells/ui/publiclink/PublicLinkViewModelTest.kt
Labels: size/L
