Repository wireapp/wire-android, pull requests merged in 2025-06, with the labels that each got.

#4045 fix: team migration banner sometimes not showing [WPB-17646]
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
Labels: size/XS

#4043 fix: error message not visible when trying to record audio during cal…
  app/src/main/kotlin/com/wire/android/ui/home/conversations/MessageComposerViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModelArrangement.kt
Labels: size/XS

#4048 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  features/cells/src/main/res/values-ru/strings.xml
  features/cells/src/main/res/values-si/strings.xml
Labels: size/XS, crowdin, l10n

#4056 fix: update bitmap loading to use withContext for coroutine scope [WPB-18107]
  app/lint-baseline.xml
  app/src/main/kotlin/com/wire/android/ui/common/imagepreview/BulletHoleImagePreview.kt
Labels: size/L

#4058 refactor: remove navigation lambdas from view models - part 3 [WPB-17842]
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/dialogs/calling/OngoingActiveCallDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/call/ConversationCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationsScreenContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioComponent.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModel.kt
  app/src/screenshotTest/kotlin/com/wire/android/kotlin/ui/home/conversations/messages/item/PreviewMessageTypes.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/call/ConversationCallViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListCallViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModelTest.kt
Labels: size/L

#4061 feat(new-registration): team account creation from app to team settings embedded (WPB-17526)
  app/src/main/kotlin/com/wire/android/ui/registration/code/CreateAccountVerificationCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/registration/details/CreateAccountDataDetailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/registration/details/CreateAccountDataDetailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/registration/selector/CreateAccountSelectorScreen.kt
  app/src/main/kotlin/com/wire/android/ui/registration/selector/CreateAccountSelectorViewModel.kt
  app/src/main/kotlin/com/wire/android/util/CustomTabsHelper.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/registration/details/CreateAccountDataDetailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/registration/selector/CreateAccountSelectorViewModelTest.kt
Labels: size/M

#4064 refactor: extract common actions code to dedicated classes [WPB-17842]
  app/src/main/kotlin/com/wire/android/ui/WireActivityActionsHandler.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivityViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/SharedCallingViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButton.kt
  app/src/main/kotlin/com/wire/android/ui/connection/ConnectionActionButtonViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/attachment/MessageAttachmentsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/banner/ConversationBannerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/call/ConversationCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/composer/MessageComposerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/metadata/EditConversationMetadataViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/GroupConversationParticipantsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/ConversationAssetMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/preview/ImagesPreviewViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messagedetails/MessageDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/draft/MessageDraftViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/migration/ConversationMigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/sendmessage/SendMessageViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListCallViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationsScreenContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/drawer/HomeDrawerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioComponent.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/settings/account/MyAccountViewModelTest.kt
  core/navigation/src/main/kotlin/com/wire/android/navigation/SavedStateViewModel.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/ActionsViewModel.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellScreenContent.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellViewModel.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/createfolder/CreateFolderViewModel.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/movetofolder/MoveToFolderScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/movetofolder/MoveToFolderViewModel.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/publiclink/PublicLinkScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/publiclink/PublicLinkViewModel.kt
  features/cells/src/test/kotlin/com/wire/android/feature/cells/ui/movetofolder/MoveToFolderViewModelTest.kt
Labels: size/L

#4065 fix: handling team settings events [WPB-18202]
  gradle/libs.versions.toml
Labels: size/XS

#4071 fix: new registration general fixes about navigation and copies (WPB-17410)
  app/src/main/kotlin/com/wire/android/ui/authentication/create/username/CreateAccountUsernameScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/registration/details/CreateAccountDataDetailScreen.kt
  app/src/main/res/values/strings.xml
Labels: size/XS

#4068 fix: emoji picker issues on tablet landscape [WPB-18132] [WPB-18133]
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/MutingOptionsSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/edit/ReactionOption.kt
  app/src/main/kotlin/com/wire/android/ui/emoji/DraggableByHandleBottomSheetBehavior.kt
  app/src/main/kotlin/com/wire/android/ui/emoji/EmojiPicker.kt
  app/src/main/kotlin/com/wire/android/ui/emoji/HandleDraggableBottomSheetDialog.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/filter/ConversationFoldersSheetContent.kt
  app/src/main/res/layout/dialog_bottom_sheet_custom_behavior.xml
  app/src/main/res/layout/view_emoji_picker.xml
  app/src/main/res/values-night/colors.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetLayout.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/bottomsheet/WireModalSheetState.kt
Labels: size/L

#4084 fix: resolve crash on initialization and revert Amplituda dependency update [WPB-17405]
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/media/audiomessage/AudioWavesMaskHelper.kt
  gradle/libs.versions.toml
Labels: size/XS

#4074 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  core/ui-common/src/main/res/values-de/strings.xml
  features/cells/src/main/res/values-de/strings.xml
Labels: size/XS, crowdin, l10n

#4086 fix: new registration flows fixes to code verification screen (WPB-18400) (WPB-18401)
  app/src/main/kotlin/com/wire/android/ui/registration/code/CreateAccountVerificationCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/registration/details/CreateAccountDataDetailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/registration/details/CreateAccountDataDetailViewState.kt
Labels: size/XS

#4087 fix: request 2fa code when removing client (#WPB-11401)
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceVerificationCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/devices/remove/RemoveDeviceViewModelTest.kt
Labels: size/S
