Repository wireapp/wire-android, pull requests merged in 2025-08, with the labels that each got.

#4146 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  features/cells/src/main/res/values-ru/strings.xml
  features/cells/src/main/res/values-si/strings.xml
Labels: size/S, crowdin, l10n

#4170 fix(ci): failing gh actions for assign PR and semantic commit messages (WPB-8645)
  .github/workflows/pr-author-assigner.yml
  .github/workflows/semantic-commit-lint.yml
Labels: size/XS

#4168 fix: updating dialog when removing a member [WPB-19134]
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileInfoMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileScreenViewModel.kt
  app/src/main/res/values/strings.xml
Labels: size/XS

#4169 fix: send UI rotations to AVS so that the output video is rotated correctly [WPB-17201]
  app/src/main/kotlin/com/wire/android/di/accountScoped/CallsModule.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/StartingCallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallScreenObservers.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/CallerDetails.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/ProximitySensorManager.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/SharedCallingViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/calling/incoming/IncomingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/model/CallState.kt
  app/src/main/kotlin/com/wire/android/ui/calling/model/ConversationName.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/FullScreenTile.kt
  app/src/main/kotlin/com/wire/android/ui/calling/outgoing/OutgoingCallScreen.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
Labels: size/S

#4153 fix: not able to unmute incoming or outgoing call until established [WPB-19112]
  app/src/main/kotlin/com/wire/android/di/accountScoped/CallsModule.kt
  app/src/main/kotlin/com/wire/android/ui/calling/common/SharedCallingViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/calling/SharedCallingViewModelTest.kt
Labels: size/M

#4193 fix: crash when client removed (cherrypick from rc) (#WPB-18706)
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/HomeViewModelTest.kt
Labels: size/XS

#4167 fix: Flickering when opening conversation details (WPB-19187)
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/ui/common/AppExtensions.kt
  app/src/main/kotlin/com/wire/android/ui/common/WireTabRow.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsTopBarCollapsing.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/SearchAndMediaRow.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/GroupConversationOptionsState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/options/LoadingGroupConversation.kt
  core/ui-common/build.gradle.kts
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/Extensions.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/button/LoadingWireSecondaryButton.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/L

#4198 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-zh/strings.xml
  features/cells/src/main/res/values-de/strings.xml
  features/cells/src/main/res/values-ru/strings.xml
Labels: size/XS, crowdin, l10n

#4191 fix: show public link info for folders (WPB-19471)
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellListItem.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/model/CellNodeUi.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/movetofolder/MoveToFolderScreen.kt
Labels: size/XS

#4213 fix: close attachments menu after selecting file (WPB-19407)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
Labels: size/XS

#4212 fix(cells): missing padding for rename screen action button (WPB-19464)
  features/cells/src/main/java/com/wire/android/feature/cells/ui/rename/RenameNodeScreen.kt
Labels: size/XS

#4204 feat(cells): Scroll to the last item when a new attachment is added (WPB-19460)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageAttachments.kt
Labels: size/XS

#4187 feat: cells feature flag (WPB-19476)
  app/src/androidTest/kotlin/com/wire/android/ui/debug/DebugScreenComposeTest.kt
  app/src/main/kotlin/com/wire/android/datastore/GlobalDataStore.kt
  app/src/main/kotlin/com/wire/android/di/accountScoped/UserModule.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugScreen.kt
  app/src/main/kotlin/com/wire/android/ui/debug/DebugWireCellOptions.kt
  app/src/main/kotlin/com/wire/android/ui/debug/UserDebugViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/debug/featureflags/DebugFeatureFlagsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/drawer/HomeDrawerViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/details/GroupDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/drawer/HomeDrawerViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/newconversation/NewConversationViewModelArrangement.kt
Labels: size/S

#4209 chore(l10n): update localization strings via Crowdin (WPB-9776)
  features/cells/src/main/res/values-ru/strings.xml
  features/cells/src/main/res/values-si/strings.xml
  features/cells/src/main/res/values-tr/strings.xml
Labels: size/XS, crowdin, l10n

#4189 fix: crash when downloading file (WPB-19465)
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellViewModel.kt
Labels: size/XS

#4218 feat: message bubble container [WPB-19488] [WPB-19489]
  app/src/main/kotlin/com/wire/android/ui/common/spacers/VerticalSpace.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageAuthorRow.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageBubbleItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageContentAndStatus.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageContentItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageItemTemplate.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageStatusIndicator.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageStyle.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/SystemMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/preview/PreviewMesssageBubbleTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mock/Mock.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/util/DurationUtil.kt
  config/detekt/baseline.xml
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/XL

#4221 feat: group multipart message assets (WPB-17177)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/MultipartAttachmentsView.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/MultipartAttachmentsViewModel.kt
Labels: size/XS

#4216 chore(l10n): update localization strings via Crowdin (WPB-9776)
  features/cells/src/main/res/values-de/strings.xml
  features/cells/src/main/res/values-ru/strings.xml
  features/cells/src/main/res/values-si/strings.xml
  features/cells/src/main/res/values-tr/strings.xml
Labels: size/XS, crowdin, l10n
