Repository wireapp/wire-android, pull requests merged in 2025-01, with the labels that each got.

#3776 fix: show no connection banner faster [#WPB-11568]
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
Labels: size/XS, echoes: product-roadmap

#3781 feat: show Guest label for personal users after migration in conversations screen - RC (WPB-14871)
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/common/BottomLineButtons.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step3/TeamMigrationConfirmationStepScreen.kt
Labels: size/XS, echoes/initiative: personal-users-to-team-users...

#3720 chore: wrong url when opening team management after migration - cherrypick (WPB-14872)
  app/src/main/kotlin/com/wire/android/di/CoreLogicModule.kt
  app/src/main/kotlin/com/wire/android/di/accountScoped/UserModule.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/step4/TeamMigrationDoneStepScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModelTest.kt
Labels: size/XS, echoes/initiative: personal-users-to-team-users...

#3784 ci: update s3 config to adjust to private (WPB-8645)
  .github/actions/deploy-to-s3/action.yml
Labels: size/XS

#3789 chore: Migrate from hilt-android-compiler to hilt-compiler (WPB-8645)
  gradle/libs.versions.toml
Labels: size/XS

#3790 refactor: adjust to edge-to-edge, remove deprecated APIs [WPB-14903]
  app/src/main/kotlin/com/wire/android/navigation/MainNavHost.kt
  app/src/main/kotlin/com/wire/android/ui/AppLockActivity.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/StartingCallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallActivity.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBar.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBarViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/emoji/HandleDraggableBottomSheetDialog.kt
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/StatusBarsHelper.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/Theme.kt
Labels: size/M, echoes: technical-roadmap

#3796 fix: emoji picker dialog showing randomly [#WPB-6681]
  app/src/main/kotlin/com/wire/android/ui/emoji/EmojiPicker.kt
Labels: size/XS, echoes: unplanned

#3805 feat: add new conversation folder [WPB-14628]
  app/src/main/kotlin/com/wire/android/di/accountScoped/ConversationModule.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/folder/ConversationFoldersScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/folder/NewConversationFolderScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/folder/NewFolderViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/common/bottomsheet/folder/NewFolderViewModelTest.kt
Labels: size/L, echoes: product-roadmap

#3797 fix: answer call from notification in foreground service [WPB-9648]
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/IncomingCallActionReceiver.kt
  app/src/main/kotlin/com/wire/android/services/CallService.kt
  app/src/main/kotlin/com/wire/android/services/ServicesManager.kt
  app/src/test/kotlin/com/wire/android/services/ServicesManagerTest.kt
Labels: size/S, echoes: technical-roadmap

#3713 chore: upload mapping file to s3 (WPB-8774)
  .github/actions/deploy-to-s3/action.yml
Labels: size/XS, echoes: technical-roadmap/throughput

#3811 fix: hide emojis panel in minimized call mode (#WPB-14254)
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/OngoingCallScreen.kt
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/incallreactions/InCallReactionsModifier.kt
Labels: size/XS, echoes: product-roadmap/feature

#3802 feat: AudioMessages play in background part 2 #WPB-11725
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/media/audiomessage/AudioFocusHelper.kt
  app/src/main/kotlin/com/wire/android/media/audiomessage/AudioState.kt
  app/src/main/kotlin/com/wire/android/media/audiomessage/ConversationAudioMessagePlayer.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationConstants.kt
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/PlayPauseAudioMessageReceiver.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/StopAudioMessageReceiver.kt
  app/src/main/kotlin/com/wire/android/services/PlayingAudioMessageService.kt
  app/src/main/kotlin/com/wire/android/services/ServicesManager.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationsScreenContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationList.kt
  app/src/main/res/layout/notification_playing_audio_message.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/media/ConversationAudioMessagePlayerTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
Labels: size/XL, echoes: product-roadmap

#3812 feat: adjust new login skeleton to edge-to-edge [WPB-14337]
  app/build.gradle.kts
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/NewLoginContainer.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/WireAuthBackgroundComponent.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/start/StartLoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/common/topappbar/CommonTopAppBar.kt
  core/navigation/src/main/kotlin/com/wire/android/navigation/style/BackgroundStyle.kt
  core/navigation/src/main/kotlin/com/wire/android/navigation/style/NavigationAnimationStyles.kt
  core/ui-common/build.gradle.kts
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/preview/EdgeToEdgePreview.kt
  gradle/libs.versions.toml
Labels: size/M, echoes: product-roadmap/feature

#3813 fix: crash when opening conversation details (#WPB-15522)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/GroupConversationDetailsScreen.kt
Labels: size/XS

#3810 fix: set the correct screen title name [WPB-15248]
  app/src/main/kotlin/com/wire/android/ui/home/HomeStateHolder.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/filter/ConversationFilterSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/filter/ConversationFiltersSheetContent.kt
Labels: size/XS, echoes: product-roadmap

#3819 fix: scrollable folders filter [WPB-15474]
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/filter/ConversationFoldersSheetContent.kt
Labels: size/XS, echoes: product-roadmap

#3820 fix: wrong error after adding folder [WPB-15478]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/folder/NewFolderViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/common/bottomsheet/folder/NewFolderViewModelTest.kt
Labels: size/XS, echoes: product-roadmap

#3766 feat: Audio message play in background WPB-11725
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/mapper/ConversationMapper.kt
  app/src/main/kotlin/com/wire/android/media/audiomessage/AudioFocusHelper.kt
  app/src/main/kotlin/com/wire/android/media/audiomessage/AudioState.kt
  app/src/main/kotlin/com/wire/android/media/audiomessage/ConversationAudioMessagePlayer.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationChannelsManager.kt
  app/src/main/kotlin/com/wire/android/notification/NotificationConstants.kt
  app/src/main/kotlin/com/wire/android/notification/PendingIntents.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/PlayPauseAudioMessageReceiver.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/StopAudioMessageReceiver.kt
  app/src/main/kotlin/com/wire/android/services/PlayingAudioMessageService.kt
  app/src/main/kotlin/com/wire/android/services/ServicesManager.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewState.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/usecase/GetConversationsFromSearchUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationsScreenContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationList.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/model/ConversationItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModel.kt
  app/src/main/res/layout/notification_playing_audio_message.xml
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/framework/TestConversationItem.kt
  app/src/test/kotlin/com/wire/android/media/ConversationAudioMessagePlayerTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelArrangement.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/messages/ConversationMessagesViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModelTest.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/XL, echoes: product-roadmap

#3821 chore: added more logs in import media screen [WPB-15656]
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaAuthenticatedViewModel.kt
Labels: size/XS, echoes: product-roadmap/bug

#3817 feat: bring back current login flow and add a feature flag for enterprise login [WPB-15543]
  app/src/main/kotlin/com/wire/android/feature/AccountSwitchUseCase.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginErrorDialog.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/start/StartLoginScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/home/appLock/forgot/ForgotLockCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/migration/MigrationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginContainer.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginScreenState.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/password/NewLoginPasswordScreen.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/welcome/NewWelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/sharing/ImportMediaScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
  app/src/main/res/values/strings.xml
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
Labels: size/XL, echoes/initiative: scale

#3823 fix: Blue dot at the end of progress #WPB-14575
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/progress/WireLinearProgressIndicator.kt
Labels: size/XS, echoes: product-roadmap/bug

#3825 feat: enter password and proxy details screen [WPB-14338]
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/common/ServerTitle.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreatePersonalAccountOverviewScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/ProxyScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginContainer.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/password/NewLoginPasswordScreen.kt
  app/src/main/res/values/strings.xml
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/bottomsheet/ModalSheetHeaderItem.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/topappbar/NavigationIconButton.kt
Labels: size/L, echoes/initiative: scale

#3828 fix: collapse expanded text field after click on send message [WPB-14574]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/MessageComposer.kt
Labels: size/XS, echoes: product-roadmap/bug

#3829 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-af/strings.xml
  app/src/main/res/values-ar/strings.xml
  app/src/main/res/values-bn/strings.xml
  app/src/main/res/values-ca/strings.xml
  app/src/main/res/values-cs/strings.xml
  app/src/main/res/values-da/strings.xml
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-el/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-et/strings.xml
  app/src/main/res/values-fa/strings.xml
  app/src/main/res/values-fi/strings.xml
  app/src/main/res/values-fr/strings.xml
  app/src/main/res/values-he/strings.xml
  app/src/main/res/values-hi/strings.xml
  app/src/main/res/values-hr/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-id/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-ja/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values-lt/strings.xml
  app/src/main/res/values-mk/strings.xml
  app/src/main/res/values-nl/strings.xml
  app/src/main/res/values-no/strings.xml
  app/src/main/res/values-pa/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ro/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values-sk/strings.xml
  app/src/main/res/values-sl/strings.xml
  app/src/main/res/values-sr/strings.xml
  app/src/main/res/values-sv/strings.xml
  app/src/main/res/values-tr/strings.xml
  app/src/main/res/values-uk/strings.xml
  app/src/main/res/values-vi/strings.xml
  app/src/main/res/values-zh/strings.xml
  core/ui-common/src/main/res/values-it/strings.xml
  features/sketch/src/main/res/values-it/strings.xml
Labels: size/S, crowdin, l10n, echoes: technical-roadmap

#3830 feat: enterprise login, adjust style initial screen - remove footer (WPB-15520)
  app/src/main/kotlin/com/wire/android/ui/authentication/login/WireAuthBackgroundComponent.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginContainer.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginScreen.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/welcome/NewWelcomeScreen.kt
  app/src/main/res/values/strings.xml
  app/src/test/kotlin/com/wire/android/ui/newauthentication/login/ValidateEmailOrSSOCodeUseCaseTest.kt
  core/navigation/src/main/kotlin/com/wire/android/navigation/style/NavigationAnimationStyles.kt
Labels: size/XS, echoes/initiative: scale

#3827 fix: MLS with unknown signature shown for other users devices WPB-15268
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsViewModel.kt
  app/src/main/res/values/strings.xml
Labels: size/XS, echoes: product-roadmap/bug

#3816 fix: Segmentation missing for countly events (WPB-14646)
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/ui/home/HomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/teammigration/TeamMigrationViewModelTest.kt
  core/analytics-disabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorderImpl.kt
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorderImpl.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/model/AnalyticsEvent.kt
Labels: size/XS, echoes: product-roadmap/bug

#3808 chore: show MLS client ID in debug screen for private builds [WPB-15215]
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
Labels: size/XS, echoes: product-roadmap/bug

#3837 fix: Wrong emojy order in message context menu #WPB-15119
  app/src/main/kotlin/com/wire/android/ui/edit/ReactionOption.kt
Labels: size/XS, echoes: product-roadmap/bug

#3832 feat: add is_team_member and user_type segmentations (WPB-14646)
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeState.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQrCodeNavArgs.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/SelfUserProfileScreen.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeViewModelTest.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/model/AnalyticsEvent.kt
Labels: size/S, echoes: product-roadmap/bug

#3836 feat: Temporarily stopping sending ui.clicked-profile event (WPB-15246)
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
Labels: size/XS, echoes: product-roadmap/bug

#3792 fix: Conversations and Profile Views are reported individually (WPB-14942)
  app/src/main/kotlin/com/wire/android/util/CurrentScreenManager.kt
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsManagerImpl.kt
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/StringExt.kt
  core/analytics-enabled/src/test/kotlin/com/wire/android/feature/analytics/StringExtTest.kt
Labels: size/S, echoes/initiative: product-metrics-in-countly

#3841 feat: Add is team member segmentation to app.open event (WPB-14523)
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  core/analytics/src/main/kotlin/com/wire/android/feature/analytics/model/AnalyticsEvent.kt
Labels: size/XS, echoes/initiative: product-metrics-in-countly

#3833 fix: message composer option height update [WPB-11039]
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/EnabledMessageComposer.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolder.kt
  app/src/test/kotlin/com/wire/android/ui/home/messagecomposer/state/MessageCompositionInputStateHolderTest.kt
Labels: size/XS, echoes: unplanned

#3834 fix: Audio wave mask fixes #WPB-11723
  app/src/main/kotlin/com/wire/android/media/audiomessage/AudioWavesMaskHelper.kt
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioComponent.kt
Labels: size/XS, echoes: product-roadmap

#3835 fix: InCallReaction background in dark mode #WPB-15550
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/XS, echoes: product-roadmap/feature

#3848 fix: Delete conversation Crash #WPB-14938
  app/src/main/kotlin/com/wire/android/notification/NotificationConstants.kt
  app/src/main/kotlin/com/wire/android/workmanager/WireWorkerFactory.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/DeleteConversationLocallyWorker.kt
  app/src/main/kotlin/com/wire/android/workmanager/worker/PersistentWebsocketCheckWorker.kt
  app/src/main/res/values/strings.xml
Labels: size/XS, echoes: product-roadmap/feature

#3850 fix: App closing after back-click on Settings WPB-15422
  app/src/main/kotlin/com/wire/android/ui/home/HomeScreen.kt
Labels: size/XS, echoes: product-roadmap/bug
