Repository wireapp/wire-android, pull requests merged in 2025-09, with the labels that each got.

#4230 feat: message bubble assets, mentions and links [WPB-19603]
  app/src/main/kotlin/com/wire/android/ui/common/attachmentdraft/ui/AttachmentFileView.kt
  app/src/main/kotlin/com/wire/android/ui/common/attachmentdraft/ui/FileHeaderView.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/ImageAssetsContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageAuthorRow.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageBubbleItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageContentAndStatus.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/preview/PreviewMessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/asset/AssetMessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/audio/AudioMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/image/ImageMessageParams.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/image/ImageMessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/location/LocationMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/MultipartAttachmentsView.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/grid/AssetGridPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/grid/FileAssetGridPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/grid/VideoAssetGridPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/standalone/AssetPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/standalone/FileAssetPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/standalone/ImageAssetPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/standalone/PdfAssetPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/standalone/VideoAssetPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/video/VideoMessage.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownComposer.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownParagraph.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/NodeData.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/L

#4229 fix: fullscreen label should not hide automatically [WPB-10823]
  app/src/main/kotlin/com/wire/android/ui/calling/ongoing/fullscreen/FullScreenTile.kt
Labels: size/XS

#4236 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-ru/strings.xml
  features/cells/src/main/res/values-de/strings.xml
  features/cells/src/main/res/values-ru/strings.xml
  features/cells/src/main/res/values-tr/strings.xml
Labels: size/XS, crowdin, l10n

#4251 fix: device fingerprint (WPB-20127)
  app/src/main/kotlin/com/wire/android/ui/settings/devices/DeviceDetailsScreen.kt
Labels: size/XS

#4254 fix: socket setting description (WPB-20137)
  app/src/main/kotlin/com/wire/android/ui/home/settings/appsettings/networkSettings/NetworkSettingsScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/appsettings/networkSettings/NetworkSettingsViewModel.kt
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-es/strings.xml
  app/src/main/res/values-hu/strings.xml
  app/src/main/res/values-it/strings.xml
  app/src/main/res/values-pl/strings.xml
  app/src/main/res/values-pt/strings.xml
  app/src/main/res/values-ru/strings.xml
  app/src/main/res/values-si/strings.xml
  app/src/main/res/values/strings.xml
Labels: size/XS

#4241 feat: make breadcrumbs clickable (WPB-19190)
  app/src/main/kotlin/com/wire/android/navigation/NavigationUtils.kt
  app/src/main/kotlin/com/wire/android/navigation/Navigator.kt
  core/navigation/src/main/kotlin/com/wire/android/navigation/PreviewNavigator.kt
  core/navigation/src/main/kotlin/com/wire/android/navigation/WireNavigator.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/ConversationFilesScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/ConversationFilesWithSlideInTransitionScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/common/Breadcrumbs.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/movetofolder/MoveToFolderScreen.kt
Labels: size/XS

#4264 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-de/strings.xml
  app/src/main/res/values-ru/strings.xml
Labels: size/XS, crowdin, l10n

#4265 feat: backend selector (WPB-20303)
  app/src/main/kotlin/com/wire/android/ui/common/WireDropDown.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/BackendSelectorDropDown.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginContainer.kt
Labels: size/S

#4266 chore: files list skeleton loading (WPB-20175)
  app/src/main/kotlin/com/wire/android/ui/debug/DebugDataOptions.kt
  app/src/main/kotlin/com/wire/android/ui/debug/LogOptions.kt
  app/src/main/kotlin/com/wire/android/ui/debug/conversation/DebugConversationScreen.kt
  app/src/main/kotlin/com/wire/android/ui/debug/featureflags/FeatureListItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/participants/ConversationParticipantItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/mention/MemberItemToMention.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/InternalContactSearchResultItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/search/SearchAllServicesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationItemFactory.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/common/ConversationList.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/SettingsItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/about/dependencies/DependenciesScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/about/licenses/LicensesItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/settings/account/MyAccountScreen.kt
  app/src/main/kotlin/com/wire/android/ui/home/whatsnew/WhatsNewItem.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileDetails.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/other/OtherUserProfileGroup.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/self/OtherAccounts.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/SurfaceBackgroundWrapper.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/rowitem/RowItem.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/common/rowitem/RowItemTemplate.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/common/LoadingScreen.kt
Labels: size/S

#4268 chore(l10n): update localization strings via Crowdin (WPB-9776)
  app/src/main/res/values-de/strings.xml
  features/cells/src/main/res/values-de/strings.xml
  features/cells/src/main/res/values-ru/strings.xml
  features/cells/src/main/res/values/strings.xml
Labels: size/XS, crowdin, l10n

#4276 feat: selected reactions on bottom sheet [WPB-19602]
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/PreviewWireModalSheetLayout.kt
  app/src/main/kotlin/com/wire/android/ui/edit/ReactionOption.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/AssetOptionsMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/MessageOptionsMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/MessageOptionsModalSheetLayout.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/edit/TextMessageOptionsMenuItems.kt
  app/src/main/kotlin/com/wire/android/ui/home/gallery/MediaGalleryScreen.kt
Labels: size/XS

#4278 fix: message bubble assets [WPB-20219]
  app/src/main/kotlin/com/wire/android/ui/common/attachmentdraft/ui/FileHeaderView.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/media/ImageAssetsContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageContentAndStatus.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageStyle.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/MessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/asset/AssetMessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/audio/AudioMessageType.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/image/ImageMessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/video/VideoMessage.kt
Labels: size/S

#4279 chore: string update (WPB-20380)
  features/cells/src/main/res/values/strings.xml
Labels: size/XS

#4272 fix: use file uuid for restore operation (WPB-20001)
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellViewModel.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/ConversationFilesScreen.kt
Labels: size/XS

#4281 fix: rename file validation (WPB-20373)
  features/cells/src/main/java/com/wire/android/feature/cells/ui/rename/RenameNodeViewModel.kt
  features/cells/src/test/kotlin/com/wire/android/feature/cells/ui/rename/RenameNodeViewModelTest.kt
Labels: size/XS

#4301 fix: wrong casting for partial deliverable message content [WPB-20551]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
Labels: size/XS

#4302 fix: message bubble improvements [WPB-20561]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageAuthorRow.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageBubbleItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageStyle.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/asset/AssetMessageTypes.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/location/LocationMessageType.kt
Labels: size/S

#4297 chore(l10n): update localization strings via Crowdin (WPB-9776)
  features/cells/src/main/res/values-de/strings.xml
  features/cells/src/main/res/values-ru/strings.xml
Labels: size/XS, crowdin, l10n

#4300 fix: correct type check for delivery status in RegularMessageItem [WPB-20551]
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
Labels: size/XS

#4290 chore: show error message when max file name length exceeded (WPB-20379)
  features/cells/src/main/java/com/wire/android/feature/cells/ui/rename/RenameNodeScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/rename/RenameNodeViewModel.kt
Labels: size/XS

#4308 fix: markdown on accent colors [WPB-20626]
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownBlockQuote.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownHeading.kt
  app/src/main/kotlin/com/wire/android/ui/markdown/MarkdownList.kt
Labels: size/XS

#4307 fix: disable bubbles feature flag
  app/src/main/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/info/ConversationInfoViewModelArrangement.kt
Labels: size/XS

#4304 feat: Adjust Bubbles for cells (WPB-19605)
  app/src/main/kotlin/com/wire/android/ui/common/attachmentdraft/ui/FileHeaderView.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageBubbleItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageContentAndStatus.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageContentItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/RegularMessageItem.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/image/ImageMessageParams.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/MultipartAttachmentsView.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/standalone/AssetNotAvailablePreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/standalone/AssetPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/standalone/FileAssetPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/standalone/ImageAssetPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/standalone/PdfAssetPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/standalone/VideoAssetPreview.kt
  app/src/main/res/drawable-night/ic_file_not_available.xml
  app/src/main/res/drawable/ic_file_not_available.xml
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireDimensions.kt
Labels: size/L

#4305 fix: show restore error dialog (WPB-20484)
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellScreenContent.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellViewModel.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/recyclebin/UnableToRestoreDialog.kt
Labels: size/XS

#4310 fix: message bubble reply accent background
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/QuotedMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/messages/item/MessageContentAndStatus.kt
  core/ui-common/src/main/kotlin/com/wire/android/ui/theme/WireColorScheme.kt
Labels: size/XS
