Repository wireapp/wire-android, pull requests merged in 2025-05, with the labels that each got.

#4012 feat: handle federated case for user ids in QR code (WPB-10530)
  app/src/androidTest/kotlin/com/wire/android/util/UserLinkQRMapperTest.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/util/deeplink/DeepLinkProcessor.kt
  app/src/main/kotlin/com/wire/android/util/deeplink/UserLinkQRMapper.kt
  app/src/test/kotlin/com/wire/android/ui/userprofile/qr/SelfQRCodeViewModelTest.kt
  app/src/test/kotlin/com/wire/android/util/DeepLinkProcessorTest.kt
Labels: size/S

#4011 chore: setup ui automator for appium replacement (WPB-8645)
  build-logic/plugins/build.gradle.kts
  build-logic/plugins/src/main/kotlin/AndroidTestLibraryConventionPlugin.kt
  build-logic/plugins/src/test/resources/version.txt
  docs/adr/0006-enterprise-login-supporting-both-flows.md
  docs/adr/0007-introducing-uiautomator.md
  gradle/libs.versions.toml
  settings.gradle.kts
  tests/testsCore/.gitignore
  tests/testsCore/build.gradle.kts
  tests/testsCore/consumer-rules.pro
  tests/testsCore/lint-baseline.xml
  tests/testsCore/proguard-rules.pro
  tests/testsCore/src/androidTest/kotlin/com/wire/android/tests/core/login/LoginTest.kt
  tests/testsCore/src/androidTest/kotlin/com/wire/android/tests/core/login/pages/LoginPage.kt
  tests/testsCore/src/androidTest/kotlin/com/wire/android/tests/core/registration/RegistrationTest.kt
  tests/testsCore/src/main/AndroidManifest.xml
  tests/testsSupport/.gitignore
  tests/testsSupport/build.gradle.kts
  tests/testsSupport/consumer-rules.pro
  tests/testsSupport/lint-baseline.xml
  tests/testsSupport/proguard-rules.pro
  tests/testsSupport/src/androidTest/kotlin/com/wire/android/tests/support/UiAutomatorSetup.kt
  tests/testsSupport/src/androidTest/kotlin/com/wire/android/tests/support/suite/RC.kt
  tests/testsSupport/src/androidTest/kotlin/com/wire/android/tests/support/suite/Regression.kt
  tests/testsSupport/src/main/AndroidManifest.xml
Labels: size/L

#4009 fix: run and await app config sync on IO dispatcher [WPB-15730]
  app/src/main/kotlin/com/wire/android/ui/home/AppSyncViewModel.kt
  app/src/test/kotlin/com/wire/android/ui/home/AppSyncViewModelTest.kt
Labels: size/XS

#4010 chore: simplify new login selector [WPB-15730]
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/navigation/LoginTypeSelector.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/test/kotlin/com/wire/android/navigation/LoginTypeSelectorTest.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  core/analytics-enabled/src/main/kotlin/com/wire/android/feature/analytics/AnonymousAnalyticsRecorderImpl.kt
  default.json
Labels: size/XS

#4015 fix: schema validation for attachments (WPB-17546)
  app/src/main/kotlin/com/wire/android/WireApplication.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/usecase/HandleUriAssetUseCase.kt
  app/src/main/kotlin/com/wire/android/util/FileManager.kt
  app/src/test/kotlin/com/wire/android/ui/home/conversations/usecase/HandleUriAssetUseCaseTest.kt
Labels: size/XS

#4017 fix: use content resolver for sending audio messages (WPB-17546)
  app/src/main/kotlin/com/wire/android/ui/home/messagecomposer/recordaudio/RecordAudioViewModel.kt
  app/src/main/kotlin/com/wire/android/util/FileUtil.kt
Labels: size/XS

#4013 feat: message grouping update (#WPB-17468)
  app/src/main/kotlin/com/wire/android/mapper/MessageDateGroupingMapper.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/ConversationScreen.kt
Labels: size/XS

#4020 fix: init Amplituda lib causing NullPointerException on some devices [WPB-17405]
  app/src/main/kotlin/com/wire/android/di/AppModule.kt
  app/src/main/kotlin/com/wire/android/media/audiomessage/AudioState.kt
  app/src/main/kotlin/com/wire/android/media/audiomessage/AudioWavesMaskHelper.kt
  app/src/main/kotlin/com/wire/android/media/audiomessage/RecordAudioMessagePlayer.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/audio/AudioMessageType.kt
  gradle/libs.versions.toml
Labels: size/XS

#4000 chore: remove some non-determinism
  app/build.gradle.kts
Labels: size/XS

#4022 bugfix: channel screen UI used for group name edit screen (#WPB-17540)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/details/metadata/EditConversationMetadataViewModel.kt
Labels: size/XS

#4019 feat: Share folder via link (WPB-17276)
  features/cells/src/main/java/com/wire/android/feature/cells/ui/AllFilesScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellFilesScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellScreenContent.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/CellViewModel.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/ConversationFilesScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/dialog/FileActionsBottomSheet.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/dialog/FolderActionsBottomSheet.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/model/CellNodeUi.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/publiclink/PublicLinkNavArgs.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/publiclink/PublicLinkScreen.kt
  features/cells/src/main/java/com/wire/android/feature/cells/ui/publiclink/PublicLinkViewModel.kt
  features/cells/src/main/res/values/strings.xml
  features/cells/src/test/kotlin/com/wire/android/feature/cells/ui/CellViewModelTest.kt
Labels: size/XS

#4029 fix: enable replying to video messages (#WPB-17664)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIMessage.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/UIQuotedMessage.kt
Labels: size/XS

#4031 chore: add learn more link to the e2ei info text (#WPB-7131)
  app/src/main/kotlin/com/wire/android/ui/e2eiEnrollment/E2EIEnrollmentScreen.kt
  app/src/main/res/values/strings.xml
Labels: size/XS

#4030 fix: align channel and group icon colors with other platforms (#WPB-17690)
  app/src/main/kotlin/com/wire/android/ui/common/AppThemeExt.kt
Labels: size/XS

#4033 fix: close bottom sheet after user action (#WPB-16282)
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/ConversationSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/common/bottomsheet/conversation/HomeSheetContent.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationListViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversationslist/ConversationsScreenContent.kt
Labels: size/XS

#4028 fix: call service crashing in background (#WPB-17663)
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
  app/src/main/kotlin/com/wire/android/services/CallService.kt
  app/src/test/kotlin/com/wire/android/notification/CallNotificationManagerTest.kt
Labels: size/XS

#4038 fix: call notification crash (#WPB-17868)
  app/src/main/kotlin/com/wire/android/notification/CallNotificationManager.kt
Labels: size/XS

#4040 feat: add support for customizable branch in custom builds [WPB-17922]
  buildSrc/src/main/kotlin/customization/Customization.kt
Labels: size/XS
