Repository wireapp/wire-android, pull requests merged in 2025-10, with the labels that each got.

#4316 feat(emm): get default Server URLs configuration via EMM (WPB-20305)
  Makefile
  app/src/main/kotlin/com/wire/android/config/DefaultServerConfig.kt
  app/src/main/kotlin/com/wire/android/config/ServerConfigProvider.kt
  app/src/main/kotlin/com/wire/android/di/ServerConfigModule.kt
  app/src/main/kotlin/com/wire/android/emm/ManagedConfigurationsKeys.kt
  app/src/main/kotlin/com/wire/android/emm/ManagedConfigurationsReceiver.kt
  app/src/main/kotlin/com/wire/android/emm/ManagedConfigurationsRepository.kt
  app/src/main/kotlin/com/wire/android/emm/ManagedServerConfig.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreateAccountOverviewViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/registration/code/CreateAccountVerificationCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/registration/details/CreateAccountDataDetailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/registration/selector/CreateAccountSelectorScreen.kt
  app/src/main/kotlin/com/wire/android/ui/registration/selector/CreateAccountSelectorViewModel.kt
  app/src/main/kotlin/com/wire/android/util/UriUtil.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/app_restrictions.xml
  app/src/test/kotlin/com/wire/android/emm/ManagedConfigurationsRepositoryTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/LoginViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/welcome/WelcomeViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/newauthentication/login/NewLoginViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/registration/details/CreateAccountDataDetailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/registration/selector/CreateAccountSelectorViewModelTest.kt
Labels: size/L

#4318 feat(cells): show Pdf preview in conversation screen (WPB-20712)
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/standalone/AssetPreview.kt
  app/src/main/kotlin/com/wire/android/ui/home/conversations/model/messagetypes/multipart/standalone/PdfAssetPreview.kt
  features/cells/src/main/res/values/strings.xml
Labels: size/S

#4329 feat(emm): add compile time flag to enable EMM support based on flavors (WPB-20290)
  app/src/main/kotlin/com/wire/android/di/ManagedConfigurationsModule.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/DynamicReceiversManager.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
Labels: size/XS

#4331 chore: restore subfolders (WPB-20559)
  features/cells/src/main/java/com/wire/android/feature/cells/ui/ConversationFilesScreen.kt
Labels: size/XS

#4327 feat(emm): epic - support managed enterprise devices configurations (WPB-19646)
  Makefile
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/kotlin/com/wire/android/config/ServerConfigProvider.kt
  app/src/main/kotlin/com/wire/android/di/ManagedConfigurationsModule.kt
  app/src/main/kotlin/com/wire/android/emm/ManagedConfigurationsKeys.kt
  app/src/main/kotlin/com/wire/android/emm/ManagedConfigurationsManager.kt
  app/src/main/kotlin/com/wire/android/emm/ManagedConfigurationsReceiver.kt
  app/src/main/kotlin/com/wire/android/emm/ManagedConfigurationsReporter.kt
  app/src/main/kotlin/com/wire/android/emm/ManagedSSOCodeConfig.kt
  app/src/main/kotlin/com/wire/android/emm/ManagedServerConfig.kt
  app/src/main/kotlin/com/wire/android/notification/broadcastreceivers/DynamicReceiversManager.kt
  app/src/main/kotlin/com/wire/android/ui/WireActivity.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/code/CreateAccountCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/create/overview/CreateAccountOverviewViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/LoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeScreen.kt
  app/src/main/kotlin/com/wire/android/ui/authentication/welcome/WelcomeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/newauthentication/login/NewLoginViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/registration/code/CreateAccountVerificationCodeViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/registration/details/CreateAccountDataDetailViewModel.kt
  app/src/main/kotlin/com/wire/android/ui/registration/selector/CreateAccountSelectorScreen.kt
  app/src/main/kotlin/com/wire/android/ui/registration/selector/CreateAccountSelectorViewModel.kt
  app/src/main/kotlin/com/wire/android/util/UriUtil.kt
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/app_restrictions.xml
  app/src/test/kotlin/com/wire/android/emm/ManagedConfigurationsManagerTest.kt
  app/src/test/kotlin/com/wire/android/emm/ManagedConfigurationsReceiverTest.kt
  app/src/test/kotlin/com/wire/android/emm/ManagedSSOCodeConfigTest.kt
  app/src/test/kotlin/com/wire/android/emm/ManagedServerLinksTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/LoginViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/create/details/CreateAccountDetailsViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/create/email/CreateAccountEmailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/email/LoginEmailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/login/sso/LoginSSOViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/authentication/welcome/WelcomeViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/newauthentication/login/NewLoginViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/registration/details/CreateAccountDataDetailViewModelTest.kt
  app/src/test/kotlin/com/wire/android/ui/registration/selector/CreateAccountSelectorViewModelTest.kt
  buildSrc/src/main/kotlin/customization/FeatureConfigs.kt
  default.json
  gradle/libs.versions.toml
Labels: size/XL
